{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[[]]},"abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"topicSections":[{"title":"Articles","anchor":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles"]},{"title":"Type Aliases","generated":true,"anchor":"Type-Aliases","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DeviceType","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/InterfaceOrientation"]},{"title":"Extended Modules","generated":true,"anchor":"Extended-Modules","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AVFAudio","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/CoreFoundation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/LicenseKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Speech","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Swift","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUI","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UniformTypeIdentifiers"]}],"variants":[{"paths":["\/documentation\/keyboardkit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkit"]}],"kind":"symbol","metadata":{"externalID":"KeyboardKit","roleHeading":"Framework","title":"KeyboardKit","modules":[{"name":"KeyboardKit"}],"symbolKind":"module","role":"collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit"},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"Logo"}]},{"inlineContent":[{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit","type":"reference","isActive":true},{"text":" lets you create amazing custom keyboards with just a few lines of code, using Swift and SwiftUI. It extends Apple’s native keyboard APIs with more capabilities and lets you create a native-looking, fully customizable keyboard in minutes.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can upgrade to KeyboardKit Pro to unlock pro features, like "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","type":"reference"},{"text":"s and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","type":"reference"},{"text":"s for ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"75+"}]},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale","isActive":true},{"type":"text","text":"s, "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","isActive":true},{"type":"text","text":", an "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","isActive":true,"type":"reference"},{"text":" keyboard, ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Themes-Article","type":"reference","isActive":true},{"text":", and much more.","type":"text"}],"type":"paragraph"},{"type":"heading","level":2,"text":"Installation","anchor":"Installation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit can be installed with the Swift Package Manager:"}]},{"type":"codeListing","code":["https:\/\/github.com\/KeyboardKit\/KeyboardKit.git"],"syntax":null},{"content":[{"type":"paragraph","inlineContent":[{"text":"KeyboardKit is a binary target and must ONLY be added to the app target. If you add it to any other target, it may crash at runtime.","type":"text"}]}],"type":"aside","name":"Important","style":"important"},{"anchor":"Supported-Platforms","level":2,"text":"Supported Platforms","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit supports all major Apple platforms (iOS, iPadOS, macOS, tvOS, watchOS, and visionOS), but is built for iOS by default. You can reach out to get an on-demand multi-platform or platform-specific build.","type":"text"}]},{"type":"heading","anchor":"Getting-Started","level":2,"text":"Getting Started"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article"},{"text":" guide helps you get started with KeyboardKit, and the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","isActive":true},{"type":"text","text":" article describes the essential types in the library."}]},{"type":"heading","level":2,"text":"Features","anchor":"Features"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit contains a large set of "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","isActive":true},{"type":"text","text":" that makes it easy to build custom keyboards that behave like the native system keyboard:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"🌱 "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","isActive":true},{"type":"text","text":" - Essential utilities, models, services & views."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"⌨️ ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","type":"reference"},{"text":" - Render a native-looking, fully customizable keyboard.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"💥 ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","type":"reference"},{"text":" - Trigger & handle keyboard-related actions.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"🤖 ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","type":"reference"},{"text":" - Features that are needed by AI-based keyboards.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"📱 "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","isActive":true},{"type":"text","text":" - App-specific utilities, settings, screens, etc."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"💡 "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","type":"reference","isActive":true},{"type":"text","text":" - Autocomplete and autocorrect as the user types."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"🗯 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article"},{"type":"text","text":" - Show input & secondary action callouts."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"📋 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article"},{"type":"text","text":" - Create custom clips and integrate with the system clipboard."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"🎤 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article"},{"type":"text","text":" - Trigger dictation from the keyboard."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"😀 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article"},{"type":"text","text":" - Emoji models, an emoji keyboard, etc."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"⌨️ "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article"},{"type":"text","text":" - Detect if an external keyboard is connected."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"🔉 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article"},{"type":"text","text":" - Trigger audio & haptic feedback with ease."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"𝒜 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts"},{"type":"text","text":" - Type with other fonts than the standard system font."}]}]},{"content":[{"inlineContent":[{"text":"👆 ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","type":"reference","isActive":true},{"text":" - Handle a rich set of gestures on any key.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"🏠 ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","type":"reference","isActive":true},{"text":" - Identify and open the host application.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"📝 ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","type":"reference","isActive":true},{"text":" - Keyboard input fields, Vietnamese support, etc.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"🔣 ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article"},{"type":"text","text":" - A dynamic, customizable keyboard layout engine."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"🌐 ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","type":"reference","isActive":true},{"text":" - Locale-specific utilities for all ","type":"text"},{"type":"strong","inlineContent":[{"text":"75","type":"text"}]},{"text":" supported locales.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"🗺️ "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article","type":"reference","isActive":true},{"type":"text","text":" - Open urls and other apps from the keyboard."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"👁 "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Previews-Article","type":"reference"},{"type":"text","text":" - Keyboard & theme previews for in-app use."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"📄 "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy-Article","isActive":true},{"type":"text","text":" - Extend the text document proxy with more capabilities."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"⚙️ "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Settings-Article","isActive":true},{"type":"text","text":" - Provide keyboard settings & link to System Settings."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"🩺 "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Status-Article","type":"reference","isActive":true},{"type":"text","text":" - Detect if a keyboard is enabled, has full access, etc."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"🎨 "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Styling-Article","type":"reference","isActive":true},{"type":"text","text":" - Style your keyboard to great extent."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"🍭 "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Themes-Article","isActive":true},{"type":"text","text":" - A theme engine with many pre-defined themes."}]}]}]},{"type":"heading","anchor":"Developer-Guides","level":2,"text":"Developer Guides"},{"type":"paragraph","inlineContent":[{"type":"text","text":"While feature articles provide surface-level instructions for each feature, "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles","isActive":true},{"type":"text","text":" provide in-depth information for many tasks."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"⌨️ ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","isActive":true},{"type":"text","text":" - This article describes how custom iOS keyboard extensions work."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"🔁 ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","isActive":true},{"text":" - This article describes how to sync data between the main app and its keyboard.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"🐛 ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","isActive":true},{"text":" - This article describes how to debug a custom keyboard extension.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"📄 ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","isActive":true},{"text":" - This developer guide describes how to use dSYMs to obtain more detailed crash reports.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"🧪 ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","type":"reference"},{"text":" - This developer guide describes how to enable experimental features.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"🧠 "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management","type":"reference"},{"type":"text","text":" - This developer guide describes how to manage memory in a keyboard extensions."}],"type":"paragraph"}]}]},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles","isActive":true},{"type":"text","text":" article also links to feature-specific developer guides that describe how to setup and configure complex features."}],"type":"paragraph"},{"level":2,"text":"Demo & Inspiration","anchor":"Demo--Inspiration","type":"heading"},{"inlineContent":[{"text":"The demo app in the ","type":"text"},{"type":"reference","overridingTitle":"KeyboardKit repository","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit","overridingTitleInlineContent":[{"text":"KeyboardKit repository","type":"text"}],"isActive":true},{"type":"text","text":" and the "},{"type":"reference","identifier":"https:\/\/keyboardkit.com\/app","isActive":true},{"type":"text","text":" on the App Store lets you try many core and pro features directly on your device, without having to write any code."}],"type":"paragraph"},{"level":2,"text":"License","anchor":"License","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit is free to use, while KeyboardKit Pro requires a license. You can sign up for KeyboardKit Pro on the ","type":"text"},{"type":"reference","identifier":"https:\/\/keyboardkit.com","isActive":true},{"type":"text","text":"."}]}]}],"references":{"Feature-Essentials.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials.jpg"}],"identifier":"Feature-Essentials.jpg"},"Feature-AI.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-AI.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","url":"\/documentation\/keyboardkit\/app-article","images":[{"identifier":"Feature-App.jpg","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"role":"article","title":"App Utilities","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Getting-Started-Article":{"type":"topic","abstract":[{"type":"text","text":"This developer guide describes how to get started with KeyboardKit."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","title":"Getting Started","role":"article","url":"\/documentation\/keyboardkit\/getting-started-article"},"Developer-Article-Experiments.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Experiments.jpg"}],"type":"image","alt":"Article Icon","identifier":"Developer-Article-Experiments.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardKitVersionNumber":{"type":"topic","abstract":[{"type":"text","text":"Project version number for KeyboardKit."}],"kind":"symbol","fragments":[{"text":"KeyboardKitVersionNumber","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardKitVersionNumber","title":"KeyboardKitVersionNumber","role":"symbol","url":"\/documentation\/keyboardkit\/keyboardkitversionnumber"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"images":[{"type":"card","identifier":"Feature-AI.jpg"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Styling-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Styling-Article","url":"\/documentation\/keyboardkit\/styling-article","images":[{"identifier":"Feature-Styling.jpg","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit styling engine.","type":"text"}],"role":"article","kind":"article","title":"Styling","type":"topic"},"https://keyboardkit.com/app":{"url":"https:\/\/keyboardkit.com\/app","titleInlineContent":[{"type":"text","text":"KeyboardKit app"}],"type":"link","identifier":"https:\/\/keyboardkit.com\/app","title":"KeyboardKit app"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Speech":{"url":"\/documentation\/keyboardkit\/speech","abstract":[],"role":"collection","type":"topic","kind":"symbol","title":"Speech","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Speech"},"Feature-Localization.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Localization.jpg"},"Feature-Previews.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Previews.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Previews.jpg"},"Feature-Callouts.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Callouts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"url":"\/documentation\/keyboardkit\/host-article","abstract":[{"text":"This article describes how KeyboardKit Pro can identify and use the host application.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Host Application","images":[{"type":"card","identifier":"Feature-Host.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts":{"url":"\/documentation\/keyboardkit\/fonts","title":"Fonts","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This is a namespace for font-related types."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fonts"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fonts"}]},"Feature-Host.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Host.jpg"},"Feature-Status.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Status.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Status.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Articles":{"url":"\/documentation\/keyboardkit\/developer-articles","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}],"role":"collectionGroup","type":"topic","kind":"article","title":"Developer Guides","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles"},"Feature-Feedback.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Feedback.jpg"},"Feature-Styling.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Styling.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Styling.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit","url":"\/documentation\/keyboardkit\/uikit","abstract":[],"role":"collection","title":"UIKit","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardKitVersionString":{"url":"\/documentation\/keyboardkit\/keyboardkitversionstring","abstract":[{"type":"text","text":"Project version string for KeyboardKit."}],"fragments":[{"text":"KeyboardKitVersionString","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"KeyboardKitVersionString","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardKitVersionString"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/CoreFoundation":{"url":"\/documentation\/keyboardkit\/corefoundation","abstract":[],"role":"collection","type":"topic","kind":"symbol","title":"CoreFoundation","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/CoreFoundation"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore":{"url":"\/documentation\/keyboardkit\/swiftuicore","abstract":[],"role":"collection","type":"topic","title":"SwiftUICore","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore"},"https://keyboardkit.com":{"url":"https:\/\/keyboardkit.com","titleInlineContent":[{"type":"text","text":"KeyboardKit website"}],"type":"link","identifier":"https:\/\/keyboardkit.com","title":"KeyboardKit website"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/InterfaceOrientation":{"url":"\/documentation\/keyboardkit\/interfaceorientation","navigatorTitle":[{"text":"InterfaceOrientation","kind":"identifier"}],"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterfaceOrientation","kind":"identifier"}],"deprecated":true,"role":"symbol","type":"topic","kind":"symbol","title":"InterfaceOrientation","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/InterfaceOrientation"},"Logo":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Logo.png"}],"type":"image","alt":"KeyboardKit logo","identifier":"Logo"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Gestures-Article":{"type":"topic","images":[{"identifier":"Feature-Gestures.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"role":"article","title":"Gestures","url":"\/documentation\/keyboardkit\/gestures-article"},"Feature-Dictation.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Dictation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"abstract":[{"type":"text","text":"This article describes KeyboardKit’s clipboard support."}],"kind":"article","title":"Clipboard","type":"topic","images":[{"identifier":"Feature-Clipboard.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","url":"\/documentation\/keyboardkit\/clipboard-article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DeviceType":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceType","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DeviceType","navigatorTitle":[{"kind":"identifier","text":"DeviceType"}],"deprecated":true,"title":"DeviceType","role":"symbol","url":"\/documentation\/keyboardkit\/devicetype"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Data-Syncing":{"url":"\/documentation\/keyboardkit\/developer-data-syncing","abstract":[{"text":"This developer guide describes how to sync data between the main app and its keyboard.","type":"text"}],"images":[{"identifier":"Developer-Article-Data-Syncing.jpg","type":"card"}],"type":"topic","title":"Data Syncing","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-Article":{"url":"\/documentation\/keyboardkit\/essentials-article","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"images":[{"identifier":"Feature-Essentials.jpg","type":"card"}],"type":"topic","title":"Essentials","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","kind":"article"},"Feature-Themes.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Themes.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Themes.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"role":"article","type":"topic","kind":"article","title":"Callouts","images":[{"type":"card","identifier":"Feature-Callouts.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article"},"Feature-Navigation.jpg":{"alt":"Feature Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Navigation.jpg"}],"identifier":"Feature-Navigation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Navigation-Article":{"type":"topic","images":[{"type":"card","identifier":"Feature-Navigation.jpg"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit navigation engine."}],"role":"article","title":"Navigation","url":"\/documentation\/keyboardkit\/navigation-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Previews-Article":{"url":"\/documentation\/keyboardkit\/previews-article","abstract":[{"text":"This article describes the KeyboardKit preview engine.","type":"text"}],"role":"article","type":"topic","title":"Previews","kind":"article","images":[{"identifier":"Feature-Previews.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Previews-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Debugging":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","url":"\/documentation\/keyboardkit\/developer-debugging","images":[{"identifier":"Developer-Article-Debugging.jpg","type":"card"}],"abstract":[{"type":"text","text":"This developer guide describes how to debug a custom keyboard extension."}],"role":"article","kind":"article","title":"Debugging","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Experiments":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","url":"\/documentation\/keyboardkit\/developer-experiments","images":[{"type":"card","identifier":"Developer-Article-Experiments.jpg"}],"abstract":[{"text":"This developer guide describes how to enable experimental features.","type":"text"}],"role":"article","title":"Experiments","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation":{"url":"\/documentation\/keyboardkit\/foundation","title":"Foundation","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation","role":"collection","kind":"symbol","abstract":[],"type":"topic"},"https://github.com/KeyboardKit/KeyboardKit":{"title":"KeyboardKit","titleInlineContent":[{"text":"KeyboardKit","type":"text"}],"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit","type":"link","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKit"},"Feature-Input.jpg":{"alt":"Feature Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg"}],"identifier":"Feature-Input.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Localization-Article":{"type":"topic","images":[{"identifier":"Feature-Localization.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","kind":"article","title":"Localization","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"url":"\/documentation\/keyboardkit\/localization-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","url":"\/documentation\/keyboardkit\/feedback-article","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"role":"article","title":"Feedback","kind":"article","type":"topic"},"Feature-Clipboard.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg"}],"identifier":"Feature-Clipboard.jpg"},"Developer-Article-Custom-Keyboards.jpg":{"type":"image","alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Custom-Keyboards.jpg","traits":["1x","light"]}],"identifier":"Developer-Article-Custom-Keyboards.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-KeyboardView":{"type":"topic","images":[{"identifier":"Feature-Essentials-KeyboardView.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","kind":"article","title":"Essentials - KeyboardView","abstract":[{"type":"text","text":"This article describes the essential "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"type":"text","text":" and how to use and configure it."}],"url":"\/documentation\/keyboardkit\/essentials-keyboardview"},"Developer-Article-Memory-Management.jpg":{"identifier":"Developer-Article-Memory-Management.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Memory-Management.jpg"}],"type":"image","alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Swift":{"url":"\/documentation\/keyboardkit\/swift","abstract":[],"role":"collection","type":"topic","title":"Swift","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Swift"},"Feature-External.jpg":{"identifier":"Feature-External.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg"}],"type":"image","alt":"Feature Icon"},"Developer-Article-dSYMs.jpg":{"identifier":"Developer-Article-dSYMs.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-dSYMs.jpg"}],"type":"image","alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Status-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Status-Article","url":"\/documentation\/keyboardkit\/status-article","images":[{"identifier":"Feature-Status.jpg","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit status engine."}],"role":"article","title":"Status","kind":"article","type":"topic"},"Feature-Gestures.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Gestures.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Gestures.jpg"},"Feature-Layout.jpg":{"identifier":"Feature-Layout.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Layout.jpg"}],"type":"image","alt":"Feature Icon"},"Feature-Essentials-KeyboardView.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials-KeyboardView.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Essentials-KeyboardView.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","title":"KeyboardView","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","role":"symbol","kind":"symbol","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"Feature-App.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-App.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"url":"\/documentation\/keyboardkit\/input-article","abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Input","images":[{"identifier":"Feature-Input.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"},"Feature-Settings.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Settings.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Settings.jpg"},"Developer-Article-Debugging.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Debugging.jpg"}],"type":"image","alt":"Article Icon","identifier":"Developer-Article-Debugging.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UniformTypeIdentifiers":{"url":"\/documentation\/keyboardkit\/uniformtypeidentifiers","abstract":[],"role":"collection","type":"topic","kind":"symbol","title":"UniformTypeIdentifiers","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UniformTypeIdentifiers"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUI":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUI","role":"collection","title":"SwiftUI","url":"\/documentation\/keyboardkit\/swiftui"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Proxy-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy-Article","url":"\/documentation\/keyboardkit\/proxy-article","images":[{"identifier":"Feature-Proxy.jpg","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}],"role":"article","title":"Proxy Utilities","kind":"article","type":"topic"},"Feature-Autocomplete.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Autocomplete.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale":{"url":"\/documentation\/keyboardkit\/foundation\/locale","navigatorTitle":[{"kind":"identifier","text":"Locale"}],"abstract":[],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:10Foundation6LocaleV","kind":"identifier","text":"Locale"}],"role":"symbol","type":"topic","kind":"symbol","title":"Locale","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Custom-Keyboards":{"type":"topic","images":[{"type":"card","identifier":"Developer-Article-Custom-Keyboards.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how custom iOS keyboard extensions work.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","role":"article","title":"Custom Keyboard Extensions","url":"\/documentation\/keyboardkit\/developer-custom-keyboards"},"Feature-Proxy.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Proxy.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Proxy.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-dSYMs":{"type":"topic","images":[{"type":"card","identifier":"Developer-Article-dSYMs.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how to use dSYMs to obtain more detailed crash reports.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","role":"article","title":"dSYMs","url":"\/documentation\/keyboardkit\/developer-dsyms"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"url":"\/documentation\/keyboardkit\/external-keyboards-article","kind":"article","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","role":"article","type":"topic","images":[{"identifier":"Feature-External.jpg","type":"card"}],"title":"External Keyboards"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"url":"\/documentation\/keyboardkit\/emojis-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"role":"article","type":"topic","kind":"article","title":"Emojis","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article"},"Developer-Article-Data-Syncing.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Data-Syncing.jpg"}],"type":"image","alt":"Article Icon","identifier":"Developer-Article-Data-Syncing.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Themes-Article":{"url":"\/documentation\/keyboardkit\/themes-article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit Pro theme engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Themes-Article","role":"article","type":"topic","images":[{"type":"card","identifier":"Feature-Themes.jpg"}],"title":"Themes"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","title":"Dictation","role":"article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"url":"\/documentation\/keyboardkit\/dictation-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Layout-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","title":"Layout","role":"article","images":[{"identifier":"Feature-Layout.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/layout-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Memory-Management":{"type":"topic","images":[{"type":"card","identifier":"Developer-Article-Memory-Management.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how to manage memory in a keyboard extensions.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management","role":"article","title":"Memory Management","url":"\/documentation\/keyboardkit\/developer-memory-management"},"Feature-Emojis.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Emojis.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","url":"\/documentation\/keyboardkit\/actions-article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"role":"article","kind":"article","title":"Actions","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"url":"\/documentation\/keyboardkit\/features-articles","abstract":[{"type":"text","text":"This article links to the various KeyboardKit features."}],"role":"collectionGroup","type":"topic","title":"Features","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/LicenseKit":{"url":"\/documentation\/keyboardkit\/licensekit","abstract":[],"role":"collection","type":"topic","title":"LicenseKit","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/LicenseKit"},"Feature-Actions.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Actions.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AVFAudio":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AVFAudio","abstract":[],"role":"collection","title":"AVFAudio","url":"\/documentation\/keyboardkit\/avfaudio"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"url":"\/documentation\/keyboardkit\/autocomplete-article","title":"Autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Settings-Article":{"title":"Settings","abstract":[{"text":"This article describes the KeyboardKit settings engine and its available settings.","type":"text"}],"role":"article","images":[{"identifier":"Feature-Settings.jpg","type":"card"}],"type":"topic","url":"\/documentation\/keyboardkit\/settings-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Settings-Article","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles"],"title":"Articles","anchor":"Articles"},{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardKitVersionNumber","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardKitVersionString"],"generated":true,"title":"Variables","anchor":"Variables"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}