{"sections":[],"variants":[{"paths":["\/documentation\/keyboardkit\/actions-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/actions-article"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article"]}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit action engine."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article"},"kind":"article","metadata":{"images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"modules":[{"name":"KeyboardKit"}],"role":"article","title":"Actions","roleHeading":"Article"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"topicSections":[{"title":"Developer Guide","anchor":"Developer-Guide","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions"]},{"title":"Types","anchor":"Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler"]}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","isActive":true},{"type":"text","text":" type is a central concept in KeyboardKit, where an action can be triggered by the keyboard or by code, then handled with a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler","isActive":true},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler","type":"reference","isActive":true},{"type":"text","text":" can either handle a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","type":"reference","isActive":true},{"type":"text","text":" in a standard way, or handle it based on a certain "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Gesture","type":"reference","isActive":true},{"type":"text","text":"."}]},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"👑 KeyboardKit Pro unlocks support for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Vietnamese"},{"text":" TELEX, VNI & VIQR text input and adds this support to the action handler. You can sign up for KeyboardKit Pro from the ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/keyboardkit.com"},{"text":".","type":"text"}]}],"style":"important","name":"Important"},{"type":"heading","anchor":"Developer-Guide","text":"Developer Guide","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions"},{"type":"text","text":" developer guide has step-by-step instructions on how to customize the action handling with a custom action handler."}]},{"text":"Namespace","anchor":"Namespace","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction"},{"type":"text","text":" enum that defines keyboard-related actions. It also serves as a namespace for other action-related types and views, like the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/StandardActionHandler"},{"type":"text","text":" that can be used to handle many actions."}],"type":"paragraph"},{"text":"Actions","anchor":"Actions","type":"heading","level":2},{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction"},{"text":" enum defines many keyboard-related actions, like ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/backspace"},{"text":", ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/character(_:)"},{"text":",","type":"text"},{"text":" ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/dismissKeyboard"},{"text":", ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/emoji(_:)-swift.enum.case"},{"text":",","type":"text"},{"text":" ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/keyboardType(_:)"},{"text":", ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/nextKeyboard"},{"text":", ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/nextLocale"},{"text":", etc. See ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction"},{"text":" for a full list of actions.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Many actions have a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/standardAction"},{"type":"text","text":", while others require manual handling by creating a custom "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler"},{"type":"text","text":"."}],"type":"paragraph"},{"anchor":"Action-Handlers","type":"heading","level":2,"text":"Action Handlers"},{"type":"paragraph","inlineContent":[{"text":"In KeyboardKit, a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler","type":"reference"},{"text":" can be used to handle actions, apply autocomplete ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Suggestion","type":"reference"},{"text":"s, trigger audio and haptic feedback, etc. The main ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Services\/actionHandler","type":"reference"},{"text":" is responsible for handling actions, and can be customized to fit your needs.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit automatically creates an instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/StandardActionHandler"},{"type":"text","text":" and injects it into "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services"},{"type":"text","text":". You can replace it with a custom action handler if you want to customize some actions. If so, it’s best to inherit the standard class and override parts of it."}]},{"type":"paragraph","inlineContent":[{"text":"For instance, to customize what happens when a user double-taps space, you can override ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/handle(_:on:)"},{"text":" and check if the action is ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/space"},{"text":" and the gesture is ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Gesture\/doubleTap"},{"text":". If so, do your custom thing, else call super to perform the standard action handling.","type":"text"}]},{"anchor":"%F0%9F%91%91-KeyboardKit-Pro","type":"heading","level":2,"text":"👑 KeyboardKit Pro"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro injects more capabilities into the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/StandardActionHandler"},{"type":"text","text":", to make it handle locale-specific input methods like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Vietnamese"},{"type":"text","text":" TELEX, VNI  and VIQR, and other locale and pro-specific replacements."}]}]}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/nextLocale":{"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/nextLocale","title":"KeyboardAction.nextLocale","url":"\/documentation\/keyboardkit\/keyboardaction\/nextlocale","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextLocale","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Picks the next locale on release and a opens a locale picker on long press."}],"type":"topic"},"Feature-Localization.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg"}],"identifier":"Feature-Localization.jpg","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"url":"\/documentation\/keyboardkit\/feedback-article","type":"topic","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"title":"Feedback","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"title":"External Keyboards","url":"\/documentation\/keyboardkit\/external-keyboards-article","images":[{"type":"card","identifier":"Feature-External.jpg"}],"kind":"article","type":"topic","role":"article"},"https://keyboardkit.com":{"type":"link","title":"KeyboardKit website","url":"https:\/\/keyboardkit.com","identifier":"https:\/\/keyboardkit.com","titleInlineContent":[{"type":"text","text":"KeyboardKit website"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","title":"Callouts","type":"topic","images":[{"identifier":"Feature-Callouts.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"text":"This article describes the KeyboardKit callout engine.","type":"text"}],"role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Navigation-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/navigation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"images":[{"identifier":"Feature-Navigation.jpg","type":"card"}],"kind":"article","title":"Navigation","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/services":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V"},{"text":".","kind":"text"},{"text":"Services","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V8ServicesC"}],"abstract":[{"type":"text","text":"Keyboard-specific services."}],"role":"symbol","title":"services","kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/services"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"url":"\/documentation\/keyboardkit\/dictation-article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","type":"topic","kind":"article","role":"article"},"Feature-Autocomplete.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Autocomplete.jpg"},"Feature-Fonts.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg"}],"identifier":"Feature-Fonts.jpg","alt":"Feature Icon"},"Feature-Host.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg"}],"identifier":"Feature-Host.jpg","alt":"Feature Icon"},"Feature-Dictation.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Dictation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/character(_:)":{"abstract":[{"text":"Inserts a text character when released.","type":"text"}],"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardaction\/character(_:)","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"character","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/character(_:)","type":"topic","title":"KeyboardAction.character(_:)"},"Feature-AI.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg"}],"identifier":"Feature-AI.jpg","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Vietnamese":{"navigatorTitle":[{"kind":"identifier","text":"Vietnamese"}],"type":"topic","kind":"symbol","title":"Vietnamese","abstract":[{"type":"text","text":"This is a namespace for Vietnamese types."}],"url":"\/documentation\/keyboardkit\/vietnamese","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Vietnamese","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Vietnamese"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/emoji(_:)-swift.enum.case":{"type":"topic","title":"KeyboardAction.emoji(_:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"emoji","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit5EmojiV","text":"Emoji","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/keyboardkit\/keyboardaction\/emoji(_:)-swift.enum.case","abstract":[{"type":"text","text":"Inserts an emoji when released."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/emoji(_:)-swift.enum.case"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","type":"topic","url":"\/documentation\/keyboardkit\/autocomplete-article","kind":"article","images":[{"type":"card","identifier":"Feature-Autocomplete.jpg"}],"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/Services/actionHandler":{"role":"symbol","type":"topic","title":"actionHandler","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionHandler","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyboardActionHandler","preciseIdentifier":"s:11KeyboardKit0A13ActionHandlerP","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Services\/actionHandler","abstract":[{"text":"The keyboard action handler to use.","type":"text"}],"url":"\/documentation\/keyboardkit\/keyboard\/services\/actionhandler","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Actions":{"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","type":"topic","title":"Actions","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This developer guide describes how to customize the action handling.","type":"text"}],"url":"\/documentation\/keyboardkit\/developer-actions","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/nextKeyboard":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextKeyboard","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/nextKeyboard","type":"topic","abstract":[{"type":"text","text":"Picks the next keyboard on release and opens the system picker on long press."}],"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardaction\/nextkeyboard","role":"symbol","title":"KeyboardAction.nextKeyboard"},"Feature-Feedback.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg"}],"identifier":"Feature-Feedback.jpg","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Localization-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit localization engine."}],"url":"\/documentation\/keyboardkit\/localization-article","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","title":"Localization","type":"topic","kind":"article","role":"article"},"Feature-External.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-External.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/StandardActionHandler":{"title":"KeyboardAction.StandardActionHandler","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/StandardActionHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardActionHandler"}],"abstract":[{"type":"text","text":"This class provides a standard way to handle actions"},{"type":"text","text":" "},{"type":"text","text":"that are triggered by the keyboard."}],"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardaction\/standardactionhandler","navigatorTitle":[{"kind":"identifier","text":"StandardActionHandler"}],"type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","images":[{"type":"card","identifier":"Feature-AI.jpg"}],"kind":"article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","title":"Input","url":"\/documentation\/keyboardkit\/input-article","images":[{"type":"card","identifier":"Feature-Input.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/emojis-article","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","title":"Emojis","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"kind":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","role":"article","images":[{"identifier":"Feature-Host.jpg","type":"card"}],"title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro lets you define and use a host application."}],"url":"\/documentation\/keyboardkit\/host-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/keyboardType(_:)":{"abstract":[{"type":"text","text":"Changes the keyboard type when pressed."}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardType","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V","text":"Keyboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V0A4TypeO","text":"KeyboardType"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/keyboardType(_:)","title":"KeyboardAction.keyboardType(_:)","kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardaction\/keyboardtype(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"url":"\/documentation\/keyboardkit\/clipboard-article","abstract":[{"text":"This article describes KeyboardKit’s clipboard support.","type":"text"}],"images":[{"type":"card","identifier":"Feature-Clipboard.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","title":"Clipboard","type":"topic","kind":"article","role":"article"},"Feature-App.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg"}],"identifier":"Feature-App.jpg","alt":"Feature Icon"},"Feature-Clipboard.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg"}],"identifier":"Feature-Clipboard.jpg","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardActionHandler":{"navigatorTitle":[{"text":"KeyboardActionHandler","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler","type":"topic","url":"\/documentation\/keyboardkit\/keyboardactionhandler","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardActionHandler","kind":"identifier"}],"role":"symbol","title":"KeyboardActionHandler","abstract":[{"text":"This protocol can be implemented by any classes that can","type":"text"},{"text":" ","type":"text"},{"text":"handle triggered ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","isActive":true,"type":"reference"},{"text":" events.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","type":"topic","abstract":[{"text":"This article describes KeyboardKit’s custom font support.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/fonts-article","role":"article","images":[{"type":"card","identifier":"Feature-Fonts.jpg"}],"title":"Fonts"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/standardAction":{"url":"\/documentation\/keyboardkit\/keyboardaction\/standardaction","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/standardAction","type":"topic","abstract":[{"type":"text","text":"The standard controller action."}],"title":"standardAction","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standardAction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A6ActionO07GestureC0a","text":"GestureAction","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","role":"article","kind":"article","title":"App Utilities","url":"\/documentation\/keyboardkit\/app-article","type":"topic","images":[{"type":"card","identifier":"Feature-App.jpg"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/dismissKeyboard":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismissKeyboard","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/keyboardaction\/dismisskeyboard","title":"KeyboardAction.dismissKeyboard","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/dismissKeyboard","role":"symbol","kind":"symbol","abstract":[{"text":"Dismisses the keyboard when released.","type":"text"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardActionHandler/handle(_:on:)":{"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardactionhandler\/handle(_:on:)","required":true,"title":"handle(_:on:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V"},{"text":".","kind":"text"},{"text":"Gesture","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V7GestureO"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"KeyboardAction","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A6ActionO"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Handle a certain keyboard action gesture."}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/handle(_:on:)"},"Feature-Navigation.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Navigation.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Navigation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/Gesture":{"url":"\/documentation\/keyboardkit\/keyboard\/gesture","kind":"symbol","navigatorTitle":[{"text":"Gesture","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Gesture","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Gesture"}],"title":"Keyboard.Gesture","type":"topic","abstract":[{"type":"text","text":"This enum defines various keyboard gestures that can"},{"type":"text","text":" "},{"text":"be used to interact with a keyboard.","type":"text"}]},"Feature-Callouts.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg"}],"identifier":"Feature-Callouts.jpg","alt":"Feature Icon"},"Feature-Layout.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Layout.jpg"}],"identifier":"Feature-Layout.jpg","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Layout-Article":{"title":"Layout","url":"\/documentation\/keyboardkit\/layout-article","kind":"article","images":[{"identifier":"Feature-Layout.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/space":{"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/space","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"space"}],"title":"KeyboardAction.space","abstract":[{"type":"text","text":"Inserts a space when released and can perform custom actions when long pressed."}],"url":"\/documentation\/keyboardkit\/keyboardaction\/space","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/backspace":{"title":"KeyboardAction.backspace","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/backspace","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backspace","kind":"identifier"}],"abstract":[{"text":"Deletes backwards when pressed, and repeats until released.","type":"text"}],"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardaction\/backspace","type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/Gesture/doubleTap":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"doubleTap"}],"abstract":[{"text":"Triggers when a button is double tapped.","type":"text"}],"kind":"symbol","title":"Keyboard.Gesture.doubleTap","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Gesture\/doubleTap","role":"symbol","url":"\/documentation\/keyboardkit\/keyboard\/gesture\/doubletap","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/Suggestion":{"url":"\/documentation\/keyboardkit\/autocomplete\/suggestion","abstract":[{"type":"text","text":"This type represents an autocomplete suggestion that"},{"type":"text","text":" "},{"type":"text","text":"is returned by an "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Suggestion","title":"Autocomplete.Suggestion","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Suggestion","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Suggestion","kind":"identifier"}],"role":"symbol"},"Feature-Input.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Input.jpg"},"Feature-Emojis.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg"}],"identifier":"Feature-Emojis.jpg","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteService":{"abstract":[{"type":"text","text":"This protocol can be implemented by any type that can be"},{"type":"text","text":" "},{"type":"text","text":"used perform autocomplete as the user types."}],"kind":"symbol","title":"AutocompleteService","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutocompleteService"}],"url":"\/documentation\/keyboardkit\/autocompleteservice","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutocompleteService"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService"},"Feature-Actions.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}],"identifier":"Feature-Actions.jpg","alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction":{"title":"KeyboardAction","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAction"}],"abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"type":"text","text":" "},{"type":"text","text":"a namespace for action-related types."}],"url":"\/documentation\/keyboardkit\/keyboardaction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"title":"Developer Guide","anchor":"Developer-Guide","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions"]}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article"]}]}]}]}