{"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"metadata":{"images":[{"type":"card","identifier":"Feature-AI.jpg"}],"role":"article","modules":[{"name":"KeyboardKit"}],"title":"AI Support","roleHeading":"Article"},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/keyboardkit\/ai-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/ai-article"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article"],"generated":true}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"type":"text","text":"Apple’s native keyboard APIs lack many features that are needed to build AI-based keyboards, for instance to read an entire document to be able to perform tasks like spellchecking and proofreading, or to let users type text within the keyboard extension."}],"type":"paragraph"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"text":"👑 KeyboardKit Pro unlocks many AI-enabling capabilities, like making it possible to read the full document and type directly within the keyboard. You can sign up for KeyboardKit Pro from the ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/keyboardkit.com"},{"text":".","type":"text"}]}],"name":"Important","type":"aside"},{"level":2,"text":"Full Document Reader","anchor":"Full-Document-Reader","type":"heading"},{"inlineContent":[{"type":"text","text":"Apple’s native text document proxy doesn’t return all the text within the document. It cuts off the available text at any time, e.g. at the previous or next paragraph, which makes it hard to provide AI-based features that require more context."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"KeyboardKit Pro therefore unlocks "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/fullDocumentContext(config:)","type":"reference","isActive":true},{"type":"text","text":" proxy extensions that let you read "},{"inlineContent":[{"type":"text","text":"all"}],"type":"strong"},{"type":"text","text":" text from the proxy:"}],"type":"paragraph"},{"syntax":"swift","code":["let proxy = keyboardContext.textDocumentProxy","let result = try await proxy.fullDocumentContext()"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"This will provide you with all the text before and after the input cursor, as well as an aggregate of all the available text in the document."}],"type":"paragraph"},{"inlineContent":[{"text":"See the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy-Article","isActive":true},{"text":" article for more information.","type":"text"}],"type":"paragraph"},{"level":2,"text":"Next Word Prediction","anchor":"Next-Word-Prediction","type":"heading"},{"inlineContent":[{"type":"text","text":"Apple’s native text prediction utilities stopped supporting next word prediction in iOS 16. It instead only provides predictions on already typed text, without any (known) way to get next word predictions."}],"type":"paragraph"},{"inlineContent":[{"text":"KeyboardKit Pro therefore unlocks ways to perform next word prediction with Apple Intelligence, and via 3rd party services like ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/NextWordPredictionMethod\/claude","isActive":true},{"text":" and ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/NextWordPredictionMethod\/openAI"},{"text":" to perform remote predictions that are more capable than the currently limited on-device models.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"See the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","type":"reference","isActive":true},{"type":"text","text":" article for more information and important considerations."}],"type":"paragraph"},{"text":"Text Input","level":2,"type":"heading","anchor":"Text-Input"},{"inlineContent":[{"type":"text","text":"Apple’s native input controller & text document proxy don’t let you type in text fields within the keyboard. Instead, text will be sent to the main app even if a text field in the keyboard is focused. This makes it hard to let user perform AI-based prompting within the keyboard."}],"type":"paragraph"},{"inlineContent":[{"text":"KeyboardKit Pro therefore unlocks a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTextField","isActive":true,"type":"reference"},{"text":" that automatically manages in-keyboard typing, without any extra code:","type":"text"}],"type":"paragraph"},{"code":["extension MyView: View {","","    @EnvironmentObject var context: KeyboardContext","","    @State var text = \"\"","","    var body: some View {","        KeyboardTextField(","            text: $text, ","            keyboardContext: context","        )","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"The keyboard-specific text components will automatically manage text routing and only take proxy ownership while they are focused."}],"type":"paragraph"},{"inlineContent":[{"text":"See the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","type":"reference"},{"text":" article for more information.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"This article describes the KeyboardKit AI support capabilities.","type":"text"}],"kind":"article","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","title":"Callouts","type":"topic","images":[{"identifier":"Feature-Callouts.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"text":"This article describes the KeyboardKit callout engine.","type":"text"}],"role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"Feature-Navigation.jpg":{"type":"image","identifier":"Feature-Navigation.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Navigation.jpg","traits":["1x","light"]}]},"Feature-Fonts.jpg":{"alt":"Feature Icon","type":"image","identifier":"Feature-Fonts.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg"}]},"Feature-Input.jpg":{"alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg"}],"type":"image","identifier":"Feature-Input.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/NextWordPredictionMethod/openAI":{"title":"Autocomplete.NextWordPredictionMethod.openAI","abstract":[{"type":"text","text":"Perform next word prediction with the OpenAI API."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openAI","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocomplete\/nextwordpredictionmethod\/openai","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/NextWordPredictionMethod\/openAI"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/emojis-article","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","title":"Emojis","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","type":"topic","abstract":[{"text":"This article describes KeyboardKit’s custom font support.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/fonts-article","role":"article","images":[{"type":"card","identifier":"Feature-Fonts.jpg"}],"title":"Fonts"},"Feature-Actions.jpg":{"type":"image","identifier":"Feature-Actions.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Localization-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit localization engine."}],"url":"\/documentation\/keyboardkit\/localization-article","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","title":"Localization","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"url":"\/documentation\/keyboardkit\/feedback-article","type":"topic","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"title":"Feedback","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"Feature-Layout.jpg":{"identifier":"Feature-Layout.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Layout.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/actions-article","role":"article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"title":"Actions"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"title":"External Keyboards","url":"\/documentation\/keyboardkit\/external-keyboards-article","images":[{"type":"card","identifier":"Feature-External.jpg"}],"kind":"article","type":"topic","role":"article"},"Feature-Proxy.jpg":{"identifier":"Feature-Proxy.jpg","type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Proxy.jpg","traits":["1x","light"]}],"alt":"Feature Icon"},"Feature-Emojis.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Emojis.jpg","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Proxy-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy-Article","type":"topic","url":"\/documentation\/keyboardkit\/proxy-article","kind":"article","images":[{"type":"card","identifier":"Feature-Proxy.jpg"}],"role":"article","title":"Proxy Utilities","abstract":[{"text":"This article describes the KeyboardKit proxy engine and its utilities.","type":"text"}]},"Feature-Feedback.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Feedback.jpg","alt":"Feature Icon"},"Feature-Host.jpg":{"identifier":"Feature-Host.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","type":"topic","url":"\/documentation\/keyboardkit\/autocomplete-article","kind":"article","images":[{"type":"card","identifier":"Feature-Autocomplete.jpg"}],"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"url":"\/documentation\/keyboardkit\/dictation-article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/fullDocumentContext(config:)":{"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/fulldocumentcontext(config:)","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/fullDocumentContext(config:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullDocumentContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Proxy","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit5ProxyV"},{"text":".","kind":"text"},{"text":"FullDocumentReaderConfiguration","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit5ProxyV31FullDocumentReaderConfigurationV"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Proxy","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit5ProxyV"},{"text":".","kind":"text"},{"text":"FullDocumentReaderResult","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit5ProxyV24FullDocumentReaderResultV"}],"title":"fullDocumentContext(config:)","type":"topic","abstract":[{"text":"Get the full document context from the proxy.","type":"text"}]},"Feature-Callouts.jpg":{"type":"image","identifier":"Feature-Callouts.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg","traits":["1x","light"]}]},"https://keyboardkit.com":{"identifier":"https:\/\/keyboardkit.com","url":"https:\/\/keyboardkit.com","type":"link","titleInlineContent":[{"type":"text","text":"KeyboardKit website"}],"title":"KeyboardKit website"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardTextField":{"navigatorTitle":[{"kind":"identifier","text":"KeyboardTextField"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTextField","type":"topic","url":"\/documentation\/keyboardkit\/keyboardtextfield","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardTextField"}],"role":"symbol","title":"KeyboardTextField","abstract":[{"text":"This view can be used to type within keyboard extensions.","type":"text"}]},"Feature-Autocomplete.jpg":{"type":"image","identifier":"Feature-Autocomplete.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","role":"article","kind":"article","title":"App Utilities","url":"\/documentation\/keyboardkit\/app-article","type":"topic","images":[{"type":"card","identifier":"Feature-App.jpg"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}]},"Feature-App.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg","traits":["1x","light"]}],"identifier":"Feature-App.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Navigation-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/navigation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"images":[{"identifier":"Feature-Navigation.jpg","type":"card"}],"kind":"article","title":"Navigation","role":"article"},"Feature-External.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg"}],"identifier":"Feature-External.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"url":"\/documentation\/keyboardkit\/clipboard-article","abstract":[{"text":"This article describes KeyboardKit’s clipboard support.","type":"text"}],"images":[{"type":"card","identifier":"Feature-Clipboard.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","title":"Clipboard","type":"topic","kind":"article","role":"article"},"Feature-Clipboard.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg","traits":["1x","light"]}],"identifier":"Feature-Clipboard.jpg"},"Feature-Dictation.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}],"identifier":"Feature-Dictation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Layout-Article":{"title":"Layout","url":"\/documentation\/keyboardkit\/layout-article","kind":"article","images":[{"identifier":"Feature-Layout.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"kind":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","role":"article","images":[{"identifier":"Feature-Host.jpg","type":"card"}],"title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro lets you define and use a host application."}],"url":"\/documentation\/keyboardkit\/host-article"},"Feature-AI.jpg":{"type":"image","alt":null,"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg","traits":["1x","light"]}],"identifier":"Feature-AI.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","title":"Input","url":"\/documentation\/keyboardkit\/input-article","images":[{"type":"card","identifier":"Feature-Input.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/NextWordPredictionMethod/claude":{"type":"topic","url":"\/documentation\/keyboardkit\/autocomplete\/nextwordpredictionmethod\/claude","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"claude"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/NextWordPredictionMethod\/claude","abstract":[{"text":"Perform next word prediction with the Claude API.","type":"text"}],"kind":"symbol","title":"Autocomplete.NextWordPredictionMethod.claude","role":"symbol"},"Feature-Localization.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg","traits":["1x","light"]}],"identifier":"Feature-Localization.jpg"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}