{"metadata":{"title":"App Utilities","roleHeading":"Article","modules":[{"name":"KeyboardKit"}],"images":[{"type":"card","identifier":"Feature-App.jpg"}],"role":"article"},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAppView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen"],"anchor":"Types"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"sections":[],"kind":"article","abstract":[{"text":"This article describes the KeyboardKit app-specific utilities.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"],"generated":true}],"primaryContentSections":[{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has app-specific utilities to help you build a great main app for your keyboard, sync data between the app & keyboard, etc."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAppView","isActive":true},{"type":"text","text":" can be used to set up the main app, and the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen","isActive":true},{"type":"text","text":" template lets you set up a complete home screen with just a few lines of code."}]},{"anchor":"Keyboard-App","type":"heading","level":2,"text":"Keyboard App"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can create an app-specific "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","isActive":true},{"type":"text","text":" value to set up your app and keyboard. See the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","isActive":true},{"type":"text","text":" guide for more details."}]},{"anchor":"Keyboard-App-View","type":"heading","level":2,"text":"Keyboard App View"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAppView","isActive":true},{"type":"text","text":" should be used as the root view of your main app. It will set up the app, make "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/UserDefaults\/keyboardSettings","isActive":true},{"type":"text","text":" sync data between the app and keyboard, set up KeyboardKit Pro if needed, etc."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The  "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAppView","isActive":true},{"type":"text","text":" will also inject observable keyboard "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/State","isActive":true},{"type":"text","text":" types into the view environment, to let you access them like this:"}]},{"type":"codeListing","code":["@main","struct MyApp: App {","","    var body: some Scene {","        WindowGroup {","            KeyboardAppView(for: .myApp) {","                ContentView() \/\/ <-- Your specific app root view","            }","        }","    }","}","","struct ContentView: View {","","    @EnvironmentObject var keyboardContext: KeyboardContext","","    var body: View {","        YourMainContentView()","            .keyboardDictation(...) \/\/ <-- Keyboard-specific modifiers go here ","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Unlike the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","isActive":true},{"type":"text","text":", the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAppView","isActive":true},{"type":"text","text":" will also inject a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext","isActive":true},{"type":"text","text":" instance to let you visualize if the keyboard is enabled, if it has Full Access, etc."}]},{"anchor":"%F0%9F%91%91-KeyboardKit-Pro","type":"heading","level":2,"text":"👑 KeyboardKit Pro"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","isActive":true},{"type":"text","text":"-specific screens that let you quickly add keyboard-related features to your main app target."}]},{"type":"tabNavigator","tabs":[{"content":[{"columns":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"app-homescreen","type":"image"}]}],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen","type":"reference","isActive":true},{"text":" can be used as the main screen of a keyboard app, to quickly get your main app up and running.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The screen shows an app icon, a keyboard status section, links to other settings screens, custom header and footer views, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"This screen can be customized with the following view modifiers:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardAppHomeScreenLocalization(_:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardAppHomeScreenStyle(_:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardAppHomeScreenVisibility(_:)"}]}]}],"type":"unorderedList"}],"size":1}],"type":"row","numberOfColumns":2}],"title":"Home Screen"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The screen has view modifiers to let you toggle the visibility of certain parts of the screen, and style and localize them to fit your needs:"}]},{"type":"codeListing","code":["NavigationStack {","    KeyboardApp.HomeScreen(","        app: .myApp,","        appIcon: Image(.icon),","        header: {},","        footer: textFieldSection","    )","    .navigationTitle(\"KeyboardKit\")","}",".keyboardAppHomeScreenLocalization(","    .init(keyboardSectionFooter: \"Here's a custom footer text.\")",")",".keyboardAppHomeScreenStyle(","    .init(appIconSize: 150)",")",".keyboardAppHomeScreenVisibility(","    .init(keyboardSection: true)",")"],"syntax":"swift"},{"type":"aside","style":"important","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"You must use an App Group for settings to sync between your app and its keyboard. See the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Settings-Article","isActive":true},{"text":" article for more information.","type":"text"}]}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkit\/app-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkit\/app-article"]}],"references":{"Feature-Essentials.jpg":{"identifier":"Feature-Essentials.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon"},"Feature-AI.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg","traits":["1x","light"]}],"identifier":"Feature-AI.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Getting-Started-Article":{"type":"topic","abstract":[{"type":"text","text":"This developer guide describes how to get started with KeyboardKit."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","title":"Getting Started","role":"article","url":"\/documentation\/keyboardkit\/getting-started-article"},"Feature-Fonts.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg"}],"identifier":"Feature-Fonts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/HomeScreenLocalization":{"url":"\/documentation\/keyboardkit\/keyboardapp\/homescreenlocalization","navigatorTitle":[{"text":"HomeScreenLocalization","kind":"identifier"}],"abstract":[{"type":"text","text":"This type can be used to configure the localizations"},{"type":"text","text":" "},{"type":"text","text":"of a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen"},{"type":"text","text":"."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HomeScreenLocalization","kind":"identifier"}],"role":"symbol","type":"topic","title":"KeyboardApp.HomeScreenLocalization","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreenLocalization"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/State":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/State","url":"\/documentation\/keyboardkit\/keyboard\/state","abstract":[{"type":"text","text":"This type specifies global keyboard state."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"State"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"title":"Keyboard.State","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"images":[{"type":"card","identifier":"Feature-AI.jpg"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardStatusContext":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardStatusContext","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext","kind":"symbol","title":"KeyboardStatusContext","abstract":[{"text":"This class has observable, keyboard status-related state.","type":"text"}],"url":"\/documentation\/keyboardkit\/keyboardstatuscontext","navigatorTitle":[{"text":"KeyboardStatusContext","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"url":"\/documentation\/keyboardkit\/fonts-article","abstract":[{"type":"text","text":"This article describes KeyboardKit’s custom font support."}],"role":"article","type":"topic","title":"Fonts","kind":"article","images":[{"identifier":"Feature-Fonts.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article"},"Feature-Callouts.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg","traits":["1x","light"]}],"identifier":"Feature-Callouts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"url":"\/documentation\/keyboardkit\/host-article","abstract":[{"text":"This article describes how KeyboardKit Pro can identify and use the host application.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Host Application","images":[{"type":"card","identifier":"Feature-Host.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article"},"Feature-Host.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg"}],"identifier":"Feature-Host.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardAppHomeScreenVisibility(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardAppHomeScreenVisibility(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardapphomescreenvisibility(_:)","abstract":[{"type":"text","text":"Apply a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreenVisibility","type":"reference"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardAppHomeScreenVisibility","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A3AppV","text":"KeyboardApp"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A3AppV20HomeScreenVisibilityV","text":"HomeScreenVisibility"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"title":"keyboardAppHomeScreenVisibility(_:)","kind":"symbol","type":"topic"},"Feature-Feedback.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg","traits":["1x","light"]}],"identifier":"Feature-Feedback.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardAppHomeScreenStyle(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardAppHomeScreenStyle(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardapphomescreenstyle(_:)","abstract":[{"type":"text","text":"Apply a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreenStyle"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardAppHomeScreenStyle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"KeyboardApp","preciseIdentifier":"s:11KeyboardKit0A3AppV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HomeScreenStyle","preciseIdentifier":"s:11KeyboardKit0A3AppV15HomeScreenStyleV"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"title":"keyboardAppHomeScreenStyle(_:)","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/HomeScreenVisibility":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreenVisibility"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This type can be used to customize the visibility of"},{"type":"text","text":" "},{"type":"text","text":"any part of a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreenVisibility","role":"symbol","title":"KeyboardApp.HomeScreenVisibility","url":"\/documentation\/keyboardkit\/keyboardapp\/homescreenvisibility","navigatorTitle":[{"kind":"identifier","text":"HomeScreenVisibility"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Gestures-Article":{"type":"topic","images":[{"identifier":"Feature-Gestures.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"role":"article","title":"Gestures","url":"\/documentation\/keyboardkit\/gestures-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp":{"url":"\/documentation\/keyboardkit\/keyboardapp","abstract":[{"text":"This type can be used to define important properties for","type":"text"},{"text":" ","type":"text"},{"text":"your app, and is also a namespace for app-based features.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardApp"}],"type":"topic","title":"KeyboardApp","navigatorTitle":[{"kind":"identifier","text":"KeyboardApp"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","kind":"symbol"},"Feature-Dictation.jpg":{"identifier":"Feature-Dictation.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"abstract":[{"type":"text","text":"This article describes KeyboardKit’s clipboard support."}],"kind":"article","title":"Clipboard","type":"topic","images":[{"identifier":"Feature-Clipboard.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","url":"\/documentation\/keyboardkit\/clipboard-article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-Article":{"url":"\/documentation\/keyboardkit\/essentials-article","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"images":[{"identifier":"Feature-Essentials.jpg","type":"card"}],"type":"topic","title":"Essentials","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAppView":{"title":"KeyboardAppView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAppView"}],"abstract":[{"text":"This view can be used as the root view of a keyboard app,","type":"text"},{"text":" ","type":"text"},{"text":"to set up KeyboardKit for a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardAppView"}],"type":"topic","url":"\/documentation\/keyboardkit\/keyboardappview","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAppView","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardSettings/store":{"url":"\/documentation\/keyboardkit\/keyboardsettings\/store","abstract":[{"text":"The store that will be used by library settings.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUserDefaults","text":"UserDefaults"}],"type":"topic","title":"store","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/store","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"role":"article","type":"topic","kind":"article","title":"Callouts","images":[{"type":"card","identifier":"Feature-Callouts.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/HomeScreen":{"url":"\/documentation\/keyboardkit\/keyboardapp\/homescreen","navigatorTitle":[{"text":"HomeScreen","kind":"identifier"}],"abstract":[{"type":"text","text":"This screen can be used as the main home screen of a"},{"type":"text","text":" "},{"type":"text","text":"keyboard app that should look like iOS Settings."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HomeScreen","kind":"identifier"}],"role":"symbol","type":"topic","title":"KeyboardApp.HomeScreen","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen"},"Feature-Input.jpg":{"identifier":"Feature-Input.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","url":"\/documentation\/keyboardkit\/feedback-article","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"role":"article","title":"Feedback","kind":"article","type":"topic"},"Feature-Clipboard.jpg":{"identifier":"Feature-Clipboard.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg"}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-KeyboardView":{"type":"topic","images":[{"identifier":"Feature-Essentials-KeyboardView.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","kind":"article","title":"Essentials - KeyboardView","abstract":[{"type":"text","text":"This article describes the essential "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"type":"text","text":" and how to use and configure it."}],"url":"\/documentation\/keyboardkit\/essentials-keyboardview"},"Feature-External.jpg":{"identifier":"Feature-External.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon"},"Feature-Gestures.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Gestures.jpg"}],"identifier":"Feature-Gestures.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/UserDefaults/keyboardSettings":{"title":"keyboardSettings","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUserDefaults","text":"UserDefaults"}],"abstract":[{"text":"This is an alias for the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/store"},{"text":".","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/foundation\/userdefaults\/keyboardsettings","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/UserDefaults\/keyboardSettings","kind":"symbol"},"Feature-Essentials-KeyboardView.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials-KeyboardView.jpg","traits":["1x","light"]}],"identifier":"Feature-Essentials-KeyboardView.jpg"},"Feature-App.jpg":{"identifier":"Feature-App.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg","traits":["1x","light"]}],"type":"image","alt":null},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","title":"KeyboardView","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","role":"symbol","kind":"symbol","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"url":"\/documentation\/keyboardkit\/input-article","abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Input","images":[{"identifier":"Feature-Input.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"},"Feature-Settings.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Settings.jpg","traits":["1x","light"]}],"identifier":"Feature-Settings.jpg","type":"image","alt":"Feature Icon"},"Feature-Autocomplete.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg","traits":["1x","light"]}],"identifier":"Feature-Autocomplete.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardAppHomeScreenLocalization(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardAppHomeScreenLocalization(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardapphomescreenlocalization(_:)","abstract":[{"type":"text","text":"Apply a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreenLocalization"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardAppHomeScreenLocalization"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A3AppV","text":"KeyboardApp"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A3AppV22HomeScreenLocalizationV","text":"HomeScreenLocalization"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"title":"keyboardAppHomeScreenLocalization(_:)","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"url":"\/documentation\/keyboardkit\/external-keyboards-article","kind":"article","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","role":"article","type":"topic","images":[{"identifier":"Feature-External.jpg","type":"card"}],"title":"External Keyboards"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"url":"\/documentation\/keyboardkit\/emojis-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"role":"article","type":"topic","kind":"article","title":"Emojis","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController":{"title":"KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This is the main input controller type that is used in a","type":"text"},{"text":" ","type":"text"},{"text":"KeyboardKit-based keyboard extension.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","title":"Dictation","role":"article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"url":"\/documentation\/keyboardkit\/dictation-article"},"Feature-Emojis.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg"}],"identifier":"Feature-Emojis.jpg","type":"image","alt":"Feature Icon"},"Feature-Actions.jpg":{"identifier":"Feature-Actions.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","url":"\/documentation\/keyboardkit\/actions-article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"role":"article","kind":"article","title":"Actions","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"url":"\/documentation\/keyboardkit\/features-articles","abstract":[{"type":"text","text":"This article links to the various KeyboardKit features."}],"role":"collectionGroup","type":"topic","title":"Features","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"},"app-homescreen":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/app-homescreen.jpg"}],"type":"image","alt":"KeyboardApp.HomeScreen","identifier":"app-homescreen"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"url":"\/documentation\/keyboardkit\/autocomplete-article","title":"Autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/HomeScreenStyle":{"url":"\/documentation\/keyboardkit\/keyboardapp\/homescreenstyle","title":"KeyboardApp.HomeScreenStyle","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreenStyle","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This style can be used to customize the style of the"},{"type":"text","text":" "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen","type":"reference","isActive":true},{"type":"text","text":"."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HomeScreenStyle","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HomeScreenStyle","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Settings-Article":{"title":"Settings","abstract":[{"text":"This article describes the KeyboardKit settings engine and its available settings.","type":"text"}],"role":"article","images":[{"identifier":"Feature-Settings.jpg","type":"card"}],"type":"topic","url":"\/documentation\/keyboardkit\/settings-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Settings-Article","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":"KeyboardInputViewController","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/title"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/fragments","value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"op":"replace"},{"op":"replace","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/navigatorTitle"}]}]}