{"metadata":{"title":"Autocomplete","images":[{"type":"card","identifier":"Feature-Autocomplete.jpg"}],"roleHeading":"Article","modules":[{"name":"KeyboardKit"}],"role":"article"},"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Autocomplete is an important part of the typing experience, where word suggestions can be presented in a toolbar above the keyboard as the user types, and incorrectly text can be autocorrected.","type":"text"}]},{"inlineContent":[{"type":"text","text":"In KeyboardKit, an "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService","type":"reference"},{"type":"text","text":" can provide suggestions and predictions to the main "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext","type":"reference"},{"text":". Unlike other services, you must use KeyboardKit Pro to unlock local autocomplete or implement it yourself.","type":"text"}],"type":"paragraph"},{"type":"aside","style":"important","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"👑 Autocomplete requires a KeyboardKit Pro license with ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/autocomplete"},{"text":" support, unless you want to implement it from scratch. You can sign up for KeyboardKit Pro from the ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/keyboardkit.com"},{"text":".","type":"text"}]}]},{"anchor":"Developer-Guide","level":2,"type":"heading","text":"Developer Guide"},{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","type":"reference","isActive":true},{"type":"text","text":" developer guide has step-by-step instructions on how to set up and perform autocomplete in a keyboard extension."}],"type":"paragraph"},{"anchor":"Namespace","level":2,"type":"heading","text":"Namespace"},{"inlineContent":[{"text":"KeyboardKit has an ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete","type":"reference"},{"text":" namespace with autocomplete-related types, like a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Suggestion","type":"reference","isActive":true},{"text":" model, a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Toolbar","type":"reference","isActive":true},{"text":" view, etc.","type":"text"}],"type":"paragraph"},{"anchor":"Context","type":"heading","text":"Context","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has an "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext","isActive":true},{"type":"text","text":" class with observable state and auto-persisted autocomplete "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/settings","isActive":true},{"type":"text","text":", that can be used to customize the autocomplete behavior."}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext","isActive":true,"type":"reference"},{"text":" has properties like ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/autocorrectDictionary","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/emojiSuggestions","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/nextCharacterPredictions","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/settings","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/suggestions","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/suggestionsFromService","isActive":true,"type":"reference"},{"type":"text","text":", and functions like "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/nextCharacterPredictionForChar(_:)","type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/nextCharacterPredictionForAction(_:)","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/reset()","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/updateWithResult(_:)","type":"reference","isActive":true},{"type":"text","text":"."}]},{"inlineContent":[{"type":"text","text":"KeyboardKit automatically creates an instance of this class and registers it with its "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","type":"reference","isActive":true},{"type":"text","text":", and also injects it into the view environment."}],"type":"paragraph"},{"text":"Services","type":"heading","level":2,"anchor":"Services"},{"inlineContent":[{"type":"text","text":"In KeyboardKit, an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService"},{"type":"text","text":" can provide suggestions when the user types and the text input cursor moves in the text. A autocomplete service returns a result with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Result\/suggestions"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Result\/emojiSuggestions"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Result\/nextCharacterPredictions"},{"type":"text","text":", etc."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"KeyboardKit injects a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/disabled"},{"type":"text","text":" service into "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services","type":"reference"},{"text":" until you set up KeyboardKit Pro or inject your own service implementation.","type":"text"}],"type":"paragraph"},{"level":2,"type":"heading","text":"Settings","anchor":"Settings"},{"inlineContent":[{"text":"KeyboardKit has an ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings","type":"reference","isActive":true},{"text":" type with auto-persisted settings that can be used to customize the autocomplete.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings","isActive":true},{"type":"text","text":" has properties like "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/hasNextWordPredictionRequestApiKey","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isAutoIgnoreEnabled","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isAutocompleteEnabled","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isAutocorrectEnabled","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isEmojiAutocompleteEnabled","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isNextCharacterPredictionEnabled","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isNextWordPredictionEnabled","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/nextWordPredictionMethod","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/nextWordPredictionRequest","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/nextWordPredictionRequestApiKey","isActive":true,"type":"reference"},{"text":", and ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/suggestionsDisplayCount","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The context "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/settings"},{"type":"text","text":" is used by default. KeyboardKit Pro unlocks a feature-specific "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/SettingsScreen"},{"text":" that can be used to handle these settings.","type":"text"}],"type":"paragraph"},{"text":"Suggestions","level":2,"type":"heading","anchor":"Suggestions"},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Suggestion"},{"type":"text","text":" model is used to define what kind of a suggestion an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService"},{"type":"text","text":" returns. A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/SuggestionType\/regular"},{"type":"text","text":" suggestion is manually applied, while an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/SuggestionType\/autocorrect"},{"type":"text","text":" suggestion is automatically applied if a word delimiter is typed."}],"type":"paragraph"},{"inlineContent":[{"text":"You can also perform ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","isActive":true},{"text":"-based autocomplete, as well as next character & next word predictions.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"You can add custom autocorrections to ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/autocorrectDictionary","type":"reference","isActive":true},{"text":" to adjust ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService"},{"type":"text","text":" autocorrection."}],"type":"paragraph"},{"text":"Views","level":2,"type":"heading","anchor":"Views"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete","isActive":true,"type":"reference"},{"type":"text","text":" namespace has autocomplete-specific views, that can be used to mimic native autocomplete toolbars and items."}]},{"type":"tabNavigator","tabs":[{"title":"Toolbar","content":[{"numberOfColumns":2,"columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"autocomplete-toolbar"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete","type":"reference"},{"text":".","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Toolbar","type":"reference"},{"text":" can be show suggestions as the keyboard autocompletes the typed text.","type":"text"}]},{"inlineContent":[{"text":"The view can be styled with a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarStyle","isActive":true},{"text":", which is applied with the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/autocompleteToolbarStyle(_:)","isActive":true},{"type":"text","text":" modifier."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Scrolling can be enabled with a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarScrollMode","isActive":true,"type":"reference"},{"text":", which is applied with the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/autocompleteScrollMode(_:)","isActive":true,"type":"reference"},{"type":"text","text":" modifier."}]}],"size":1}],"type":"row"}]}]},{"type":"heading","text":"👑 KeyboardKit Pro","level":2,"anchor":"%F0%9F%91%91-KeyboardKit-Pro"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro unlocks a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService","isActive":true,"type":"reference"},{"text":" and injects it into ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services","isActive":true},{"type":"text","text":" when you set up KeyboardKit Pro. This service can perform local and remote autocomplete, next character and word predictions, emoji autocomplete, etc."}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro also unlocks a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/SettingsScreen","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emoji"},{"text":".","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emoji\/ColonSearch","type":"reference","isActive":true},{"type":"text","text":" that can add emoji suggestions to an autocomplete result, as well as remote "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/NextWordPredictionMethod\/claude","type":"reference","isActive":true},{"type":"text","text":" and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/NextWordPredictionMethod\/openAI"},{"type":"text","text":" next word prediction requests."}]},{"type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"These services and utilities require a KeyboardKit Pro license that unlocks the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/autocomplete"},{"text":" feature. The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/SettingsScreen"},{"text":" also requires the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/settingsScreens","type":"reference","isActive":true},{"type":"text","text":" feature."}]}],"style":"important"},{"anchor":"Screens","text":"Screens","level":3,"type":"heading"},{"inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks an "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete","isActive":true},{"type":"text","text":"-specific "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/SettingsScreen"},{"type":"text","text":" that can be used to manage autocomplete-related settings:"}],"type":"paragraph"},{"tabs":[{"title":"Settings Screen","content":[{"type":"row","columns":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"autocomplete-settingsscreen","type":"image"}]}],"size":1},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen","type":"reference","isActive":true},{"text":" template will automatically link to this screen if the current license unlocks the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/autocomplete","type":"reference","isActive":true},{"text":" feature.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"This screen can be customized with the following view modifiers:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/autocompleteSettingsScreenLocalization(_:)","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/autocompleteSettingsScreenVisibility(_:)"}]}]}]}]}],"numberOfColumns":2}]}],"type":"tabNavigator"},{"level":3,"type":"heading","anchor":"On-device-Autocomplete","text":"On-device Autocomplete"},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService"},{"text":" performs on-device autocomplete by deafult. It works offline, doesn’t require Full Access, integrates with system services like the local lexicon, and supports the following languages:","type":"text"}],"type":"paragraph"},{"tabs":[{"title":"iOS, iPadOS, visionOS","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Arabic, Arabic, Najdi, Bulgarian (Bulgaria), Czech (Czechia), Danish (Denmark), Dutch (Netherlands), English (Australia), English (Canada), English (India), English (New Zealand), English (Singapore), English (South Africa), English (United Kingdom), English (United States), Finnish (Finland), French (France), German (Germany), Greek (Greece), Hebrew (Israel), Hindi, Hungarian (Hungary), Icelandic (Iceland), Indonesian (Indonesia), Irish (Ireland), Italian (Italy), Lithuanian (Lithuania), Norwegian Bokmål (Norway), Norwegian Nynorsk, Polish (Poland), Portuguese (Brazil), Portuguese (Portugal), Punjabi, Romanian (Romania), Russian (Russia), Slovenian (Slovenia), Spanish (Mexico), Spanish (Spain), Swedish (Sweden), Telugu, Turkish (Türkiye), Ukrainian (Ukraine), Vietnamese (Vietnam)"}]}]},{"title":"macOS","content":[{"inlineContent":[{"type":"text","text":"Arabic, Arabic, Najdi, Bulgarian, Czech, Danish, Dutch, English, English (Australia), English (Canada), English (India), English (Japan), English (New Zealand), English (Singapore), English (South Africa), English (United Kingdom), Finnish, French, German, Greek, Hebrew, Hindi, Hungarian, Icelandic, Indonesian, Irish, Italian, Korean, Lithuanian, Norwegian Bokmål, Norwegian Nynorsk, Polish, Portuguese (Brazil), Portuguese (Portugal), Punjabi, Romanian, Russian, Slovenian, Spanish, Swedish, Telugu, Turkish, Ukrainian, Vietnamese"}],"type":"paragraph"}]}],"type":"tabNavigator"},{"inlineContent":[{"type":"text","text":"The service will perform next-character predictions based on the autocomplete result, to slightly increase the tap area of more probable "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView"},{"type":"text","text":" keys, and perform emoji autocomplete if "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isEmojiAutocompleteEnabled"},{"type":"text","text":" is enabled."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/learn(_:)"},{"type":"text","text":" any suggestions to permanently add them to the device dictionary, and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/unlearn(_:)"},{"type":"text","text":" suggestions to remove them from that dictionary. You can temporarily "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/ignore(_:)"},{"type":"text","text":" suggestions, and undo it with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/removeIgnoredWord(_:)"},{"type":"text","text":"."}]},{"style":"important","type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The on-device tools that are provided by Apple are not as good as the ones in the native keyboards. Make sure to test this feature in the demo app to ensure that is is good enough for your needs, before you purchase a license."}]}]},{"type":"heading","level":3,"text":"Remote Autocomplete","anchor":"Remote-Autocomplete"},{"type":"paragraph","inlineContent":[{"text":"Since the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService","type":"reference"},{"text":" doesn’t supports all locales, you can use a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/RemotePredictionRequest","type":"reference"},{"text":" to fill in the missing parts, by integrating with a remote service.","type":"text"}]},{"inlineContent":[{"type":"text","text":"The easiest way is to set the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService\/remoteAutocompleteRequest","type":"reference","isActive":true},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService\/remoteNextWordPredictionRequest","type":"reference","isActive":true},{"type":"text","text":" properties, which let you enable remote autocomplete without having to subclass the service."}],"type":"paragraph"},{"inlineContent":[{"text":"If you only want to use remote autocomplete for some locales, then subclassing ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService"},{"text":" is more flexible.","type":"text"}],"type":"paragraph"},{"name":"Important","content":[{"inlineContent":[{"type":"text","text":"Make sure that you prompt the user and get a consent to use remote autocomplete before sending typed text to a remote service!"}],"type":"paragraph"}],"type":"aside","style":"important"},{"type":"heading","text":"Next Character Prediction","level":3,"anchor":"Next-Character-Prediction"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService","isActive":true},{"type":"text","text":" will perform next-character predictions based on the final autocomplete result, to increase the tap area of more probable "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","isActive":true},{"type":"text","text":" keys."}]},{"type":"heading","level":3,"text":"Next Word Prediction","anchor":"Next-Word-Prediction"},{"type":"paragraph","inlineContent":[{"text":"Apple’s native next word prediction stopped working in iOS 16. KeyboardKit Pro therefore unlocks ways to perform next word prediction via 3rd party integrations. The easiest way is to add a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/NextWordPredictionMethod\/claude","isActive":true,"type":"reference"},{"text":" or ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/NextWordPredictionMethod\/openAI","isActive":true,"type":"reference"},{"text":" request to your ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","isActive":true,"type":"reference"},{"text":"’s ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/autocomplete","isActive":true,"type":"reference"},{"text":" config.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can also set the service’s "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService\/remoteNextWordPredictionRequest"},{"type":"text","text":" explicitly, and even let users user their own service account with the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/nextWordPredictionRequestType"},{"type":"text","text":" and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/nextWordPredictionRequestApiKey"},{"type":"text","text":" settings."}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"AI-based next word prediction requires Full Access. It’s disabled by default, to avoid sending typed text to 3rd parties without the user’s explicit consent. When a user has given its explicit content, you can enable it with ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isNextWordPredictionEnabled"},{"text":".","type":"text"}]}],"name":"Important","type":"aside","style":"important"},{"type":"heading","level":3,"text":"Emoji autocomplete","anchor":"Emoji-autocomplete"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks an emoji "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emoji\/ColonSearch"},{"type":"text","text":" engine that makes it possible to search for emojis by starting the current word with a colon. This is used by "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService","isActive":true},{"type":"text","text":" when the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isEmojiAutocompleteEnabled","isActive":true},{"type":"text","text":" setting is true."}]},{"name":"Important","type":"aside","content":[{"inlineContent":[{"text":"Emoji autocomplete requires a KeyboardKit Pro license that unlocks both the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/autocomplete"},{"type":"text","text":" and the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/emojiAddons","isActive":true},{"text":" features.","type":"text"}],"type":"paragraph"}],"style":"important"}]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"topicSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete"],"anchor":"Developer-Guide","title":"Developer Guide"},{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings"],"anchor":"Types","title":"Types"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article"],"generated":true}],"abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}],"variants":[{"paths":["\/documentation\/keyboardkit\/autocomplete-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/autocomplete-article"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article"},"references":{"Feature-Navigation.jpg":{"type":"image","identifier":"Feature-Navigation.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Navigation.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Layout-Article":{"title":"Layout","url":"\/documentation\/keyboardkit\/layout-article","kind":"article","images":[{"identifier":"Feature-Layout.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteContext/settings":{"title":"settings","abstract":[{"type":"text","text":"Auto-persisted autocomplete settings."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settings","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutocompleteSettings","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit20AutocompleteSettingsV"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocompletecontext\/settings","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/settings"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","title":"Input","url":"\/documentation\/keyboardkit\/input-article","images":[{"type":"card","identifier":"Feature-Input.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","kind":"article"},"Feature-App.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon","identifier":"Feature-App.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteSettings/isAutoIgnoreEnabled":{"url":"\/documentation\/keyboardkit\/autocompletesettings\/isautoignoreenabled","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isAutoIgnoreEnabled","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAutoIgnoreEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isAutoIgnoreEnabled","abstract":[{"text":"Whether to automatically ignore adjusted suggestions, by default ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteSettings/hasNextWordPredictionRequestApiKey":{"title":"hasNextWordPredictionRequestApiKey","abstract":[{"text":"Whether the user has provided a next word prediction","type":"text"},{"text":" ","type":"text"},{"text":"request API key.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasNextWordPredictionRequestApiKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocompletesettings\/hasnextwordpredictionrequestapikey","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/hasNextWordPredictionRequestApiKey"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/emojiAddons":{"title":"ProFeature.emojiAddons","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emojiAddons","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/profeature\/emojiaddons","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/emojiAddons"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","title":"Callouts","type":"topic","images":[{"identifier":"Feature-Callouts.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"text":"This article describes the KeyboardKit callout engine.","type":"text"}],"role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/autocomplete":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/autocomplete","abstract":[{"type":"text","text":"The autocomplete configuration to use."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocomplete","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A3AppV25AutocompleteConfigurationV","text":"AutocompleteConfiguration","kind":"typeIdentifier"}],"title":"autocomplete","url":"\/documentation\/keyboardkit\/keyboardapp\/autocomplete","type":"topic","kind":"symbol"},"Feature-Dictation.jpg":{"alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg"}],"type":"image","identifier":"Feature-Dictation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteContext/autocorrectDictionary":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/autocorrectDictionary","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocorrectDictionary","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Autocomplete","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit12AutocompleteV"},{"text":".","kind":"text"},{"text":"TextReplacementDictionary","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit12AutocompleteV25TextReplacementDictionaryV"}],"abstract":[{"type":"text","text":"This dictionary can be used to define autocorrection"},{"type":"text","text":" "},{"type":"text","text":"replacements for various locales."}],"role":"symbol","title":"autocorrectDictionary","url":"\/documentation\/keyboardkit\/autocompletecontext\/autocorrectdictionary","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emoji":{"abstract":[{"type":"text","text":"This type represents an emoji character and is used as a"},{"type":"text","text":" "},{"type":"text","text":"namespace for emoji-related types and functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emoji","kind":"symbol","type":"topic","role":"symbol","title":"Emoji","url":"\/documentation\/keyboardkit\/emoji","navigatorTitle":[{"text":"Emoji","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Emoji","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteSettings/nextWordPredictionMethod":{"type":"topic","url":"\/documentation\/keyboardkit\/autocompletesettings\/nextwordpredictionmethod","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextWordPredictionMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Autocomplete","preciseIdentifier":"s:11KeyboardKit12AutocompleteV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"NextWordPredictionMethod","preciseIdentifier":"s:11KeyboardKit12AutocompleteV24NextWordPredictionMethodO","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/nextWordPredictionMethod","abstract":[{"type":"text","text":"A custom, user-specified next word predicton method."}],"kind":"symbol","title":"nextWordPredictionMethod","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","role":"article","kind":"article","title":"App Utilities","url":"\/documentation\/keyboardkit\/app-article","type":"topic","images":[{"type":"card","identifier":"Feature-App.jpg"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteSettings/suggestionsDisplayCount":{"title":"suggestionsDisplayCount","abstract":[{"type":"text","text":"The number of autocomplete suggestions to display, by default "},{"code":"3","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestionsDisplayCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocompletesettings\/suggestionsdisplaycount","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/suggestionsDisplayCount"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteService/unlearn(_:)":{"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/unlearn(_:)","title":"unlearn(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unlearn","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Autocomplete","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit12AutocompleteV"},{"text":".","kind":"text"},{"text":"Suggestion","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit12AutocompleteV10SuggestionV"},{"text":")","kind":"text"}],"url":"\/documentation\/keyboardkit\/autocompleteservice\/unlearn(_:)","abstract":[{"text":"Make the service unlearn a certain suggestion.","type":"text"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/autocompleteToolbarStyle(_:)":{"abstract":[{"type":"text","text":"Apply a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarStyle","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"autocompleteToolbarStyle"},{"text":"(","kind":"text"},{"text":"Autocomplete","preciseIdentifier":"s:11KeyboardKit12AutocompleteV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ToolbarStyle","preciseIdentifier":"s:11KeyboardKit12AutocompleteV12ToolbarStyleV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"title":"autocompleteToolbarStyle(_:)","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/autocompleteToolbarStyle(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/autocompletetoolbarstyle(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteService/learn(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/learn(_:)","type":"topic","url":"\/documentation\/keyboardkit\/autocompleteservice\/learn(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"learn"},{"kind":"text","text":"("},{"preciseIdentifier":"s:11KeyboardKit12AutocompleteV","kind":"typeIdentifier","text":"Autocomplete"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11KeyboardKit12AutocompleteV10SuggestionV","kind":"typeIdentifier","text":"Suggestion"},{"kind":"text","text":")"}],"role":"symbol","title":"learn(_:)","abstract":[{"text":"Make the service learn a certain suggestion.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/autocompleteSettingsScreenLocalization(_:)":{"type":"topic","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/autocompletesettingsscreenlocalization(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocompleteSettingsScreenLocalization","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Autocomplete","preciseIdentifier":"s:11KeyboardKit12AutocompleteV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SettingsScreenLocalization","preciseIdentifier":"s:11KeyboardKit12AutocompleteV26SettingsScreenLocalizationV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/autocompleteSettingsScreenLocalization(_:)","abstract":[{"type":"text","text":"Apply a custom screen localization."}],"kind":"symbol","title":"autocompleteSettingsScreenLocalization(_:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"title":"External Keyboards","url":"\/documentation\/keyboardkit\/external-keyboards-article","images":[{"type":"card","identifier":"Feature-External.jpg"}],"kind":"article","type":"topic","role":"article"},"Feature-Feedback.jpg":{"identifier":"Feature-Feedback.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteContext/nextCharacterPredictionForAction(_:)":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/nextCharacterPredictionForAction(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextCharacterPredictionForAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"KeyboardAction","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A6ActionO"},{"text":") -> ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"text":"Get a 0-1 next character prediction for an ","type":"text"},{"code":"action","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"nextCharacterPredictionForAction(_:)","url":"\/documentation\/keyboardkit\/autocompletecontext\/nextcharacterpredictionforaction(_:)","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteService/ignore(_:)":{"type":"topic","url":"\/documentation\/keyboardkit\/autocompleteservice\/ignore(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"ignore","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:11KeyboardKit12AutocompleteV","kind":"typeIdentifier","text":"Autocomplete"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11KeyboardKit12AutocompleteV10SuggestionV","kind":"typeIdentifier","text":"Suggestion"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/ignore(_:)","abstract":[{"text":"Make the service ignore a certain suggestion.","type":"text"}],"kind":"symbol","title":"ignore(_:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteContext/suggestions":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/suggestions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"suggestions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Autocomplete","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit12AutocompleteV"},{"text":".","kind":"text"},{"text":"Suggestion","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit12AutocompleteV10SuggestionV"},{"text":"]","kind":"text"}],"abstract":[{"text":"The suggestions that should be presented to the user,","type":"text"},{"text":" ","type":"text"},{"text":"which is an aggregate of the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/suggestionsFromService","isActive":true,"type":"reference"},{"text":".","type":"text"}],"role":"symbol","title":"suggestions","url":"\/documentation\/keyboardkit\/autocompletecontext\/suggestions","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emoji/ColonSearch":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColonSearch"}],"kind":"symbol","url":"\/documentation\/keyboardkit\/emoji\/colonsearch","role":"symbol","abstract":[{"text":"This class can be used to set up emoji search, where","type":"text"},{"text":" ","type":"text"},{"code":":smile","type":"codeVoice"},{"text":" can be used to get a smiling emoji.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emoji\/ColonSearch","title":"Emoji.ColonSearch","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ColonSearch"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteSettings/isEmojiAutocompleteEnabled":{"abstract":[{"text":"Whether emoji autocomplete is enabled, by default ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isEmojiAutocompleteEnabled","url":"\/documentation\/keyboardkit\/autocompletesettings\/isemojiautocompleteenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEmojiAutocompleteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isEmojiAutocompleteEnabled","kind":"symbol","role":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/emojis-article","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","title":"Emojis","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article"},"Feature-AI.jpg":{"identifier":"Feature-AI.jpg","type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteSettings/isNextWordPredictionEnabled":{"title":"isNextWordPredictionEnabled","abstract":[{"text":"Whether next word prediction is enabled, by default ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNextWordPredictionEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocompletesettings\/isnextwordpredictionenabled","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isNextWordPredictionEnabled"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteSettings/nextWordPredictionRequestType":{"abstract":[],"deprecated":true,"title":"nextWordPredictionRequestType","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextWordPredictionRequestType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit12AutocompleteV","text":"Autocomplete","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit12AutocompleteV24NextWordPredictionMethodO","text":"NextWordPredictionMethod","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/keyboardkit\/autocompletesettings\/nextwordpredictionrequesttype","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/nextWordPredictionRequestType"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteSettings/nextWordPredictionRequestApiKey":{"type":"topic","url":"\/documentation\/keyboardkit\/autocompletesettings\/nextwordpredictionrequestapikey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextWordPredictionRequestApiKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/nextWordPredictionRequestApiKey","abstract":[{"text":"A custom, user-specified next word predicton request API key.","type":"text"}],"kind":"symbol","title":"nextWordPredictionRequestApiKey","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/Suggestion":{"url":"\/documentation\/keyboardkit\/autocomplete\/suggestion","abstract":[{"type":"text","text":"This type represents an autocomplete suggestion that"},{"type":"text","text":" "},{"type":"text","text":"is returned by an "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Suggestion","title":"Autocomplete.Suggestion","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Suggestion","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Suggestion","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteSettings/nextWordPredictionRequest":{"title":"nextWordPredictionRequest","abstract":[{"text":"Try to build a next word prediction request from the","type":"text"},{"text":" ","type":"text"},{"text":"selected request type and provided API key, if any.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextWordPredictionRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Autocomplete","preciseIdentifier":"s:11KeyboardKit12AutocompleteV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"RemotePredictionRequest","preciseIdentifier":"s:11KeyboardKit12AutocompleteV23RemotePredictionRequestV"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocompletesettings\/nextwordpredictionrequest","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/nextWordPredictionRequest"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/NextWordPredictionMethod/claude":{"type":"topic","url":"\/documentation\/keyboardkit\/autocomplete\/nextwordpredictionmethod\/claude","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"claude"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/NextWordPredictionMethod\/claude","abstract":[{"text":"Perform next word prediction with the Claude API.","type":"text"}],"kind":"symbol","title":"Autocomplete.NextWordPredictionMethod.claude","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"url":"\/documentation\/keyboardkit\/clipboard-article","abstract":[{"text":"This article describes KeyboardKit’s clipboard support.","type":"text"}],"images":[{"type":"card","identifier":"Feature-Clipboard.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","title":"Clipboard","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteContext/updateWithResult(_:)":{"title":"updateWithResult(_:)","abstract":[{"text":"Update the context with a certain result.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateWithResult"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit12AutocompleteV","text":"Autocomplete"},{"kind":"text","text":"."},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit12AutocompleteV6ResultV"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocompletecontext\/updatewithresult(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/updateWithResult(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/Result/suggestions":{"title":"suggestions","abstract":[{"type":"text","text":"Suggestions for the provided texts."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"suggestions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Suggestion","preciseIdentifier":"s:11KeyboardKit12AutocompleteV10SuggestionV","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocomplete\/result\/suggestions","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Result\/suggestions"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteContext/reset()":{"title":"reset()","abstract":[{"text":"Reset the context.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reset","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocompletecontext\/reset()","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/reset()"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"kind":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","role":"article","images":[{"identifier":"Feature-Host.jpg","type":"card"}],"title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro lets you define and use a host application."}],"url":"\/documentation\/keyboardkit\/host-article"},"Feature-Actions.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg","traits":["1x","light"]}],"identifier":"Feature-Actions.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/autocompleteSettingsScreenVisibility(_:)":{"type":"topic","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/autocompletesettingsscreenvisibility(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocompleteSettingsScreenVisibility","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Autocomplete","preciseIdentifier":"s:11KeyboardKit12AutocompleteV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SettingsScreenVisibility","preciseIdentifier":"s:11KeyboardKit12AutocompleteV24SettingsScreenVisibilityV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/autocompleteSettingsScreenVisibility(_:)","abstract":[{"type":"text","text":"Apply a custom screen visibility."}],"kind":"symbol","title":"autocompleteSettingsScreenVisibility(_:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"url":"\/documentation\/keyboardkit\/feedback-article","type":"topic","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"title":"Feedback","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Localization-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit localization engine."}],"url":"\/documentation\/keyboardkit\/localization-article","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","title":"Localization","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"kind":"symbol","title":"KeyboardView","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"autocomplete-toolbar":{"alt":"AutocompleteToolbar","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/autocomplete-toolbar.jpg"}],"identifier":"autocomplete-toolbar"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/Toolbar":{"url":"\/documentation\/keyboardkit\/autocomplete\/toolbar","abstract":[{"text":"This toolbar can be added above the keyboard to show","type":"text"},{"text":" ","type":"text"},{"text":"autocomplete suggestions as the user types.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Toolbar","title":"Autocomplete.Toolbar","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Toolbar","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Toolbar","kind":"identifier"}],"role":"symbol"},"Feature-Layout.jpg":{"alt":"Feature Icon","identifier":"Feature-Layout.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Layout.jpg","traits":["1x","light"]}],"type":"image"},"autocomplete-settingsscreen":{"alt":"Autocomplete.SettingsScreen","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/autocomplete-settingsscreen.jpg","traits":["1x","light"]}],"identifier":"autocomplete-settingsscreen","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/actions-article","role":"article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"title":"Actions"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/SettingsScreen":{"abstract":[{"text":"This screen can be used as a settings screen for any","type":"text"},{"text":" ","type":"text"},{"text":"dictation-related keyboard settings.","type":"text"}],"url":"\/documentation\/keyboardkit\/dictation\/settingsscreen","title":"Dictation.SettingsScreen","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/SettingsScreen","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsScreen"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SettingsScreen"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteContext/emojiSuggestions":{"title":"emojiSuggestions","abstract":[{"text":"The characters that are more likely to be typed next.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emojiSuggestions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Autocomplete","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit12AutocompleteV"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit12AutocompleteV10SuggestionV","kind":"typeIdentifier","text":"Suggestion"},{"kind":"text","text":"]"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocompletecontext\/emojisuggestions","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/emojiSuggestions"},"Feature-Localization.jpg":{"alt":"Feature Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg"}],"identifier":"Feature-Localization.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteContext":{"navigatorTitle":[{"text":"AutocompleteContext","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext","type":"topic","url":"\/documentation\/keyboardkit\/autocompletecontext","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutocompleteContext","kind":"identifier"}],"role":"symbol","title":"AutocompleteContext","abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"text":"for keyboard autocomplete.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/StandardAutocompleteService/remoteAutocompleteRequest":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteAutocompleteRequest","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit12AutocompleteV23RemotePredictionRequestV","text":"RemotePredictionRequest","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService\/remoteAutocompleteRequest","title":"remoteAutocompleteRequest","url":"\/documentation\/keyboardkit\/autocomplete\/standardautocompleteservice\/remoteautocompleterequest","abstract":[{"text":"A remote autocomplete request.","type":"text"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteContext/nextCharacterPredictionForChar(_:)":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/nextCharacterPredictionForChar(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextCharacterPredictionForChar","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Get a 0-1 next character prediction for a "},{"type":"codeVoice","code":"char"},{"type":"text","text":"."}],"role":"symbol","title":"nextCharacterPredictionForChar(_:)","url":"\/documentation\/keyboardkit\/autocompletecontext\/nextcharacterpredictionforchar(_:)","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/autocomplete":{"title":"ProFeature.autocomplete","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocomplete","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/profeature\/autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/autocomplete"},"Feature-Fonts.jpg":{"alt":"Feature Icon","identifier":"Feature-Fonts.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteSettings/isAutocorrectEnabled":{"type":"topic","url":"\/documentation\/keyboardkit\/autocompletesettings\/isautocorrectenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAutocorrectEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isAutocorrectEnabled","abstract":[{"text":"Whether autocorrect is enabled, by default ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","title":"isAutocorrectEnabled","role":"symbol"},"Feature-External.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg"}],"alt":"Feature Icon","type":"image","identifier":"Feature-External.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteSettings/isAutocompleteEnabled":{"title":"isAutocompleteEnabled","abstract":[{"type":"text","text":"Whether autocomplete is enabled, by default "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAutocompleteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocompletesettings\/isautocompleteenabled","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isAutocompleteEnabled"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","title":"KeyboardApp","navigatorTitle":[{"text":"KeyboardApp","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/keyboardapp","abstract":[{"type":"text","text":"This type can be used to define important properties for"},{"type":"text","text":" "},{"type":"text","text":"your app, and is also a namespace for app-based features."}],"role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardApp","kind":"identifier"}]},"Feature-Autocomplete.jpg":{"identifier":"Feature-Autocomplete.jpg","alt":"Article Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/SuggestionType/autocorrect":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocorrect","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/SuggestionType\/autocorrect","abstract":[{"type":"text","text":"An autocorrect suggestion is applied when a user"},{"type":"text","text":" "},{"type":"text","text":"types a word or sentence delimiter."}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocomplete\/suggestiontype\/autocorrect","title":"Autocomplete.SuggestionType.autocorrect"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/HomeScreen":{"navigatorTitle":[{"text":"HomeScreen","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen","type":"topic","url":"\/documentation\/keyboardkit\/keyboardapp\/homescreen","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HomeScreen","kind":"identifier"}],"role":"symbol","title":"KeyboardApp.HomeScreen","abstract":[{"type":"text","text":"This screen can be used as the main home screen of a"},{"type":"text","text":" "},{"type":"text","text":"keyboard app that should look like iOS Settings."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","type":"topic","abstract":[{"text":"This article describes KeyboardKit’s custom font support.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/fonts-article","role":"article","images":[{"type":"card","identifier":"Feature-Fonts.jpg"}],"title":"Fonts"},"Feature-Emojis.jpg":{"alt":"Feature Icon","identifier":"Feature-Emojis.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"url":"\/documentation\/keyboardkit\/dictation-article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","type":"topic","kind":"article","role":"article"},"Feature-Input.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg"}],"alt":"Feature Icon","type":"image","identifier":"Feature-Input.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/autocompleteScrollMode(_:)":{"title":"autocompleteScrollMode(_:)","abstract":[{"text":"Apply a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarScrollMode","type":"reference","isActive":true},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"autocompleteScrollMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Autocomplete","preciseIdentifier":"s:11KeyboardKit12AutocompleteV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ToolbarScrollMode","preciseIdentifier":"s:11KeyboardKit12AutocompleteV17ToolbarScrollModeO"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/autocompletescrollmode(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/autocompleteScrollMode(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteService/disabled":{"type":"topic","url":"\/documentation\/keyboardkit\/autocompleteservice\/disabled","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" is "},{"type":"codeVoice","code":"Autocomplete.DisabledAutocompleteService"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/disabled","abstract":[{"type":"text","text":"Create a disabled service instance."}],"kind":"symbol","title":"disabled","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","images":[{"type":"card","identifier":"Feature-AI.jpg"}],"kind":"article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteSettings/isNextCharacterPredictionEnabled":{"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings\/isNextCharacterPredictionEnabled","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNextCharacterPredictionEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isNextCharacterPredictionEnabled","url":"\/documentation\/keyboardkit\/autocompletesettings\/isnextcharacterpredictionenabled","abstract":[{"type":"text","text":"Whether next character prediction is enabled, by default "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteService":{"abstract":[{"type":"text","text":"This protocol can be implemented by any type that can be"},{"type":"text","text":" "},{"type":"text","text":"used perform autocomplete as the user types."}],"kind":"symbol","title":"AutocompleteService","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutocompleteService"}],"url":"\/documentation\/keyboardkit\/autocompleteservice","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutocompleteService"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/services":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V"},{"text":".","kind":"text"},{"text":"Services","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V8ServicesC"}],"abstract":[{"type":"text","text":"Keyboard-specific services."}],"role":"symbol","title":"services","kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/services"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteContext/nextCharacterPredictions":{"title":"nextCharacterPredictions","abstract":[{"text":"The characters that are more likely to be typed next.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextCharacterPredictions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Character","kind":"typeIdentifier","preciseIdentifier":"s:SJ"},{"text":" : ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"]","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocompletecontext\/nextcharacterpredictions","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/nextCharacterPredictions"},"Feature-Clipboard.jpg":{"identifier":"Feature-Clipboard.jpg","type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/ToolbarStyle":{"navigatorTitle":[{"kind":"identifier","text":"ToolbarStyle"}],"type":"topic","kind":"symbol","title":"Autocomplete.ToolbarStyle","abstract":[{"text":"This style can be used to modify the visual style of","type":"text"},{"text":" ","type":"text"},{"text":"the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Toolbar","type":"reference"},{"text":" component.","type":"text"}],"url":"\/documentation\/keyboardkit\/autocomplete\/toolbarstyle","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToolbarStyle"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/StandardAutocompleteService/remoteNextWordPredictionRequest":{"title":"remoteNextWordPredictionRequest","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService\/remoteNextWordPredictionRequest","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteNextWordPredictionRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit12AutocompleteV23RemotePredictionRequestV","text":"RemotePredictionRequest"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A remote next word prediction request."}],"kind":"symbol","url":"\/documentation\/keyboardkit\/autocomplete\/standardautocompleteservice\/remotenextwordpredictionrequest","type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/state":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","title":"state","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/state","abstract":[{"type":"text","text":"Keyboard-specific state."}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","preciseIdentifier":"s:11KeyboardKit0A0V","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"s:11KeyboardKit0A0V5StateC","kind":"typeIdentifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteSettings":{"abstract":[{"text":"This type has auto-persisted autocomplete settings.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteSettings","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocompletesettings","title":"AutocompleteSettings","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutocompleteSettings"}],"navigatorTitle":[{"kind":"identifier","text":"AutocompleteSettings"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/SettingsScreen":{"title":"Autocomplete.SettingsScreen","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/SettingsScreen","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsScreen","kind":"identifier"}],"abstract":[{"type":"text","text":"This screen can be used as a settings screen for any"},{"type":"text","text":" "},{"type":"text","text":"autocomplete-related keyboard settings."}],"url":"\/documentation\/keyboardkit\/autocomplete\/settingsscreen","kind":"symbol","navigatorTitle":[{"text":"SettingsScreen","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/Result/nextCharacterPredictions":{"url":"\/documentation\/keyboardkit\/autocomplete\/result\/nextcharacterpredictions","abstract":[{"text":"Next character predictions for the provided text, if any.","type":"text"}],"title":"nextCharacterPredictions","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Result\/nextCharacterPredictions","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextCharacterPredictions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Character","preciseIdentifier":"s:SJ","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"kind":"symbol","role":"symbol"},"Feature-Callouts.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Callouts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/StandardAutocompleteService":{"url":"\/documentation\/keyboardkit\/autocomplete\/standardautocompleteservice","kind":"symbol","navigatorTitle":[{"text":"StandardAutocompleteService","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StandardAutocompleteService","kind":"identifier"}],"title":"Autocomplete.StandardAutocompleteService","type":"topic","abstract":[{"type":"text","text":"This service can be used to perform autocomplete and"},{"type":"text","text":" "},{"type":"text","text":"autocorrect directly on device."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Navigation-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/navigation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"images":[{"identifier":"Feature-Navigation.jpg","type":"card"}],"kind":"article","title":"Navigation","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/RemotePredictionRequest":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RemotePredictionRequest"}],"abstract":[{"type":"text","text":"This type can be used to perform remote autocomplete"},{"type":"text","text":" "},{"type":"text","text":"requests of various types."}],"title":"Autocomplete.RemotePredictionRequest","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/RemotePredictionRequest","type":"topic","kind":"symbol","url":"\/documentation\/keyboardkit\/autocomplete\/remotepredictionrequest","navigatorTitle":[{"text":"RemotePredictionRequest","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/SuggestionType/regular":{"title":"Autocomplete.SuggestionType.regular","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/SuggestionType\/regular","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"regular"}],"abstract":[{"type":"text","text":"A regular suggestion is applied when it’s tapped."}],"kind":"symbol","url":"\/documentation\/keyboardkit\/autocomplete\/suggestiontype\/regular","type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Autocomplete":{"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/developer-autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","abstract":[{"text":"This developer guide describes how to set up and customize autocomplete.","type":"text"}],"type":"topic","role":"article","kind":"article","title":"Autocomplete"},"Feature-Host.jpg":{"type":"image","alt":"Feature Icon","identifier":"Feature-Host.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/NextWordPredictionMethod/openAI":{"title":"Autocomplete.NextWordPredictionMethod.openAI","abstract":[{"type":"text","text":"Perform next word prediction with the OpenAI API."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openAI","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocomplete\/nextwordpredictionmethod\/openai","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/NextWordPredictionMethod\/openAI"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/ToolbarScrollMode":{"url":"\/documentation\/keyboardkit\/autocomplete\/toolbarscrollmode","abstract":[{"type":"text","text":"This enum defines various "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Toolbar"},{"type":"text","text":" scroll modes."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarScrollMode","title":"Autocomplete.ToolbarScrollMode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToolbarScrollMode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ToolbarScrollMode"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete":{"type":"topic","role":"symbol","abstract":[{"text":"This namespace contains autocomplete-related types.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Autocomplete","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/autocomplete","kind":"symbol","title":"Autocomplete","navigatorTitle":[{"text":"Autocomplete","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteContext/suggestionsFromService":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteContext\/suggestionsFromService","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"suggestionsFromService","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit12AutocompleteV","text":"Autocomplete","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Suggestion","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit12AutocompleteV10SuggestionV"},{"text":"]","kind":"text"}],"abstract":[{"text":"The suggestions that were returned by the service.","type":"text"}],"role":"symbol","title":"suggestionsFromService","url":"\/documentation\/keyboardkit\/autocompletecontext\/suggestionsfromservice","kind":"symbol"},"https://keyboardkit.com":{"identifier":"https:\/\/keyboardkit.com","title":"KeyboardKit website","type":"link","titleInlineContent":[{"text":"KeyboardKit website","type":"text"}],"url":"https:\/\/keyboardkit.com"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/settingsScreens":{"type":"topic","url":"\/documentation\/keyboardkit\/profeature\/settingsscreens","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"settingsScreens","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/settingsScreens","abstract":[],"kind":"symbol","title":"ProFeature.settingsScreens","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteService/removeIgnoredWord(_:)":{"type":"topic","url":"\/documentation\/keyboardkit\/autocompleteservice\/removeignoredword(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeIgnoredWord"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/removeIgnoredWord(_:)","abstract":[{"type":"text","text":"Remove a certain ignored word from the service."}],"kind":"symbol","title":"removeIgnoredWord(_:)","required":true},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/Result/emojiSuggestions":{"title":"emojiSuggestions","abstract":[{"text":"Emoji suggestions, if any.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emojiSuggestions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Suggestion","preciseIdentifier":"s:11KeyboardKit12AutocompleteV10SuggestionV"},{"kind":"text","text":"]?"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/autocomplete\/result\/emojisuggestions","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Result\/emojiSuggestions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Developer Guide","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete"],"anchor":"Developer-Guide"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}