{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"kind":"article","seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"],"generated":true}],"variants":[{"paths":["\/documentation\/keyboardkit\/callouts-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/callouts-article"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article"},"primaryContentSections":[{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Callouts are an important part of the typing experience, where an ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/InputCallout"},{"text":" can show the currently pressed key and an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/ActionCallout"},{"type":"text","text":" can show secondary actions when certain keys are long pressed."}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"👑 KeyboardKit Pro unlocks localized secondary callout actions for all "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/keyboardKitSupported","isActive":true},{"type":"text","text":" locales that are included in the license. You can sign up for KeyboardKit Pro from the "},{"isActive":true,"type":"reference","identifier":"https:\/\/keyboardkit.com"},{"type":"text","text":"."}]}],"type":"aside","style":"important","name":"Important"},{"anchor":"Namespace","type":"heading","level":2,"text":"Namespace"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts","isActive":true,"type":"reference"},{"type":"text","text":" namespace that contains callout-related types and views, like callout "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions","isActive":true,"type":"reference"},{"text":" , the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/InputCallout","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/ActionCallout","isActive":true},{"type":"text","text":" views, callout-related styles, etc."}]},{"anchor":"Context","level":2,"text":"Context","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has an observable "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/CalloutContext","isActive":true},{"type":"text","text":" class that has observable callout state, such as the current "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/CalloutContext\/inputAction","isActive":true},{"type":"text","text":" or the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/CalloutContext\/secondaryActions","isActive":true},{"type":"text","text":" that should be presented."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit automatically creates an instance of this class and injects it into "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","isActive":true},{"type":"text","text":", then updates this context when keys are pressed."}]},{"anchor":"Callouts","level":2,"text":"Callouts","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/InputCallout","isActive":true},{"type":"text","text":" can be presented from a pressed key to zoom in on its character. This is by default only used on iPhone devices, while iPad devices by default changes the color of the pressed key."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/ActionCallout","isActive":true},{"type":"text","text":" can be presented from a long pressed key, to show secondary callout "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions","isActive":true},{"type":"text","text":" for the currently pressed key."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit will by default use the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions\/standard(for:context:)","isActive":true},{"type":"text","text":" function to resolve the standard callout actions for all "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/keyboardKitSupported","isActive":true},{"type":"text","text":" locales. You can use the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardCalloutActions(_:)","isActive":true},{"type":"text","text":" modifier to customize callout actions for any action:"}]},{"code":["\/\/ See the demo app for a better, interactive example.","struct MyKeyboardView: View {","","    let state: Keyboard.State","    let services: Keyboard.Services","    let context: KeyboardContext { state.keyboardContext }","    ","    var body: some View {","        ... \/\/ Insert the view to use here, for instance a KeyboardView","            .keyboardCalloutActions { params in","                switch params.action {","                case .backspace: [...]  \/\/ Return custom actions here","                default: params.standardActions() ","                }","            }","    }","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can customize callouts for any actions, then use the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/ActionsBuilderParams\/standardActions()","isActive":true},{"type":"text","text":" to return the standard actions for all other actions."}]},{"anchor":"Styling","level":2,"text":"Styling","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardCalloutStyle(_:)","isActive":true},{"type":"text","text":" view modifier to customize the style of the input and action callouts and their items."}]},{"anchor":"Views","level":2,"text":"Views","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts","isActive":true},{"type":"text","text":" namespace has callout-specific views, that can be used to present input and action callouts that mimic native callouts."}]},{"tabs":[{"content":[{"numberOfColumns":2,"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"callouts-actioncallout"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/ActionCallout","isActive":true,"type":"reference"},{"text":" view can present secondary actions when a key with secondary actions is long-pressed.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The user can swipe left\/right while pressing to move the selection.","type":"text"}]}],"size":1}],"type":"row"}],"title":"ActionCallout"},{"content":[{"numberOfColumns":2,"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"callouts-inputcallout"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/InputCallout","isActive":true,"type":"reference"},{"text":" view can be used to zoom in the currently pressed input key as the user types.","type":"text"}]}],"size":1}],"type":"row"}],"title":"InputCallout"}],"type":"tabNavigator"},{"anchor":"%F0%9F%91%91-KeyboardKit-Pro","level":2,"text":"👑 KeyboardKit Pro","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks localized callout "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions","isActive":true},{"type":"text","text":" for all "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/keyboardKitSupported","isActive":true},{"type":"text","text":" locales in your license. It will automatically add them to the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","isActive":true},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can access these localized callout actions with the optional values like "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions\/swedish","isActive":true},{"type":"text","text":", and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions\/swedishCurrencyActions","isActive":true},{"type":"text","text":", or by using the throwing builders, like "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions\/swedishBuilder()","isActive":true},{"type":"text","text":". These builders will fail if the locale is not included in your license."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"topicSections":[{"title":"Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/CalloutContext"],"anchor":"Types"}],"metadata":{"images":[{"type":"card","identifier":"Feature-Callouts.jpg"}],"roleHeading":"Article","modules":[{"name":"KeyboardKit"}],"role":"article","title":"Callouts"},"references":{"Feature-Essentials.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials.jpg","traits":["1x","light"]}],"identifier":"Feature-Essentials.jpg","type":"image","alt":"Feature Icon"},"callouts-inputcallout":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/callouts-inputcallout.jpg","traits":["1x","light"]}],"identifier":"callouts-inputcallout","type":"image","alt":"InputCallout"},"Feature-AI.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg","traits":["1x","light"]}],"identifier":"Feature-AI.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","url":"\/documentation\/keyboardkit\/app-article","images":[{"identifier":"Feature-App.jpg","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"role":"article","title":"App Utilities","kind":"article","type":"topic"},"Feature-Fonts.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg","traits":["1x","light"]}],"identifier":"Feature-Fonts.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/keyboardKitSupported":{"url":"\/documentation\/keyboardkit\/foundation\/locale\/keyboardkitsupported","kind":"symbol","abstract":[{"text":"A list of KeyboardKit supported locales.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/keyboardKitSupported","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardKitSupported","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"},{"text":"]","kind":"text"}],"type":"topic","title":"keyboardKitSupported"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"images":[{"type":"card","identifier":"Feature-AI.jpg"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts/Actions/swedishBuilder()":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions\/swedishBuilder()","url":"\/documentation\/keyboardkit\/callouts\/actions\/swedishbuilder()","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"swedishBuilder"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Callouts","preciseIdentifier":"s:11KeyboardKit8CalloutsV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Actions","preciseIdentifier":"s:11KeyboardKit8CalloutsV7ActionsV"}],"kind":"symbol","title":"swedishBuilder()","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"url":"\/documentation\/keyboardkit\/fonts-article","abstract":[{"type":"text","text":"This article describes KeyboardKit’s custom font support."}],"role":"article","type":"topic","title":"Fonts","kind":"article","images":[{"identifier":"Feature-Fonts.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article"},"Feature-Callouts.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg","traits":["1x","light"]}],"identifier":"Feature-Callouts.jpg","type":"image","alt":null},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"url":"\/documentation\/keyboardkit\/host-article","abstract":[{"text":"This article describes how KeyboardKit Pro can identify and use the host application.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Host Application","images":[{"type":"card","identifier":"Feature-Host.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article"},"Feature-Host.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg","traits":["1x","light"]}],"identifier":"Feature-Host.jpg","type":"image","alt":"Feature Icon"},"Feature-Feedback.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg","traits":["1x","light"]}],"identifier":"Feature-Feedback.jpg","type":"image","alt":"Feature Icon"},"callouts-actioncallout":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/callouts-actioncallout.jpg","traits":["1x","light"]}],"identifier":"callouts-actioncallout","type":"image","alt":"ActionCallout"},"https://keyboardkit.com":{"url":"https:\/\/keyboardkit.com","identifier":"https:\/\/keyboardkit.com","title":"KeyboardKit website","type":"link","titleInlineContent":[{"text":"KeyboardKit website","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Gestures-Article":{"type":"topic","images":[{"identifier":"Feature-Gestures.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"role":"article","title":"Gestures","url":"\/documentation\/keyboardkit\/gestures-article"},"Feature-Dictation.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}],"identifier":"Feature-Dictation.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"abstract":[{"type":"text","text":"This article describes KeyboardKit’s clipboard support."}],"kind":"article","title":"Clipboard","type":"topic","images":[{"identifier":"Feature-Clipboard.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","url":"\/documentation\/keyboardkit\/clipboard-article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts/CalloutStyle":{"url":"\/documentation\/keyboardkit\/callouts\/calloutstyle","title":"Callouts.CalloutStyle","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/CalloutStyle","role":"symbol","kind":"symbol","abstract":[{"text":"This style can be used to modify the visual style of","type":"text"},{"text":" ","type":"text"},{"text":"the various callout components.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CalloutStyle","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"CalloutStyle","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-Article":{"url":"\/documentation\/keyboardkit\/essentials-article","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"images":[{"identifier":"Feature-Essentials.jpg","type":"card"}],"type":"topic","title":"Essentials","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts/Actions/swedish":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swedish","kind":"identifier"},{"text":": `Self`","kind":"text"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions\/swedish","kind":"symbol","title":"swedish","abstract":[],"url":"\/documentation\/keyboardkit\/callouts\/actions\/swedish"},"Feature-Input.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg","traits":["1x","light"]}],"identifier":"Feature-Input.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","url":"\/documentation\/keyboardkit\/feedback-article","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"role":"article","title":"Feedback","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/CalloutContext":{"url":"\/documentation\/keyboardkit\/calloutcontext","title":"CalloutContext","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/CalloutContext","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This context has observable callout-related state and is"},{"type":"text","text":" "},{"type":"text","text":"used for both input and action callouts."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CalloutContext"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CalloutContext"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts/Actions/standard(for:context:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions\/standard(for:context:)","url":"\/documentation\/keyboardkit\/callouts\/actions\/standard(for:context:)","abstract":[{"text":"The standard callout actions to use for the provided","type":"text"},{"text":" ","type":"text"},{"text":"keyboard action and context.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:11KeyboardKit0A6ActionO"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11KeyboardKit0A7ContextC","text":"KeyboardContext","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:11KeyboardKit0A6ActionO"},{"kind":"text","text":"]?"}],"kind":"symbol","title":"standard(for:context:)","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-KeyboardView":{"type":"topic","images":[{"identifier":"Feature-Essentials-KeyboardView.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","kind":"article","title":"Essentials - KeyboardView","abstract":[{"type":"text","text":"This article describes the essential "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"type":"text","text":" and how to use and configure it."}],"url":"\/documentation\/keyboardkit\/essentials-keyboardview"},"Feature-Clipboard.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg","traits":["1x","light"]}],"identifier":"Feature-Clipboard.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/CalloutContext/inputAction":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"inputAction","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:11KeyboardKit0A6ActionO"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/CalloutContext\/inputAction","kind":"symbol","title":"inputAction","abstract":[{"type":"text","text":"The current input action, if any."}],"url":"\/documentation\/keyboardkit\/calloutcontext\/inputaction"},"Feature-External.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg","traits":["1x","light"]}],"identifier":"Feature-External.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts/InputCallout":{"url":"\/documentation\/keyboardkit\/callouts\/inputcallout","title":"Callouts.InputCallout","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/InputCallout","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This callout can show the currenly pressed key, when"},{"type":"text","text":" "},{"type":"text","text":"typing on an iPhone."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputCallout"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputCallout"}]},"Feature-Gestures.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Gestures.jpg","traits":["1x","light"]}],"identifier":"Feature-Gestures.jpg","type":"image","alt":"Feature Icon"},"Feature-Essentials-KeyboardView.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials-KeyboardView.jpg","traits":["1x","light"]}],"identifier":"Feature-Essentials-KeyboardView.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts":{"url":"\/documentation\/keyboardkit\/callouts","title":"Callouts","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This namespace contains keyboard callout-related types."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Callouts"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Callouts"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts/ActionsBuilderParams/standardActions()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardActions"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"KeyboardAction","preciseIdentifier":"s:11KeyboardKit0A6ActionO"},{"kind":"text","text":"]?"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/ActionsBuilderParams\/standardActions()","abstract":[{"type":"text","text":"Get the standard callout actions for the context."}],"role":"symbol","title":"standardActions()","url":"\/documentation\/keyboardkit\/callouts\/actionsbuilderparams\/standardactions()"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/CalloutContext/secondaryActions":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"secondaryActions","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A6ActionO","text":"KeyboardAction","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"text":"The current secondary actions.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/CalloutContext\/secondaryActions","role":"symbol","title":"secondaryActions","url":"\/documentation\/keyboardkit\/calloutcontext\/secondaryactions"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts/Actions/swedishCurrencyActions":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swedishCurrencyActions"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:11KeyboardKit0A6ActionO","kind":"typeIdentifier","text":"KeyboardAction"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions\/swedishCurrencyActions","title":"swedishCurrencyActions","role":"symbol","url":"\/documentation\/keyboardkit\/callouts\/actions\/swedishcurrencyactions"},"Feature-App.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg","traits":["1x","light"]}],"identifier":"Feature-App.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardCalloutActions(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardCalloutActions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Callouts","preciseIdentifier":"s:11KeyboardKit8CalloutsV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ActionsBuilder","preciseIdentifier":"s:11KeyboardKit8CalloutsV14ActionsBuildera"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardCalloutActions(_:)","abstract":[{"type":"text","text":"This view modifier can be used to set custom callout"},{"type":"text","text":" "},{"type":"text","text":"actions to show when long pressing a key."}],"role":"symbol","title":"keyboardCalloutActions(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardcalloutactions(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"url":"\/documentation\/keyboardkit\/input-article","abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Input","images":[{"identifier":"Feature-Input.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","title":"KeyboardView","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","role":"symbol","kind":"symbol","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts/ActionCallout":{"url":"\/documentation\/keyboardkit\/callouts\/actioncallout","title":"Callouts.ActionCallout","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/ActionCallout","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This callout can show secondary callout actions when"},{"type":"text","text":" "},{"type":"text","text":"long pressing input keys with secondary actions."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionCallout"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActionCallout"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/state":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Keyboard","preciseIdentifier":"s:11KeyboardKit0A0V"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"s:11KeyboardKit0A0V5StateC"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Keyboard-specific state."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","role":"symbol","title":"state","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/state"},"Feature-Autocomplete.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg","traits":["1x","light"]}],"identifier":"Feature-Autocomplete.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"url":"\/documentation\/keyboardkit\/external-keyboards-article","kind":"article","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","role":"article","type":"topic","images":[{"identifier":"Feature-External.jpg","type":"card"}],"title":"External Keyboards"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"url":"\/documentation\/keyboardkit\/emojis-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"role":"article","type":"topic","kind":"article","title":"Emojis","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardCalloutStyle(_:)":{"url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardcalloutstyle(_:)","kind":"symbol","abstract":[{"type":"text","text":"Apply a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/CalloutStyle","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardCalloutStyle(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardCalloutStyle","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit8CalloutsV","text":"Callouts","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit8CalloutsV12CalloutStyleV","text":"CalloutStyle","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"type":"topic","title":"keyboardCalloutStyle(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","title":"Dictation","role":"article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"url":"\/documentation\/keyboardkit\/dictation-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts/Actions":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Actions","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions","abstract":[{"text":"This type can be used to define callout actions that","type":"text"},{"text":" ","type":"text"},{"text":"can be shown in an ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/ActionCallout","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","title":"Callouts.Actions","url":"\/documentation\/keyboardkit\/callouts\/actions","navigatorTitle":[{"text":"Actions","kind":"identifier"}]},"Feature-Emojis.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg","traits":["1x","light"]}],"identifier":"Feature-Emojis.jpg","type":"image","alt":"Feature Icon"},"Feature-Actions.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg","traits":["1x","light"]}],"identifier":"Feature-Actions.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","url":"\/documentation\/keyboardkit\/actions-article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"role":"article","kind":"article","title":"Actions","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"url":"\/documentation\/keyboardkit\/features-articles","abstract":[{"type":"text","text":"This article links to the various KeyboardKit features."}],"role":"collectionGroup","type":"topic","title":"Features","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"url":"\/documentation\/keyboardkit\/autocomplete-article","title":"Autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"],"generated":true}]}]}]}