{"sections":[],"kind":"article","metadata":{"images":[{"type":"card","identifier":"Feature-Clipboard.jpg"}],"title":"Clipboard","role":"article","modules":[{"name":"KeyboardKit"}],"roleHeading":"Article"},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","interfaceLanguage":"swift"},"abstract":[{"text":"This article describes KeyboardKit’s clipboard support.","type":"text"}],"topicSections":[{"title":"Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ClipboardContext","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ClipboardSettings"],"anchor":"Types"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"],"generated":true}],"variants":[{"paths":["\/documentation\/keyboardkit\/clipboard-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/clipboard-article"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"KeyboardKit makes it easy to integrate with the system clipboard. The user can add custom "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ClipboardSettings\/clips","isActive":true},{"type":"text","text":" with texts that are commonly typed."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"👑 KeyboardKit Pro unlocks system clipboard integration capabilities for licenses that include the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/clipboardAddons"},{"type":"text","text":" feature. You can sign up for KeyboardKit Pro from the "},{"type":"reference","isActive":true,"identifier":"https:\/\/keyboardkit.com"},{"type":"text","text":"."}]}],"style":"important","type":"aside","name":"Important"},{"type":"heading","anchor":"Namespace","level":2,"text":"Namespace"},{"inlineContent":[{"type":"text","text":"KeyboardKit has an "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard","isActive":true},{"type":"text","text":" namespace with clipboard-related types."}],"type":"paragraph"},{"anchor":"Context","text":"Context","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"KeyboardKit has an "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ClipboardContext","isActive":true},{"type":"text","text":" that can be used to interact with the system clipboard and manage user-specific clips with the auto-persisted "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ClipboardContext\/settings","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"KeyboardKit automatically creates an instance of this class, injects it into "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","isActive":true},{"type":"text","text":" and also injects it into the view hierarchy environment."}],"type":"paragraph"},{"anchor":"Settings","text":"Settings","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ClipboardSettings","isActive":true},{"type":"text","text":" type with clipboard-related settings like "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ClipboardSettings\/clips","isActive":true},{"type":"text","text":", which lets users save often used text clips."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The context "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ClipboardContext\/settings","isActive":true},{"type":"text","text":" is used by default. KeyboardKit Pro unlocks a feature-specific "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/SettingsScreen","isActive":true},{"type":"text","text":" that can be used to handle these settings and save custom clips."}],"type":"paragraph"},{"anchor":"%F0%9F%91%91-KeyboardKit-Pro","text":"👑 KeyboardKit Pro","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/SettingsScreen","isActive":true},{"type":"text","text":" that can be used in the app, and a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/ClipsScreen","isActive":true},{"type":"text","text":" that can be used in the keyboard or as a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/Clip","isActive":true},{"type":"text","text":" picker. Both screens let users manage their clips, but in slightly different ways."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"These views and utilities require a KeyboardKit Pro license that unlocks the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/clipboardAddons"},{"type":"text","text":" feature. The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/SettingsScreen"},{"type":"text","text":" also requires the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/settingsScreens"},{"type":"text","text":" feature."}]}],"style":"important","type":"aside","name":"Important"},{"type":"heading","anchor":"Screens","level":3,"text":"Screens"},{"inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard","isActive":true},{"type":"text","text":"-related screens that can be used to manage custom clips, and to paste clips from the keyboard:"}],"type":"paragraph"},{"type":"tabNavigator","tabs":[{"content":[{"type":"row","columns":[{"content":[{"inlineContent":[{"type":"image","identifier":"clipboard-settingsscreen"}],"type":"paragraph"}],"size":1},{"content":[{"inlineContent":[{"type":"text","text":"A "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/SettingsScreen"},{"type":"text","text":" can be used to add, remove and reorganize clips. It will prefill texts from the system clipboard."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen"},{"type":"text","text":" template will automatically link to this screen if the current license unlocks the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/clipboardAddons"},{"type":"text","text":" feature."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This screen can be customized with the following view modifiers:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/clipboardSettingsScreenLocalization(_:)","type":"reference","isActive":true}]}]}],"type":"unorderedList"}],"size":1}],"numberOfColumns":2}],"title":"Settings Screen"},{"content":[{"type":"row","columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"clipboard-clipsscreen"}],"type":"paragraph"}]},{"size":1,"content":[{"inlineContent":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard","isActive":true},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/ClipsScreen","isActive":true},{"type":"text","text":" can be used as a clips picker that triggers "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/pasteFromClipboard","isActive":true},{"type":"text","text":" actions."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The screen lets users save the pasteboard text, pick and manage clips, etc. It’s used by "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","isActive":true},{"type":"text","text":" to send clips to the app."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This screen can be customized with the following view modifiers:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/clipboardClipsScreenLocalization(_:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/clipboardClipsScreenStyle(_:)"}]}]}],"type":"unorderedList"}]}],"numberOfColumns":2}],"title":"Clips Screen"}]},{"anchor":"Views","text":"Views","type":"heading","level":3},{"inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard","isActive":true},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/Keyboard","isActive":true},{"type":"text","text":" view that can replace the main keyboard to send clips to the current application."}],"type":"paragraph"},{"type":"tabNavigator","tabs":[{"content":[{"type":"row","columns":[{"content":[{"inlineContent":[{"type":"image","identifier":"clipboard-keyboard"}],"type":"paragraph"}],"size":1},{"content":[{"inlineContent":[{"type":"text","text":"A "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard"},{"type":"text","text":"."},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/Keyboard"},{"type":"text","text":" can be used to paste text clips into the app, either from the system clipboard or custom clips."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"A "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView"},{"type":"text","text":" will automatically switch to this view when the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/keyboardType"},{"type":"text","text":" is set to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/KeyboardType\/clipboard"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This view can be customized with the following view modifiers:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/clipboardKeyboardLocalization(_:)","type":"reference","isActive":true}]}]}],"type":"unorderedList"}],"size":1}],"numberOfColumns":2}],"title":"Keyboard"}]}],"kind":"content"}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/clipboardAddons":{"url":"\/documentation\/keyboardkit\/profeature\/clipboardaddons","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/clipboardAddons","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clipboardAddons","kind":"identifier"}],"type":"topic","title":"ProFeature.clipboardAddons"},"Feature-Essentials.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials.jpg","traits":["1x","light"]}],"identifier":"Feature-Essentials.jpg"},"Feature-AI.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg","traits":["1x","light"]}],"identifier":"Feature-AI.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","url":"\/documentation\/keyboardkit\/app-article","images":[{"identifier":"Feature-App.jpg","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"role":"article","title":"App Utilities","kind":"article","type":"topic"},"Feature-Fonts.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg","traits":["1x","light"]}],"identifier":"Feature-Fonts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/clipboardClipsScreenStyle(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clipboardClipsScreenStyle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9ClipboardV","text":"Clipboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9ClipboardV16ClipsScreenStyleV","text":"ClipsScreenStyle"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/clipboardClipsScreenStyle(_:)","abstract":[{"type":"text","text":"Apply a custom screen style."}],"role":"symbol","title":"clipboardClipsScreenStyle(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/clipboardclipsscreenstyle(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"images":[{"type":"card","identifier":"Feature-AI.jpg"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/keyboardType":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11KeyboardKit0A0V","kind":"typeIdentifier","text":"Keyboard"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11KeyboardKit0A0V0A4TypeO","kind":"typeIdentifier","text":"KeyboardType"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/keyboardType","kind":"symbol","title":"keyboardType","abstract":[{"text":"The keyboard type that is currently used.","type":"text"}],"url":"\/documentation\/keyboardkit\/keyboardcontext\/keyboardtype"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard/Clip":{"url":"\/documentation\/keyboardkit\/clipboard\/clip","title":"Clipboard.Clip","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/Clip","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This struct represents a custom clipboard clip."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Clip","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Clip","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"url":"\/documentation\/keyboardkit\/fonts-article","abstract":[{"type":"text","text":"This article describes KeyboardKit’s custom font support."}],"role":"article","type":"topic","title":"Fonts","kind":"article","images":[{"identifier":"Feature-Fonts.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article"},"Feature-Callouts.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg","traits":["1x","light"]}],"identifier":"Feature-Callouts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"url":"\/documentation\/keyboardkit\/host-article","abstract":[{"text":"This article describes how KeyboardKit Pro can identify and use the host application.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Host Application","images":[{"type":"card","identifier":"Feature-Host.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article"},"Feature-Host.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg","traits":["1x","light"]}],"identifier":"Feature-Host.jpg"},"Feature-Feedback.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg","traits":["1x","light"]}],"identifier":"Feature-Feedback.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ClipboardSettings":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClipboardSettings","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ClipboardSettings","kind":"symbol","title":"ClipboardSettings","abstract":[{"text":"This type has auto-persisted clipboard settings.","type":"text"}],"url":"\/documentation\/keyboardkit\/clipboardsettings","navigatorTitle":[{"text":"ClipboardSettings","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/KeyboardType/clipboard":{"url":"\/documentation\/keyboardkit\/keyboard\/keyboardtype\/clipboard","title":"Keyboard.KeyboardType.clipboard","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/KeyboardType\/clipboard","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A clipboard keyboard."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clipboard"}],"type":"topic"},"https://keyboardkit.com":{"type":"link","title":"KeyboardKit website","identifier":"https:\/\/keyboardkit.com","titleInlineContent":[{"text":"KeyboardKit website","type":"text"}],"url":"https:\/\/keyboardkit.com"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/clipboardSettingsScreenLocalization(_:)":{"abstract":[{"type":"text","text":"Apply a custom screen localization."}],"kind":"symbol","title":"clipboardSettingsScreenLocalization(_:)","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/clipboardSettingsScreenLocalization(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clipboardSettingsScreenLocalization"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9ClipboardV","text":"Clipboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9ClipboardV26SettingsScreenLocalizationV","text":"SettingsScreenLocalization"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"url":"\/documentation\/keyboardkit\/swiftuicore\/view\/clipboardsettingsscreenlocalization(_:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Gestures-Article":{"type":"topic","images":[{"identifier":"Feature-Gestures.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"role":"article","title":"Gestures","url":"\/documentation\/keyboardkit\/gestures-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard":{"url":"\/documentation\/keyboardkit\/clipboard","title":"Clipboard","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This is a namespace for clipboard related types."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Clipboard"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Clipboard"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/pasteFromClipboard":{"abstract":[{"type":"text","text":"Pastes from the system clipboard when tapped."}],"kind":"symbol","title":"KeyboardAction.pasteFromClipboard","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/pasteFromClipboard","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pasteFromClipboard","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/keyboardaction\/pastefromclipboard","role":"symbol"},"Feature-Dictation.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}],"identifier":"Feature-Dictation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-Article":{"url":"\/documentation\/keyboardkit\/essentials-article","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"images":[{"identifier":"Feature-Essentials.jpg","type":"card"}],"type":"topic","title":"Essentials","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/clipboardKeyboardLocalization(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clipboardKeyboardLocalization","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:11KeyboardKit9ClipboardV","text":"Clipboard","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11KeyboardKit9ClipboardV0A12Localizationa","text":"KeyboardLocalization","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Apply a custom keyboard localization."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/clipboardKeyboardLocalization(_:)","role":"symbol","title":"clipboardKeyboardLocalization(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/clipboardkeyboardlocalization(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"role":"article","type":"topic","kind":"article","title":"Callouts","images":[{"type":"card","identifier":"Feature-Callouts.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/clipboardClipsScreenLocalization(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clipboardClipsScreenLocalization"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9ClipboardV","text":"Clipboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9ClipboardV23ClipsScreenLocalizationV","text":"ClipsScreenLocalization"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/clipboardClipsScreenLocalization(_:)","abstract":[{"type":"text","text":"Apply a custom screen localization."}],"role":"symbol","title":"clipboardClipsScreenLocalization(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/clipboardclipsscreenlocalization(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/HomeScreen":{"url":"\/documentation\/keyboardkit\/keyboardapp\/homescreen","navigatorTitle":[{"text":"HomeScreen","kind":"identifier"}],"abstract":[{"type":"text","text":"This screen can be used as the main home screen of a"},{"type":"text","text":" "},{"type":"text","text":"keyboard app that should look like iOS Settings."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HomeScreen","kind":"identifier"}],"role":"symbol","type":"topic","title":"KeyboardApp.HomeScreen","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard/SettingsScreen":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsScreen","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/SettingsScreen","abstract":[{"type":"text","text":"This screen can be used as a settings screen for any"},{"type":"text","text":" "},{"type":"text","text":"clipboard-related keyboard settings and clips."}],"role":"symbol","title":"Clipboard.SettingsScreen","url":"\/documentation\/keyboardkit\/clipboard\/settingsscreen","navigatorTitle":[{"text":"SettingsScreen","kind":"identifier"}]},"Feature-Input.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg","traits":["1x","light"]}],"identifier":"Feature-Input.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","url":"\/documentation\/keyboardkit\/feedback-article","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"role":"article","title":"Feedback","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard/Keyboard":{"url":"\/documentation\/keyboardkit\/clipboard\/keyboard","title":"Clipboard.Keyboard","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/Keyboard","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This view can be used as a clipboard keyboard and be"},{"type":"text","text":" "},{"type":"text","text":"used as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/KeyboardType\/clipboard"},{"type":"text","text":" keyboard."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Keyboard"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Keyboard"}]},"Feature-Clipboard.jpg":{"type":"image","alt":null,"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg","traits":["1x","light"]}],"identifier":"Feature-Clipboard.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-KeyboardView":{"type":"topic","images":[{"identifier":"Feature-Essentials-KeyboardView.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","kind":"article","title":"Essentials - KeyboardView","abstract":[{"type":"text","text":"This article describes the essential "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"type":"text","text":" and how to use and configure it."}],"url":"\/documentation\/keyboardkit\/essentials-keyboardview"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ClipboardContext/settings":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settings","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit17ClipboardSettingsV","text":"ClipboardSettings","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ClipboardContext\/settings","kind":"symbol","title":"settings","abstract":[{"text":"Auto-persisted clipboard settings.","type":"text"}],"url":"\/documentation\/keyboardkit\/clipboardcontext\/settings"},"Feature-External.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg","traits":["1x","light"]}],"identifier":"Feature-External.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard/ClipsScreen":{"url":"\/documentation\/keyboardkit\/clipboard\/clipsscreen","title":"Clipboard.ClipsScreen","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/ClipsScreen","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This screen can be used to list the system clipboard"},{"type":"text","text":" "},{"type":"text","text":"content and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/Clip","isActive":true},{"type":"text","text":" items."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClipsScreen","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ClipsScreen","kind":"identifier"}]},"clipboard-keyboard":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/clipboard-keyboard.jpg","traits":["1x","light"]}],"type":"image","alt":"Clipboard.ClipsScreen","identifier":"clipboard-keyboard"},"Feature-Gestures.jpg":{"type":"image","identifier":"Feature-Gestures.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Gestures.jpg","traits":["1x","light"]}]},"Feature-Essentials-KeyboardView.jpg":{"type":"image","identifier":"Feature-Essentials-KeyboardView.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials-KeyboardView.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","title":"KeyboardView","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","role":"symbol","kind":"symbol","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"Feature-App.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg"}],"identifier":"Feature-App.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"url":"\/documentation\/keyboardkit\/input-article","abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Input","images":[{"identifier":"Feature-Input.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"},"Feature-Autocomplete.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"identifier":"Feature-Autocomplete.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/state":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Keyboard","preciseIdentifier":"s:11KeyboardKit0A0V"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"s:11KeyboardKit0A0V5StateC"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Keyboard-specific state."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","role":"symbol","title":"state","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/state"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/settingsScreens":{"abstract":[],"kind":"symbol","title":"ProFeature.settingsScreens","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/settingsScreens","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settingsScreens","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/profeature\/settingsscreens","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"url":"\/documentation\/keyboardkit\/external-keyboards-article","kind":"article","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","role":"article","type":"topic","images":[{"identifier":"Feature-External.jpg","type":"card"}],"title":"External Keyboards"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"url":"\/documentation\/keyboardkit\/emojis-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"role":"article","type":"topic","kind":"article","title":"Emojis","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article"},"clipboard-clipsscreen":{"type":"image","alt":"Clipboard.ClipsScreen","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/clipboard-clipsscreen.jpg"}],"identifier":"clipboard-clipsscreen"},"clipboard-settingsscreen":{"type":"image","alt":"Clipboard.SettingsScreen","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/clipboard-settingsscreen.jpg","traits":["1x","light"]}],"identifier":"clipboard-settingsscreen"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","title":"Dictation","role":"article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"url":"\/documentation\/keyboardkit\/dictation-article"},"Feature-Emojis.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg"}],"identifier":"Feature-Emojis.jpg","type":"image","alt":"Feature Icon"},"Feature-Actions.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}],"identifier":"Feature-Actions.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","url":"\/documentation\/keyboardkit\/actions-article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"role":"article","kind":"article","title":"Actions","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"url":"\/documentation\/keyboardkit\/features-articles","abstract":[{"type":"text","text":"This article links to the various KeyboardKit features."}],"role":"collectionGroup","type":"topic","title":"Features","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ClipboardSettings/clips":{"url":"\/documentation\/keyboardkit\/clipboardsettings\/clips","title":"clips","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ClipboardSettings\/clips","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A list of custom clips stored by the user."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clips"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:11KeyboardKit9ClipboardV","text":"Clipboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Clip","preciseIdentifier":"s:11KeyboardKit9ClipboardV4ClipV"},{"kind":"text","text":"]"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ClipboardContext":{"url":"\/documentation\/keyboardkit\/clipboardcontext","navigatorTitle":[{"kind":"identifier","text":"ClipboardContext"}],"abstract":[{"type":"text","text":"This class has observable and persisted clipboard states."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClipboardContext"}],"role":"symbol","type":"topic","kind":"symbol","title":"ClipboardContext","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ClipboardContext"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"url":"\/documentation\/keyboardkit\/autocomplete-article","title":"Autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"]}],"path":"\/seeAlsoSections","op":"replace"}]}]}