{"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides"]]},"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit includes dSYMs as part of each release. You can add these dSYMs to your app, to improve the crash reports for crashes that originate from the KeyboardKit SDK.","type":"text"}]},{"text":"What are dSYMs and why do we need them?","type":"heading","level":2,"anchor":"What-are-dSYMs-and-why-do-we-need-them"},{"type":"paragraph","inlineContent":[{"type":"text","text":"dSYM stands for “debug symbol file”, which acts as a translation guide between compiled machine code and the original source code."}]},{"type":"paragraph","inlineContent":[{"text":"When KeyboardKit is compiled for release, the compiler optimizes it by stripping out human-readable information like function names, variable names, and line numbers, and replacing them with memory addresses.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"While this makes the SDK smaller and faster, it also means that when crashes occur, the crash report will show hexadecimal addresses like ","type":"text"},{"type":"codeVoice","code":"0xabc123"},{"text":" instead of meaningful information.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is where dSYMs become essential. dSYMs connect the obscure memory addresses with the original source code locations. When you upload dSYMs with your app, Apple can automatically “symbolicate” the crash reports, which converts the memory addresses into readable stack traces that show exactly in which function and on which lines the crash occurred."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Without dSYMs, debugging crashes is nearly impossible. With them, you get crash reports that show exactly where things went wrong."}]},{"text":"Uploading apps without dSYMs","type":"heading","level":2,"anchor":"Uploading-apps-without-dSYMs"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you upload an app to App Store Connect without including the KeyboardKit dSYMs, Xcode shows a warning that dSYMs are missing:"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"developer-dsyms-xcode-upload-warning"}]},{"type":"paragraph","inlineContent":[{"text":"This means that crashes that originate from KeyboardKit will be unsymbolicated, which will cause the crash report to lack information:","type":"text"}]},{"type":"paragraph","inlineContent":[{"identifier":"developer-dsyms-unsymbolicated-crash-report","type":"image"}]},{"type":"paragraph","inlineContent":[{"text":"The crash report above tells us that KeyboardKit has crashed when calling ","type":"text"},{"code":"[NSString initWithUTF8String]","type":"codeVoice"},{"text":", but we can’t see anything more. To get more information, we need the dSYMs.","type":"text"}]},{"anchor":"Uploading-apps-with-dSYMs","level":2,"type":"heading","text":"Uploading apps with dSYMs"},{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit-Binaries"},{"text":" repository will publish dSYMs with each release and list it next to the framework. If you download the dSYMs for the version you use and include it with your app, Xcode can provide symbolicated crash reports.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You must upload the dSYMs with each new version of your app. To do so, first archive the app so that it appears in the archives modal:"}],"type":"paragraph"},{"inlineContent":[{"identifier":"developer-dsyms-xcode-archives","type":"image"}],"type":"paragraph"},{"inlineContent":[{"text":"To add dSYMs to an archive, right-click the archive you want to upload, select “Show in Finder”, right-click the archive in Finder, select “Show Package Contents” add the ","type":"text"},{"code":"KeyboardKit.framework.dSYMs","type":"codeVoice"},{"text":" to the dSYMs folder:","type":"text"}],"type":"paragraph"},{"inlineContent":[{"identifier":"developer-dsyms-finder","type":"image"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Return to Xcode and press “Distribute App”. You should now get a green checkmark instead of the warning. This means that the dSYMs were properly uploaded with your app, and that crash reports will be symblicated for this version."}],"type":"paragraph"},{"inlineContent":[{"type":"image","identifier":"developer-dsyms-xcode-upload-success"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"While Xcode requires that you include dSYMs with each upload, some crash management tools like Crashlytics let you upload dSYMs later. Follow the guides of each specific tool, like the "},{"identifier":"https:\/\/firebase.google.com\/docs\/crashlytics\/get-deobfuscated-reports?platform=ios","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"},{"content":[{"inlineContent":[{"text":"You must upload separate dSYMs for each platform. If the app has an iOS and a macOS verison, you must upload dSYMs for both.","type":"text"}],"type":"paragraph"}],"name":"Important","type":"aside","style":"important"}]}],"variants":[{"paths":["\/documentation\/keyboardkit\/developer-dsyms"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/developer-dsyms"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","sections":[],"abstract":[{"type":"text","text":"This developer guide describes how to use dSYMs to obtain more detailed crash reports."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"images":[{"type":"card","identifier":"Developer-Article-dSYMs.jpg"}],"color":{"standardColorIdentifier":"purple"},"modules":[{"name":"KeyboardKit"}],"role":"article","title":"dSYMs","roleHeading":"Article"},"seeAlsoSections":[{"anchor":"Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"],"title":"Essentials","generated":true}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"Developer-Article-Memory-Management.jpg":{"type":"image","identifier":"Developer-Article-Memory-Management.jpg","alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Memory-Management.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Debugging":{"abstract":[{"text":"This developer guide describes how to debug a custom keyboard extension.","type":"text"}],"kind":"article","images":[{"identifier":"Developer-Article-Debugging.jpg","type":"card"}],"title":"Debugging","role":"article","url":"\/documentation\/keyboardkit\/developer-debugging","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging"},"Developer-Article-dSYMs.jpg":{"identifier":"Developer-Article-dSYMs.jpg","alt":null,"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-dSYMs.jpg"}]},"developer-dsyms-finder":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-dsyms-finder.png","traits":["1x","light"]}],"type":"image","identifier":"developer-dsyms-finder","alt":"A screenshot of Finder and an added dSYMs file"},"developer-dsyms-xcode-upload-success":{"identifier":"developer-dsyms-xcode-upload-success","alt":"A screenshot of the Xcode successful upload modal","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-dsyms-xcode-upload-success.png","traits":["1x","light"]}],"type":"image"},"https://github.com/KeyboardKit/KeyboardKit-Binaries":{"titleInlineContent":[{"text":"KeyboardKit Binaries","type":"text"}],"type":"link","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit-Binaries","title":"KeyboardKit Binaries","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKit-Binaries"},"Developer-Article-Data-Syncing.jpg":{"alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Data-Syncing.jpg","traits":["1x","light"]}],"type":"image","identifier":"Developer-Article-Data-Syncing.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Experiments":{"kind":"article","url":"\/documentation\/keyboardkit\/developer-experiments","role":"article","type":"topic","title":"Experiments","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","images":[{"type":"card","identifier":"Developer-Article-Experiments.jpg"}],"abstract":[{"text":"This developer guide describes how to enable experimental features.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Data-Syncing":{"url":"\/documentation\/keyboardkit\/developer-data-syncing","type":"topic","images":[{"type":"card","identifier":"Developer-Article-Data-Syncing.jpg"}],"title":"Data Syncing","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","role":"article","abstract":[{"type":"text","text":"This developer guide describes how to sync data between the main app and its keyboard."}],"kind":"article"},"developer-dsyms-unsymbolicated-crash-report":{"identifier":"developer-dsyms-unsymbolicated-crash-report","alt":"A screenshot of an Xcode crash report with unsymbolicated crash symbols","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-dsyms-unsymbolicated-crash-report.png","traits":["1x","light"]}],"type":"image"},"Developer-Article-Debugging.jpg":{"alt":"Article Icon","type":"image","identifier":"Developer-Article-Debugging.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Debugging.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Memory-Management":{"url":"\/documentation\/keyboardkit\/developer-memory-management","abstract":[{"text":"This developer guide describes how to manage memory in a keyboard extensions.","type":"text"}],"images":[{"identifier":"Developer-Article-Memory-Management.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management","title":"Memory Management","type":"topic","kind":"article","role":"article"},"https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios":{"type":"link","identifier":"https:\/\/firebase.google.com\/docs\/crashlytics\/get-deobfuscated-reports?platform=ios","title":"Crashlytics guide","titleInlineContent":[{"text":"Crashlytics guide","type":"text"}],"url":"https:\/\/firebase.google.com\/docs\/crashlytics\/get-deobfuscated-reports?platform=ios"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Custom-Keyboards":{"kind":"article","abstract":[{"type":"text","text":"This developer guide describes how custom iOS keyboard extensions work."}],"images":[{"identifier":"Developer-Article-Custom-Keyboards.jpg","type":"card"}],"title":"Custom Keyboard Extensions","role":"article","url":"\/documentation\/keyboardkit\/developer-custom-keyboards","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards"},"Developer-Article-Experiments.jpg":{"identifier":"Developer-Article-Experiments.jpg","alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Experiments.jpg","traits":["1x","light"]}],"type":"image"},"Developer-Article-Custom-Keyboards.jpg":{"alt":"Article Icon","type":"image","identifier":"Developer-Article-Custom-Keyboards.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Custom-Keyboards.jpg"}]},"developer-dsyms-xcode-upload-warning":{"alt":"A screenshot of the Xcode dSYMs missing alert modal","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-dsyms-xcode-upload-warning.png","traits":["1x","light"]}],"type":"image","identifier":"developer-dsyms-xcode-upload-warning"},"developer-dsyms-xcode-archives":{"identifier":"developer-dsyms-xcode-archives","alt":"A screenshot of the Xcode archives modal","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-dsyms-xcode-archives.png","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Guides":{"url":"\/documentation\/keyboardkit\/developer-guides","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides","role":"collectionGroup","title":"Developer Guides","type":"topic","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Essentials","title":"Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}