{"sections":[],"metadata":{"title":"Memory Management","images":[{"type":"card","identifier":"Developer-Article-Memory-Management.jpg"}],"modules":[{"name":"KeyboardKit"}],"role":"article","roleHeading":"Article","color":{"standardColorIdentifier":"purple"}},"variants":[{"paths":["\/documentation\/keyboardkit\/developer-memory-management"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/developer-memory-management"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"},"abstract":[{"type":"text","text":"This developer guide describes how to manage memory in a keyboard extensions."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles"]]},"seeAlsoSections":[{"generated":true,"title":"Developer Essentials","anchor":"Developer-Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments"]}],"primaryContentSections":[{"content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"inlineContent":[{"text":"Custom keyboard extensions are severely limited when it comes to how much memory they can allocate. Based on the device and iOS version, a keyboard extension is not allowed to allocate more than ","type":"text"},{"type":"strong","inlineContent":[{"text":"~60-70 MB","type":"text"}]},{"text":".","type":"text"}],"type":"paragraph"},{"style":"warning","content":[{"type":"paragraph","inlineContent":[{"text":"If your keyboard extension allocate more memory than what is allowed by iOS, your keyboard extension will be instantly terminated.","type":"text"}]}],"type":"aside","name":"Warning"},{"anchor":"Why-is-this-a-problem","level":2,"type":"heading","text":"Why is this a problem?"},{"inlineContent":[{"text":"These strict memory limitations have been in effect for many years, and don’t seem to change even though our devices become more powerful. Despite several discussions with Apple, these limitations remain more or less unchanged.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"This makes it hard for keyboards to provide more powerful features. AI & ML could be used to provide amazing keyboard features, but since such models generally require a lot of memory, keyboard extensions are oftne unable to use them directly.","type":"text"}],"type":"paragraph"},{"anchor":"What-can-we-do","level":2,"type":"heading","text":"What can we do?"},{"inlineContent":[{"text":"Many keyboards work around these memory limitations by opening the main app to perform certain tasks, or by integrating with remote APIs. This will however result in a bad experience, since users must enable Full Access, app navigation is limited, and requests are slow.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"To avoid crashes, make sure to carefully monitor your keyboard extension’s memory usage, and to defer memory intense tasks until the keyboard has first been rendered. You should also reach out to Apple if you struggle with these limitations.","type":"text"}],"type":"paragraph"},{"anchor":"Memory-Leaks","level":2,"type":"heading","text":"Memory Leaks"},{"inlineContent":[{"text":"It’s imperative that you inspect your keyboard extension’s memory consumption, to ensure that it doesn’t have any memory leaks. This can easily happen when yoy keep a strong reference to the keyboard input view controller, but it can be easily avoided.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Try to find ways to avoid passing around the keyboard input controller, since this will cause a memory leak if the controller reference is not weak or unowned. KeyboardKit makes this easy by providing you with decoupled state & services.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"If you have a leak, you will see the memory consumption increase when you switch keyboards back and forth. You will also see multiple instances of the same type in the memory graph (see below). This will nto happen when you don’t have a leak.","type":"text"}],"type":"paragraph"},{"anchor":"Monitoring-memory-consumption","level":2,"type":"heading","text":"Monitoring memory consumption"},{"inlineContent":[{"text":"It’s ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"very","type":"text"}]},{"text":" important that you carefully monitor your keyboard’s memory consumption, if you suspect that it’s close to the ","type":"text"},{"type":"strong","inlineContent":[{"text":"60-70 MB","type":"text"}]},{"text":" limit.","type":"text"}],"type":"paragraph"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"text":"Always monitor a keyboard extension’s memory consumption on a physical device! The iOS Simulator will use a lot more memory.","type":"text"}]}],"type":"aside","name":"Important"},{"columns":[{"content":[{"inlineContent":[{"type":"image","identifier":"developer-debugging-attaching"}],"type":"paragraph"}],"size":1},{"content":[{"inlineContent":[{"type":"text","text":"You can monitor a keyboard extension’s memory consumption by attaching the Xcode debugger to the keyboard extension."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"See the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging"},{"type":"text","text":" article for more information on how to debug a keyboard extension."}],"type":"paragraph"}],"size":1}],"type":"row","numberOfColumns":2},{"columns":[{"content":[{"inlineContent":[{"type":"text","text":"Once attached, you can your memory with the Debug Navigator (top-leading spray bottle) button in the Xcode Project Navigator."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This will show how much memory your keyboard is using. This is great to quickly inspect the consumption at a specific time."}],"type":"paragraph"}],"size":1},{"content":[{"inlineContent":[{"type":"image","identifier":"developer-memory-consumption"}],"type":"paragraph"}],"size":1}],"type":"row","numberOfColumns":2},{"columns":[{"content":[{"inlineContent":[{"type":"image","identifier":"developer-memory-graph"}],"type":"paragraph"}],"size":1},{"content":[{"inlineContent":[{"type":"text","text":"You can inspect the full memory graph by tapping Debug Memory Graph in the Xcode Debug Area."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This will pause the process and list all allocated memory, together with an interactive memory graph."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This graph should only show “KeyboardController (1)”! If you see “KeyboardController (2)”, you may have a memory leak!"}],"type":"paragraph"}],"size":1}],"type":"row","numberOfColumns":2},{"inlineContent":[{"text":"These memory restrictions make it very hard to add powerful features to custom keyboard extensions. If you are frustrated with these limitations, please reach out to Apple and share your concerns.s","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"developer-memory-consumption":{"identifier":"developer-memory-consumption","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-memory-consumption.jpg"}],"alt":"A screenshot of how to monitor the memory consumption"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Custom-Keyboards":{"type":"topic","images":[{"type":"card","identifier":"Developer-Article-Custom-Keyboards.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how custom iOS keyboard extensions work.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","role":"article","title":"Custom Keyboard Extensions","url":"\/documentation\/keyboardkit\/developer-custom-keyboards"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Experiments":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","url":"\/documentation\/keyboardkit\/developer-experiments","images":[{"type":"card","identifier":"Developer-Article-Experiments.jpg"}],"abstract":[{"text":"This developer guide describes how to enable experimental features.","type":"text"}],"role":"article","title":"Experiments","kind":"article","type":"topic"},"Developer-Article-Debugging.jpg":{"identifier":"Developer-Article-Debugging.jpg","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Debugging.jpg"}],"alt":"Article Icon"},"Developer-Article-Memory-Management.jpg":{"identifier":"Developer-Article-Memory-Management.jpg","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Memory-Management.jpg"}],"alt":null},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Data-Syncing":{"url":"\/documentation\/keyboardkit\/developer-data-syncing","abstract":[{"text":"This developer guide describes how to sync data between the main app and its keyboard.","type":"text"}],"images":[{"identifier":"Developer-Article-Data-Syncing.jpg","type":"card"}],"type":"topic","title":"Data Syncing","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","kind":"article"},"developer-memory-graph":{"identifier":"developer-memory-graph","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-memory-graph.jpg"}],"alt":"A screenshot of how to inspect the memory graph"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Articles":{"url":"\/documentation\/keyboardkit\/developer-articles","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}],"role":"collectionGroup","type":"topic","kind":"article","title":"Developer Guides","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles"},"Developer-Article-Data-Syncing.jpg":{"identifier":"Developer-Article-Data-Syncing.jpg","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Data-Syncing.jpg"}],"alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-dSYMs":{"type":"topic","images":[{"type":"card","identifier":"Developer-Article-dSYMs.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how to use dSYMs to obtain more detailed crash reports.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","role":"article","title":"dSYMs","url":"\/documentation\/keyboardkit\/developer-dsyms"},"Developer-Article-Custom-Keyboards.jpg":{"identifier":"Developer-Article-Custom-Keyboards.jpg","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Custom-Keyboards.jpg"}],"alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Debugging":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","url":"\/documentation\/keyboardkit\/developer-debugging","images":[{"identifier":"Developer-Article-Debugging.jpg","type":"card"}],"abstract":[{"type":"text","text":"This developer guide describes how to debug a custom keyboard extension."}],"role":"article","kind":"article","title":"Debugging","type":"topic"},"Developer-Article-Experiments.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Experiments.jpg"}],"alt":"Article Icon","type":"image","identifier":"Developer-Article-Experiments.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"Developer-Article-dSYMs.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-dSYMs.jpg"}],"alt":"Article Icon","identifier":"Developer-Article-dSYMs.jpg"},"developer-debugging-attaching":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-debugging-attaching.png"}],"alt":"A screenshot of how to attach to the debugger","identifier":"developer-debugging-attaching"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"anchor":"Developer-Essentials","title":"Developer Essentials","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments"]}],"path":"\/seeAlsoSections","op":"replace"}]}]}