{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkit\/developer-custom-keyboards"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkit\/developer-custom-keyboards"]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles"]]},"metadata":{"color":{"standardColorIdentifier":"purple"},"images":[{"identifier":"Developer-Article-Custom-Keyboards.jpg","type":"card"}],"title":"Custom Keyboard Extensions","role":"article","modules":[{"name":"KeyboardKit"}],"roleHeading":"Article"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"text":"A ","type":"text"},{"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/creating-a-custom-keyboard","isActive":true,"type":"reference"},{"text":" is an app extension that you ship together with your app. Once enabled in Settings, it can replace the native system keyboard by selecting it with the bottom-leading 🌐 key while typing.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Keyboard extensions are the only kind of apps that can be used directly with other apps in iOS. By extending your app’s features for use in a custom iOS keyboard, your users will be able to use them in any app that supports text input.","type":"text"}],"type":"paragraph"},{"anchor":"How-do-I-create-a-custom-keyboard","text":"How do I create a custom keyboard?","type":"heading","level":2},{"inlineContent":[{"text":"You can add a custom keyboard to any iOS app, from Xcode’s “File > New > Target…” menu option. This will add a keyboard extension to your app and make it possible to switch to that keyboard while typing in any app.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"See ","type":"text"},{"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/creating-a-custom-keyboard","isActive":true,"overridingTitleInlineContent":[{"text":"this article","type":"text"}],"type":"reference","overridingTitle":"this article"},{"text":" for a guide on how to create a custom keyboard extension from scratch, and ","type":"text"},{"identifier":"https:\/\/developer.apple.com\/library\/archive\/documentation\/General\/Conceptual\/ExtensibilityPG\/CustomKeyboard.html","isActive":true,"type":"reference"},{"text":" for more extensive information.","type":"text"}],"type":"paragraph"},{"anchor":"What-can-a-custom-keyboard-be-used-for","text":"What can a custom keyboard be used for?","type":"heading","level":2},{"inlineContent":[{"text":"A custom keyboard can be used to provide custom autocomplete & spell-checking functionality, more sophisticated text analysis, AI-based features, etc. The possibilities are endless, but Apple’s native APIs are very limited by default.","type":"text"}],"type":"paragraph"},{"anchor":"What-can-a-custom-keyboard-do","text":"What can a custom keyboard do?","type":"heading","level":2},{"inlineContent":[{"text":"A custom keyboard can render any user interface and resize the keyboard area to fit its content. It uses a ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"document proxy","type":"text"}]},{"text":" to read and write text from and to the currnetly active text field, and can require Full Access to enable capabilities like network access.","type":"text"}],"type":"paragraph"},{"anchor":"What-can-a-custom-keyboard-NOT-do","text":"What can a custom keyboard NOT do?","type":"heading","level":2},{"inlineContent":[{"text":"Apple’s native APIs are very limited, and basically just lets you read and write text in limited ways. Some things are however not possible. For instance, a keyboard can’t draw outside its bounds, and is memory capped at ~70 MB. Apple also doesn’t provide a keyboard view.","type":"text"}],"type":"paragraph"},{"anchor":"Why-should-I-use-KeyboardKit","text":"Why should I use KeyboardKit?","type":"heading","level":2},{"inlineContent":[{"text":"KeyboardKit extends Apple’s native APIs and adds more features to make it a easier to create amazing custom keyboards. KeyboardKit also has a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","isActive":true,"type":"reference"},{"text":" that renders a native-looking, fully customizable keyboard with just a few lines of code.","type":"text"}],"type":"paragraph"},{"anchor":"Why-should-I-use-KeyboardKit-Pro","text":"Why should I use KeyboardKit Pro?","type":"heading","level":2},{"inlineContent":[{"text":"KeyboardKit Pro extends KeyboardKit with pro features, like support for 75+ locales, autocomplete, dictation, fonts, an emoji keyboard, clipboard management, themes, etc.","type":"text"}],"type":"paragraph"},{"anchor":"Further-Reading","text":"Further Reading","type":"heading","level":2},{"inlineContent":[{"text":"See ","type":"text"},{"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/creating-a-custom-keyboard","isActive":true,"overridingTitleInlineContent":[{"text":"this article","type":"text"}],"type":"reference","overridingTitle":"this article"},{"text":" for a guide on how to create a custom keyboard extension from scratch, and ","type":"text"},{"identifier":"https:\/\/developer.apple.com\/library\/archive\/documentation\/General\/Conceptual\/ExtensibilityPG\/CustomKeyboard.html","isActive":true,"overridingTitleInlineContent":[{"text":"this article","type":"text"}],"type":"reference","overridingTitle":"this article"},{"text":" for more extensive information.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"See KeyboardKit’s ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","isActive":true,"type":"reference"},{"text":" guide for further reading on how KeyboardKit can help you create a custom keyboard from scratch.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","interfaceLanguage":"swift"},"kind":"article","seeAlsoSections":[{"generated":true,"anchor":"Developer-Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"],"title":"Developer Essentials"}],"abstract":[{"text":"This developer guide describes how custom iOS keyboard extensions work.","type":"text"}],"references":{"https://developer.apple.com/documentation/uikit/creating-a-custom-keyboard":{"title":"custom iOS keyboard extension","titleInlineContent":[{"type":"text","text":"custom iOS keyboard extension"}],"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/creating-a-custom-keyboard","type":"link","url":"https:\/\/developer.apple.com\/documentation\/uikit\/creating-a-custom-keyboard"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Data-Syncing":{"url":"\/documentation\/keyboardkit\/developer-data-syncing","abstract":[{"text":"This developer guide describes how to sync data between the main app and its keyboard.","type":"text"}],"images":[{"identifier":"Developer-Article-Data-Syncing.jpg","type":"card"}],"type":"topic","title":"Data Syncing","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Getting-Started-Article":{"type":"topic","abstract":[{"type":"text","text":"This developer guide describes how to get started with KeyboardKit."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","title":"Getting Started","role":"article","url":"\/documentation\/keyboardkit\/getting-started-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Experiments":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","url":"\/documentation\/keyboardkit\/developer-experiments","images":[{"type":"card","identifier":"Developer-Article-Experiments.jpg"}],"abstract":[{"text":"This developer guide describes how to enable experimental features.","type":"text"}],"role":"article","title":"Experiments","kind":"article","type":"topic"},"Developer-Article-dSYMs.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-dSYMs.jpg","traits":["1x","light"]}],"identifier":"Developer-Article-dSYMs.jpg","type":"image","alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Memory-Management":{"type":"topic","images":[{"type":"card","identifier":"Developer-Article-Memory-Management.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how to manage memory in a keyboard extensions.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management","role":"article","title":"Memory Management","url":"\/documentation\/keyboardkit\/developer-memory-management"},"Developer-Article-Custom-Keyboards.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Custom-Keyboards.jpg","traits":["1x","light"]}],"type":"image","alt":null,"identifier":"Developer-Article-Custom-Keyboards.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-dSYMs":{"type":"topic","images":[{"type":"card","identifier":"Developer-Article-dSYMs.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how to use dSYMs to obtain more detailed crash reports.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","role":"article","title":"dSYMs","url":"\/documentation\/keyboardkit\/developer-dsyms"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Debugging":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","url":"\/documentation\/keyboardkit\/developer-debugging","images":[{"identifier":"Developer-Article-Debugging.jpg","type":"card"}],"abstract":[{"type":"text","text":"This developer guide describes how to debug a custom keyboard extension."}],"role":"article","kind":"article","title":"Debugging","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","title":"KeyboardView","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","role":"symbol","kind":"symbol","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Articles":{"url":"\/documentation\/keyboardkit\/developer-articles","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}],"role":"collectionGroup","type":"topic","kind":"article","title":"Developer Guides","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles"},"Developer-Article-Debugging.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Debugging.jpg","traits":["1x","light"]}],"type":"image","alt":"Article Icon","identifier":"Developer-Article-Debugging.jpg"},"Developer-Article-Data-Syncing.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Data-Syncing.jpg","traits":["1x","light"]}],"type":"image","alt":"Article Icon","identifier":"Developer-Article-Data-Syncing.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"Developer-Article-Memory-Management.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Memory-Management.jpg","traits":["1x","light"]}],"type":"image","alt":"Article Icon","identifier":"Developer-Article-Memory-Management.jpg"},"Developer-Article-Experiments.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Experiments.jpg","traits":["1x","light"]}],"type":"image","alt":"Article Icon","identifier":"Developer-Article-Experiments.jpg"},"https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/CustomKeyboard.html":{"url":"https:\/\/developer.apple.com\/library\/archive\/documentation\/General\/Conceptual\/ExtensibilityPG\/CustomKeyboard.html","titleInlineContent":[{"text":"this article","type":"text"}],"type":"link","identifier":"https:\/\/developer.apple.com\/library\/archive\/documentation\/General\/Conceptual\/ExtensibilityPG\/CustomKeyboard.html","title":"this article"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"title":"Developer Essentials","anchor":"Developer-Essentials","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"]}],"path":"\/seeAlsoSections","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}