{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"This article links to various developer guides, include feature customiation guides.","type":"text"}],"kind":"article","seeAlsoSections":[{"title":"Articles","anchor":"Articles","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]}],"variants":[{"paths":["\/documentation\/keyboardkit\/developer-articles"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/developer-articles"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"KeyboardKit’s developer guides provide you with hands-on support for various topics that are involved in building keyboard extensions."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"For instance "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","isActive":true},{"type":"text","text":" goes through how to debug a keyboard extension while "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management","isActive":true},{"type":"text","text":" helps you inspect your memory."}],"type":"paragraph"},{"anchor":"Developer-Essentials","text":"Developer Essentials","type":"heading","level":2},{"items":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"],"style":"compactGrid","type":"links"},{"anchor":"Feature-Customizations","text":"Feature Customizations","type":"heading","level":2},{"items":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"],"style":"compactGrid","type":"links"}]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit"]]},"topicSections":[{"title":"Developer Essentials","anchor":"Developer-Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"]},{"title":"Feature Customizations","anchor":"Feature-Customizations","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"]}],"metadata":{"title":"Developer Guides","role":"collectionGroup","modules":[{"name":"KeyboardKit"}]},"references":{"Feature-Themes.jpg":{"identifier":"Feature-Themes.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Themes.jpg","traits":["1x","light"]}],"type":"image","alt":"Article Icon"},"Feature-Feedback.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg"}],"identifier":"Feature-Feedback.jpg","type":"image","alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Feedback":{"type":"topic","images":[{"identifier":"Feature-Feedback.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","abstract":[{"type":"text","text":"This developer guide describes how to customize keyboard feedback."}],"role":"article","title":"Feedback","url":"\/documentation\/keyboardkit\/developer-feedback"},"Developer-Article-Experiments.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Experiments.jpg"}],"identifier":"Developer-Article-Experiments.jpg","type":"image","alt":"Article Icon"},"Developer-Article-Memory-Management.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Memory-Management.jpg","traits":["1x","light"]}],"identifier":"Developer-Article-Memory-Management.jpg","type":"image","alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Experiments":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","url":"\/documentation\/keyboardkit\/developer-experiments","images":[{"type":"card","identifier":"Developer-Article-Experiments.jpg"}],"abstract":[{"text":"This developer guide describes how to enable experimental features.","type":"text"}],"role":"article","title":"Experiments","kind":"article","type":"topic"},"Developer-Article-dSYMs.jpg":{"identifier":"Developer-Article-dSYMs.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-dSYMs.jpg"}],"type":"image","alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Memory-Management":{"type":"topic","images":[{"type":"card","identifier":"Developer-Article-Memory-Management.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how to manage memory in a keyboard extensions.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management","role":"article","title":"Memory Management","url":"\/documentation\/keyboardkit\/developer-memory-management"},"Feature-Dictation.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg"}],"identifier":"Feature-Dictation.jpg","type":"image","alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Dictation":{"type":"topic","images":[{"identifier":"Feature-Dictation.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","abstract":[{"type":"text","text":"This developer guide describes how to set up and customize dictation."}],"role":"article","title":"Dictation","url":"\/documentation\/keyboardkit\/developer-dictation"},"Feature-Actions.jpg":{"alt":"Article Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}],"identifier":"Feature-Actions.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Debugging":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","url":"\/documentation\/keyboardkit\/developer-debugging","images":[{"identifier":"Developer-Article-Debugging.jpg","type":"card"}],"abstract":[{"type":"text","text":"This developer guide describes how to debug a custom keyboard extension."}],"role":"article","kind":"article","title":"Debugging","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Getting-Started-Article":{"type":"topic","abstract":[{"type":"text","text":"This developer guide describes how to get started with KeyboardKit."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","title":"Getting Started","role":"article","url":"\/documentation\/keyboardkit\/getting-started-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Custom-Keyboards":{"type":"topic","images":[{"type":"card","identifier":"Developer-Article-Custom-Keyboards.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how custom iOS keyboard extensions work.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","role":"article","title":"Custom Keyboard Extensions","url":"\/documentation\/keyboardkit\/developer-custom-keyboards"},"Feature-Essentials.jpg":{"alt":"Feature Icon","type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials.jpg","traits":["1x","light"]}],"identifier":"Feature-Essentials.jpg"},"Developer-Article-Custom-Keyboards.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Custom-Keyboards.jpg","traits":["1x","light"]}],"identifier":"Developer-Article-Custom-Keyboards.jpg","type":"image","alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"Developer-Article-Debugging.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Debugging.jpg"}],"identifier":"Developer-Article-Debugging.jpg","type":"image","alt":"Article Icon"},"Feature-Localization.jpg":{"alt":"Article Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg"}],"identifier":"Feature-Localization.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-dSYMs":{"type":"topic","images":[{"type":"card","identifier":"Developer-Article-dSYMs.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how to use dSYMs to obtain more detailed crash reports.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","role":"article","title":"dSYMs","url":"\/documentation\/keyboardkit\/developer-dsyms"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Data-Syncing":{"url":"\/documentation\/keyboardkit\/developer-data-syncing","abstract":[{"text":"This developer guide describes how to sync data between the main app and its keyboard.","type":"text"}],"images":[{"identifier":"Developer-Article-Data-Syncing.jpg","type":"card"}],"type":"topic","title":"Data Syncing","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Localization":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","url":"\/documentation\/keyboardkit\/developer-localization","images":[{"identifier":"Feature-Localization.jpg","type":"card"}],"abstract":[{"type":"text","text":"This developer guide describes how to customize keyboard localization."}],"role":"article","title":"Localization","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Autocomplete":{"type":"topic","images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","abstract":[{"type":"text","text":"This developer guide describes how to set up and customize autocomplete."}],"role":"article","title":"Autocomplete","url":"\/documentation\/keyboardkit\/developer-autocomplete"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Themes":{"abstract":[{"text":"This developer guide describes how to create custom keyboard themes.","type":"text"}],"kind":"article","title":"Themes","type":"topic","images":[{"type":"card","identifier":"Feature-Themes.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes","url":"\/documentation\/keyboardkit\/developer-themes","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"url":"\/documentation\/keyboardkit\/features-articles","abstract":[{"type":"text","text":"This article links to the various KeyboardKit features."}],"role":"collectionGroup","type":"topic","title":"Features","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Actions":{"type":"topic","images":[{"type":"card","identifier":"Feature-Actions.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how to customize the action handling.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","role":"article","title":"Actions","url":"\/documentation\/keyboardkit\/developer-actions"},"Developer-Article-Data-Syncing.jpg":{"alt":"Article Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Data-Syncing.jpg"}],"identifier":"Developer-Article-Data-Syncing.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-Article":{"url":"\/documentation\/keyboardkit\/essentials-article","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"images":[{"identifier":"Feature-Essentials.jpg","type":"card"}],"type":"topic","title":"Essentials","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","kind":"article"},"Feature-Autocomplete.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"identifier":"Feature-Autocomplete.jpg","type":"image","alt":"Article Icon"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"title":"Developer Essentials","anchor":"Developer-Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"]},{"title":"Feature Customizations","anchor":"Feature-Customizations","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"],"generated":true,"anchor":"Articles"}],"path":"\/seeAlsoSections"}]}]}