{"metadata":{"images":[{"type":"card","identifier":"Feature-Autocomplete.jpg"}],"roleHeading":"Article","color":{"standardColorIdentifier":"purple"},"role":"article","modules":[{"name":"KeyboardKit"}],"title":"Autocomplete"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides"],["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article"]]},"sections":[],"seeAlsoSections":[{"anchor":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"],"title":"Features","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete"},"primaryContentSections":[{"content":[{"anchor":"Overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"text":"KeyboardKit makes it easy to perform autocomplete from a keyboard extension. See the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","type":"reference"},{"text":" article for information about this feature and its many capabilities.","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"text":"👑 Autocomplete requires a KeyboardKit Pro license with ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/autocomplete","isActive":true,"type":"reference"},{"text":" support, unless you want to implement it from scratch. You can sign up for KeyboardKit Pro from the ","type":"text"},{"identifier":"https:\/\/keyboardkit.com","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"style":"important","name":"Important","type":"aside"},{"anchor":"How-to-perform-autocomplete","level":2,"text":"How to perform autocomplete","type":"heading"},{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","type":"reference","isActive":true},{"type":"text","text":" will automatically call the main "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Services\/autocompleteService","type":"reference","isActive":true},{"type":"text","text":" "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardController\/performAutocomplete()","type":"reference","isActive":true},{"type":"text","text":" when the current text changes or the input cursor is moved, then update the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/State\/autocompleteContext","type":"reference","isActive":true},{"type":"text","text":" with the autocomplete result."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can trigger autocomplete programmatically by calling the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Services\/autocompleteService"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/autocomplete(_:updating:)"},{"type":"text","text":", which will perform perform autocomplete then update the provided context."}],"type":"paragraph"},{"anchor":"How-to-create-a-custom-autocomplete-service","level":2,"text":"How to create a custom autocomplete service","type":"heading"},{"inlineContent":[{"text":"You can create a custom ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService","isActive":true},{"text":" to customize the autocomplete behavior or integrate with a 3rd party service. You can implement the service protocol from scratch, or inherit and customize the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService","isActive":true},{"text":":","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["class CustomAutocompleteService: Autocomplete.StandardAutocompleteService {","","    override func autocompleteSuggestions(","        for text: String","    ) async throws -> [Autocomplete.Suggestion] {","        let original = super.autocompleteSuggestions(for: text)","        let reversed = original.reversed()","        return Array(reversed)","    }","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"You can override "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/autocomplete(_:)","type":"reference"},{"type":"text","text":" to replace the or tweak the standard suggestions, or override any other function to customize parts of the result, like "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService\/autocompleteSuggestions(for:)","type":"reference"},{"type":"text","text":" and "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService\/nextWordPredictionResult(for:)","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"text":"To use this service instead of the standard service, just inject it into ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services"},{"text":" by replacing the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Services\/autocompleteService"},{"text":" property:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewWillSetupKeyboardKit() {","        services.autocompleteService = CustomAutocompleteService()","        setupKeyboardKit(for: .myApp)  \/\/ See the getting-started guide","    }","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"This will make KeyboardKit use your custom autocomplete service instead of the standard one."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"This developer guide describes how to set up and customize autocomplete."}],"variants":[{"paths":["\/documentation\/keyboardkit\/developer-autocomplete"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkit\/developer-autocomplete"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/StandardAutocompleteService/autocompleteSuggestions(for:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocompleteSuggestions","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"Autocomplete","preciseIdentifier":"s:11KeyboardKit12AutocompleteV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Suggestion","preciseIdentifier":"s:11KeyboardKit12AutocompleteV10SuggestionV","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/keyboardkit\/autocomplete\/standardautocompleteservice\/autocompletesuggestions(for:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService\/autocompleteSuggestions(for:)","abstract":[],"type":"topic","kind":"symbol","role":"symbol","title":"autocompleteSuggestions(for:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"Feature-Actions.jpg":{"identifier":"Feature-Actions.jpg","alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/services":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V"},{"text":".","kind":"text"},{"text":"Services","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V8ServicesC"}],"abstract":[{"type":"text","text":"Keyboard-specific services."}],"role":"symbol","title":"services","kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/services"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Dictation":{"kind":"article","abstract":[{"text":"This developer guide describes how to set up and customize dictation.","type":"text"}],"images":[{"identifier":"Feature-Dictation.jpg","type":"card"}],"title":"Dictation","role":"article","url":"\/documentation\/keyboardkit\/developer-dictation","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardController/performAutocomplete()":{"title":"performAutocomplete()","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardController\/performAutocomplete()","type":"topic","required":true,"role":"symbol","abstract":[{"type":"text","text":"Perform an autocomplete operation."}],"url":"\/documentation\/keyboardkit\/keyboardcontroller\/performautocomplete()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"performAutocomplete","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/Services/autocompleteService":{"url":"\/documentation\/keyboardkit\/keyboard\/services\/autocompleteservice","kind":"symbol","title":"autocompleteService","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocompleteService","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutocompleteService","preciseIdentifier":"s:11KeyboardKit19AutocompleteServiceP","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"The autocomplete service to use.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Services\/autocompleteService"},"Feature-Feedback.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg"}],"type":"image","alt":"Article Icon","identifier":"Feature-Feedback.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Guides":{"url":"\/documentation\/keyboardkit\/developer-guides","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides","role":"collectionGroup","title":"Developer Guides","type":"topic","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteService":{"abstract":[{"type":"text","text":"This protocol can be implemented by any type that can be"},{"type":"text","text":" "},{"type":"text","text":"used perform autocomplete as the user types."}],"kind":"symbol","title":"AutocompleteService","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutocompleteService"}],"url":"\/documentation\/keyboardkit\/autocompleteservice","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutocompleteService"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Actions":{"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","type":"topic","title":"Actions","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This developer guide describes how to customize the action handling.","type":"text"}],"url":"\/documentation\/keyboardkit\/developer-actions","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","type":"topic","url":"\/documentation\/keyboardkit\/autocomplete-article","kind":"article","images":[{"type":"card","identifier":"Feature-Autocomplete.jpg"}],"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Localization":{"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","abstract":[{"type":"text","text":"This developer guide describes how to customize keyboard localization."}],"title":"Localization","type":"topic","url":"\/documentation\/keyboardkit\/developer-localization","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"kind":"article"},"https://keyboardkit.com":{"url":"https:\/\/keyboardkit.com","titleInlineContent":[{"text":"KeyboardKit website","type":"text"}],"title":"KeyboardKit website","type":"link","identifier":"https:\/\/keyboardkit.com"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Themes":{"url":"\/documentation\/keyboardkit\/developer-themes","kind":"article","title":"Themes","type":"topic","images":[{"identifier":"Feature-Themes.jpg","type":"card"}],"abstract":[{"type":"text","text":"This developer guide describes how to create custom keyboard themes."}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"},"Feature-Themes.jpg":{"identifier":"Feature-Themes.jpg","alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Themes.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteService/autocomplete(_:)":{"kind":"symbol","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/autocomplete(_:)","abstract":[{"type":"text","text":"Get autocomplete suggestions for the provided "},{"code":"text","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/keyboardkit\/autocompleteservice\/autocomplete(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocomplete","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Autocomplete","preciseIdentifier":"s:11KeyboardKit12AutocompleteV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11KeyboardKit12AutocompleteV6ResultV"}],"title":"autocomplete(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/autocomplete":{"title":"ProFeature.autocomplete","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocomplete","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/profeature\/autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/autocomplete"},"Feature-Autocomplete.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Autocomplete.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/StandardAutocompleteService/nextWordPredictionResult(for:)":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService\/nextWordPredictionResult(for:)","title":"nextWordPredictionResult(for:)","kind":"symbol","abstract":[{"text":"Get next word predictions for a text.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextWordPredictionResult","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Autocomplete","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit12AutocompleteV"},{"text":".","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit12AutocompleteV6ResultV"},{"text":"?","kind":"text"}],"url":"\/documentation\/keyboardkit\/autocomplete\/standardautocompleteservice\/nextwordpredictionresult(for:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/State/autocompleteContext":{"url":"\/documentation\/keyboardkit\/keyboard\/state\/autocompletecontext","kind":"symbol","title":"autocompleteContext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autocompleteContext"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11KeyboardKit19AutocompleteContextC","kind":"typeIdentifier","text":"AutocompleteContext"}],"type":"topic","abstract":[{"type":"text","text":"Observable autocomplete-related state."}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/State\/autocompleteContext"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController":{"navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"role":"symbol","title":"KeyboardInputViewController","abstract":[{"text":"This is the main input controller type that is used in a","type":"text"},{"text":" ","type":"text"},{"text":"KeyboardKit-based keyboard extension.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/StandardAutocompleteService":{"url":"\/documentation\/keyboardkit\/autocomplete\/standardautocompleteservice","kind":"symbol","navigatorTitle":[{"text":"StandardAutocompleteService","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/StandardAutocompleteService","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StandardAutocompleteService","kind":"identifier"}],"title":"Autocomplete.StandardAutocompleteService","type":"topic","abstract":[{"type":"text","text":"This service can be used to perform autocomplete and"},{"type":"text","text":" "},{"type":"text","text":"autocorrect directly on device."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteService/autocomplete(_:updating:)":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService\/autocomplete(_:updating:)","abstract":[{"text":"Perform a background autocomplete operation and sync","type":"text"},{"text":" ","type":"text"},{"text":"the result or error to the provided context.","type":"text"}],"url":"\/documentation\/keyboardkit\/autocompleteservice\/autocomplete(_:updating:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocomplete","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"updating","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutocompleteContext","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit19AutocompleteContextC"},{"text":")","kind":"text"}],"title":"autocomplete(_:updating:)"},"Feature-Dictation.jpg":{"alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Dictation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Feedback":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","abstract":[{"text":"This developer guide describes how to customize keyboard feedback.","type":"text"}],"role":"article","title":"Feedback","kind":"article","url":"\/documentation\/keyboardkit\/developer-feedback","images":[{"identifier":"Feature-Feedback.jpg","type":"card"}]},"Feature-Localization.jpg":{"identifier":"Feature-Localization.jpg","alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg","traits":["1x","light"]}],"type":"image"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"generated":true,"title":"Features","anchor":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"]}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"op":"replace","value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/navigatorTitle","value":[{"kind":"identifier","text":"KeyboardInputViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}