{"kind":"article","sections":[],"abstract":[{"text":"This developer guide describes how to debug a custom keyboard extension.","type":"text"}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"],"generated":true,"anchor":"Developer-Essentials","title":"Developer Essentials"}],"metadata":{"modules":[{"name":"KeyboardKit"}],"role":"article","images":[{"identifier":"Developer-Article-Debugging.jpg","type":"card"}],"color":{"standardColorIdentifier":"purple"},"title":"Debugging","roleHeading":"Article"},"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"type":"text","text":"Custom keyboard extensions are a bit tricky to debug, since launching the app will not trigger breakpoints in your keyboard by default. This article will show you how to get started with debugging your keyboard extension."}],"type":"paragraph"},{"type":"heading","level":2,"text":"Attaching to the debugger","anchor":"Attaching-to-the-debugger"},{"inlineContent":[{"type":"text","text":"To debug the keyboard extension, you must either launch the extension instead of the app, or manually attach the Xcode debugger to the keyboard process, using the "},{"type":"codeVoice","code":"Debug > Attach to Process by PID or Name..."},{"type":"text","text":" menu option."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Once the debugger is attached to the keyboard, you will be able to make printouts, place breakpoints, inspect the memory graph, etc. By becoming comfortable with debugging your keyboard, you will find it a lot easier to find and fix problems."}]},{"text":"Attaching the debugger by launching the keyboard","type":"heading","anchor":"Attaching-the-debugger-by-launching-the-keyboard","level":3},{"type":"paragraph","inlineContent":[{"text":"You can launch your keyboard instead of the main app, by switching target in the Xcode Target Switcher then choosing “Project > Run”.","type":"text"}]},{"type":"paragraph","inlineContent":[{"identifier":"developer-debugging-target","type":"image"}]},{"inlineContent":[{"type":"text","text":"This method make the debugger wait for the keyboard to launch & open, before it automatically attaches itself to the keyboard process."}],"type":"paragraph"},{"content":[{"inlineContent":[{"type":"text","text":"This can cause the keyboard launch to take too long, which may cause Xcode to terminate it. This can lead to inaccurate behavior."}],"type":"paragraph"}],"type":"aside","name":"Warning","style":"warning"},{"anchor":"Attaching-the-debugger-manually","type":"heading","level":3,"text":"Attaching the debugger manually"},{"inlineContent":[{"text":"Instead of launching the keyboard to automatically attach the debugger, you can attach the debugger ","type":"text"},{"inlineContent":[{"type":"text","text":"after"}],"type":"emphasis"},{"text":" the keyboard has launched.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"image","identifier":"developer-debugging-attaching"}],"type":"paragraph"},{"inlineContent":[{"text":"To attach the debugger to the keyboard process, launch the app then open the keyboard. You can then attach the debugger with ","type":"text"},{"code":"Debug > Attach to Process by PID or Name...","type":"codeVoice"},{"text":" and enter the keyboard target name.","type":"text"}],"type":"paragraph"},{"level":2,"anchor":"Common-warnings","text":"Common warnings","type":"heading"},{"inlineContent":[{"text":"When debugging your keyboard extension, you may see the following warning being logged multiple times as you use the keyboard:","type":"text"}],"type":"paragraph"},{"inlineContent":[{"code":"-[UIInputViewController needsInputModeSwitchKey] was called before a connection was established to the host application. This will produce an inaccurate result. Please make sure to call this after your primary view controller has been initialized.","type":"codeVoice"}],"type":"paragraph"},{"inlineContent":[{"text":"This warning is logged because KeyboardKit checks the ","type":"text"},{"code":"needsInputModeSwitchKey","type":"codeVoice"},{"text":" property to determine whether or not to add a globe key to the keyboard. This warning is logged even after the keyboard is presented.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Even if you see warnings like this, it doesn’t mean that they have any negative effect on the keyboard. It would be nice to remove these warnings from the system log, but sometimes it’s not feasible.","type":"text"}],"type":"paragraph"},{"level":2,"anchor":"Debug-printing","text":"Debug printing","type":"heading"},{"inlineContent":[{"text":"When the debugger is attached to the keyboard process, you may find that the ","type":"text"},{"code":"print","type":"codeVoice"},{"text":" command doesn’t always work as expected. If so, you can use ","type":"text"},{"code":"NSLog(...)","type":"codeVoice"},{"text":" instead.","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["print(\"This may not print.\")","NSLog(\"This will always print.\")"]},{"type":"paragraph","inlineContent":[{"text":"Since NSLog is more limited than printing, you may want to consider usung custom or other system logging methods, like ","type":"text"},{"code":"os_log_*","type":"codeVoice"},{"text":".","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/keyboardkit\/developer-debugging"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkit\/developer-debugging"]}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Memory-Management":{"type":"topic","images":[{"type":"card","identifier":"Developer-Article-Memory-Management.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how to manage memory in a keyboard extensions.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management","role":"article","title":"Memory Management","url":"\/documentation\/keyboardkit\/developer-memory-management"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"Developer-Article-Memory-Management.jpg":{"alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Memory-Management.jpg"}],"identifier":"Developer-Article-Memory-Management.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Articles":{"url":"\/documentation\/keyboardkit\/developer-articles","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}],"role":"collectionGroup","type":"topic","kind":"article","title":"Developer Guides","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles"},"Developer-Article-Experiments.jpg":{"alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Experiments.jpg","traits":["1x","light"]}],"identifier":"Developer-Article-Experiments.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Data-Syncing":{"url":"\/documentation\/keyboardkit\/developer-data-syncing","abstract":[{"text":"This developer guide describes how to sync data between the main app and its keyboard.","type":"text"}],"images":[{"identifier":"Developer-Article-Data-Syncing.jpg","type":"card"}],"type":"topic","title":"Data Syncing","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Custom-Keyboards":{"type":"topic","images":[{"type":"card","identifier":"Developer-Article-Custom-Keyboards.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how custom iOS keyboard extensions work.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","role":"article","title":"Custom Keyboard Extensions","url":"\/documentation\/keyboardkit\/developer-custom-keyboards"},"developer-debugging-attaching":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-debugging-attaching.png","traits":["1x","light"]}],"type":"image","identifier":"developer-debugging-attaching","alt":"A screenshot of how to attach to the debugger"},"Developer-Article-Debugging.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Debugging.jpg"}],"type":"image","identifier":"Developer-Article-Debugging.jpg","alt":null},"Developer-Article-Custom-Keyboards.jpg":{"identifier":"Developer-Article-Custom-Keyboards.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Custom-Keyboards.jpg","traits":["1x","light"]}],"type":"image","alt":"Article Icon"},"Developer-Article-Data-Syncing.jpg":{"identifier":"Developer-Article-Data-Syncing.jpg","alt":"Article Icon","type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Data-Syncing.jpg","traits":["1x","light"]}]},"Developer-Article-dSYMs.jpg":{"identifier":"Developer-Article-dSYMs.jpg","alt":"Article Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-dSYMs.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Experiments":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","url":"\/documentation\/keyboardkit\/developer-experiments","images":[{"type":"card","identifier":"Developer-Article-Experiments.jpg"}],"abstract":[{"text":"This developer guide describes how to enable experimental features.","type":"text"}],"role":"article","title":"Experiments","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-dSYMs":{"type":"topic","images":[{"type":"card","identifier":"Developer-Article-dSYMs.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how to use dSYMs to obtain more detailed crash reports.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","role":"article","title":"dSYMs","url":"\/documentation\/keyboardkit\/developer-dsyms"},"developer-debugging-target":{"identifier":"developer-debugging-target","alt":"A screenshot of how to launch the keyboard extension","type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-debugging-target.png","traits":["1x","light"]}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"title":"Developer Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"],"generated":true,"anchor":"Developer-Essentials"}],"path":"\/seeAlsoSections","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}