{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit"]]},"topicSections":[{"anchor":"Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"],"title":"Essentials"},{"anchor":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"],"title":"Features"}],"metadata":{"modules":[{"name":"KeyboardKit"}],"title":"Developer Guides","role":"collectionGroup"},"seeAlsoSections":[{"anchor":"Articles","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"],"title":"Articles"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkit\/developer-guides"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkit\/developer-guides"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides"},"abstract":[{"text":"This article links to various developer guides, include feature customiation guides.","type":"text"}],"primaryContentSections":[{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit’s developer guides provide you with hands-on support for various topics that are involved in building keyboard extensions.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"For instance ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging"},{"text":" goes through how to debug a keyboard extension while ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"},{"text":" helps you inspect your memory.","type":"text"}]},{"anchor":"Developer-Essentials","type":"heading","level":2,"text":"Developer Essentials"},{"style":"compactGrid","type":"links","items":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"]},{"anchor":"Feature-Customizations","type":"heading","level":2,"text":"Feature Customizations"},{"style":"compactGrid","type":"links","items":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"]}],"kind":"content"}],"kind":"article","references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Experiments":{"kind":"article","url":"\/documentation\/keyboardkit\/developer-experiments","role":"article","type":"topic","title":"Experiments","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","images":[{"type":"card","identifier":"Developer-Article-Experiments.jpg"}],"abstract":[{"text":"This developer guide describes how to enable experimental features.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-KeyboardView":{"kind":"article","type":"topic","url":"\/documentation\/keyboardkit\/essentials-keyboardview","title":"Essentials - KeyboardView","abstract":[{"type":"text","text":"This article describes the essential "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"type":"text","text":" and how to use and configure it."}],"images":[{"type":"card","identifier":"Feature-Essentials-KeyboardView.jpg"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView"},"Developer-Article-Custom-Keyboards.jpg":{"identifier":"Developer-Article-Custom-Keyboards.jpg","alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Custom-Keyboards.jpg","traits":["1x","light"]}],"type":"image"},"Feature-Actions.jpg":{"type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg","traits":["1x","light"]}],"alt":"Article Icon","identifier":"Feature-Actions.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Debugging":{"abstract":[{"text":"This developer guide describes how to debug a custom keyboard extension.","type":"text"}],"kind":"article","images":[{"identifier":"Developer-Article-Debugging.jpg","type":"card"}],"title":"Debugging","role":"article","url":"\/documentation\/keyboardkit\/developer-debugging","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"Feature-Essentials.jpg":{"alt":"Feature Icon","identifier":"Feature-Essentials.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-dSYMs":{"url":"\/documentation\/keyboardkit\/developer-dsyms","type":"topic","images":[{"identifier":"Developer-Article-dSYMs.jpg","type":"card"}],"title":"dSYMs","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","role":"article","abstract":[{"type":"text","text":"This developer guide describes how to use dSYMs to obtain more detailed crash reports."}],"kind":"article"},"Developer-Article-dSYMs.jpg":{"identifier":"Developer-Article-dSYMs.jpg","alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-dSYMs.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","type":"topic","url":"\/documentation\/keyboardkit\/essentials-article","kind":"article","images":[{"identifier":"Feature-Essentials.jpg","type":"card"}],"role":"article","title":"Essentials","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Dictation":{"kind":"article","abstract":[{"text":"This developer guide describes how to set up and customize dictation.","type":"text"}],"images":[{"identifier":"Feature-Dictation.jpg","type":"card"}],"title":"Dictation","role":"article","url":"\/documentation\/keyboardkit\/developer-dictation","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation"},"Feature-Feedback.jpg":{"identifier":"Feature-Feedback.jpg","alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg"}],"type":"image"},"Developer-Article-Debugging.jpg":{"identifier":"Developer-Article-Debugging.jpg","alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Debugging.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Actions":{"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","type":"topic","title":"Actions","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This developer guide describes how to customize the action handling.","type":"text"}],"url":"\/documentation\/keyboardkit\/developer-actions","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Autocomplete":{"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/developer-autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","abstract":[{"text":"This developer guide describes how to set up and customize autocomplete.","type":"text"}],"type":"topic","role":"article","kind":"article","title":"Autocomplete"},"Developer-Article-Memory-Management.jpg":{"alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Memory-Management.jpg","traits":["1x","light"]}],"identifier":"Developer-Article-Memory-Management.jpg","type":"image"},"Developer-Article-Data-Syncing.jpg":{"type":"image","identifier":"Developer-Article-Data-Syncing.jpg","alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Data-Syncing.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Localization":{"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","abstract":[{"type":"text","text":"This developer guide describes how to customize keyboard localization."}],"title":"Localization","type":"topic","url":"\/documentation\/keyboardkit\/developer-localization","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Themes":{"url":"\/documentation\/keyboardkit\/developer-themes","kind":"article","title":"Themes","type":"topic","images":[{"identifier":"Feature-Themes.jpg","type":"card"}],"abstract":[{"type":"text","text":"This developer guide describes how to create custom keyboard themes."}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Getting-Started-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","abstract":[{"type":"text","text":"This developer guide describes how to get started with KeyboardKit."}],"kind":"article","role":"article","type":"topic","url":"\/documentation\/keyboardkit\/getting-started-article","title":"Getting Started"},"Feature-Autocomplete.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"alt":"Article Icon","type":"image","identifier":"Feature-Autocomplete.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"kind":"symbol","title":"KeyboardView","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"Feature-Essentials-KeyboardView.jpg":{"identifier":"Feature-Essentials-KeyboardView.jpg","alt":"Feature Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials-KeyboardView.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Custom-Keyboards":{"kind":"article","abstract":[{"type":"text","text":"This developer guide describes how custom iOS keyboard extensions work."}],"images":[{"identifier":"Developer-Article-Custom-Keyboards.jpg","type":"card"}],"title":"Custom Keyboard Extensions","role":"article","url":"\/documentation\/keyboardkit\/developer-custom-keyboards","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards"},"Developer-Article-Experiments.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Experiments.jpg"}],"alt":"Article Icon","type":"image","identifier":"Developer-Article-Experiments.jpg"},"Feature-Themes.jpg":{"type":"image","identifier":"Feature-Themes.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Themes.jpg","traits":["1x","light"]}],"alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Memory-Management":{"url":"\/documentation\/keyboardkit\/developer-memory-management","abstract":[{"text":"This developer guide describes how to manage memory in a keyboard extensions.","type":"text"}],"images":[{"identifier":"Developer-Article-Memory-Management.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management","title":"Memory Management","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Data-Syncing":{"url":"\/documentation\/keyboardkit\/developer-data-syncing","type":"topic","images":[{"type":"card","identifier":"Developer-Article-Data-Syncing.jpg"}],"title":"Data Syncing","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","role":"article","abstract":[{"type":"text","text":"This developer guide describes how to sync data between the main app and its keyboard."}],"kind":"article"},"Feature-Dictation.jpg":{"alt":"Article Icon","type":"image","identifier":"Feature-Dictation.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Feedback":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","abstract":[{"text":"This developer guide describes how to customize keyboard feedback.","type":"text"}],"role":"article","title":"Feedback","kind":"article","url":"\/documentation\/keyboardkit\/developer-feedback","images":[{"identifier":"Feature-Feedback.jpg","type":"card"}]},"Feature-Localization.jpg":{"alt":"Article Icon","type":"image","identifier":"Feature-Localization.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg","traits":["1x","light"]}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Essentials","anchor":"Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"]},{"title":"Features","anchor":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"],"title":"Articles","generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}