{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"This developer guide describes how to customize keyboard localization."}],"kind":"article","seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"],"anchor":"Feature-Customizations","title":"Feature Customizations","generated":true}],"variants":[{"paths":["\/documentation\/keyboardkit\/developer-localization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/developer-localization"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit supports 75 locales. See the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article"},{"type":"text","text":" article for information about how to localize your keyboard and its various views."}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"👑 KeyboardKit Pro can be used to unlock supported locales. You can sign up for KeyboardKit Pro from the "},{"identifier":"https:\/\/keyboardkit.com","type":"reference","isActive":true},{"type":"text","text":"."}]}],"type":"aside","name":"Important","style":"important"},{"anchor":"How-to-set-the-primary-language","type":"heading","level":2,"text":"How to set the primary language"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Setting the keyboard "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/locale"},{"type":"text","text":" will update the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UIInputViewController"},{"type":"text","text":"‘s "},{"type":"codeVoice","code":"primaryLanguage"},{"type":"text","text":" property. This will affect things like spell checking and text direction, and sets the keyboard’s language subtitle in the system keyboard switcher."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"primaryLanguage"},{"type":"text","text":" property seems to always return "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", even after it has been set properly. This can be confusing, but you can verify that it has been set by inspecting that the proper language is displayed in the system keyboard switcher."}]},{"anchor":"How-to-support-LTR--RTL-locales","type":"heading","level":3,"text":"How to support LTR & RTL locales"},{"inlineContent":[{"text":"KeyboardKit supports LTR (Left-To-Right) & RTL (Right-To-Left) locales. Just change the locale as shown above, and KeyboardKit will automatically adjust the text direction, spell checking, etc.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can also force a keyboard extension to render itself in RTL. To do this, just adjust the keyboard extension’s "},{"inlineContent":[{"text":"Info.plist","type":"text"}],"type":"strong"},{"text":" file like this:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Set ","type":"text"},{"inlineContent":[{"text":"PrefersRightToLeft","type":"text"}],"type":"strong"},{"text":" to ","type":"text"},{"inlineContent":[{"text":"1","type":"text"}],"type":"strong"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Set ","type":"text"},{"type":"strong","inlineContent":[{"text":"PrimaryLanguage","type":"text"}]},{"text":" to the language code of your locale, e.g. ","type":"text"},{"type":"strong","inlineContent":[{"text":"fa","type":"text"}]},{"text":" for Perian (Farsi).","type":"text"}]}]}]},{"inlineContent":[{"text":"Just be aware that setting the primary language like this may affect external keyboard mappings if you don’t set the primary language.","type":"text"}],"type":"paragraph"},{"text":"How to translate localized content","anchor":"How-to-translate-localized-content","type":"heading","level":2},{"inlineContent":[{"text":"Each ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/keyboardKitSupported"},{"text":" locale has a localized file in ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Resources\/[id].lproj"}]},{"text":" with texts that are applied with the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KKL10n"},{"text":" enum:","type":"text"}],"type":"paragraph"},{"syntax":null,"type":"codeListing","code":["let translation = KKL10n.keyboardTypeNumeric.text"]},{"type":"paragraph","inlineContent":[{"text":"You can translate any key for any supported locale, using the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KKL10n\/text(forLocale:)","type":"reference","isActive":true},{"text":", which parses the resource for the provided locale.","type":"text"}]},{"text":"How to translate locale display names","anchor":"How-to-translate-locale-display-names","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can change the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/localePresentationLocale"},{"type":"text","text":" to set which locale to use when displaying locales. It’s set to the current locale by default, but you can change it to any locale, or set it to nil to use each locale’s own language."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit also extends "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale","type":"reference","isActive":true},{"text":" with ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/localizedName","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/localizedName(in:)","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/localizedLanguageName(in:)","type":"reference","isActive":true},{"type":"text","text":" to let you display a locale in any way you like."}]}]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles"],["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article"]]},"metadata":{"roleHeading":"Article","modules":[{"name":"KeyboardKit"}],"color":{"standardColorIdentifier":"purple"},"title":"Localization","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"role":"article"},"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/keyboardKitSupported":{"url":"\/documentation\/keyboardkit\/foundation\/locale\/keyboardkitsupported","kind":"symbol","abstract":[{"text":"A list of KeyboardKit supported locales.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/keyboardKitSupported","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardKitSupported","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"},{"text":"]","kind":"text"}],"type":"topic","title":"keyboardKitSupported"},"Feature-Themes.jpg":{"alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Themes.jpg","traits":["1x","light"]}],"identifier":"Feature-Themes.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/localePresentationLocale":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/localePresentationLocale","url":"\/documentation\/keyboardkit\/keyboardcontext\/localepresentationlocale","abstract":[{"type":"text","text":"The locale to use to localize other locale names. If"},{"type":"text","text":" "},{"type":"text","text":"this is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", each locale will use its own language."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localePresentationLocale","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"localePresentationLocale","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Feedback":{"type":"topic","images":[{"identifier":"Feature-Feedback.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","abstract":[{"type":"text","text":"This developer guide describes how to customize keyboard feedback."}],"role":"article","title":"Feedback","url":"\/documentation\/keyboardkit\/developer-feedback"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Articles":{"url":"\/documentation\/keyboardkit\/developer-articles","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}],"role":"collectionGroup","type":"topic","kind":"article","title":"Developer Guides","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles"},"Feature-Feedback.jpg":{"alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg","traits":["1x","light"]}],"identifier":"Feature-Feedback.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UIInputViewController":{"abstract":[],"kind":"symbol","title":"UIInputViewController","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UIInputViewController","navigatorTitle":[{"text":"UIInputViewController","kind":"identifier"}],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIInputViewController","text":"UIInputViewController","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/uikit\/uiinputviewcontroller","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/localizedLanguageName(in:)":{"url":"\/documentation\/keyboardkit\/foundation\/locale\/localizedlanguagename(in:)","abstract":[{"type":"text","text":"The language name of this locale in another locale."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedLanguageName"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","kind":"symbol","title":"localizedLanguageName(in:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/localizedLanguageName(in:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext":{"title":"KeyboardContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"type":"text","text":"for the core keyboard functionality."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"type":"topic","url":"\/documentation\/keyboardkit\/keyboardcontext","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale":{"url":"\/documentation\/keyboardkit\/foundation\/locale","navigatorTitle":[{"kind":"identifier","text":"Locale"}],"abstract":[],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"s:10Foundation6LocaleV","kind":"identifier","text":"Locale"}],"role":"symbol","type":"topic","kind":"symbol","title":"Locale","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/locale":{"url":"\/documentation\/keyboardkit\/keyboardcontext\/locale","abstract":[{"text":"The current locale, by default ","type":"text"},{"code":".current","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale"}],"type":"topic","title":"locale","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/locale","kind":"symbol"},"Feature-Dictation.jpg":{"alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}],"identifier":"Feature-Dictation.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Dictation":{"type":"topic","images":[{"identifier":"Feature-Dictation.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","abstract":[{"type":"text","text":"This developer guide describes how to set up and customize dictation."}],"role":"article","title":"Dictation","url":"\/documentation\/keyboardkit\/developer-dictation"},"Feature-Actions.jpg":{"alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg","traits":["1x","light"]}],"identifier":"Feature-Actions.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KKL10n":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KKL10n","url":"\/documentation\/keyboardkit\/kkl10n","abstract":[{"type":"text","text":"This enum defines localized keyboard texts."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KKL10n"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KKL10n"}],"title":"KKL10n","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Localization-Article":{"type":"topic","images":[{"identifier":"Feature-Localization.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","kind":"article","title":"Localization","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"url":"\/documentation\/keyboardkit\/localization-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"Feature-Localization.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg","traits":["1x","light"]}],"identifier":"Feature-Localization.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Themes":{"abstract":[{"text":"This developer guide describes how to create custom keyboard themes.","type":"text"}],"kind":"article","title":"Themes","type":"topic","images":[{"type":"card","identifier":"Feature-Themes.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes","url":"\/documentation\/keyboardkit\/developer-themes","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Autocomplete":{"type":"topic","images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","abstract":[{"type":"text","text":"This developer guide describes how to set up and customize autocomplete."}],"role":"article","title":"Autocomplete","url":"\/documentation\/keyboardkit\/developer-autocomplete"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/localizedName(in:)":{"type":"topic","abstract":[{"type":"text","text":"The full name of this locale in another locale."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedName"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/localizedName(in:)","title":"localizedName(in:)","role":"symbol","url":"\/documentation\/keyboardkit\/foundation\/locale\/localizedname(in:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/localizedName":{"url":"\/documentation\/keyboardkit\/foundation\/locale\/localizedname","kind":"symbol","abstract":[{"text":"The full name of this locale in its own language.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/localizedName","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","title":"localizedName"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"url":"\/documentation\/keyboardkit\/features-articles","abstract":[{"type":"text","text":"This article links to the various KeyboardKit features."}],"role":"collectionGroup","type":"topic","title":"Features","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Actions":{"type":"topic","images":[{"type":"card","identifier":"Feature-Actions.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how to customize the action handling.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","role":"article","title":"Actions","url":"\/documentation\/keyboardkit\/developer-actions"},"https://keyboardkit.com":{"title":"KeyboardKit website","titleInlineContent":[{"type":"text","text":"KeyboardKit website"}],"identifier":"https:\/\/keyboardkit.com","url":"https:\/\/keyboardkit.com","type":"link"},"Feature-Autocomplete.jpg":{"alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg","traits":["1x","light"]}],"identifier":"Feature-Autocomplete.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KKL10n/text(forLocale:)":{"abstract":[{"type":"text","text":"Get the localized text for a certain "},{"type":"codeVoice","code":"Locale"},{"type":"text","text":"."}],"kind":"symbol","title":"text(forLocale:)","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KKL10n\/text(forLocale:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forLocale","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkit\/kkl10n\/text(forlocale:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"],"anchor":"Feature-Customizations","title":"Feature Customizations","generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}