{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing"},"abstract":[{"type":"text","text":"This developer guide describes how to sync data between the main app and its keyboard."}],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"inlineContent":[{"type":"text","text":"KeyboardKit makes it easy to sync data between the main app and its keyboard extension, by setting up an App Group and adding that information to your "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"text":"Step 1. Create an App Group","level":2,"anchor":"Step-1-Create-an-App-Group","type":"heading"},{"inlineContent":[{"type":"text","text":"You must first create an App Group in the Apple Developer Portal, under Certificates, Identifiers & Profiles. Select “Identifiers” and tap the plus button to add a new App Group with the name “group.<your-apps-bundle-id>”."}],"type":"paragraph"},{"inlineContent":[{"type":"image","identifier":"developer-data-sync-developer-portal"}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"text":"macOS App Groups must start with Team ID instead of “group.”. This means that you must use different groups on iOS and macOS.","type":"text"}]}],"style":"important","name":"Important","type":"aside"},{"text":"Step 2. Add the App Group to all targets","level":2,"anchor":"Step-2-Add-the-App-Group-to-all-targets","type":"heading"},{"inlineContent":[{"type":"text","text":"After creating your new App Group, you must enable it for both your app and its keyboard extension, under “Signing & Capabilites”."}],"type":"paragraph"},{"inlineContent":[{"type":"image","identifier":"developer-data-sync-xcode-app"}],"type":"paragraph"},{"content":[{"inlineContent":[{"type":"text","text":"It’s important to enable the App Group for all targets that will share data, otherwise the data will not be synced across all targets."}],"type":"paragraph"}],"style":"important","name":"Important","type":"aside"},{"text":"Step 3. Set up KeyboardKit to use the App Group","level":2,"anchor":"Step-3-Set-up-KeyboardKit-to-use-the-App-Group","type":"heading"},{"inlineContent":[{"type":"text","text":"To use the App Group with KeyboardKit, just add it to the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/appGroupId"},{"type":"text","text":" in the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp"},{"type":"text","text":" you use to set up KeyboardKit. This will replace the main setting "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/store"},{"type":"text","text":" with a store that syncs changes between the main app and its keyboard."}],"type":"paragraph"},{"inlineContent":[{"type":"image","identifier":"developer-data-sync-keyboard-app"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","type":"reference","isActive":true},{"text":" guide shows you how to create an app-specific ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","type":"reference","isActive":true},{"text":" value and use it to set up your app and keyboard.","type":"text"}]},{"text":"Manual Setup (Optional)","anchor":"Manual-Setup-Optional","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you don’t want to use a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","type":"reference","isActive":true},{"type":"text","text":" to set up data sync, you can set up the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings","type":"reference","isActive":true},{"type":"text","text":" settings "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/store","type":"reference","isActive":true},{"type":"text","text":" manually as well. Just set the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/store","type":"reference","isActive":true},{"type":"text","text":" to a custom "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/UserDefaults","type":"reference","isActive":true},{"type":"text","text":" that is configured to sync data in a way that fits your needs."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When you set up data sync manually, you have to make sure that the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/store","type":"reference","isActive":true},{"type":"text","text":" is properly configured in both the app and the keyboard."}]}]}],"variants":[{"paths":["\/documentation\/keyboardkit\/developer-data-syncing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/developer-data-syncing"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides"],["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Settings-Article"]]},"kind":"article","metadata":{"images":[{"identifier":"Developer-Article-Data-Syncing.jpg","type":"card"}],"role":"article","modules":[{"name":"KeyboardKit"}],"roleHeading":"Article","title":"Data Syncing","color":{"standardColorIdentifier":"purple"}},"schemaVersion":{"patch":0,"minor":3,"major":0},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"],"generated":true,"anchor":"Essentials"}],"references":{"Developer-Article-Custom-Keyboards.jpg":{"alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Custom-Keyboards.jpg"}],"type":"image","identifier":"Developer-Article-Custom-Keyboards.jpg"},"Developer-Article-Experiments.jpg":{"alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Experiments.jpg","traits":["1x","light"]}],"type":"image","identifier":"Developer-Article-Experiments.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Getting-Started-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","abstract":[{"type":"text","text":"This developer guide describes how to get started with KeyboardKit."}],"kind":"article","role":"article","type":"topic","url":"\/documentation\/keyboardkit\/getting-started-article","title":"Getting Started"},"Developer-Article-Debugging.jpg":{"identifier":"Developer-Article-Debugging.jpg","alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Debugging.jpg"}],"type":"image"},"Developer-Article-dSYMs.jpg":{"alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-dSYMs.jpg"}],"type":"image","identifier":"Developer-Article-dSYMs.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardSettings":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardSettings","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings","type":"topic","navigatorTitle":[{"text":"KeyboardSettings","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This type has auto-persisted keyboard settings.","type":"text"}],"url":"\/documentation\/keyboardkit\/keyboardsettings","role":"symbol","title":"KeyboardSettings"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","title":"KeyboardApp","navigatorTitle":[{"text":"KeyboardApp","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/keyboardapp","abstract":[{"type":"text","text":"This type can be used to define important properties for"},{"type":"text","text":" "},{"type":"text","text":"your app, and is also a namespace for app-based features."}],"role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardApp","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Custom-Keyboards":{"kind":"article","abstract":[{"type":"text","text":"This developer guide describes how custom iOS keyboard extensions work."}],"images":[{"identifier":"Developer-Article-Custom-Keyboards.jpg","type":"card"}],"title":"Custom Keyboard Extensions","role":"article","url":"\/documentation\/keyboardkit\/developer-custom-keyboards","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards"},"developer-data-sync-developer-portal":{"alt":"A screenshot of the Apple Developer Portal","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-data-sync-developer-portal.png","traits":["1x","light"]}],"type":"image","identifier":"developer-data-sync-developer-portal"},"developer-data-sync-xcode-app":{"identifier":"developer-data-sync-xcode-app","alt":"A screenshot of how to enable App Groups in Xcode","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-data-sync-xcode-app.png"}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/UserDefaults":{"url":"\/documentation\/keyboardkit\/foundation\/userdefaults","kind":"symbol","title":"UserDefaults","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:objc(cs)NSUserDefaults","text":"UserDefaults"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserDefaults"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/UserDefaults"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Memory-Management":{"url":"\/documentation\/keyboardkit\/developer-memory-management","abstract":[{"text":"This developer guide describes how to manage memory in a keyboard extensions.","type":"text"}],"images":[{"identifier":"Developer-Article-Memory-Management.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management","title":"Memory Management","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Guides":{"url":"\/documentation\/keyboardkit\/developer-guides","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides","role":"collectionGroup","title":"Developer Guides","type":"topic","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}]},"Feature-Settings.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Settings.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Settings.jpg"},"developer-data-sync-keyboard-app":{"type":"image","identifier":"developer-data-sync-keyboard-app","alt":"A screenshot of how to add the App Group to the Keyboard App struct","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-data-sync-keyboard-app.png","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Settings-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit settings engine and its available settings."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Settings-Article","kind":"article","type":"topic","role":"article","title":"Settings","url":"\/documentation\/keyboardkit\/settings-article","images":[{"identifier":"Feature-Settings.jpg","type":"card"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Debugging":{"abstract":[{"text":"This developer guide describes how to debug a custom keyboard extension.","type":"text"}],"kind":"article","images":[{"identifier":"Developer-Article-Debugging.jpg","type":"card"}],"title":"Debugging","role":"article","url":"\/documentation\/keyboardkit\/developer-debugging","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/appGroupId":{"url":"\/documentation\/keyboardkit\/keyboardapp\/appgroupid","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/appGroupId","abstract":[{"type":"text","text":"The app’s App Group identifier, if any."}],"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appGroupId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"appGroupId","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Experiments":{"kind":"article","url":"\/documentation\/keyboardkit\/developer-experiments","role":"article","type":"topic","title":"Experiments","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","images":[{"type":"card","identifier":"Developer-Article-Experiments.jpg"}],"abstract":[{"text":"This developer guide describes how to enable experimental features.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-dSYMs":{"url":"\/documentation\/keyboardkit\/developer-dsyms","type":"topic","images":[{"identifier":"Developer-Article-dSYMs.jpg","type":"card"}],"title":"dSYMs","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","role":"article","abstract":[{"type":"text","text":"This developer guide describes how to use dSYMs to obtain more detailed crash reports."}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"Developer-Article-Memory-Management.jpg":{"alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Memory-Management.jpg","traits":["1x","light"]}],"identifier":"Developer-Article-Memory-Management.jpg","type":"image"},"Developer-Article-Data-Syncing.jpg":{"alt":null,"type":"image","identifier":"Developer-Article-Data-Syncing.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Data-Syncing.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardSettings/store":{"url":"\/documentation\/keyboardkit\/keyboardsettings\/store","type":"topic","title":"store","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/store","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserDefaults","preciseIdentifier":"c:objc(cs)NSUserDefaults"}],"role":"symbol","abstract":[{"type":"text","text":"The store that will be used by library settings."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"anchor":"Essentials","title":"Essentials","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"]}],"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}