{"metadata":{"title":"Themes","role":"article","images":[{"type":"card","identifier":"Feature-Themes.jpg"}],"modules":[{"name":"KeyboardKit"}],"color":{"standardColorIdentifier":"purple"},"roleHeading":"Article"},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"Overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"The KeyboardKit ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme","type":"reference","isActive":true},{"type":"text","text":" engine makes it easy to style an entire keyboard with a single theme. KeyboardKit Pro has many "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme\/predefined","isActive":true},{"type":"text","text":" themes, and lets you create completely custom themes as well."}]},{"type":"aside","name":"Important","style":"important","content":[{"inlineContent":[{"type":"text","text":"👑 KeyboardKit Pro unlocks a theme engine for all licenses that include the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/themes","isActive":true},{"type":"text","text":" feature. You can sign up for KeyboardKit Pro from the "},{"type":"reference","identifier":"https:\/\/keyboardkit.com","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]},{"type":"heading","text":"How to create a custom theme","anchor":"How-to-create-a-custom-theme","level":2},{"inlineContent":[{"text":"Since a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme","isActive":true,"type":"reference"},{"text":" is just a struct, you can easily create your own custom themes by just defining new static theme value types.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"For instance, this theme only changes the color of the primary button:"}],"type":"paragraph"},{"code":["extension KeyboardTheme {","","    static var greenPrimary: Self {","        get throws {","            try? Self(primaryBackgroundColor: .green)","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"You can also use other themes as a baseline when creating a custom theme, if you only want to change some parts of another theme:"}],"type":"paragraph"},{"code":["extension KeyboardTheme {","","    static var pinkPrimary: Self {","        get throws {","            var theme = try? KeyboardTheme.minimal","            theme.buttonStyles[.primary]?.backgroundColor = .green","            return theme","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"You can also create custom themes that just tweak a theme style variation, if you just want to change the styles that the theme uses:","type":"text"}],"type":"paragraph"},{"code":["extension KeyboardTheme {","","    static var standardBlack: Self {","        .standard(.init(tint: .black))","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"All these combinations make the theme engine very flexible and powerful.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides"],["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Themes-Article"]]},"variants":[{"paths":["\/documentation\/keyboardkit\/developer-themes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/developer-themes"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization"],"anchor":"Features","title":"Features","generated":true}],"sections":[],"abstract":[{"text":"This developer guide describes how to create custom keyboard themes.","type":"text"}],"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes","interfaceLanguage":"swift"},"references":{"Feature-Localization.jpg":{"identifier":"Feature-Localization.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg","traits":["1x","light"]}],"type":"image","alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Dictation":{"kind":"article","abstract":[{"text":"This developer guide describes how to set up and customize dictation.","type":"text"}],"images":[{"identifier":"Feature-Dictation.jpg","type":"card"}],"title":"Dictation","role":"article","url":"\/documentation\/keyboardkit\/developer-dictation","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/themes":{"type":"topic","title":"ProFeature.themes","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/themes","url":"\/documentation\/keyboardkit\/profeature\/themes","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"themes","kind":"identifier"}]},"Feature-Actions.jpg":{"type":"image","alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}],"identifier":"Feature-Actions.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardTheme":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardTheme","kind":"identifier"}],"abstract":[{"text":"This struct defines a keyboard-specific theme, which can","type":"text"},{"text":" ","type":"text"},{"text":"be used to define a bunch of styles at once.","type":"text"}],"type":"topic","title":"KeyboardTheme","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme","kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardtheme","navigatorTitle":[{"text":"KeyboardTheme","kind":"identifier"}],"role":"symbol"},"https://keyboardkit.com":{"url":"https:\/\/keyboardkit.com","identifier":"https:\/\/keyboardkit.com","type":"link","title":"KeyboardKit website","titleInlineContent":[{"text":"KeyboardKit website","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardTheme/predefined":{"kind":"symbol","role":"symbol","title":"predefined","url":"\/documentation\/keyboardkit\/keyboardtheme\/predefined","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"predefined","kind":"identifier"},{"text":": [","kind":"text"},{"text":"KeyboardTheme","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A5ThemeV"},{"text":"]","kind":"text"}],"type":"topic","abstract":[{"text":"Get all predefined themes.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme\/predefined"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Localization":{"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","abstract":[{"type":"text","text":"This developer guide describes how to customize keyboard localization."}],"title":"Localization","type":"topic","url":"\/documentation\/keyboardkit\/developer-localization","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"kind":"article"},"Feature-Dictation.jpg":{"type":"image","identifier":"Feature-Dictation.jpg","alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}]},"Feature-Autocomplete.jpg":{"alt":"Article Icon","type":"image","identifier":"Feature-Autocomplete.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg","traits":["1x","light"]}]},"Feature-Themes.jpg":{"alt":"Feature Icon","type":"image","identifier":"Feature-Themes.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Themes.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Feedback":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","abstract":[{"text":"This developer guide describes how to customize keyboard feedback.","type":"text"}],"role":"article","title":"Feedback","kind":"article","url":"\/documentation\/keyboardkit\/developer-feedback","images":[{"identifier":"Feature-Feedback.jpg","type":"card"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Actions":{"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","type":"topic","title":"Actions","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This developer guide describes how to customize the action handling.","type":"text"}],"url":"\/documentation\/keyboardkit\/developer-actions","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Autocomplete":{"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/developer-autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","abstract":[{"text":"This developer guide describes how to set up and customize autocomplete.","type":"text"}],"type":"topic","role":"article","kind":"article","title":"Autocomplete"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Themes-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/themes-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Themes-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit Pro theme engine."}],"images":[{"type":"card","identifier":"Feature-Themes.jpg"}],"kind":"article","title":"Themes","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Guides":{"url":"\/documentation\/keyboardkit\/developer-guides","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides","role":"collectionGroup","title":"Developer Guides","type":"topic","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}]},"Feature-Feedback.jpg":{"alt":"Article Icon","identifier":"Feature-Feedback.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg"}],"type":"image"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization"],"title":"Features","anchor":"Features"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}