{"kind":"article","sections":[],"abstract":[{"text":"This developer guide describes how to set up and customize dictation.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles"],["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"seeAlsoSections":[{"title":"Feature Customizations","anchor":"Feature-Customizations","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"],"generated":true}],"metadata":{"role":"article","title":"Dictation","images":[{"identifier":"Feature-Dictation.jpg","type":"card"}],"modules":[{"name":"KeyboardKit"}],"roleHeading":"Article","color":{"standardColorIdentifier":"purple"}},"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Overview","text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit makes it easy to perform dictation directly from the keyboard extension, in a way where the keyboard only has to open the main app to start dictation. See the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","isActive":true,"type":"reference"},{"text":" article for more information about this feature.","type":"text"}]},{"style":"important","name":"Important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"👑 Dictation requires a KeyboardKit Pro license with ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/dictation","type":"reference","isActive":true},{"text":" support, unless you want to implement the feature from scratch. You can sign up for KeyboardKit Pro from the ","type":"text"},{"identifier":"https:\/\/keyboardkit.com","type":"reference","isActive":true},{"text":".","type":"text"}]}]},{"text":"How to perform dictation","type":"heading","level":2,"anchor":"How-to-perform-dictation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Dictation can be performed in the main "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod\/app"},{"type":"text","text":" or its "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod\/keyboard"},{"type":"text","text":" extension (which is the main use case for keyboard-based applications)."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Keyboard extensions must open the main app to start dictation. After this, dictation is performed based on the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSettings\/dictationMethod"},{"type":"text","text":":"}]},{"items":[{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod\/app","type":"reference"},{"text":" - Dictation is performed in the app, then navigates back to the keyboard to apply the result.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod\/keyboard","type":"reference"},{"text":" (BETA) - Dictation is started in the app, then navigates back to the keyboard to perform dictation within the extension.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"style":"tip","name":"Tip","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod\/keyboard","type":"reference","isActive":true},{"text":" method is recommended, but is currently opt-in. It can be enabled with the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiment\/keyboardDictation","type":"reference","isActive":true},{"text":" experiment.","type":"text"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"After setting up dictation as described below, you can start dictation by triggering the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/dictation"},{"type":"text","text":" action in your keyboard extension."}]},{"text":"How to set up dictation","type":"heading","level":2,"anchor":"How-to-set-up-dictation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Setting up dictation just involves adding the required permissions, setting up an App Group to enable "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing"},{"type":"text","text":" between the main app and its keyboard, and setting up a speech recognizer. The steps below will guide you through this process."}]},{"text":"Step 1. Required permissions","type":"heading","level":3,"anchor":"Step-1-Required-permissions"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Before you can start dictation, you must add these required keys to your app’s "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":", otherwise the app will crash at runtime:"}]},{"code":["<key>NSMicrophoneUsageDescription<\/key>","<string>Describe why you need microphone access.<\/string>","<key>NSSpeechRecognitionUsageDescription<\/key>","<string>Describe why you need speech recognition.<\/string>"],"type":"codeListing","syntax":null},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you use the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod\/keyboard"},{"type":"text","text":" dictation method, you must also add background audio permissions to keep dictation alive in the background:"}]},{"code":["<key>UIBackgroundModes<\/key>","<array>","    <string>audio<\/string>","<\/array>"],"type":"codeListing","syntax":null},{"type":"paragraph","inlineContent":[{"identifier":"developer-dictation-background-modes","type":"image"}]},{"type":"paragraph","inlineContent":[{"text":"If you don’t add this to the ","type":"text"},{"code":"Info.plist","type":"codeVoice"},{"text":", dictation will stop detecting speech and volume as soon as the app returns to the keyboard.","type":"text"}]},{"text":"Step 2. Set up an App Group","type":"heading","level":3,"anchor":"Step-2-Set-up-an-App-Group"},{"type":"paragraph","inlineContent":[{"text":"To share data between your app and keyboard, you must setup an App Group for both targets, as described in the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","type":"reference","isActive":true},{"text":" article.","type":"text"}]},{"text":"Step 3. Set up a URL Scheme","type":"heading","level":3,"anchor":"Step-3-Set-up-a-URL-Scheme"},{"type":"paragraph","inlineContent":[{"text":"To make it possible for the keyboard to open the app and start dictation, you must set up a deep link URL scheme to open the main app:","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"developer-dictation-url-scheme"}]},{"type":"paragraph","inlineContent":[{"text":"The URL scheme must be unique for your app, for instance ","type":"text"},{"code":"myapp:\/\/","type":"codeVoice"},{"text":". Add this to your ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","isActive":true,"type":"reference"},{"text":"’s ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/deepLinks-swift.property","isActive":true,"type":"reference"},{"text":"  ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/DeepLinks-swift.struct\/app","isActive":true,"type":"reference"},{"text":" property:","type":"text"}]},{"type":"codeListing","code":["KeyboardApp(..., deepLinks: .init(app: \"myapp:\/\/\"))"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit will use ","type":"text"},{"code":"<SCHEME>dictation","type":"codeVoice"},{"text":" as the default dictation deep link, but you can customize this if it conflicts with your app.","type":"text"}]},{"anchor":"Step-4-Create-a-Speech-Recognizer","level":3,"text":"Step 4. Create a Speech Recognizer","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit uses a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSpeechRecognizer","isActive":true,"type":"reference"},{"text":" protocol to decouple KeyboardKit from the Speech framework, to avoid having to add dictation permissions in apps that don’t use dictation.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Instead, you can copy this standard speech recognizer and add it to your app, then inject it with "},{"type":"codeVoice","code":".standard"},{"type":"text","text":" when setting up dictation:"}]},{"code":["import KeyboardKit","import Speech","","public extension DictationSpeechRecognizer where Self == StandardSpeechRecognizer {","","    static var standard: Self { .init() }","} ","","public class StandardSpeechRecognizer: DictationSpeechRecognizer {","","    public init() {}","","    private var recognizer: SFSpeechRecognizer?","    private var request: SFSpeechAudioBufferRecognitionRequest?","    private var speechRecognizerTask: SFSpeechRecognitionTask?","","    private typealias Err = Dictation.ServiceError","","    public var authorizationStatus: Dictation.AuthorizationStatus {","        SFSpeechRecognizer.authorizationStatus().keyboardDictationStatus","    }","","    public var supportedLocales: [Locale] {","        Array(SFSpeechRecognizer.supportedLocales())","    }","","    public func requestDictationAuthorization() async throws -> Dictation.AuthorizationStatus {","        await withCheckedContinuation { continuation in","            SFSpeechRecognizer.requestAuthorization { status in","                continuation.resume(returning: status.keyboardDictationStatus)","            }","        }","    }","","    public func resetDictationResult() async throws {}","","    public func startDictation(","        with locale: Locale","    ) async throws {","        try await startDictation(","            with: locale,","            resultHandler: nil","        )","    }","","    public func startDictation(","        with locale: Locale,","        resultHandler: ((Dictation.SpeechRecognizerResult) -> Void)?","    ) async throws {","        recognizer = SFSpeechRecognizer(locale: locale)","        guard let recognizer else { throw Err.missingSpeechRecognizer }","        request = SFSpeechAudioBufferRecognitionRequest()","        request?.shouldReportPartialResults = true","        guard let request else { throw Err.missingSpeechRecognitionRequest }","        speechRecognizerTask = recognizer.recognitionTask(with: request) {","            let result = Dictation.SpeechRecognizerResult(","                dictatedText: $0?.bestTranscription.formattedString,","                error: $1,","                isFinal: $0?.isFinal ?? true)","            resultHandler?(result)","        }","    }","","    public func stopDictation() async throws {","        request?.endAudio()","        request = nil","        speechRecognizerTask?.cancel()","        speechRecognizerTask = nil","    }","","    public func setupAudioEngineBuffer(_ buffer: AVAudioPCMBuffer) {","        request?.append(buffer)","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The standard speech recognizer uses the Speech framework to perform local, on-device recognition. It supports the following locales:"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Arabic (ar-SA), Cantonese (yue-CN), Catalan (ca-ES), Chinese (zh-CN), Chinese (zh-HK), Chinese (zh-TW), Croatian (hr-HR), Czech (cs-CZ), Danish (da-DK), Dutch (nl-BE), Dutch (nl-NL), English (en-AE), English (en-AU), English (en-CA), English (en-GB), English (en-ID), English (en-IE), English (en-IN), English (en-NZ), English (en-PH), English (en-SA), English (en-SG), English (en-US), English (en-ZA), Finnish (fi-FI), French (fr-BE), French (fr-CA), French (fr-CH), French (fr-FR), German (de-AT), German (de-CH), German (de-DE), Greek (el-GR), Hebrew (he-IL), Hindi (hi-IN), Hindi (hi-IN-translit), Hindi (hi-Latn), Hungarian (hu-HU), Indonesian (id-ID), Italian (it-CH), Italian (it-IT), Japanese (ja-JP), Korean (ko-KR), Malay (ms-MY), Norwegian Bokmål (nb-NO), Polish (pl-PL), Portuguese (pt-BR), Portuguese (pt-PT), Romanian (ro-RO), Russian (ru-RU), Shanghainese (wuu-CN), Slovak (sk-SK), Spanish (es-419), Spanish (es-CL), Spanish (es-CO), Spanish (es-ES), Spanish (es-MX), Spanish (es-US), Swedish (sv-SE), Thai (th-TH), Turkish (tr-TR), Ukrainian (uk-UA), Vietnamese (vi-VN)"}]},{"type":"paragraph","inlineContent":[{"text":"You can also implement the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSpeechRecognizer","isActive":true},{"text":" protocol from scratch, for instance to perform speech recognition with a custom AI model or framework that supports more languages.","type":"text"}]},{"level":3,"type":"heading","text":"Step 5. Set up your Keyboard Extension","anchor":"Step-5-Set-up-your-Keyboard-Extension"},{"type":"paragraph","inlineContent":[{"text":"To set up dictation for your keyboard extension, just set it up with a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","type":"reference","isActive":true},{"text":" with the app group and deep links from above. See the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","type":"reference","isActive":true},{"text":" article for more information.","type":"text"}]},{"anchor":"Step-6-Set-up-your-Main-Application","text":"Step 6. Set up your Main Application","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"To set up dictation for the main app, use a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAppView","type":"reference"},{"text":" with the same ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","type":"reference"},{"text":", then apply the dictation view modifier:","type":"text"}]},{"code":["struct ContentView: View {","","    @Environment(\\.openURL) var openURL","    ","    @EnvironmentObject var dictationContext: DictationContext","    @EnvironmentObject var keyboardContext: KeyboardContext","","    var body: some View {","        Text(\"Insert app here :)\")","            .keyboardDictation(","                speechRecognizer: .standard \/\/ The one we just created, or a custom one.","            )","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"If you use the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod\/app","type":"reference"},{"text":" dictation method, you should also present a view when the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext\/dictationState","type":"reference"},{"text":" is ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationState\/active","type":"reference","isActive":true},{"text":", e.g. a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressView","type":"reference","isActive":true},{"text":".","type":"text"}]},{"level":3,"type":"heading","text":"Step 7. Start dictation","anchor":"Step-7-Start-dictation"},{"type":"paragraph","inlineContent":[{"text":"You can now start dictation in your keyboard by triggering a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/dictation","isActive":true,"type":"reference"},{"text":" action or by calling ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationService\/startDictationFromKeyboard()","isActive":true},{"text":", or use ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationService\/startDictationInApp()","isActive":true},{"text":" to perform in-app dictation.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext","type":"reference"},{"text":" will be updated when dictation is active. The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","isActive":true},{"type":"text","text":" will automatically replace the keyboard with a dictation "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressView","isActive":true},{"type":"text","text":" when the context’s "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext\/dictationState","isActive":true},{"text":" is ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationState\/active","isActive":true},{"type":"text","text":", but you can use any view you like."}]},{"type":"heading","level":3,"text":"Step 8. Navigating between the keyboard and its main app","anchor":"Step-8-Navigating-between-the-keyboard-and-its-main-app"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit will open the main application to start dictation, then return to the keyboard extension based on the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSettings\/dictationMethod","isActive":true},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit uses its ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","isActive":true},{"type":"text","text":" capabilities to "},{"type":"emphasis","inlineContent":[{"text":"try","type":"text"}]},{"text":" to identify the keyboard host application. If successful, it can navigate back to the host application with a deep link to proceed with dictation, without any handling on your side.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the host application is "},{"type":"emphasis","inlineContent":[{"type":"text","text":"not"}]},{"text":" known or can’t be opened, the user can still tap the top leading back arrow to navigate back to the last app. If the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext","isActive":true},{"type":"text","text":"’s "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider\/hostApplication","isActive":true},{"type":"text","text":" property is nil, you should point your users to that arrow."}]},{"type":"paragraph","inlineContent":[{"text":"See the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","type":"reference"},{"text":" article for more information on which apps that are currently supported, and how to add more apps to this list.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/keyboardkit\/developer-dictation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/developer-dictation"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"Feature-Themes.jpg":{"type":"image","alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Themes.jpg"}],"identifier":"Feature-Themes.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Articles":{"url":"\/documentation\/keyboardkit\/developer-articles","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}],"role":"collectionGroup","type":"topic","kind":"article","title":"Developer Guides","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Articles"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Feedback":{"type":"topic","images":[{"identifier":"Feature-Feedback.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","abstract":[{"type":"text","text":"This developer guide describes how to customize keyboard feedback."}],"role":"article","title":"Feedback","url":"\/documentation\/keyboardkit\/developer-feedback"},"Feature-Feedback.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg"}],"identifier":"Feature-Feedback.jpg","type":"image","alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/DictationMethod/app":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"app","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod\/app","abstract":[{"text":"Dictation is performed in the main app.","type":"text"}],"role":"symbol","title":"Dictation.DictationMethod.app","url":"\/documentation\/keyboardkit\/dictation\/dictationmethod\/app"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Experiment/keyboardDictation":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardDictation","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Keyboard dictation performs dictation in the keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiment\/keyboardDictation","role":"symbol","title":"Experiment.keyboardDictation","url":"\/documentation\/keyboardkit\/experiment\/keyboarddictation"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationContext":{"type":"topic","abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"text":" ","type":"text"},{"type":"text","text":"for keyboard-based dictation."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DictationContext"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext","navigatorTitle":[{"kind":"identifier","text":"DictationContext"}],"title":"DictationContext","role":"symbol","url":"\/documentation\/keyboardkit\/dictationcontext"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/ProgressView":{"url":"\/documentation\/keyboardkit\/dictation\/progressview","navigatorTitle":[{"text":"ProgressView","kind":"identifier"}],"abstract":[{"type":"text","text":"This view can be used to visualize ongoing dictation"},{"type":"text","text":" "},{"type":"text","text":"progress and let users cancel or apply."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProgressView","kind":"identifier"}],"role":"symbol","type":"topic","title":"Dictation.ProgressView","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressView"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardHostApplication/allCases":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"allCases","kind":"identifier"},{"text":": [`Self`","kind":"text"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication\/allCases","title":"allCases","role":"symbol","url":"\/documentation\/keyboardkit\/keyboardhostapplication\/allcases"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/DictationState/active":{"url":"\/documentation\/keyboardkit\/dictation\/dictationstate\/active","title":"Dictation.DictationState.active","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationState\/active","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Dictation is active and is updating the contexts"},{"type":"text","text":" "},{"type":"text","text":"with dictation data."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationService/startDictationInApp()":{"type":"topic","abstract":[{"text":"Start a dictation operation in the main app.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDictationInApp"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationService\/startDictationInApp()","title":"startDictationInApp()","role":"symbol","required":true,"url":"\/documentation\/keyboardkit\/dictationservice\/startdictationinapp()"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAppView":{"title":"KeyboardAppView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAppView"}],"abstract":[{"text":"This view can be used as the root view of a keyboard app,","type":"text"},{"text":" ","type":"text"},{"text":"to set up KeyboardKit for a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardAppView"}],"type":"topic","url":"\/documentation\/keyboardkit\/keyboardappview","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAppView","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationService/startDictationFromKeyboard()":{"url":"\/documentation\/keyboardkit\/dictationservice\/startdictationfromkeyboard()","title":"startDictationFromKeyboard()","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationService\/startDictationFromKeyboard()","required":true,"kind":"symbol","abstract":[{"text":"Start a dictation operation from the keyboard.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDictationFromKeyboard"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/deepLinks-swift.property":{"url":"\/documentation\/keyboardkit\/keyboardapp\/deeplinks-swift.property","kind":"symbol","abstract":[{"type":"text","text":"App-specific deep links, if any."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/deepLinks-swift.property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"deepLinks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A3AppV9DeepLinksV","text":"DeepLinks"},{"kind":"text","text":"?"}],"type":"topic","title":"deepLinks"},"Feature-Dictation.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}],"identifier":"Feature-Dictation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","title":"KeyboardView","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","role":"symbol","kind":"symbol","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/dictation":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/dictation","url":"\/documentation\/keyboardkit\/profeature\/dictation","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dictation"}],"title":"ProFeature.dictation","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationSettings/dictationMethod":{"url":"\/documentation\/keyboardkit\/dictationsettings\/dictationmethod","kind":"symbol","abstract":[{"text":"The dictation method to use, by default ","type":"text"},{"type":"codeVoice","code":".app"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSettings\/dictationMethod","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dictationMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Dictation","preciseIdentifier":"s:11KeyboardKit9DictationV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"DictationMethod","preciseIdentifier":"s:11KeyboardKit9DictationV0C6MethodO","kind":"typeIdentifier"}],"type":"topic","title":"dictationMethod"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp":{"url":"\/documentation\/keyboardkit\/keyboardapp","abstract":[{"text":"This type can be used to define important properties for","type":"text"},{"text":" ","type":"text"},{"text":"your app, and is also a namespace for app-based features.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardApp"}],"type":"topic","title":"KeyboardApp","navigatorTitle":[{"kind":"identifier","text":"KeyboardApp"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Getting-Started-Article":{"type":"topic","abstract":[{"type":"text","text":"This developer guide describes how to get started with KeyboardKit."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","title":"Getting Started","role":"article","url":"\/documentation\/keyboardkit\/getting-started-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/DictationMethod/keyboard":{"type":"topic","abstract":[{"text":"Dictation is performed in the keyboard.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboard"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod\/keyboard","title":"Dictation.DictationMethod.keyboard","role":"symbol","url":"\/documentation\/keyboardkit\/dictation\/dictationmethod\/keyboard"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/DeepLinks-swift.struct/app":{"url":"\/documentation\/keyboardkit\/keyboardapp\/deeplinks-swift.struct\/app","kind":"symbol","abstract":[{"text":"A deep link for opening the app.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/DeepLinks-swift.struct\/app","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"app"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","title":"app"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"url":"\/documentation\/keyboardkit\/host-article","abstract":[{"text":"This article describes how KeyboardKit Pro can identify and use the host application.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Host Application","images":[{"type":"card","identifier":"Feature-Host.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardHostApplicationProvider/hostApplicationBundleId":{"type":"topic","abstract":[{"text":"The host application bundle ID to resolve.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hostApplicationBundleId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider\/hostApplicationBundleId","title":"hostApplicationBundleId","role":"symbol","required":true,"url":"\/documentation\/keyboardkit\/keyboardhostapplicationprovider\/hostapplicationbundleid"},"Feature-Actions.jpg":{"type":"image","alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg","traits":["1x","light"]}],"identifier":"Feature-Actions.jpg"},"Feature-Host.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg","traits":["1x","light"]}],"identifier":"Feature-Host.jpg"},"developer-dictation-background-modes":{"type":"image","alt":"Xcode Background Modes","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-dictation-background-modes.jpg","traits":["1x","light"]}],"identifier":"developer-dictation-background-modes"},"Feature-Localization.jpg":{"type":"image","alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg","traits":["1x","light"]}],"identifier":"Feature-Localization.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Data-Syncing":{"url":"\/documentation\/keyboardkit\/developer-data-syncing","abstract":[{"text":"This developer guide describes how to sync data between the main app and its keyboard.","type":"text"}],"images":[{"identifier":"Developer-Article-Data-Syncing.jpg","type":"card"}],"type":"topic","title":"Data Syncing","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Themes":{"abstract":[{"text":"This developer guide describes how to create custom keyboard themes.","type":"text"}],"kind":"article","title":"Themes","type":"topic","images":[{"type":"card","identifier":"Feature-Themes.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes","url":"\/documentation\/keyboardkit\/developer-themes","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationSpeechRecognizer":{"url":"\/documentation\/keyboardkit\/dictationspeechrecognizer","navigatorTitle":[{"text":"DictationSpeechRecognizer","kind":"identifier"}],"abstract":[{"type":"text","text":"This protocol can be implemented by any type that can be"},{"type":"text","text":" "},{"type":"text","text":"used to perform speech recognition."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DictationSpeechRecognizer","kind":"identifier"}],"role":"symbol","type":"topic","title":"DictationSpeechRecognizer","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSpeechRecognizer"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Localization":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","url":"\/documentation\/keyboardkit\/developer-localization","images":[{"identifier":"Feature-Localization.jpg","type":"card"}],"abstract":[{"type":"text","text":"This developer guide describes how to customize keyboard localization."}],"role":"article","title":"Localization","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Autocomplete":{"type":"topic","images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","abstract":[{"type":"text","text":"This developer guide describes how to set up and customize autocomplete."}],"role":"article","title":"Autocomplete","url":"\/documentation\/keyboardkit\/developer-autocomplete"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","title":"Dictation","role":"article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"url":"\/documentation\/keyboardkit\/dictation-article"},"developer-dictation-url-scheme":{"type":"image","alt":"Xcode URL Scheme","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/developer-dictation-url-scheme.jpg","traits":["1x","light"]}],"identifier":"developer-dictation-url-scheme"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"url":"\/documentation\/keyboardkit\/features-articles","abstract":[{"type":"text","text":"This article links to the various KeyboardKit features."}],"role":"collectionGroup","type":"topic","title":"Features","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardHostApplicationProvider/hostApplication":{"type":"topic","abstract":[{"text":"Get an app within ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication\/allCases","type":"reference","isActive":true},{"text":" ","type":"text"},{"text":"that matches the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider\/hostApplicationBundleId","type":"reference","isActive":true},{"text":", if any.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostApplication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A15HostApplicationV","text":"KeyboardHostApplication"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider\/hostApplication","title":"hostApplication","role":"symbol","url":"\/documentation\/keyboardkit\/keyboardhostapplicationprovider\/hostapplication"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/dictation":{"abstract":[{"type":"text","text":"Represents a dictation key."}],"kind":"symbol","title":"KeyboardAction.dictation","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/dictation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dictation"}],"url":"\/documentation\/keyboardkit\/keyboardaction\/dictation","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Actions":{"type":"topic","images":[{"type":"card","identifier":"Feature-Actions.jpg"}],"kind":"article","abstract":[{"text":"This developer guide describes how to customize the action handling.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","role":"article","title":"Actions","url":"\/documentation\/keyboardkit\/developer-actions"},"Developer-Article-Data-Syncing.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Data-Syncing.jpg","traits":["1x","light"]}],"identifier":"Developer-Article-Data-Syncing.jpg","type":"image","alt":"Article Icon"},"https://keyboardkit.com":{"url":"https:\/\/keyboardkit.com","identifier":"https:\/\/keyboardkit.com","title":"KeyboardKit website","type":"link","titleInlineContent":[{"type":"text","text":"KeyboardKit website"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationContext/dictationState":{"url":"\/documentation\/keyboardkit\/dictationcontext\/dictationstate","kind":"symbol","abstract":[{"type":"text","text":"The current dictation state."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext\/dictationState","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dictationState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9DictationV","text":"Dictation"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9DictationV0C5StateO","text":"DictationState"}],"type":"topic","title":"dictationState"},"Feature-Autocomplete.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"identifier":"Feature-Autocomplete.jpg","type":"image","alt":"Article Icon"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Feature-Customizations","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"],"title":"Feature Customizations"}],"op":"replace"}]}]}