{"kind":"article","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides"],["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article"]]},"sections":[],"metadata":{"role":"article","color":{"standardColorIdentifier":"purple"},"title":"Feedback","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"roleHeading":"Article","modules":[{"name":"KeyboardKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback"},"primaryContentSections":[{"content":[{"text":"Overview","type":"heading","anchor":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Feedback is an important part of a keyboard typing experience. See the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","isActive":true},{"text":" article for information about the keyboard feedback feature and its many capabilities.","type":"text"}]},{"anchor":"How-to-trigger-keyboard-feedback","type":"heading","level":2,"text":"How to trigger keyboard feedback"},{"inlineContent":[{"type":"text","text":"You can trigger "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/Audio","type":"reference"},{"type":"text","text":" & "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/Haptic","type":"reference","isActive":true},{"type":"text","text":" feedback with a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FeedbackService"},{"type":"text","text":" or by using the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler"},{"type":"text","text":". The standard action handler will trigger feedback for all actions that it handles, in accordance to the current "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FeedbackContext\/settings","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"text":"Use ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FeedbackService\/triggerAudioFeedback(_:)"},{"type":"text","text":" to trigger audio feedback, "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FeedbackService\/triggerHapticFeedback(_:)","isActive":true},{"type":"text","text":" to trigger haptic feedback, and the action handler’s "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/triggerFeedback(for:on:)","isActive":true},{"type":"text","text":" to trigger feedback for a specific action."}],"type":"paragraph"},{"anchor":"How-to-customize-keyboard-feedback","type":"heading","level":2,"text":"How to customize keyboard feedback"},{"type":"paragraph","inlineContent":[{"text":"You can configure the main ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/State\/feedbackContext","isActive":true,"type":"reference"},{"type":"text","text":" and its "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FeedbackContext\/settings"},{"type":"text","text":" to change the feedback behavior. For instance, this will customize the audio feedback for input keys, then disable haptic feedback:"}]},{"type":"codeListing","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewWillSetupKeyboardKit() {","        setupKeyboardKit(for: .myApp)  \/\/ See the getting-started guide","        let context = state.feedbackContext","        context.audioConfiguration.input = .custom(id: 1329)","        context.settings.isHapticFeedbackEnabled = false","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"You can also use use the context to register custom feedback for any gesture on any action.","type":"text"}]},{"type":"codeListing","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewWillSetupKeyboardKit() {","        setupKeyboardKit(for: .myApp)  \/\/ See the getting-started guide","        let context = state.feedbackContext","        context.registerCustomFeedback(.audio(.rocketFuse, for: .press, on: .rocket))","        context.registerCustomFeedback(.audio(.rocketLaunch, for: .release, on: .rocket))","        context.registerCustomFeedback(.haptic(.selection, for: .repeat, on: .rocket))","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since the configuration is observable, any changes will automatically cause the keyboard to update, e.g. if you have feedback toggles."}]},{"type":"heading","text":"How to define custom audio feedback","level":2,"anchor":"How-to-define-custom-audio-feedback"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/Audio","isActive":true},{"text":" feedback type uses ","type":"text"},{"inlineContent":[{"text":"AudioServices","type":"text"}],"type":"strong"},{"type":"text","text":", which means you can use any system audio (see "},{"identifier":"https:\/\/iphonedev.wiki\/index.php\/AudioServices","isActive":true,"type":"reference"},{"type":"text","text":") as custom audio feedback:"}]},{"syntax":"swift","code":["extension Feedback.Audio {","","    static let sentMessage = .custom(id: 1004)","}"],"type":"codeListing"},{"inlineContent":[{"text":"You can also use the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/Audio\/customUrl(_:)","type":"reference","isActive":true},{"text":" feedback type to define a custom audio feedback that loads a sound effect from an audio file:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["extension Feedback.Audio {","","    static let sentMessage = .customUrl(","        Bundle.main.url(forResource: \"sent\", withExtension: \"mp3\")","    )","}"],"type":"codeListing"},{"inlineContent":[{"text":"You can also implement a custom action handler to trigger feedback in a different ways. See the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","isActive":true,"type":"reference"},{"text":" article for more information.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/keyboardkit\/developer-feedback"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkit\/developer-feedback"]}],"abstract":[{"type":"text","text":"This developer guide describes how to customize keyboard feedback."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Features","title":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"],"generated":true}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardActionHandler/triggerFeedback(for:on:)":{"type":"topic","url":"\/documentation\/keyboardkit\/keyboardactionhandler\/triggerfeedback(for:on:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"triggerFeedback"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"Keyboard","preciseIdentifier":"s:11KeyboardKit0A0V","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Gesture","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V7GestureO"},{"kind":"text","text":", "},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"KeyboardAction","preciseIdentifier":"s:11KeyboardKit0A6ActionO","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/triggerFeedback(for:on:)","abstract":[{"text":"Trigger feedback for a certain action gesture.","type":"text"}],"kind":"symbol","title":"triggerFeedback(for:on:)","required":true},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Themes":{"url":"\/documentation\/keyboardkit\/developer-themes","kind":"article","title":"Themes","type":"topic","images":[{"identifier":"Feature-Themes.jpg","type":"card"}],"abstract":[{"type":"text","text":"This developer guide describes how to create custom keyboard themes."}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"},"Feature-Dictation.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}],"type":"image","alt":"Article Icon","identifier":"Feature-Dictation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback/Haptic":{"navigatorTitle":[{"text":"Haptic","kind":"identifier"}],"title":"Feedback.Haptic","abstract":[{"text":"This enum defines standard haptic feedback types.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Haptic","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/feedback\/haptic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/Haptic"},"Feature-Localization.jpg":{"type":"image","alt":"Article Icon","identifier":"Feature-Localization.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg","traits":["1x","light"]}]},"Feature-Actions.jpg":{"identifier":"Feature-Actions.jpg","alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Dictation":{"kind":"article","abstract":[{"text":"This developer guide describes how to set up and customize dictation.","type":"text"}],"images":[{"identifier":"Feature-Dictation.jpg","type":"card"}],"title":"Dictation","role":"article","url":"\/documentation\/keyboardkit\/developer-dictation","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/FeedbackService/triggerHapticFeedback(_:)":{"type":"topic","url":"\/documentation\/keyboardkit\/feedbackservice\/triggerhapticfeedback(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"triggerHapticFeedback"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit8FeedbackV","text":"Feedback"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit8FeedbackV6HapticO","text":"Haptic"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FeedbackService\/triggerHapticFeedback(_:)","abstract":[{"type":"text","text":"Trigger the provided haptic feedback."}],"kind":"symbol","title":"triggerHapticFeedback(_:)","required":true},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Autocomplete":{"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/developer-autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","abstract":[{"text":"This developer guide describes how to set up and customize autocomplete.","type":"text"}],"type":"topic","role":"article","kind":"article","title":"Autocomplete"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Guides":{"url":"\/documentation\/keyboardkit\/developer-guides","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides","role":"collectionGroup","title":"Developer Guides","type":"topic","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/FeedbackContext/settings":{"title":"settings","abstract":[{"type":"text","text":"Feedback-specific, auto-persisted settings."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit16FeedbackSettingsV","text":"FeedbackSettings"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/feedbackcontext\/settings","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FeedbackContext\/settings"},"Feature-Autocomplete.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg","traits":["1x","light"]}],"type":"image","alt":"Article Icon","identifier":"Feature-Autocomplete.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Actions":{"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","type":"topic","title":"Actions","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This developer guide describes how to customize the action handling.","type":"text"}],"url":"\/documentation\/keyboardkit\/developer-actions","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/FeedbackService":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FeedbackService","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeedbackService","kind":"identifier"}],"navigatorTitle":[{"text":"FeedbackService","kind":"identifier"}],"abstract":[{"text":"This protocol can be implemented by any type that can be","type":"text"},{"text":" ","type":"text"},{"text":"used to trigger audio and haptic feedback.","type":"text"}],"role":"symbol","title":"FeedbackService","url":"\/documentation\/keyboardkit\/feedbackservice","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/actions-article","role":"article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"title":"Actions"},"https://iphonedev.wiki/index.php/AudioServices":{"title":"this site","type":"link","url":"https:\/\/iphonedev.wiki\/index.php\/AudioServices","identifier":"https:\/\/iphonedev.wiki\/index.php\/AudioServices","titleInlineContent":[{"text":"this site","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardActionHandler":{"navigatorTitle":[{"text":"KeyboardActionHandler","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler","type":"topic","url":"\/documentation\/keyboardkit\/keyboardactionhandler","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardActionHandler","kind":"identifier"}],"role":"symbol","title":"KeyboardActionHandler","abstract":[{"text":"This protocol can be implemented by any classes that can","type":"text"},{"text":" ","type":"text"},{"text":"handle triggered ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","isActive":true,"type":"reference"},{"text":" events.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction":{"title":"KeyboardAction","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAction"}],"abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"type":"text","text":" "},{"type":"text","text":"a namespace for action-related types."}],"url":"\/documentation\/keyboardkit\/keyboardaction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"type":"topic","role":"symbol"},"Feature-Feedback.jpg":{"identifier":"Feature-Feedback.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg","traits":["1x","light"]}],"type":"image"},"Feature-Themes.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Themes.jpg","traits":["1x","light"]}],"type":"image","alt":"Article Icon","identifier":"Feature-Themes.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Localization":{"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","abstract":[{"type":"text","text":"This developer guide describes how to customize keyboard localization."}],"title":"Localization","type":"topic","url":"\/documentation\/keyboardkit\/developer-localization","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/State/feedbackContext":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"feedbackContext","kind":"identifier"},{"kind":"text","text":": "},{"text":"FeedbackContext","preciseIdentifier":"s:11KeyboardKit15FeedbackContextC","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/State\/feedbackContext","role":"symbol","kind":"symbol","title":"feedbackContext","url":"\/documentation\/keyboardkit\/keyboard\/state\/feedbackcontext","type":"topic","abstract":[{"text":"Observable feedback-related state.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/FeedbackService/triggerAudioFeedback(_:)":{"kind":"symbol","url":"\/documentation\/keyboardkit\/feedbackservice\/triggeraudiofeedback(_:)","required":true,"title":"triggerAudioFeedback(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"triggerAudioFeedback","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Feedback","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit8FeedbackV"},{"text":".","kind":"text"},{"text":"Audio","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit8FeedbackV5AudioO"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"text":"Trigger the provided audio feedback.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FeedbackService\/triggerAudioFeedback(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback/Audio":{"url":"\/documentation\/keyboardkit\/feedback\/audio","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/Audio","title":"Feedback.Audio","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Audio","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Audio","kind":"identifier"}],"abstract":[{"type":"text","text":"This enum defines standard audio feedback types."}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback/Audio/customUrl(_:)":{"title":"Feedback.Audio.customUrl(_:)","abstract":[{"text":"Represents a custom sound at a certain URL.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/feedback\/audio\/customurl(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/Audio\/customUrl(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customUrl","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?)","kind":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"url":"\/documentation\/keyboardkit\/feedback-article","type":"topic","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"title":"Feedback","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"],"generated":true,"title":"Features"}]}]}]}