{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/keyboardkit\/developer-actions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/developer-actions"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"Actions","roleHeading":"Article","color":{"standardColorIdentifier":"purple"},"role":"article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"modules":[{"name":"KeyboardKit"}]},"kind":"article","abstract":[{"text":"This developer guide describes how to customize the action handling.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides"],["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"],"generated":true,"anchor":"Features","title":"Features"}],"sections":[],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Actions","interfaceLanguage":"swift"},"primaryContentSections":[{"content":[{"level":2,"text":"Overview","anchor":"Overview","type":"heading"},{"inlineContent":[{"text":"KeyboardKit makes it easy to handle app-specific ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction"},{"text":"s. See the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article"},{"text":" article for information about the action feature and its many capabilities.","type":"text"}],"type":"paragraph"},{"level":2,"text":"How to handle keyboard actions","anchor":"How-to-handle-keyboard-actions","type":"heading"},{"inlineContent":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","isActive":true},{"type":"text","text":" can be handled with a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler","isActive":true},{"type":"text","text":", as described in the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","isActive":true},{"type":"text","text":" article. KeyboardKit uses this approach when performing certain operations."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can trigger actions programmatically with "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/handle(action:)","type":"reference","isActive":true},{"type":"text","text":", or trigger "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/handle(_:on:)","type":"reference","isActive":true},{"type":"text","text":" to simulate a certain action gesture. You can trigger autocomplete with "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/handle(suggestion:)","type":"reference","isActive":true},{"type":"text","text":" and feedback with "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/triggerFeedback(for:on:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"},{"type":"heading","anchor":"How-to-create-a-custom-action-handler","text":"How to create a custom action handler","level":2},{"type":"paragraph","inlineContent":[{"text":"You can create a custom ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler","type":"reference"},{"text":" to customize how certain actions are handled, and to handle actions that don’t have a standard or default behavior, like ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/image"},{"text":", ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/command"},{"text":", etc.","type":"text"}]},{"inlineContent":[{"type":"text","text":"You can implement the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler"},{"type":"text","text":" protocol from scratch, or inherit and customize "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/StandardActionHandler"},{"type":"text","text":":"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["class CustomActionHandler: KeyboardAction.StandardActionHandler {","","    open override func handle(","        _ gesture: Keyboard.Gesture, ","        on action: KeyboardAction","    ) {","        if gesture == .press && action == .space {","            print(\"Pressed space!\")","        }","        super.handle(gesture, on: action) ","    }","}"]},{"inlineContent":[{"text":"To use your custom handler instead of the standard one, just inject it into ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services","type":"reference"},{"text":" by replacing its ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Services\/actionHandler","type":"reference"},{"text":" property:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewWillSetupKeyboardKit() {","        setupKeyboardKit(for: .myApp) { [weak self] result in","            guard let self else { return }","            self.services.actionHandler = CustomActionHandler(controller: self)","        }","    }","}"]},{"inlineContent":[{"type":"text","text":"This will make KeyboardKit use your custom action handler instead of the standard one. See the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","type":"reference","isActive":true},{"type":"text","text":" guide for more info."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardActionHandler/triggerFeedback(for:on:)":{"type":"topic","url":"\/documentation\/keyboardkit\/keyboardactionhandler\/triggerfeedback(for:on:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"triggerFeedback"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"Keyboard","preciseIdentifier":"s:11KeyboardKit0A0V","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Gesture","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V7GestureO"},{"kind":"text","text":", "},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"KeyboardAction","preciseIdentifier":"s:11KeyboardKit0A6ActionO","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/triggerFeedback(for:on:)","abstract":[{"text":"Trigger feedback for a certain action gesture.","type":"text"}],"kind":"symbol","title":"triggerFeedback(for:on:)","required":true},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Themes":{"url":"\/documentation\/keyboardkit\/developer-themes","kind":"article","title":"Themes","type":"topic","images":[{"identifier":"Feature-Themes.jpg","type":"card"}],"abstract":[{"type":"text","text":"This developer guide describes how to create custom keyboard themes."}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"},"Feature-Dictation.jpg":{"type":"image","identifier":"Feature-Dictation.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}],"alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Getting-Started-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","abstract":[{"type":"text","text":"This developer guide describes how to get started with KeyboardKit."}],"kind":"article","role":"article","type":"topic","url":"\/documentation\/keyboardkit\/getting-started-article","title":"Getting Started"},"Feature-Localization.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg","traits":["1x","light"]}],"identifier":"Feature-Localization.jpg","type":"image","alt":"Article Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/image":{"type":"topic","abstract":[{"type":"text","text":"The image to which the action refers, if any."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI5ImageV","text":"Image","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/keyboardkit\/keyboardaction\/image","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/image","title":"image"},"Feature-Actions.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}],"alt":"Feature Icon","identifier":"Feature-Actions.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Feedback":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","abstract":[{"text":"This developer guide describes how to customize keyboard feedback.","type":"text"}],"role":"article","title":"Feedback","kind":"article","url":"\/documentation\/keyboardkit\/developer-feedback","images":[{"identifier":"Feature-Feedback.jpg","type":"card"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/command":{"url":"\/documentation\/keyboardkit\/keyboardaction\/command","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/command","abstract":[{"type":"text","text":"Represents a command (⌘) key."}],"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"command","kind":"identifier"}],"type":"topic","title":"KeyboardAction.command"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Dictation":{"kind":"article","abstract":[{"text":"This developer guide describes how to set up and customize dictation.","type":"text"}],"images":[{"identifier":"Feature-Dictation.jpg","type":"card"}],"title":"Dictation","role":"article","url":"\/documentation\/keyboardkit\/developer-dictation","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Guides":{"url":"\/documentation\/keyboardkit\/developer-guides","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides","role":"collectionGroup","title":"Developer Guides","type":"topic","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Autocomplete":{"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/developer-autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","abstract":[{"text":"This developer guide describes how to set up and customize autocomplete.","type":"text"}],"type":"topic","role":"article","kind":"article","title":"Autocomplete"},"Feature-Autocomplete.jpg":{"identifier":"Feature-Autocomplete.jpg","alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/StandardActionHandler":{"title":"KeyboardAction.StandardActionHandler","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/StandardActionHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardActionHandler"}],"abstract":[{"type":"text","text":"This class provides a standard way to handle actions"},{"type":"text","text":" "},{"type":"text","text":"that are triggered by the keyboard."}],"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardaction\/standardactionhandler","navigatorTitle":[{"kind":"identifier","text":"StandardActionHandler"}],"type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/actions-article","role":"article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"title":"Actions"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardActionHandler/handle(_:on:)":{"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardactionhandler\/handle(_:on:)","required":true,"title":"handle(_:on:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V"},{"text":".","kind":"text"},{"text":"Gesture","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V7GestureO"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"KeyboardAction","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A6ActionO"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Handle a certain keyboard action gesture."}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/handle(_:on:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardActionHandler":{"navigatorTitle":[{"text":"KeyboardActionHandler","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler","type":"topic","url":"\/documentation\/keyboardkit\/keyboardactionhandler","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardActionHandler","kind":"identifier"}],"role":"symbol","title":"KeyboardActionHandler","abstract":[{"text":"This protocol can be implemented by any classes that can","type":"text"},{"text":" ","type":"text"},{"text":"handle triggered ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","isActive":true,"type":"reference"},{"text":" events.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/services":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V"},{"text":".","kind":"text"},{"text":"Services","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V8ServicesC"}],"abstract":[{"type":"text","text":"Keyboard-specific services."}],"role":"symbol","title":"services","kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/services"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction":{"title":"KeyboardAction","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAction"}],"abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"type":"text","text":" "},{"type":"text","text":"a namespace for action-related types."}],"url":"\/documentation\/keyboardkit\/keyboardaction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"type":"topic","role":"symbol"},"Feature-Feedback.jpg":{"alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Feedback.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardActionHandler/handle(action:)":{"url":"\/documentation\/keyboardkit\/keyboardactionhandler\/handle(action:)","role":"symbol","abstract":[{"type":"text","text":"Handle a certain keyboard action."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A6ActionO","text":"KeyboardAction"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"handle(action:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/handle(action:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardActionHandler/handle(suggestion:)":{"abstract":[{"text":"Handle a certain autocomplete suggestion.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/handle(suggestion:)","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/keyboardactionhandler\/handle(suggestion:)","title":"handle(suggestion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"suggestion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Autocomplete","preciseIdentifier":"s:11KeyboardKit12AutocompleteV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Suggestion","preciseIdentifier":"s:11KeyboardKit12AutocompleteV10SuggestionV","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Localization":{"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","abstract":[{"type":"text","text":"This developer guide describes how to customize keyboard localization."}],"title":"Localization","type":"topic","url":"\/documentation\/keyboardkit\/developer-localization","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"kind":"article"},"Feature-Themes.jpg":{"alt":"Article Icon","type":"image","identifier":"Feature-Themes.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Themes.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/Services/actionHandler":{"role":"symbol","type":"topic","title":"actionHandler","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionHandler","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyboardActionHandler","preciseIdentifier":"s:11KeyboardKit0A13ActionHandlerP","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Services\/actionHandler","abstract":[{"text":"The keyboard action handler to use.","type":"text"}],"url":"\/documentation\/keyboardkit\/keyboard\/services\/actionhandler","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"anchor":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Autocomplete","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Feedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Localization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Themes"],"generated":true,"title":"Features"}],"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}