{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/keyboardkit\/developer-experiments"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/developer-experiments"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"article","seeAlsoSections":[{"anchor":"Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"],"generated":true,"title":"Essentials"}],"abstract":[{"type":"text","text":"This developer guide describes how to enable experimental features."}],"metadata":{"modules":[{"name":"KeyboardKit"}],"color":{"standardColorIdentifier":"purple"},"title":"Experiments","roleHeading":"Article","role":"article","images":[{"identifier":"Developer-Article-Experiments.jpg","type":"card"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Experiments"},"topicSections":[{"anchor":"Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiment","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiments","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExperimentsContext"],"title":"Types"}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit sometimes introduces new features or changes that may cause side-effects to important parts of the keyboard engine. Such changes are often introduces as an ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiment"},{"text":", and disabled by default.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Developers can manually opt-in to enable individual experiments, to be able to try them out before they become enabled by default."}]},{"type":"heading","level":2,"anchor":"Experiments","text":"Experiments"},{"type":"paragraph","inlineContent":[{"text":"Experiments are defined by the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiment","isActive":true,"type":"reference"},{"text":" enum. All active experiments are defined with the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiments","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiments\/active","isActive":true,"type":"reference"},{"text":" property. All experiments that are not included in this list have ended and have no effect on the SDK.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can use ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiment\/isEnabled"},{"text":" to check if an experiment is enabled, and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiment\/setIsEnabled(_:)"},{"text":" to manually enable or disable experiments.","type":"text"}]},{"type":"heading","level":2,"anchor":"Context","text":"Context"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has an "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExperimentsContext","isActive":true},{"type":"text","text":" class with observable state, that can be used to enable and disable active experiments."}]},{"type":"codeListing","syntax":"swift","code":["struct MyView: View {","","    @StateObject private var context = ExperimentsContext()","","    var body: some View {","        ...","    }","} "]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExperimentsContext","isActive":true,"type":"reference"},{"text":" has properties and functions like ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExperimentsContext\/enabledState(for:)","isActive":true,"type":"reference"}]},{"inlineContent":[{"type":"text","text":"Unlike most other context classes, the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExperimentsContext"},{"type":"text","text":" is not injected into the view environment. You must set up an instance like above when you want to use one."}],"type":"paragraph"}]}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"Developer-Article-Memory-Management.jpg":{"type":"image","identifier":"Developer-Article-Memory-Management.jpg","alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Memory-Management.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Experiment/isEnabled":{"abstract":[{"type":"text","text":"Whether the experiment is enabled."}],"kind":"symbol","title":"isEnabled","role":"symbol","url":"\/documentation\/keyboardkit\/experiment\/isenabled","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiment\/isEnabled"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Debugging":{"abstract":[{"text":"This developer guide describes how to debug a custom keyboard extension.","type":"text"}],"kind":"article","images":[{"identifier":"Developer-Article-Debugging.jpg","type":"card"}],"title":"Debugging","role":"article","url":"\/documentation\/keyboardkit\/developer-debugging","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-dSYMs":{"url":"\/documentation\/keyboardkit\/developer-dsyms","type":"topic","images":[{"identifier":"Developer-Article-dSYMs.jpg","type":"card"}],"title":"dSYMs","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","role":"article","abstract":[{"type":"text","text":"This developer guide describes how to use dSYMs to obtain more detailed crash reports."}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Experiment/setIsEnabled(_:)":{"abstract":[{"type":"text","text":"Set whether the experiment is enabled."}],"kind":"symbol","title":"setIsEnabled(_:)","role":"symbol","url":"\/documentation\/keyboardkit\/experiment\/setisenabled(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setIsEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiment\/setIsEnabled(_:)"},"Developer-Article-dSYMs.jpg":{"alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-dSYMs.jpg"}],"identifier":"Developer-Article-dSYMs.jpg","type":"image"},"Developer-Article-Data-Syncing.jpg":{"type":"image","identifier":"Developer-Article-Data-Syncing.jpg","alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Data-Syncing.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Experiment":{"navigatorTitle":[{"kind":"identifier","text":"Experiment"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiment","type":"topic","url":"\/documentation\/keyboardkit\/experiment","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Experiment"}],"role":"symbol","title":"Experiment","abstract":[{"text":"This enum defines all available experiments.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Data-Syncing":{"url":"\/documentation\/keyboardkit\/developer-data-syncing","type":"topic","images":[{"type":"card","identifier":"Developer-Article-Data-Syncing.jpg"}],"title":"Data Syncing","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","role":"article","abstract":[{"type":"text","text":"This developer guide describes how to sync data between the main app and its keyboard."}],"kind":"article"},"Developer-Article-Debugging.jpg":{"type":"image","identifier":"Developer-Article-Debugging.jpg","alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Debugging.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ExperimentsContext/enabledState(for:)":{"abstract":[{"type":"text","text":"Get an enabled state binding for a certain experiment."}],"kind":"symbol","title":"enabledState(for:)","role":"symbol","url":"\/documentation\/keyboardkit\/experimentscontext\/enabledstate(for:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabledState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"Experiment","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit10ExperimentO"},{"text":") -> ","kind":"text"},{"text":"Binding","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV"},{"text":"<","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExperimentsContext\/enabledState(for:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Experiments":{"navigatorTitle":[{"text":"Experiments","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiments","type":"topic","url":"\/documentation\/keyboardkit\/experiments","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Experiments","kind":"identifier"}],"role":"symbol","title":"Experiments","abstract":[{"type":"text","text":"This type is a namespace for "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiment","isActive":true},{"type":"text","text":" types."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Memory-Management":{"url":"\/documentation\/keyboardkit\/developer-memory-management","abstract":[{"text":"This developer guide describes how to manage memory in a keyboard extensions.","type":"text"}],"images":[{"identifier":"Developer-Article-Memory-Management.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management","title":"Memory Management","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Custom-Keyboards":{"kind":"article","abstract":[{"type":"text","text":"This developer guide describes how custom iOS keyboard extensions work."}],"images":[{"identifier":"Developer-Article-Custom-Keyboards.jpg","type":"card"}],"title":"Custom Keyboard Extensions","role":"article","url":"\/documentation\/keyboardkit\/developer-custom-keyboards","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Experiments/active":{"url":"\/documentation\/keyboardkit\/experiments\/active","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiments\/active","title":"active","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit10ExperimentO","text":"Experiment","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","abstract":[],"kind":"symbol","deprecated":true},"Developer-Article-Experiments.jpg":{"identifier":"Developer-Article-Experiments.jpg","type":"image","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Experiments.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ExperimentsContext":{"url":"\/documentation\/keyboardkit\/experimentscontext","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExperimentsContext","title":"ExperimentsContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExperimentsContext"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ExperimentsContext"}],"abstract":[{"text":"This class provides observable experiment state that can","type":"text"},{"type":"text","text":" "},{"type":"text","text":"be used in views."}],"kind":"symbol"},"Developer-Article-Custom-Keyboards.jpg":{"type":"image","identifier":"Developer-Article-Custom-Keyboards.jpg","alt":"Article Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Developer-Article-Custom-Keyboards.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Guides":{"url":"\/documentation\/keyboardkit\/developer-guides","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides","role":"collectionGroup","title":"Developer Guides","type":"topic","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"anchor":"Essentials","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Custom-Keyboards","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Data-Syncing","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Debugging","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-dSYMs","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Memory-Management"],"generated":true,"title":"Essentials"}],"path":"\/seeAlsoSections"}]}]}