{"sections":[],"kind":"article","metadata":{"roleHeading":"Article","role":"article","title":"Dictation","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"modules":[{"name":"KeyboardKit"}]},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","interfaceLanguage":"swift"},"abstract":[{"text":"This article describes the KeyboardKit dictation engine.","type":"text"}],"topicSections":[{"title":"Developer Guide","anchor":"Developer-Guide","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation"]},{"title":"Types","anchor":"Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationEngine","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationService","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSettings","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSpeechRecognizer"]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"]}],"variants":[{"paths":["\/documentation\/keyboardkit\/dictation-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/dictation-article"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Dictation can be used to enter text by speaking instead of typing. This can be complicated to set up, since keyboard extensions are not allowed to access the microphone. KeyboardKit makes this easy.","type":"text"}]},{"content":[{"inlineContent":[{"text":"👑 Dictation requires a KeyboardKit Pro license with ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/dictation"},{"text":" support, unless you want to implement the feature from scratch. You can sign up for KeyboardKit Pro from the ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/keyboardkit.com"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"Important","type":"aside","style":"important"},{"anchor":"Developer-Guide","text":"Developer Guide","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"See the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation"},{"text":" developer guide for detailed information on how to set up dictation for a main application and its keyboard extension.","type":"text"}]},{"anchor":"Namespace","text":"Namespace","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation"},{"text":" namespace with dictation-related types like ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/AuthorizationStatus"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod"},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationState"},{"text":", and views like ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/Indicator"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressView"},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/VolumeVisualizer"},{"text":".","type":"text"}]},{"anchor":"Context","text":"Context","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext"},{"text":" that has observable dictation state, as well as auto-persisted, dictation-specific ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext\/settings"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit automatically creates an instance of this class, injects it into ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state"},{"text":" and also injects it into the view hierarchy environment.","type":"text"}]},{"anchor":"Services","text":"Services","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"In KeyboardKit, a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationService"},{"text":" can be used to perform dictation from both an app or a keyboard extension. The keyboard can open the main app to start dictation, then navigate back to perform dictation from within the extension.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit injects a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationService\/disabled"},{"text":" service into ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services"},{"text":" until you set up KeyboardKit Pro or inject your own service implementation.","type":"text"}]},{"anchor":"Settings","text":"Settings","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSettings"},{"text":" type with dictation-related settings like the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSettings\/dictationMethod"},{"text":" and a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSettings\/silenceLimit"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSettings\/dictationMethod"},{"text":" supports ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod\/app"},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod\/keyboard"},{"text":" dictation. App-based dictation opens the main app to perform dictation, then returns to the keyboard to apply the result, while keyboard-based dictation only opens the main app if needed.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The context ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext\/settings"},{"text":" is used by default. KeyboardKit Pro unlocks a feature-specific ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/SettingsScreen"},{"text":" that can be used to handle these settings.","type":"text"}]},{"anchor":"%F0%9F%91%91-KeyboardKit-Pro","text":"👑 KeyboardKit Pro","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro unlocks a standard dictation service, a speech recognizer, as well as a bunch of views and dictation-specific utilities.","type":"text"}]},{"content":[{"inlineContent":[{"text":"These services and utilities require a KeyboardKit Pro license that unlocks the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/dictation"},{"text":" feature. The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/SettingsScreen"},{"text":" also requires the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/settingsScreens"},{"text":" feature.","type":"text"}],"type":"paragraph"}],"name":"Important","type":"aside","style":"important"},{"anchor":"Services","text":"Services","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro unlocks a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/StandardDictationService"},{"text":" that can be used trigger dictation from a keyboard extension, by opening the main app to start dictation, then (if possible) return to the keyboard to apply the result.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro will automatically register a standard dictation service as the main ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Services\/dictationService"},{"text":" when a license is registered.","type":"text"}]},{"anchor":"Speech-Recognizer","text":"Speech Recognizer","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/StandardDictationService"},{"text":" requires that you pass in a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSpeechRecognizer"},{"text":". The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation"},{"text":" developer guide has source code for a local, private, on-device speech recognizer that supports the following locales:","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Arabic (ar-SA), Cantonese (yue-CN), Catalan (ca-ES), Chinese (zh-CN), Chinese (zh-HK), Chinese (zh-TW), Croatian (hr-HR), Czech (cs-CZ), Danish (da-DK), Dutch (nl-BE), Dutch (nl-NL), English (en-AE), English (en-AU), English (en-CA), English (en-GB), English (en-ID), English (en-IE), English (en-IN), English (en-NZ), English (en-PH), English (en-SA), English (en-SG), English (en-US), English (en-ZA), Finnish (fi-FI), French (fr-BE), French (fr-CA), French (fr-CH), French (fr-FR), German (de-AT), German (de-CH), German (de-DE), Greek (el-GR), Hebrew (he-IL), Hindi (hi-IN), Hindi (hi-IN-translit), Hindi (hi-Latn), Hungarian (hu-HU), Indonesian (id-ID), Italian (it-CH), Italian (it-IT), Japanese (ja-JP), Korean (ko-KR), Malay (ms-MY), Norwegian Bokmål (nb-NO), Polish (pl-PL), Portuguese (pt-BR), Portuguese (pt-PT), Romanian (ro-RO), Russian (ru-RU), Shanghainese (wuu-CN), Slovak (sk-SK), Spanish (es-419), Spanish (es-CL), Spanish (es-CO), Spanish (es-ES), Spanish (es-MX), Spanish (es-US), Swedish (sv-SE), Thai (th-TH), Turkish (tr-TR), Ukrainian (uk-UA), Vietnamese (vi-VN)","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can implement the speech recognizer protocol from scratch, for instance to use your own ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article"},{"text":" model for speech recognition.","type":"text"}]},{"anchor":"Volume-Recorder","text":"Volume Recorder","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/StandardDictationService"},{"text":" can use a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/VolumeRecorder"},{"text":" to record the microphone volume during dictation. The volume levels can be visualized with a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/VolumeVisualizer"},{"text":" next to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext\/dictatedText"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro will automatically inject a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/StandardVolumeRecorder"},{"text":" instance into the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/StandardDictationService"},{"text":" service.","type":"text"}]},{"anchor":"Screens","text":"Screens","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro unlocks a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation"},{"text":"-specific ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/SettingsScreen"},{"text":" that can be used to manage dictation-related settings:","type":"text"}]},{"tabs":[{"title":"Settings Screen","content":[{"numberOfColumns":2,"type":"row","columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"dictation-settingsscreen"}],"type":"paragraph"}]},{"size":1,"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen"},{"type":"text","text":" template will automatically link to this screen if the current license unlocks the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/dictation"},{"type":"text","text":" feature."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This screen can be customized with the following view modifiers:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/dictationSettingsScreenLocalization(_:)"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}]}],"type":"tabNavigator"},{"anchor":"Views","text":"Views","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro unlocks ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation"},{"text":"-specific views that can be used to visualize and manage ongoing dictation operations:","type":"text"}]},{"tabs":[{"title":"Progress View","content":[{"numberOfColumns":2,"type":"row","columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"dictation-progressview"}],"type":"paragraph"}]},{"size":1,"content":[{"inlineContent":[{"type":"text","text":"A dictation "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressView"},{"type":"text","text":" can be used to show and handle an ongoing dictation operation."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This view can be customized with the following view modifiers:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/dictationProgressViewLocalization(_:)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/dictationProgressViewStyle(_:)"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}]},{"title":"Indicator","content":[{"numberOfColumns":2,"type":"row","columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"dictation-indicator"}],"type":"paragraph"}]},{"size":1,"content":[{"inlineContent":[{"type":"text","text":"A dictation "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/Indicator"},{"type":"text","text":" can be used to indicate whether there is an active dictation operation in progress."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The view can be wrapped in a button or menu to allow a user to stop or adjust the operation by tapping the indicator."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This view can be customized with the following view modifiers:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/dictationIndicatorStyle(_:)"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}]}],"type":"tabNavigator"},{"anchor":"Visualizers","text":"Visualizers","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro unlocks ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation"},{"text":"-specific visualizers that can be used to visualize dictation information:","type":"text"}]},{"tabs":[{"title":"Volume Visualizer","content":[{"numberOfColumns":2,"type":"row","columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"dictation-volumevisualizer"}],"type":"paragraph"}]},{"size":1,"content":[{"inlineContent":[{"type":"text","text":"A dictation "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/VolumeVisualizer"},{"type":"text","text":" can be used to render "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext\/volumeData"},{"type":"text","text":" that is recorded by a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/VolumeRecorder"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This visualizer is used by the dictation-specific "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressView"},{"type":"text","text":", which is used by the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This view can be customized with the following view modifiers:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/dictationVolumeVisualizerStyle(_:)"},{"type":"text","text":"."}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}]},{"title":"Bar Visualizer","content":[{"numberOfColumns":2,"type":"row","columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"dictation-barvisualizer"}],"type":"paragraph"}]},{"size":1,"content":[{"inlineContent":[{"type":"text","text":"A dictation "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/BarVisualizer"},{"type":"text","text":" can be used to render a collection of randomly animated bars."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This can be used to provide a more fun animation, rather than the more correct volume visualizer."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This view can be customized with the following view modifiers:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/dictationBarVisualizerStyle(_:)"},{"type":"text","text":"."}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}]}],"type":"tabNavigator"}]}],"references":{"Feature-Essentials.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Essentials.jpg"},"Feature-AI.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-AI.jpg","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/BarVisualizer":{"url":"\/documentation\/keyboardkit\/dictation\/barvisualizer","navigatorTitle":[{"text":"BarVisualizer","kind":"identifier"}],"abstract":[{"type":"text","text":"This visualizer can be used to render a list of bars"},{"type":"text","text":" "},{"type":"text","text":"that animate randomly when "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/BarVisualizer\/isAnimating"},{"type":"text","text":" is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarVisualizer","kind":"identifier"}],"role":"symbol","type":"topic","title":"Dictation.BarVisualizer","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/BarVisualizer"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationService":{"url":"\/documentation\/keyboardkit\/dictationservice","navigatorTitle":[{"text":"DictationService","kind":"identifier"}],"abstract":[{"type":"text","text":"This protocol can be implemented by any type that can be"},{"type":"text","text":" "},{"type":"text","text":"used to perform dictation."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DictationService","kind":"identifier"}],"role":"symbol","type":"topic","title":"DictationService","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationService"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","url":"\/documentation\/keyboardkit\/app-article","images":[{"identifier":"Feature-App.jpg","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"role":"article","title":"App Utilities","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/DisabledDictationService":{"url":"\/documentation\/keyboardkit\/dictation\/disableddictationservice","kind":"symbol","abstract":[{"type":"text","text":"This class can be used to disable dictation."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DisabledDictationService","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisabledDictationService"}],"navigatorTitle":[{"kind":"identifier","text":"DisabledDictationService"}],"type":"topic","title":"Dictation.DisabledDictationService"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationSettings/silenceLimit":{"url":"\/documentation\/keyboardkit\/dictationsettings\/silencelimit","title":"silenceLimit","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSettings\/silenceLimit","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The max number of seconds of silence, after which dictation automatically ends."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"silenceLimit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"type":"topic"},"Feature-Fonts.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Fonts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/Indicator":{"url":"\/documentation\/keyboardkit\/dictation\/indicator","title":"Dictation.Indicator","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/Indicator","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This view can be presented when dictation is active."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Indicator"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Indicator"}]},"dictation-volumevisualizer":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/dictation-volumevisualizer.jpg"}],"type":"image","identifier":"dictation-volumevisualizer","alt":"DictationScreen"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/DictationMethod/app":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"app","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod\/app","abstract":[{"text":"Dictation is performed in the main app.","type":"text"}],"role":"symbol","title":"Dictation.DictationMethod.app","url":"\/documentation\/keyboardkit\/dictation\/dictationmethod\/app"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/Services/dictationService":{"type":"topic","abstract":[{"text":"The dictation service to use.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dictationService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DictationService","preciseIdentifier":"s:11KeyboardKit16DictationServiceP"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Services\/dictationService","title":"dictationService","role":"symbol","url":"\/documentation\/keyboardkit\/keyboard\/services\/dictationservice"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"images":[{"type":"card","identifier":"Feature-AI.jpg"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/DictationMethod":{"url":"\/documentation\/keyboardkit\/dictation\/dictationmethod","kind":"symbol","abstract":[{"type":"text","text":"This enum defines the supported dictation methods."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DictationMethod"}],"navigatorTitle":[{"kind":"identifier","text":"DictationMethod"}],"type":"topic","title":"Dictation.DictationMethod"},"dictation-progressview":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/dictation-progressview.jpg"}],"type":"image","identifier":"dictation-progressview","alt":"Dictation.ProgressView"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationSettings/dictationMethod":{"url":"\/documentation\/keyboardkit\/dictationsettings\/dictationmethod","kind":"symbol","abstract":[{"text":"The dictation method to use, by default ","type":"text"},{"type":"codeVoice","code":".app"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSettings\/dictationMethod","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dictationMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Dictation","preciseIdentifier":"s:11KeyboardKit9DictationV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"DictationMethod","preciseIdentifier":"s:11KeyboardKit9DictationV0C6MethodO","kind":"typeIdentifier"}],"type":"topic","title":"dictationMethod"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/DictationState":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationState","url":"\/documentation\/keyboardkit\/dictation\/dictationstate","abstract":[{"text":"This enum defines the states that a dictation engine","type":"text"},{"type":"text","text":" "},{"type":"text","text":"can be in."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DictationState"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DictationState"}],"kind":"symbol","title":"Dictation.DictationState","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"url":"\/documentation\/keyboardkit\/fonts-article","abstract":[{"type":"text","text":"This article describes KeyboardKit’s custom font support."}],"role":"article","type":"topic","title":"Fonts","kind":"article","images":[{"identifier":"Feature-Fonts.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"url":"\/documentation\/keyboardkit\/host-article","abstract":[{"text":"This article describes how KeyboardKit Pro can identify and use the host application.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Host Application","images":[{"type":"card","identifier":"Feature-Host.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationContext":{"type":"topic","abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"text":" ","type":"text"},{"type":"text","text":"for keyboard-based dictation."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DictationContext"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext","navigatorTitle":[{"kind":"identifier","text":"DictationContext"}],"title":"DictationContext","role":"symbol","url":"\/documentation\/keyboardkit\/dictationcontext"},"Feature-Host.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Host.jpg"},"Feature-Callouts.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Callouts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/VolumeVisualizer":{"url":"\/documentation\/keyboardkit\/dictation\/volumevisualizer","title":"Dictation.VolumeVisualizer","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/VolumeVisualizer","role":"symbol","kind":"symbol","abstract":[{"text":"This visualizer can be used to render a list of bars","type":"text"},{"text":" ","type":"text"},{"text":"that represent the provided volume data.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VolumeVisualizer"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"VolumeVisualizer"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/StandardDictationService":{"abstract":[{"text":"This service can be used to start dictation from the","type":"text"},{"text":" ","type":"text"},{"text":"keyboard and perform it in the app or keyboard.","type":"text"}],"kind":"symbol","title":"Dictation.StandardDictationService","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/StandardDictationService","navigatorTitle":[{"text":"StandardDictationService","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StandardDictationService","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/dictation\/standarddictationservice","role":"symbol"},"Feature-Feedback.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Feedback.jpg"},"dictation-indicator":{"alt":"Dictation.Indicator","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/dictation-indicator.jpg","traits":["1x","light"]}],"type":"image","identifier":"dictation-indicator"},"https://keyboardkit.com":{"url":"https:\/\/keyboardkit.com","type":"link","title":"KeyboardKit website","titleInlineContent":[{"text":"KeyboardKit website","type":"text"}],"identifier":"https:\/\/keyboardkit.com"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Gestures-Article":{"type":"topic","images":[{"identifier":"Feature-Gestures.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"role":"article","title":"Gestures","url":"\/documentation\/keyboardkit\/gestures-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationContext/dictatedText":{"url":"\/documentation\/keyboardkit\/dictationcontext\/dictatedtext","abstract":[{"text":"The currently dictated text.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dictatedText"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","type":"topic","kind":"symbol","title":"dictatedText","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext\/dictatedText"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationSettings":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSettings","url":"\/documentation\/keyboardkit\/dictationsettings","abstract":[{"type":"text","text":"This type has auto-persisted dictation settings."}],"role":"symbol","navigatorTitle":[{"text":"DictationSettings","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DictationSettings","kind":"identifier"}],"title":"DictationSettings","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation":{"url":"\/documentation\/keyboardkit\/dictation","navigatorTitle":[{"text":"Dictation","kind":"identifier"}],"abstract":[{"type":"text","text":"This namespace contains dictation-related types."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Dictation","kind":"identifier"}],"role":"symbol","type":"topic","title":"Dictation","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/dictationIndicatorStyle(_:)":{"abstract":[],"kind":"symbol","title":"dictationIndicatorStyle(_:)","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/dictationIndicatorStyle(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dictationIndicatorStyle"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9DictationV","text":"Dictation"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9DictationV14IndicatorStyleV","text":"IndicatorStyle"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkit\/swiftuicore\/view\/dictationindicatorstyle(_:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"abstract":[{"type":"text","text":"This article describes KeyboardKit’s clipboard support."}],"kind":"article","title":"Clipboard","type":"topic","images":[{"identifier":"Feature-Clipboard.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","url":"\/documentation\/keyboardkit\/clipboard-article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/BarVisualizerStyle":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarVisualizerStyle","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/BarVisualizerStyle","kind":"symbol","title":"Dictation.BarVisualizerStyle","abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"type":"text","text":"a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/BarVisualizer","type":"reference","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/keyboardkit\/dictation\/barvisualizerstyle","navigatorTitle":[{"text":"BarVisualizerStyle","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-Article":{"url":"\/documentation\/keyboardkit\/essentials-article","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"images":[{"identifier":"Feature-Essentials.jpg","type":"card"}],"type":"topic","title":"Essentials","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationService/disabled":{"url":"\/documentation\/keyboardkit\/dictationservice\/disabled","abstract":[{"type":"text","text":"Create a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DisabledDictationService","type":"reference","isActive":true},{"type":"text","text":" instance."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"disabled","kind":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" is "},{"type":"codeVoice","code":"Dictation.DisabledDictationService"},{"type":"text","text":"."}]},"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationService\/disabled"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"role":"article","type":"topic","kind":"article","title":"Callouts","images":[{"type":"card","identifier":"Feature-Callouts.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article"},"Feature-Dictation.jpg":{"alt":"Article Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Dictation.jpg"},"dictation-settingsscreen":{"alt":"Dictation.SettingsScreen","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/dictation-settingsscreen.jpg","traits":["1x","light"]}],"type":"image","identifier":"dictation-settingsscreen"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/BarVisualizer/isAnimating":{"url":"\/documentation\/keyboardkit\/dictation\/barvisualizer\/isanimating","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAnimating","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"isAnimating","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/BarVisualizer\/isAnimating"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/HomeScreen":{"url":"\/documentation\/keyboardkit\/keyboardapp\/homescreen","navigatorTitle":[{"text":"HomeScreen","kind":"identifier"}],"abstract":[{"type":"text","text":"This screen can be used as the main home screen of a"},{"type":"text","text":" "},{"type":"text","text":"keyboard app that should look like iOS Settings."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HomeScreen","kind":"identifier"}],"role":"symbol","type":"topic","title":"KeyboardApp.HomeScreen","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Dictation":{"type":"topic","images":[{"identifier":"Feature-Dictation.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation","abstract":[{"type":"text","text":"This developer guide describes how to set up and customize dictation."}],"role":"article","title":"Dictation","url":"\/documentation\/keyboardkit\/developer-dictation"},"Feature-Input.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Input.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","url":"\/documentation\/keyboardkit\/feedback-article","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"role":"article","title":"Feedback","kind":"article","type":"topic"},"dictation-barvisualizer":{"alt":"DictationScreen","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/dictation-barvisualizer.jpg","traits":["1x","light"]}],"type":"image","identifier":"dictation-barvisualizer"},"Feature-Clipboard.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Clipboard.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-KeyboardView":{"type":"topic","images":[{"identifier":"Feature-Essentials-KeyboardView.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","kind":"article","title":"Essentials - KeyboardView","abstract":[{"type":"text","text":"This article describes the essential "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"type":"text","text":" and how to use and configure it."}],"url":"\/documentation\/keyboardkit\/essentials-keyboardview"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/DictationMethod/keyboard":{"type":"topic","abstract":[{"text":"Dictation is performed in the keyboard.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboard"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod\/keyboard","title":"Dictation.DictationMethod.keyboard","role":"symbol","url":"\/documentation\/keyboardkit\/dictation\/dictationmethod\/keyboard"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/services":{"abstract":[{"text":"Keyboard-specific services.","type":"text"}],"kind":"symbol","title":"services","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"services","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11KeyboardKit0A0V","text":"Keyboard","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11KeyboardKit0A0V8ServicesC","text":"Services","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/services","role":"symbol"},"Feature-External.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-External.jpg"},"Feature-Gestures.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Gestures.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Gestures.jpg"},"Feature-Essentials-KeyboardView.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials-KeyboardView.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Essentials-KeyboardView.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","title":"KeyboardView","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","role":"symbol","kind":"symbol","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"Feature-App.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-App.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"url":"\/documentation\/keyboardkit\/input-article","abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Input","images":[{"identifier":"Feature-Input.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/dictationProgressViewLocalization(_:)":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dictationProgressViewLocalization"},{"kind":"text","text":"("},{"preciseIdentifier":"s:11KeyboardKit9DictationV","text":"Dictation","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit9DictationV24ProgressViewLocalizationV","text":"ProgressViewLocalization","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/dictationProgressViewLocalization(_:)","title":"dictationProgressViewLocalization(_:)","role":"symbol","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/dictationprogressviewlocalization(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/VolumeVisualizerStyle":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VolumeVisualizerStyle","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/VolumeVisualizerStyle","abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"type":"text","text":"a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/VolumeVisualizer","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","title":"Dictation.VolumeVisualizerStyle","url":"\/documentation\/keyboardkit\/dictation\/volumevisualizerstyle","navigatorTitle":[{"text":"VolumeVisualizerStyle","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/SettingsScreen":{"title":"Dictation.SettingsScreen","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SettingsScreen"}],"abstract":[{"type":"text","text":"This screen can be used as a settings screen for any"},{"type":"text","text":" "},{"type":"text","text":"dictation-related keyboard settings."}],"role":"symbol","navigatorTitle":[{"text":"SettingsScreen","kind":"identifier"}],"type":"topic","url":"\/documentation\/keyboardkit\/dictation\/settingsscreen","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/SettingsScreen","kind":"symbol"},"Feature-Autocomplete.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Autocomplete.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/dictationProgressViewStyle(_:)":{"abstract":[],"kind":"symbol","title":"dictationProgressViewStyle(_:)","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/dictationProgressViewStyle(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dictationProgressViewStyle","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit9DictationV","text":"Dictation","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9DictationV17ProgressViewStyleV","text":"ProgressViewStyle"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkit\/swiftuicore\/view\/dictationprogressviewstyle(_:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/AuthorizationStatus":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/AuthorizationStatus","url":"\/documentation\/keyboardkit\/dictation\/authorizationstatus","abstract":[{"type":"text","text":"This enum defines various dictation statuses."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AuthorizationStatus"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthorizationStatus"}],"title":"Dictation.AuthorizationStatus","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/state":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Keyboard","preciseIdentifier":"s:11KeyboardKit0A0V"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"s:11KeyboardKit0A0V5StateC"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Keyboard-specific state."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","role":"symbol","title":"state","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/state"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/dictationSettingsScreenLocalization(_:)":{"url":"\/documentation\/keyboardkit\/swiftuicore\/view\/dictationsettingsscreenlocalization(_:)","kind":"symbol","abstract":[{"text":"Apply a custom screen localization.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/dictationSettingsScreenLocalization(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dictationSettingsScreenLocalization","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Dictation","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9DictationV"},{"text":".","kind":"text"},{"text":"SettingsScreenLocalization","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9DictationV26SettingsScreenLocalizationV"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"type":"topic","title":"dictationSettingsScreenLocalization(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/VolumeRecorder":{"type":"topic","abstract":[{"type":"text","text":"This protocol can be implemented by any type that is"},{"type":"text","text":" "},{"type":"text","text":"able to record dictation volume levels."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VolumeRecorder"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/VolumeRecorder","navigatorTitle":[{"text":"VolumeRecorder","kind":"identifier"}],"title":"Dictation.VolumeRecorder","role":"symbol","url":"\/documentation\/keyboardkit\/dictation\/volumerecorder"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/settingsScreens":{"abstract":[],"kind":"symbol","title":"ProFeature.settingsScreens","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/settingsScreens","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settingsScreens","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/profeature\/settingsscreens","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/ProgressView":{"url":"\/documentation\/keyboardkit\/dictation\/progressview","navigatorTitle":[{"text":"ProgressView","kind":"identifier"}],"abstract":[{"type":"text","text":"This view can be used to visualize ongoing dictation"},{"type":"text","text":" "},{"type":"text","text":"progress and let users cancel or apply."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProgressView","kind":"identifier"}],"role":"symbol","type":"topic","title":"Dictation.ProgressView","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressView"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"url":"\/documentation\/keyboardkit\/emojis-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"role":"article","type":"topic","kind":"article","title":"Emojis","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"url":"\/documentation\/keyboardkit\/external-keyboards-article","kind":"article","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","role":"article","type":"topic","images":[{"identifier":"Feature-External.jpg","type":"card"}],"title":"External Keyboards"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/dictationBarVisualizerStyle(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dictationBarVisualizerStyle"},{"kind":"text","text":"("},{"preciseIdentifier":"s:11KeyboardKit9DictationV","kind":"typeIdentifier","text":"Dictation"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11KeyboardKit9DictationV18BarVisualizerStyleV","kind":"typeIdentifier","text":"BarVisualizerStyle"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"type":"topic","kind":"symbol","abstract":[{"text":"Apply a custom ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/BarVisualizerStyle","type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/dictationBarVisualizerStyle(_:)","role":"symbol","title":"dictationBarVisualizerStyle(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/dictationbarvisualizerstyle(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationContext/settings":{"type":"topic","abstract":[{"text":"Dictation-specific, auto-persisted settings.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"},{"kind":"text","text":": "},{"text":"DictationSettings","preciseIdentifier":"s:11KeyboardKit17DictationSettingsV","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext\/settings","title":"settings","role":"symbol","url":"\/documentation\/keyboardkit\/dictationcontext\/settings"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/dictation":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/dictation","url":"\/documentation\/keyboardkit\/profeature\/dictation","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dictation"}],"title":"ProFeature.dictation","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationSpeechRecognizer":{"url":"\/documentation\/keyboardkit\/dictationspeechrecognizer","navigatorTitle":[{"text":"DictationSpeechRecognizer","kind":"identifier"}],"abstract":[{"type":"text","text":"This protocol can be implemented by any type that can be"},{"type":"text","text":" "},{"type":"text","text":"used to perform speech recognition."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DictationSpeechRecognizer","kind":"identifier"}],"role":"symbol","type":"topic","title":"DictationSpeechRecognizer","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationSpeechRecognizer"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationEngine":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationEngine","url":"\/documentation\/keyboardkit\/dictationengine","abstract":[{"text":"This protocol can be implemented by any type that can be","type":"text"},{"type":"text","text":" "},{"type":"text","text":"used to perform dictation by accessing the microphone."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DictationEngine"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DictationEngine"}],"kind":"symbol","title":"DictationEngine","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/StandardVolumeRecorder":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/StandardVolumeRecorder","url":"\/documentation\/keyboardkit\/dictation\/standardvolumerecorder","abstract":[{"type":"text","text":"This standard volume recorder will record the volume"},{"type":"text","text":" "},{"type":"text","text":"during a dictation operation."}],"role":"symbol","navigatorTitle":[{"text":"StandardVolumeRecorder","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StandardVolumeRecorder"}],"title":"Dictation.StandardVolumeRecorder","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","url":"\/documentation\/keyboardkit\/actions-article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"role":"article","kind":"article","title":"Actions","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"url":"\/documentation\/keyboardkit\/features-articles","abstract":[{"type":"text","text":"This article links to the various KeyboardKit features."}],"role":"collectionGroup","type":"topic","title":"Features","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/dictationVolumeVisualizerStyle(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dictationVolumeVisualizerStyle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9DictationV","text":"Dictation"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit9DictationV21VolumeVisualizerStyleV","text":"VolumeVisualizerStyle"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/dictationVolumeVisualizerStyle(_:)","abstract":[{"type":"text","text":"Apply a custom "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/VolumeVisualizerStyle"},{"type":"text","text":"."}],"role":"symbol","title":"dictationVolumeVisualizerStyle(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/dictationvolumevisualizerstyle(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DictationContext/volumeData":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DictationContext\/volumeData","url":"\/documentation\/keyboardkit\/dictationcontext\/volumedata","abstract":[{"type":"text","text":"The currently recorded audio volumes."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"volumeData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":"]"}],"kind":"symbol","title":"volumeData","type":"topic"},"Feature-Actions.jpg":{"identifier":"Feature-Actions.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon"},"Feature-Emojis.jpg":{"identifier":"Feature-Emojis.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"url":"\/documentation\/keyboardkit\/autocomplete-article","title":"Autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"anchor":"Developer-Guide","title":"Developer Guide","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Dictation"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"}]}]}