{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"This article describes the essential "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView"},{"type":"text","text":" and how to use and configure it."}],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkit\/essentials-keyboardview"]},{"paths":["\/documentation\/keyboardkit\/essentials-keyboardview"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView"},"primaryContentSections":[{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView"},{"text":" that mimics the native iOS keyboard. It can be used for alphabetic, numeric & symbolic keyboards, as well as completely custom ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout"},{"text":"s, and supports many different ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/InputType"},{"text":"s:","type":"text"}]},{"type":"row","columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"identifier":"keyboardview-english-callout","type":"image"}]}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"identifier":"keyboardview-swedish-theme","type":"image"}]}]}],"numberOfColumns":2},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView"},{"text":" will set up most things for you, like applying gestures, styles, callouts, etc. based on the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Services"},{"text":" and ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/State"},{"text":". It automatically observes and adapts to all observable contexts and can render all ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/keyboardKitSupported"},{"text":" locales.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView"},{"text":" will by default take up as much space as it needs, and resize the keyboard extension frame accordingly. It will also honor settings like ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/isAutoCollapseKeyboardEnabled"},{"text":", ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/keyboardDockEdge"},{"text":", ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/isKeyboardFloating"},{"text":" etc.","type":"text"}]},{"type":"aside","name":"Tip","style":"tip","content":[{"type":"paragraph","inlineContent":[{"text":"👑 KeyboardKit Pro Gold unlocks support for all supported locales and injects an ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/EmojiKeyboard","isActive":true,"type":"reference"},{"text":" view into the keyboard view.","type":"text"}]}]},{"type":"heading","text":"Customization","level":2,"anchor":"Customization"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView"},{"text":" can be customized in many ways, for instance by changing observable state in the various contexts and settings, by applying various view modifiers and by using the initializer’s view builders to customize the various nested content views.","type":"text"}]},{"type":"heading","text":"Customizing the Keyboard Views","level":3,"anchor":"Customizing-the-Keyboard-Views"},{"type":"paragraph","inlineContent":[{"text":"You can customize any view or button content in the keyboard, by injecting custom view builders into the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView"},{"text":" initializer:","type":"text"}]},{"code":["KeyboardView(","    layout: ...,                        \/\/ You can inject a custom layout if you want to","    services: controller.services,      \/\/ You can inject a controller's or custom services","    buttonContent: { $0.view },         \/\/ You can customize the content view of any button","    buttonView: { $0.view },            \/\/ You can customize the entire view of any button","    collapsedView: { $0.view },         \/\/ You can customize the collapsed keyboard view","    emojiKeyboard: { $0.view },         \/\/ You can customize the emoji keyboard, if any","    toolbar: { params in params.view }  \/\/ You can customize the toolbar above the keyboard",")"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"You can return ","type":"text"},{"code":"$0.view","type":"codeVoice"},{"text":" (or ","type":"text"},{"code":"params in params.view","type":"codeVoice"},{"text":") to use the original views, or return any custom view based on the params.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can also completely replace the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView"},{"text":" with another view at any time. Use the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardReplacementOverlay(isPresented:content:)"},{"text":" view extension if you want the replacement view to have the same size as the keyboard view.","type":"text"}]},{"type":"heading","text":"Customizing the Keyboard Style","level":3,"anchor":"Customizing-the-Keyboard-Style"},{"type":"paragraph","inlineContent":[{"text":"You can apply a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardViewStyle(_:)"},{"text":" view modifier to style the keyboard, a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardButtonStyle(builder:)"},{"text":" view modifier to customize the style of any button, and modifiers like ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardToolbarStyle(_:)"},{"text":" to style other parts of the view.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can also apply a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardTheme(_:)"},{"text":" view modifier to apply a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme"},{"text":" that styles many parts of the keyboard view.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"See the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Styling-Article"},{"text":" and ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Themes-Article"},{"text":" articles for more information.","type":"text"}]},{"type":"heading","text":"Customizing the Keyboard Behavior","level":3,"anchor":"Customizing-the-Keyboard-Behavior"},{"type":"paragraph","inlineContent":[{"text":"The easiest way to customize the keyboard behavior is to inherit ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/StandardActionHandler"},{"text":" and override ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/handle(_:on:)"},{"text":" and other functions to customize the behavior of any gesture on any action.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"See the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article"},{"text":" article for more information.","type":"text"}]},{"type":"heading","text":"Customizing the Keyboard Layout","level":3,"anchor":"Customizing-the-Keyboard-Layout"},{"type":"paragraph","inlineContent":[{"text":"The easiest way to customize the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout"},{"text":" that is rendered by the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView"},{"text":" is to use ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/standard(for:)"},{"text":" to get a standard layout for the current context, then modify it and inject the resulting layout into the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","isActive":true,"type":"reference"},{"text":" initializer.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"See the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","type":"reference","isActive":true},{"type":"text","text":" article for more information."}]},{"type":"heading","text":"Customizing the Keyboard Callout Actions","level":3,"anchor":"Customizing-the-Keyboard-Callout-Actions"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The easiest way to customize the keyboard callout actions is to apply a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardCalloutActions(_:)","type":"reference","isActive":true},{"type":"text","text":" view modifier to the view and customize the standard actions that are provided as view builder parameters."}]},{"inlineContent":[{"type":"text","text":"See the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article"},{"type":"text","text":" article for more information."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article"],["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"],["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article"]]},"topicSections":[{"title":"Types","anchor":"Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardViewItem","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardViewStyle"]}],"metadata":{"modules":[{"name":"KeyboardKit"}],"roleHeading":"Article","role":"article","title":"Essentials - KeyboardView","images":[{"type":"card","identifier":"Feature-Essentials-KeyboardView.jpg"}]},"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/keyboardKitSupported":{"url":"\/documentation\/keyboardkit\/foundation\/locale\/keyboardkitsupported","kind":"symbol","abstract":[{"text":"A list of KeyboardKit supported locales.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/keyboardKitSupported","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardKitSupported","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"},{"text":"]","kind":"text"}],"type":"topic","title":"keyboardKitSupported"},"Feature-Themes.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Themes.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon","identifier":"Feature-Themes.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardButtonStyle(builder:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardButtonStyle(builder:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardbuttonstyle(builder:)","abstract":[{"text":"Apply a custom ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ButtonStyle"},{"text":" builder that","type":"text"},{"text":" ","type":"text"},{"text":"can vary the button style of any action.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardButtonStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"builder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A0V","text":"Keyboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A0V18ButtonStyleBuildera","text":"ButtonStyleBuilder","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"title":"keyboardButtonStyle(builder:)","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Styling-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Styling-Article","url":"\/documentation\/keyboardkit\/styling-article","images":[{"identifier":"Feature-Styling.jpg","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit styling engine.","type":"text"}],"role":"article","kind":"article","title":"Styling","type":"topic"},"Feature-Callouts.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon","identifier":"Feature-Callouts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/DockEdge":{"url":"\/documentation\/keyboardkit\/keyboard\/dockedge","abstract":[{"text":"This enum defines supported keyboard dock edges.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DockEdge"}],"type":"topic","title":"Keyboard.DockEdge","navigatorTitle":[{"kind":"identifier","text":"DockEdge"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/DockEdge","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/Services":{"url":"\/documentation\/keyboardkit\/keyboard\/services","navigatorTitle":[{"kind":"identifier","text":"Services"}],"abstract":[{"text":"This type specifies global keyboard services.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Services"}],"role":"symbol","type":"topic","kind":"symbol","title":"Keyboard.Services","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Services"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardCalloutActions(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardCalloutActions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Callouts","preciseIdentifier":"s:11KeyboardKit8CalloutsV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ActionsBuilder","preciseIdentifier":"s:11KeyboardKit8CalloutsV14ActionsBuildera"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardCalloutActions(_:)","abstract":[{"type":"text","text":"This view modifier can be used to set custom callout"},{"type":"text","text":" "},{"type":"text","text":"actions to show when long pressing a key."}],"role":"symbol","title":"keyboardCalloutActions(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardcalloutactions(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/isKeyboardFloating":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isKeyboardFloating","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/isKeyboardFloating","kind":"symbol","title":"isKeyboardFloating","abstract":[{"text":"Whether the keyboard is in floating mode.","type":"text"}],"url":"\/documentation\/keyboardkit\/keyboardcontext\/iskeyboardfloating"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/standard(for:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"KeyboardContext","preciseIdentifier":"s:11KeyboardKit0A7ContextC","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"KeyboardLayout","preciseIdentifier":"s:11KeyboardKit0A6LayoutV","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/standard(for:)","kind":"symbol","title":"standard(for:)","abstract":[{"text":"The standard keyboard layout to use for the provided","type":"text"},{"text":" ","type":"text"},{"text":"keyboard context and input set.","type":"text"}],"url":"\/documentation\/keyboardkit\/keyboardlayout\/standard(for:)"},"keyboardview-english-callout":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/keyboardview-english-callout.jpg","traits":["1x","light"]}],"type":"image","alt":"KeyboardView","identifier":"keyboardview-english-callout"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardToolbarStyle(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardToolbarStyle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V","text":"Keyboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V12ToolbarStyleV","text":"ToolbarStyle"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardToolbarStyle(_:)","abstract":[{"type":"text","text":"Apply a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ToolbarStyle"},{"type":"text","text":"."}],"role":"symbol","title":"keyboardToolbarStyle(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardtoolbarstyle(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/ToolbarStyle":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ToolbarStyle","url":"\/documentation\/keyboardkit\/keyboard\/toolbarstyle","abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Toolbar"},{"type":"text","text":" component."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ToolbarStyle"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToolbarStyle"}],"kind":"symbol","title":"Keyboard.ToolbarStyle","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Layout-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","title":"Layout","role":"article","images":[{"identifier":"Feature-Layout.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/layout-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","title":"KeyboardView","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","role":"symbol","kind":"symbol","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardReplacementOverlay(isPresented:content:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"keyboardReplacementOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"isPresented"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This modifier can be used to overlay a keyboard view"},{"type":"text","text":" "},{"text":"with a replacement view that keeps the keyboard size.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardReplacementOverlay(isPresented:content:)","role":"symbol","title":"keyboardReplacementOverlay(isPresented:content:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardreplacementoverlay(ispresented:content:)"},"Feature-Actions.jpg":{"identifier":"Feature-Actions.jpg","type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/InputType":{"type":"topic","abstract":[{"text":"This enum defines all supported text input types.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InputType","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/InputType","navigatorTitle":[{"text":"InputType","kind":"identifier"}],"title":"Keyboard.InputType","role":"symbol","url":"\/documentation\/keyboardkit\/keyboard\/inputtype"},"Feature-Essentials.jpg":{"type":"image","alt":"Feature Icon","identifier":"Feature-Essentials.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"Feature-Layout.jpg":{"type":"image","alt":"Feature Icon","identifier":"Feature-Layout.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Layout.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/EmojiKeyboard":{"url":"\/documentation\/keyboardkit\/emojikeyboard","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmojiKeyboard"}],"type":"topic","title":"EmojiKeyboard","navigatorTitle":[{"kind":"identifier","text":"EmojiKeyboard"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/EmojiKeyboard","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/State":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/State","url":"\/documentation\/keyboardkit\/keyboard\/state","abstract":[{"type":"text","text":"This type specifies global keyboard state."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"State"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"title":"Keyboard.State","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Themes-Article":{"url":"\/documentation\/keyboardkit\/themes-article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit Pro theme engine."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Themes-Article","role":"article","type":"topic","images":[{"type":"card","identifier":"Feature-Themes.jpg"}],"title":"Themes"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardTheme(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardTheme(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardtheme(_:)","abstract":[{"type":"text","text":"Apply a keyboard theme to the provided view."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardTheme"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"KeyboardTheme","preciseIdentifier":"s:11KeyboardKit0A5ThemeV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"kind":"symbol","title":"keyboardTheme(_:)","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"role":"article","type":"topic","kind":"article","title":"Callouts","images":[{"type":"card","identifier":"Feature-Callouts.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/StandardActionHandler":{"type":"topic","abstract":[{"type":"text","text":"This class provides a standard way to handle actions"},{"type":"text","text":" "},{"text":"that are triggered by the keyboard.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardActionHandler"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/StandardActionHandler","navigatorTitle":[{"kind":"identifier","text":"StandardActionHandler"}],"title":"KeyboardAction.StandardActionHandler","role":"symbol","url":"\/documentation\/keyboardkit\/keyboardaction\/standardactionhandler"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardViewStyle(_:)":{"url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardviewstyle(_:)","abstract":[{"text":"Apply a custom ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardViewStyle","type":"reference","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardViewStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"KeyboardViewStyle","preciseIdentifier":"s:11KeyboardKit0A9ViewStyleV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"keyboardViewStyle(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardViewStyle(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardActionHandler/handle(_:on:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"preciseIdentifier":"s:11KeyboardKit0A0V","kind":"typeIdentifier","text":"Keyboard"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11KeyboardKit0A0V7GestureO","kind":"typeIdentifier","text":"Gesture"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11KeyboardKit0A6ActionO","kind":"typeIdentifier","text":"KeyboardAction"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","abstract":[{"text":"Handle a certain keyboard action gesture.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler\/handle(_:on:)","required":true,"title":"handle(_:on:)","url":"\/documentation\/keyboardkit\/keyboardactionhandler\/handle(_:on:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardTheme":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme","url":"\/documentation\/keyboardkit\/keyboardtheme","abstract":[{"text":"This struct defines a keyboard-specific theme, which can","type":"text"},{"text":" ","type":"text"},{"text":"be used to define a bunch of styles at once.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardTheme"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardTheme"}],"kind":"symbol","title":"KeyboardTheme","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardViewItem":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardViewItem","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardViewItem","abstract":[{"text":"This view renders a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView"},{"text":" item view.","type":"text"}],"role":"symbol","title":"KeyboardViewItem","url":"\/documentation\/keyboardkit\/keyboardviewitem","navigatorTitle":[{"text":"KeyboardViewItem","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardSettings/isAutoCollapseKeyboardEnabled":{"url":"\/documentation\/keyboardkit\/keyboardsettings\/isautocollapsekeyboardenabled","abstract":[{"text":"Whether to auto-collapse the keyboard when an external keyboard is connected.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isAutoCollapseKeyboardEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"isAutoCollapseKeyboardEnabled","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/isAutoCollapseKeyboardEnabled","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"url":"\/documentation\/keyboardkit\/features-articles","abstract":[{"type":"text","text":"This article links to the various KeyboardKit features."}],"role":"collectionGroup","type":"topic","title":"Features","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/ButtonStyle":{"url":"\/documentation\/keyboardkit\/keyboard\/buttonstyle","title":"Keyboard.ButtonStyle","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ButtonStyle","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This style can be used to style a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Button"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ButtonStyle"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ButtonStyle"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardLayout","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout","abstract":[{"type":"text","text":"This type defines the full set of keys on a keyboard and"},{"text":" ","type":"text"},{"text":"is also a namespace for layout-related types.","type":"text"}],"role":"symbol","title":"KeyboardLayout","url":"\/documentation\/keyboardkit\/keyboardlayout","navigatorTitle":[{"kind":"identifier","text":"KeyboardLayout"}]},"Feature-Styling.jpg":{"identifier":"Feature-Styling.jpg","type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Styling.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardSettings/keyboardDockEdge":{"url":"\/documentation\/keyboardkit\/keyboardsettings\/keyboarddockedge","abstract":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/DockEdge"},{"text":" to use, if any.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardDockEdge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V","text":"Keyboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V8DockEdgeO","text":"DockEdge"},{"kind":"text","text":"?"}],"type":"topic","title":"keyboardDockEdge","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/keyboardDockEdge","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardViewStyle":{"type":"topic","abstract":[{"text":"This style can be used to style a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardViewStyle"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardViewStyle","navigatorTitle":[{"kind":"identifier","text":"KeyboardViewStyle"}],"title":"KeyboardViewStyle","role":"symbol","url":"\/documentation\/keyboardkit\/keyboardviewstyle"},"Feature-Essentials-KeyboardView.jpg":{"identifier":"Feature-Essentials-KeyboardView.jpg","type":"image","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials-KeyboardView.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-Article":{"url":"\/documentation\/keyboardkit\/essentials-article","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"images":[{"identifier":"Feature-Essentials.jpg","type":"card"}],"type":"topic","title":"Essentials","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","url":"\/documentation\/keyboardkit\/actions-article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"role":"article","kind":"article","title":"Actions","type":"topic"},"keyboardview-swedish-theme":{"identifier":"keyboardview-swedish-theme","type":"image","alt":"KeyboardView","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/keyboardview-swedish-theme.jpg","traits":["1x","light"]}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"}]}]}