{"topicSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExternalKeyboardContext"],"title":"Types","anchor":"Types"}],"kind":"article","variants":[{"paths":["\/documentation\/keyboardkit\/external-keyboards-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkit\/external-keyboards-article"]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"primaryContentSections":[{"content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Keyboard extensions start to behave strangely when you type on an external keyboard. For instance, the keyboard extension will stop receiving information about when text changes, and will only update the context when the text cursor moves."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Due to this, KeyboardKit makes it possible to automatically collapse the software keyboard when a hardware keyboard is connected, to avoid a subpar software keyboard experience."}],"type":"paragraph"},{"type":"aside","name":"Tip","style":"tip","content":[{"inlineContent":[{"text":"👑 KeyboardKit Pro unlocks tools to easily detect if an external keyboard is connected, to let you collapse the software keyboard.","type":"text"}],"type":"paragraph"}]},{"level":2,"text":"Context","type":"heading","anchor":"Context"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has an "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExternalKeyboardContext","type":"reference","isActive":true},{"text":" class with observable state, that is automatically updated if an external keyboard is connected or disconnected.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExternalKeyboardContext"},{"text":" has properties like ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExternalKeyboardContext\/isEnabledOnSimulator"},{"text":", and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExternalKeyboardContext\/isExternalKeyboardConnected"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit automatically creates an instance of this class and registers it with its "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","type":"reference"},{"type":"text","text":", and also injects it into the view environment."}]},{"level":2,"text":"Collapsed View","type":"heading","anchor":"Collapsed-View"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit will automatically collapse the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"type":"text","text":" into a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/CollapsedView","type":"reference","isActive":true},{"type":"text","text":" when "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/isKeyboardCollapsed","type":"reference","isActive":true},{"type":"text","text":" becomes true."}]},{"type":"paragraph","inlineContent":[{"identifier":"keyboard-collapsedview","type":"image"}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"type":"text","text":" lets you define which view to use as collapsed view. You can add more controls to the standard collapsed view."}]},{"type":"heading","level":2,"text":"👑 KeyboardKit Pro","anchor":"%F0%9F%91%91-KeyboardKit-Pro"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro will automatically keep the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExternalKeyboardContext","type":"reference"},{"text":" up to date when an external keyboard is connected and disconnected, and update ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/isKeyboardCollapsed","type":"reference"},{"text":" if the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/isAutoCollapseKeyboardEnabled","type":"reference"},{"text":" setting is enabled.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Without KeyboardKit Pro, you must manually listen for the connection changes yourself and update the keyboard context accordingly."}]},{"name":"Warning","content":[{"inlineContent":[{"type":"text","text":"KeyboardKit Pro will consider an Apple Smart Keyboard Folio to be connected even when it’s just snapped on to the device and not being actively used. This should be improved."}],"type":"paragraph"}],"style":"warning","type":"aside"}],"kind":"content"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article"]}],"metadata":{"modules":[{"name":"KeyboardKit"}],"role":"article","images":[{"identifier":"Feature-External.jpg","type":"card"}],"title":"External Keyboards","roleHeading":"Article"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/isKeyboardCollapsed":{"title":"isKeyboardCollapsed","abstract":[{"type":"text","text":"Whether the keyboard is collapsed."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isKeyboardCollapsed","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/keyboardcontext\/iskeyboardcollapsed","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/isKeyboardCollapsed"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Navigation-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/navigation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"images":[{"identifier":"Feature-Navigation.jpg","type":"card"}],"kind":"article","title":"Navigation","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Localization-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit localization engine."}],"url":"\/documentation\/keyboardkit\/localization-article","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","title":"Localization","type":"topic","kind":"article","role":"article"},"Feature-Dictation.jpg":{"type":"image","identifier":"Feature-Dictation.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/CollapsedView":{"abstract":[{"text":"This view can be used to render a collapsed keyboard,","type":"text"},{"text":" ","type":"text"},{"text":"e.g. when an external keyboard is connected.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/CollapsedView","kind":"symbol","type":"topic","role":"symbol","title":"Keyboard.CollapsedView","url":"\/documentation\/keyboardkit\/keyboard\/collapsedview","navigatorTitle":[{"kind":"identifier","text":"CollapsedView"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CollapsedView","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/state":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","title":"state","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/state","abstract":[{"type":"text","text":"Keyboard-specific state."}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","preciseIdentifier":"s:11KeyboardKit0A0V","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"s:11KeyboardKit0A0V5StateC","kind":"typeIdentifier"}]},"Feature-AI.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg","traits":["1x","light"]}],"alt":"Feature Icon","type":"image","identifier":"Feature-AI.jpg"},"Feature-Localization.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg","traits":["1x","light"]}],"identifier":"Feature-Localization.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","type":"topic","url":"\/documentation\/keyboardkit\/autocomplete-article","kind":"article","images":[{"type":"card","identifier":"Feature-Autocomplete.jpg"}],"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}]},"Feature-Actions.jpg":{"type":"image","identifier":"Feature-Actions.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}]},"Feature-Fonts.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg","traits":["1x","light"]}],"alt":"Feature Icon","type":"image","identifier":"Feature-Fonts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardSettings/isAutoCollapseKeyboardEnabled":{"url":"\/documentation\/keyboardkit\/keyboardsettings\/isautocollapsekeyboardenabled","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/isAutoCollapseKeyboardEnabled","abstract":[{"text":"Whether to auto-collapse the keyboard when an external keyboard is connected.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isAutoCollapseKeyboardEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isAutoCollapseKeyboardEnabled","kind":"symbol"},"Feature-External.jpg":{"alt":null,"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg","traits":["1x","light"]}],"identifier":"Feature-External.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","images":[{"type":"card","identifier":"Feature-AI.jpg"}],"kind":"article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ExternalKeyboardContext/isEnabledOnSimulator":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnabledOnSimulator","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","title":"isEnabledOnSimulator","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExternalKeyboardContext\/isEnabledOnSimulator","abstract":[{"text":"Whether the context is enabled on simulator.","type":"text"}],"kind":"symbol","url":"\/documentation\/keyboardkit\/externalkeyboardcontext\/isenabledonsimulator","type":"topic"},"Feature-Navigation.jpg":{"alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Navigation.jpg"}],"identifier":"Feature-Navigation.jpg","type":"image"},"Feature-Emojis.jpg":{"identifier":"Feature-Emojis.jpg","alt":"Feature Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg"}]},"Feature-Layout.jpg":{"alt":"Feature Icon","identifier":"Feature-Layout.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Layout.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","title":"Input","url":"\/documentation\/keyboardkit\/input-article","images":[{"type":"card","identifier":"Feature-Input.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Layout-Article":{"title":"Layout","url":"\/documentation\/keyboardkit\/layout-article","kind":"article","images":[{"identifier":"Feature-Layout.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/emojis-article","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","title":"Emojis","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"kind":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","role":"article","images":[{"identifier":"Feature-Host.jpg","type":"card"}],"title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro lets you define and use a host application."}],"url":"\/documentation\/keyboardkit\/host-article"},"Feature-Autocomplete.jpg":{"type":"image","identifier":"Feature-Autocomplete.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"Feature-Clipboard.jpg":{"type":"image","identifier":"Feature-Clipboard.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg","traits":["1x","light"]}],"alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/actions-article","role":"article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"title":"Actions"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"url":"\/documentation\/keyboardkit\/clipboard-article","abstract":[{"text":"This article describes KeyboardKit’s clipboard support.","type":"text"}],"images":[{"type":"card","identifier":"Feature-Clipboard.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","title":"Clipboard","type":"topic","kind":"article","role":"article"},"Feature-App.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg"}],"alt":"Feature Icon","identifier":"Feature-App.jpg","type":"image"},"Feature-Input.jpg":{"type":"image","alt":"Feature Icon","identifier":"Feature-Input.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ExternalKeyboardContext":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ExternalKeyboardContext","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExternalKeyboardContext","title":"ExternalKeyboardContext","url":"\/documentation\/keyboardkit\/externalkeyboardcontext","abstract":[{"text":"This context can be used to keep track of if an external","type":"text"},{"type":"text","text":" "},{"type":"text","text":"keyboard is connected to the device."}],"navigatorTitle":[{"text":"ExternalKeyboardContext","kind":"identifier"}],"type":"topic"},"Feature-Feedback.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg","traits":["1x","light"]}],"identifier":"Feature-Feedback.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"kind":"symbol","title":"KeyboardView","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ExternalKeyboardContext/isExternalKeyboardConnected":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isExternalKeyboardConnected","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ExternalKeyboardContext\/isExternalKeyboardConnected","type":"topic","url":"\/documentation\/keyboardkit\/externalkeyboardcontext\/isexternalkeyboardconnected","kind":"symbol","title":"isExternalKeyboardConnected","abstract":[{"text":"Whether an external keyboard is connected.","type":"text"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"Feature-Callouts.jpg":{"type":"image","identifier":"Feature-Callouts.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg","traits":["1x","light"]}]},"Feature-Host.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg","traits":["1x","light"]}],"identifier":"Feature-Host.jpg","type":"image"},"keyboard-collapsedview":{"type":"image","identifier":"keyboard-collapsedview","alt":"Collapsed View","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/keyboard-collapsedview.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"url":"\/documentation\/keyboardkit\/dictation-article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","type":"topic","abstract":[{"text":"This article describes KeyboardKit’s custom font support.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/fonts-article","role":"article","images":[{"type":"card","identifier":"Feature-Fonts.jpg"}],"title":"Fonts"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","role":"article","kind":"article","title":"App Utilities","url":"\/documentation\/keyboardkit\/app-article","type":"topic","images":[{"type":"card","identifier":"Feature-App.jpg"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"url":"\/documentation\/keyboardkit\/feedback-article","type":"topic","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"title":"Feedback","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","title":"Callouts","type":"topic","images":[{"identifier":"Feature-Callouts.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"text":"This article describes the KeyboardKit callout engine.","type":"text"}],"role":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article"],"generated":true}]}]}]}