{"topicSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontContext","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontSettings"],"title":"Types","anchor":"Types"}],"kind":"article","sections":[],"abstract":[{"type":"text","text":"This article describes KeyboardKit’s custom font support."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"]}],"metadata":{"role":"article","images":[{"identifier":"Feature-Fonts.jpg","type":"card"}],"modules":[{"name":"KeyboardKit"}],"roleHeading":"Article","title":"Fonts"},"primaryContentSections":[{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit makes it easy to apply a custom "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/UnicodeFont"},{"type":"text","text":", which lets users type with a different font than the standard system font."}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"👑 KeyboardKit Pro unlocks custom font capabilities for licenses that include the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/fonts"},{"type":"text","text":" feature. This feature is "},{"type":"strong","inlineContent":[{"text":"NOT","type":"text"}]},{"type":"text","text":" part of the standard license tiers and must be enabled with a "},{"identifier":"https:\/\/keyboardkit.com","type":"reference","isActive":true},{"text":".","type":"text"}]}],"type":"aside","name":"Important"},{"anchor":"Namespace","text":"Namespace","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"KeyboardKit has an "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts","isActive":true},{"text":" namespace with font-related types.","type":"text"}],"type":"paragraph"},{"anchor":"Context","text":"Context","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has an ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontContext","type":"reference","isActive":true},{"text":" that can be used to enable custom keyboard fonts, and that has auto-persisted ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontContext\/settings","type":"reference","isActive":true},{"text":" values.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit automatically creates an instance of this class, injects it into ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","type":"reference","isActive":true},{"text":" and also injects it into the view hierarchy environment.","type":"text"}]},{"type":"heading","level":2,"text":"Settings","anchor":"Settings"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontSettings","isActive":true,"type":"reference"},{"text":" type with font-related settings like ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontSettings\/font","type":"reference","isActive":true},{"text":", and ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontSettings\/isFontUnderlined","type":"reference","isActive":true},{"text":", which lets users type with a custom font.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The context "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontContext\/settings","isActive":true},{"type":"text","text":" is used by default. KeyboardKit Pro unlocks a feature-specific "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/SettingsScreen","isActive":true},{"type":"text","text":" that can be used to handle these settings."}]},{"anchor":"Models","type":"heading","level":2,"text":"Models"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/UnicodeFont","type":"reference","isActive":true},{"text":" enum defines all currently supported unicode fonts. It has a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/UnicodeFont\/transformKeyboardLayout(_:options:)","type":"reference","isActive":true},{"text":" function that can be used to transform a layout with a font-specific Unicode representation.","type":"text"}]},{"anchor":"%F0%9F%91%91-KeyboardKit-Pro","type":"heading","level":2,"text":"👑 KeyboardKit Pro"},{"anchor":"Screens","type":"heading","level":3,"text":"Screens"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro’s ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/fonts","type":"reference","isActive":true},{"text":" feature unlocks a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts","type":"reference","isActive":true},{"text":".","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/SettingsScreen","type":"reference","isActive":true},{"text":" that can be used to pick a custom keyboard font, which is then automatically applied to the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"These views and utilities require a KeyboardKit Pro license that unlocks the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/fonts","isActive":true,"type":"reference"},{"type":"text","text":" feature. The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/SettingsScreen","isActive":true,"type":"reference"},{"text":" also requires the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/settingsScreens"},{"type":"text","text":" feature."}]}],"style":"important","type":"aside","name":"Important"},{"type":"tabNavigator","tabs":[{"content":[{"type":"row","columns":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"fonts-settingsscreen","type":"image"}]}],"size":1},{"content":[{"inlineContent":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts","isActive":true},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/SettingsScreen","isActive":true},{"type":"text","text":" can be used to pick a custom font."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen","isActive":true},{"type":"text","text":" template will automatically link to this screen if the current license unlocks the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/fonts","isActive":true},{"type":"text","text":" feature."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This screen can be customized with the following view modifiers:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/fontSettingsScreenFonts(_:)","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/fontSettingsScreenLocalization(_:)","isActive":true}]}]}],"type":"unorderedList"}],"size":1}],"numberOfColumns":2}],"title":"Settings Screen"},{"content":[{"type":"row","columns":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"keyboardview-font","type":"image"}]}],"size":1},{"content":[{"inlineContent":[{"type":"text","text":"By setting the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontSettings","isActive":true},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontSettings\/font","isActive":true},{"type":"text","text":", the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","isActive":true},{"type":"text","text":" will automatically apply the font."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"When typing, the selected unicode font will be used to send text with that font to the proxy."}],"type":"paragraph"}],"size":1}],"numberOfColumns":2}],"title":"Keyboard View"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkit\/fonts-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkit\/fonts-article"]}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/FontContext/settings":{"type":"topic","abstract":[{"text":"Auto-persisted font settings.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FontSettings","preciseIdentifier":"s:11KeyboardKit12FontSettingsV"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontContext\/settings","title":"settings","role":"symbol","url":"\/documentation\/keyboardkit\/fontcontext\/settings"},"Feature-Essentials.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Essentials.jpg"},"Feature-AI.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-AI.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/fontSettingsScreenFonts(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fontSettingsScreenFonts"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit5FontsV","text":"Fonts"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit5FontsV11UnicodeFontO","text":"UnicodeFont"},{"kind":"text","text":"]) -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/fontSettingsScreenFonts(_:)","abstract":[{"type":"text","text":"Apply a custom set of fonts to list in font settings."}],"role":"symbol","title":"fontSettingsScreenFonts(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/fontsettingsscreenfonts(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","url":"\/documentation\/keyboardkit\/app-article","images":[{"identifier":"Feature-App.jpg","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"role":"article","title":"App Utilities","kind":"article","type":"topic"},"Feature-Fonts.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg"}],"type":"image","alt":null,"identifier":"Feature-Fonts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/fontSettingsScreenLocalization(_:)":{"type":"topic","abstract":[{"text":"Apply a custom screen localization.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fontSettingsScreenLocalization"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Fonts","preciseIdentifier":"s:11KeyboardKit5FontsV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SettingsScreenLocalization","preciseIdentifier":"s:11KeyboardKit5FontsV26SettingsScreenLocalizationV"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/fontSettingsScreenLocalization(_:)","title":"fontSettingsScreenLocalization(_:)","role":"symbol","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/fontsettingsscreenlocalization(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/FontSettings/font":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Fonts","preciseIdentifier":"s:11KeyboardKit5FontsV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"UnicodeFont","preciseIdentifier":"s:11KeyboardKit5FontsV11UnicodeFontO"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The currently selected font."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontSettings\/font","role":"symbol","title":"font","url":"\/documentation\/keyboardkit\/fontsettings\/font"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"images":[{"type":"card","identifier":"Feature-AI.jpg"}],"type":"topic"},"keyboardview-font":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/keyboardview-font.jpg"}],"type":"image","alt":"KeyboardView with fonts","identifier":"keyboardview-font"},"Feature-Callouts.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Callouts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"url":"\/documentation\/keyboardkit\/host-article","abstract":[{"text":"This article describes how KeyboardKit Pro can identify and use the host application.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Host Application","images":[{"type":"card","identifier":"Feature-Host.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article"},"Feature-Host.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Host.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts":{"url":"\/documentation\/keyboardkit\/fonts","title":"Fonts","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This is a namespace for font-related types."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fonts"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Fonts"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/FontSettings/isFontUnderlined":{"url":"\/documentation\/keyboardkit\/fontsettings\/isfontunderlined","kind":"symbol","abstract":[{"type":"text","text":"Whether the selected font should be underlined."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontSettings\/isFontUnderlined","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFontUnderlined","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","title":"isFontUnderlined"},"Feature-Feedback.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Feedback.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts/UnicodeFont":{"url":"\/documentation\/keyboardkit\/fonts\/unicodefont","navigatorTitle":[{"text":"UnicodeFont","kind":"identifier"}],"abstract":[{"type":"text","text":"This enum defines all supported Unicode fonts."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnicodeFont","kind":"identifier"}],"role":"symbol","type":"topic","title":"Fonts.UnicodeFont","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/UnicodeFont"},"https://keyboardkit.com":{"url":"https:\/\/keyboardkit.com","titleInlineContent":[{"type":"text","text":"custom license agreement"}],"type":"link","identifier":"https:\/\/keyboardkit.com","title":"custom license agreement"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Gestures-Article":{"type":"topic","images":[{"identifier":"Feature-Gestures.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"role":"article","title":"Gestures","url":"\/documentation\/keyboardkit\/gestures-article"},"Feature-Dictation.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Dictation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"abstract":[{"type":"text","text":"This article describes KeyboardKit’s clipboard support."}],"kind":"article","title":"Clipboard","type":"topic","images":[{"identifier":"Feature-Clipboard.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","url":"\/documentation\/keyboardkit\/clipboard-article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-Article":{"url":"\/documentation\/keyboardkit\/essentials-article","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"images":[{"identifier":"Feature-Essentials.jpg","type":"card"}],"type":"topic","title":"Essentials","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"role":"article","type":"topic","kind":"article","title":"Callouts","images":[{"type":"card","identifier":"Feature-Callouts.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/HomeScreen":{"url":"\/documentation\/keyboardkit\/keyboardapp\/homescreen","navigatorTitle":[{"text":"HomeScreen","kind":"identifier"}],"abstract":[{"type":"text","text":"This screen can be used as the main home screen of a"},{"type":"text","text":" "},{"type":"text","text":"keyboard app that should look like iOS Settings."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HomeScreen","kind":"identifier"}],"role":"symbol","type":"topic","title":"KeyboardApp.HomeScreen","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen"},"Feature-Input.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Input.jpg"},"fonts-settingsscreen":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/fonts-settingsscreen.jpg"}],"type":"image","alt":"Fonts.SettingsScreen","identifier":"fonts-settingsscreen"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","url":"\/documentation\/keyboardkit\/feedback-article","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"role":"article","title":"Feedback","kind":"article","type":"topic"},"Feature-Clipboard.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Clipboard.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-KeyboardView":{"type":"topic","images":[{"identifier":"Feature-Essentials-KeyboardView.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","kind":"article","title":"Essentials - KeyboardView","abstract":[{"type":"text","text":"This article describes the essential "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"type":"text","text":" and how to use and configure it."}],"url":"\/documentation\/keyboardkit\/essentials-keyboardview"},"Feature-External.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-External.jpg"},"Feature-Gestures.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Gestures.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Gestures.jpg"},"Feature-Essentials-KeyboardView.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials-KeyboardView.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Essentials-KeyboardView.jpg"},"Feature-App.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-App.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","title":"KeyboardView","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","role":"symbol","kind":"symbol","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"url":"\/documentation\/keyboardkit\/input-article","abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Input","images":[{"identifier":"Feature-Input.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"},"Feature-Autocomplete.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Autocomplete.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts/UnicodeFont/transformKeyboardLayout(_:options:)":{"url":"\/documentation\/keyboardkit\/fonts\/unicodefont\/transformkeyboardlayout(_:options:)","kind":"symbol","abstract":[{"type":"text","text":"Transform a keyboard layout for the Unicode font."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/UnicodeFont\/transformKeyboardLayout(_:options:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformKeyboardLayout","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A6LayoutV","text":"KeyboardLayout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit5FontsV","text":"Fonts","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit5FontsV17UnicodeFontOptionO","text":"UnicodeFontOption","kind":"typeIdentifier"},{"text":"]) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A6LayoutV","text":"KeyboardLayout","kind":"typeIdentifier"}],"type":"topic","title":"transformKeyboardLayout(_:options:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts/SettingsScreen":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SettingsScreen","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/SettingsScreen","abstract":[{"type":"text","text":"This screen can be used as a settings screen for any"},{"text":" ","type":"text"},{"text":"font-related keyboard settings, and as a font picker.","type":"text"}],"role":"symbol","title":"Fonts.SettingsScreen","url":"\/documentation\/keyboardkit\/fonts\/settingsscreen","navigatorTitle":[{"text":"SettingsScreen","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/state":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Keyboard","preciseIdentifier":"s:11KeyboardKit0A0V"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"s:11KeyboardKit0A0V5StateC"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Keyboard-specific state."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","role":"symbol","title":"state","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/state"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/FontContext":{"url":"\/documentation\/keyboardkit\/fontcontext","kind":"symbol","abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"type":"text","text":"for font-related functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontContext","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FontContext"}],"navigatorTitle":[{"kind":"identifier","text":"FontContext"}],"type":"topic","title":"FontContext"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/settingsScreens":{"abstract":[],"kind":"symbol","title":"ProFeature.settingsScreens","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/settingsScreens","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settingsScreens","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/profeature\/settingsscreens","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"url":"\/documentation\/keyboardkit\/external-keyboards-article","kind":"article","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","role":"article","type":"topic","images":[{"identifier":"Feature-External.jpg","type":"card"}],"title":"External Keyboards"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/fonts":{"url":"\/documentation\/keyboardkit\/profeature\/fonts","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/fonts","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fonts","kind":"identifier"}],"type":"topic","title":"ProFeature.fonts"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"url":"\/documentation\/keyboardkit\/emojis-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"role":"article","type":"topic","kind":"article","title":"Emojis","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","title":"Dictation","role":"article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"url":"\/documentation\/keyboardkit\/dictation-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/FontSettings":{"url":"\/documentation\/keyboardkit\/fontsettings","kind":"symbol","abstract":[{"text":"This type has auto-persisted font settings.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/FontSettings","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FontSettings"}],"navigatorTitle":[{"text":"FontSettings","kind":"identifier"}],"type":"topic","title":"FontSettings"},"Feature-Emojis.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Emojis.jpg"},"Feature-Actions.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Actions.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","url":"\/documentation\/keyboardkit\/actions-article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"role":"article","kind":"article","title":"Actions","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"url":"\/documentation\/keyboardkit\/features-articles","abstract":[{"type":"text","text":"This article links to the various KeyboardKit features."}],"role":"collectionGroup","type":"topic","title":"Features","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"url":"\/documentation\/keyboardkit\/autocomplete-article","title":"Autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"],"generated":true}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}