{"topicSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/GestureButton","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/GestureButtonConfiguration","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/GestureButtonTimer","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/GestureButtonScrollState","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DragGestureHandler"],"title":"Types","anchor":"Types"}],"kind":"article","sections":[],"abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"],"generated":true}],"metadata":{"modules":[{"name":"KeyboardKit"}],"title":"Gestures","images":[{"type":"card","identifier":"Feature-Gestures.jpg"}],"role":"article","roleHeading":"Article"},"primaryContentSections":[{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Native iOS keyboards use more gestures than you may at first think. For instance, keys can be pressed, released, long pressed, etc., the spacebar can be dragged to move the cursor, shift keys can be double tapped to toggle caps-lock, etc."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"These gestures can be complicated to set up, but KeyboardKit provides you with a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Gesture","isActive":true},{"text":" enum that defines all supported gestures, as well as views and extensions that trigger rich gesture actions that can be handled by a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"type":"heading","level":2,"text":"Namespace","anchor":"Namespace"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures","isActive":true,"type":"reference"},{"text":" namespace with gesture-related types, like ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/GestureButton","isActive":true,"type":"reference"},{"text":". It however doesn’t contain the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Gesture","isActive":true,"type":"reference"},{"text":" enum, which is an essential type that is defined in the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard","isActive":true,"type":"reference"},{"text":" namespace.","type":"text"}]},{"type":"heading","level":2,"text":"View Modifiers","anchor":"View-Modifiers"},{"type":"paragraph","inlineContent":[{"text":"You can use the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardButtonGestureConfiguration(_:)","isActive":true,"type":"reference"},{"text":" view modifier to customize the keyboard gestures, for instance the double-tap timeout, the long press delay, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can use the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardButtonGestures(for:actionHandler:repeatTimer:calloutContext:isPressed:isGestureAutoCancellable:scrollState:releaseOutsideTolerance:secondaryActionState:)","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"view modifier to apply custom keyboard gesture to any view:","type":"text"}]},{"type":"codeListing","code":["Text(\"😀\")","    .keyboardButtonGestures(","        for: .emoji(\"😀\"),","        ...","    )"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"This will apply all standard gestures for the provided action. You can also set up completely custom gesture actions with this modifier.","type":"text"}]},{"type":"heading","level":2,"text":"Drag gesture handlers","anchor":"Drag-gesture-handlers"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DragGestureHandler","isActive":true,"type":"reference"},{"text":" protocol that handles drag gestures. For instance, a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures\/SpacebarDragGestureHandler","isActive":true,"type":"reference"},{"text":" handles drag gestures on the spacebar.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkit\/gestures-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkit\/gestures-article"]}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-KeyboardView":{"type":"topic","images":[{"identifier":"Feature-Essentials-KeyboardView.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","kind":"article","title":"Essentials - KeyboardView","abstract":[{"type":"text","text":"This article describes the essential "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"type":"text","text":" and how to use and configure it."}],"url":"\/documentation\/keyboardkit\/essentials-keyboardview"},"Feature-Feedback.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg"}],"identifier":"Feature-Feedback.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/GestureButtonScrollState":{"url":"\/documentation\/keyboardkit\/gesturebuttonscrollstate","navigatorTitle":[{"kind":"identifier","text":"GestureButtonScrollState"}],"abstract":[{"type":"text","text":"This class can be used to coordinate gesture state for a"},{"type":"text","text":" "},{"type":"text","text":"scroll view and any nested "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/GestureButton"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GestureButtonScrollState"}],"role":"symbol","type":"topic","kind":"symbol","title":"GestureButtonScrollState","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/GestureButtonScrollState"},"Feature-External.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg"}],"identifier":"Feature-External.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction":{"url":"\/documentation\/keyboardkit\/keyboardaction","navigatorTitle":[{"text":"KeyboardAction","kind":"identifier"}],"abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"type":"text","text":" "},{"type":"text","text":"a namespace for action-related types."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardAction","kind":"identifier"}],"role":"symbol","type":"topic","title":"KeyboardAction","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction"},"Feature-Callouts.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg","traits":["1x","light"]}],"identifier":"Feature-Callouts.jpg","type":"image","alt":"Feature Icon"},"Feature-App.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg"}],"identifier":"Feature-App.jpg","type":"image","alt":"Feature Icon"},"Feature-Input.jpg":{"type":"image","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg","traits":["1x","light"]}],"identifier":"Feature-Input.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/GestureButton":{"url":"\/documentation\/keyboardkit\/gesturebutton","navigatorTitle":[{"kind":"identifier","text":"GestureButton"}],"abstract":[{"type":"text","text":"This button can be used to trigger gesture-based actions."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GestureButton"}],"role":"symbol","type":"topic","kind":"symbol","title":"GestureButton","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/GestureButton"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard":{"url":"\/documentation\/keyboardkit\/keyboard","navigatorTitle":[{"text":"Keyboard","kind":"identifier"}],"abstract":[{"type":"text","text":"This namespace contains essential keyboard-related types."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Keyboard","kind":"identifier"}],"role":"symbol","type":"topic","title":"Keyboard","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard"},"Feature-Fonts.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg"}],"identifier":"Feature-Fonts.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"url":"\/documentation\/keyboardkit\/input-article","abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Input","images":[{"identifier":"Feature-Input.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/GestureButtonConfiguration":{"url":"\/documentation\/keyboardkit\/gesturebuttonconfiguration","title":"GestureButtonConfiguration","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/GestureButtonConfiguration","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This configuration can be used to setup a gesture button."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GestureButtonConfiguration"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GestureButtonConfiguration"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardActionHandler":{"url":"\/documentation\/keyboardkit\/keyboardactionhandler","navigatorTitle":[{"kind":"identifier","text":"KeyboardActionHandler"}],"abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"text":" ","type":"text"},{"type":"text","text":"handle triggered "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","type":"reference"},{"type":"text","text":" events."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardActionHandler"}],"role":"symbol","type":"topic","kind":"symbol","title":"KeyboardActionHandler","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler"},"Feature-Dictation.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}],"identifier":"Feature-Dictation.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","title":"KeyboardView","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","role":"symbol","kind":"symbol","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/Gesture":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Gesture","url":"\/documentation\/keyboardkit\/keyboard\/gesture","abstract":[{"text":"This enum defines various keyboard gestures that can","type":"text"},{"text":" ","type":"text"},{"text":"be used to interact with a keyboard.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"Gesture","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Gesture","kind":"identifier"}],"title":"Keyboard.Gesture","kind":"symbol","type":"topic"},"Feature-Actions.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg","traits":["1x","light"]}],"identifier":"Feature-Actions.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","url":"\/documentation\/keyboardkit\/feedback-article","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"role":"article","title":"Feedback","kind":"article","type":"topic"},"Feature-Emojis.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg"}],"identifier":"Feature-Emojis.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"url":"\/documentation\/keyboardkit\/external-keyboards-article","kind":"article","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","role":"article","type":"topic","images":[{"identifier":"Feature-External.jpg","type":"card"}],"title":"External Keyboards"},"Feature-Essentials.jpg":{"identifier":"Feature-Essentials.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"url":"\/documentation\/keyboardkit\/host-article","abstract":[{"text":"This article describes how KeyboardKit Pro can identify and use the host application.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Host Application","images":[{"type":"card","identifier":"Feature-Host.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"Feature-AI.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon","identifier":"Feature-AI.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Gestures/SpacebarDragGestureHandler":{"url":"\/documentation\/keyboardkit\/gestures\/spacebardraggesturehandler","title":"Gestures.SpacebarDragGestureHandler","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures\/SpacebarDragGestureHandler","role":"symbol","kind":"symbol","abstract":[{"text":"This custom gesture handler can handle drag gestures","type":"text"},{"text":" ","type":"text"},{"text":"on the spacebar, that moves the input cursor.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SpacebarDragGestureHandler","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SpacebarDragGestureHandler","kind":"identifier"}]},"Feature-Host.jpg":{"alt":"Feature Icon","type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg","traits":["1x","light"]}],"identifier":"Feature-Host.jpg"},"Feature-Gestures.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Gestures.jpg"}],"type":"image","alt":null,"identifier":"Feature-Gestures.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","url":"\/documentation\/keyboardkit\/app-article","images":[{"identifier":"Feature-App.jpg","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"role":"article","title":"App Utilities","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"images":[{"type":"card","identifier":"Feature-AI.jpg"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardButtonGestureConfiguration(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardButtonGestureConfiguration(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardbuttongestureconfiguration(_:)","abstract":[{"type":"text","text":"Customize the keyboard button gesture configuration."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardButtonGestureConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit26GestureButtonConfigurationV","text":"GestureButtonConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"title":"keyboardButtonGestureConfiguration(_:)","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"abstract":[{"type":"text","text":"This article describes KeyboardKit’s clipboard support."}],"kind":"article","title":"Clipboard","type":"topic","images":[{"identifier":"Feature-Clipboard.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","url":"\/documentation\/keyboardkit\/clipboard-article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"role":"article","type":"topic","kind":"article","title":"Callouts","images":[{"type":"card","identifier":"Feature-Callouts.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"url":"\/documentation\/keyboardkit\/autocomplete-article","title":"Autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Gestures":{"type":"topic","abstract":[{"text":"This namespace contains gesture-related types.","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Gestures","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures","navigatorTitle":[{"text":"Gestures","kind":"identifier"}],"title":"Gestures","role":"symbol","url":"\/documentation\/keyboardkit\/gestures"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/DragGestureHandler":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DragGestureHandler","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/DragGestureHandler","kind":"symbol","title":"DragGestureHandler","abstract":[{"type":"text","text":"This protocol can be implemented by any type that can be"},{"type":"text","text":" "},{"type":"text","text":"used to handle drag gestures."}],"url":"\/documentation\/keyboardkit\/draggesturehandler","navigatorTitle":[{"text":"DragGestureHandler","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"url":"\/documentation\/keyboardkit\/emojis-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"role":"article","type":"topic","kind":"article","title":"Emojis","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","title":"Dictation","role":"article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"url":"\/documentation\/keyboardkit\/dictation-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardButtonGestures(for:actionHandler:repeatTimer:calloutContext:isPressed:isGestureAutoCancellable:scrollState:releaseOutsideTolerance:secondaryActionState:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardButtonGestures"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A6ActionO","text":"KeyboardAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A13ActionHandlerP","text":"KeyboardActionHandler"},{"kind":"text","text":", "},{"kind":"externalParam","text":"repeatTimer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit18GestureButtonTimerC","text":"GestureButtonTimer"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"calloutContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit14CalloutContextC","text":"CalloutContext"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isPressed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"isGestureAutoCancellable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"scrollState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit24GestureButtonScrollStateC","text":"GestureButtonScrollState"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"releaseOutsideTolerance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"secondaryActionState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V","text":"Keyboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V20SwipeDownActionStateV","text":"SwipeDownActionState"},{"kind":"text","text":"?>?) -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardButtonGestures(for:actionHandler:repeatTimer:calloutContext:isPressed:isGestureAutoCancellable:scrollState:releaseOutsideTolerance:secondaryActionState:)","abstract":[{"type":"text","text":"Apply keyboard button gestures that use the provided"},{"type":"text","text":" "},{"type":"codeVoice","code":"actionHandler"},{"type":"text","text":" to trigger gesture actions."}],"role":"symbol","title":"keyboardButtonGestures(for:actionHandler:repeatTimer:calloutContext:isPressed:isGestureAutoCancellable:scrollState:releaseOutsideTolerance:secondaryActionState:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardbuttongestures(for:actionhandler:repeattimer:calloutcontext:ispressed:isgestureautocancellable:scrollstate:releaseoutsidetolerance:secondaryactionstate:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"url":"\/documentation\/keyboardkit\/features-articles","abstract":[{"type":"text","text":"This article links to the various KeyboardKit features."}],"role":"collectionGroup","type":"topic","title":"Features","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/GestureButtonTimer":{"url":"\/documentation\/keyboardkit\/gesturebuttontimer","title":"GestureButtonTimer","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/GestureButtonTimer","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This internal class can be used to repeat an action when"},{"type":"text","text":" "},{"type":"text","text":"a button is kept pressed."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GestureButtonTimer"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GestureButtonTimer"}]},"Feature-Essentials-KeyboardView.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials-KeyboardView.jpg"}],"identifier":"Feature-Essentials-KeyboardView.jpg","type":"image","alt":"Feature Icon"},"Feature-Clipboard.jpg":{"alt":"Feature Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg"}],"identifier":"Feature-Clipboard.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","url":"\/documentation\/keyboardkit\/actions-article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"role":"article","kind":"article","title":"Actions","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-Article":{"url":"\/documentation\/keyboardkit\/essentials-article","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"images":[{"identifier":"Feature-Essentials.jpg","type":"card"}],"type":"topic","title":"Essentials","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"url":"\/documentation\/keyboardkit\/fonts-article","abstract":[{"type":"text","text":"This article describes KeyboardKit’s custom font support."}],"role":"article","type":"topic","title":"Fonts","kind":"article","images":[{"identifier":"Feature-Fonts.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article"},"Feature-Autocomplete.jpg":{"alt":"Feature Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"identifier":"Feature-Autocomplete.jpg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"],"generated":true}],"path":"\/seeAlsoSections"}]}]}