{"kind":"article","seeAlsoSections":[{"title":"Articles","generated":true,"anchor":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides"]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit"]]},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Getting-Started-Article","interfaceLanguage":"swift"},"metadata":{"role":"article","roleHeading":"Article","title":"Getting Started","modules":[{"name":"KeyboardKit"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"This developer guide describes how to get started with KeyboardKit.","type":"text"}],"variants":[{"paths":["\/documentation\/keyboardkit\/getting-started-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/getting-started-article"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"text":"This guide goes through all the steps involved in adding KeyboardKit to your project and setting it up for the main app and its keyboard.","type":"text"}],"type":"paragraph"},{"anchor":"Step-1-Add-KeyboardKit-to-your-project","type":"heading","level":2,"text":"Step 1. Add KeyboardKit to your project"},{"inlineContent":[{"text":"KeyboardKit can be installed with the Swift Package Manager:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":null,"code":["https:\/\/github.com\/KeyboardKit\/KeyboardKit.git"]},{"style":"important","name":"Important","type":"aside","content":[{"inlineContent":[{"text":"KeyboardKit is a binary target and must ONLY be added to the app target. If you add it to any other target, it may crash at runtime.","type":"text"}],"type":"paragraph"}]},{"anchor":"Step-2-Define-app-specific-information","type":"heading","level":2,"text":"Step 2. Define app-specific information"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The easiest way to set up KeyboardKit is with a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","isActive":true,"type":"reference"},{"type":"text","text":" that can define an "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/appGroupId","type":"reference"},{"text":", a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/licenseKey"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/deepLinks-swift.property","type":"reference","isActive":true},{"type":"text","text":", etc."}]},{"type":"codeListing","code":["import KeyboardKit","","extension KeyboardApp {","","    static var myApp: KeyboardApp {","        .init(","            name: \"My App\",","            licenseKey: \"your-license-key\",             \/\/ Unlocks KeyboardKit Pro","            appGroupId: \"group.com.myapp\",              \/\/ Sets up App Group data sync","            locales: .keyboardKitSupported,             \/\/ Sets up the enabled locales","            autocomplete: .init(                        \/\/ Sets up autocomplete addons  ","                nextWordPredictionRequest: .claude(...) \/\/ Sets up AI-based prediction","            ),","            deepLinks: .init(app: \"myapp:\/\/\", ...)      \/\/ Defines how to open the app","        )","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Define this in a file that you add to your app "},{"type":"emphasis","inlineContent":[{"type":"text","text":"and"}]},{"type":"text","text":" keyboard extension, to be able to use it in both targets. See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article"},{"type":"text","text":" for more info."}]},{"text":"Step 3. Set up the keyboard extension","type":"heading","level":2,"anchor":"Step-3-Set-up-the-keyboard-extension"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use KeyboardKit, first make your controller inherit "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController"},{"type":"text","text":" instead of "},{"type":"codeVoice","code":"UIInputViewController"},{"type":"text","text":":"}]},{"type":"codeListing","code":["import KeyboardKit","","class KeyboardController: KeyboardInputViewController {}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"This adds tons of capabilities to the controller, new lifecycle functions, as well as keyboard-specific ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services","isActive":true,"type":"reference"},{"text":" and observable ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can now set up KeyboardKit by calling "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/setupKeyboardKit(for:completion:)","type":"reference"},{"type":"text","text":" in "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/viewWillSetupKeyboardKit()","type":"reference"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"swift","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewWillSetupKeyboardKit() {","        setupKeyboardKit(for: .myApp) { result in","            \/\/ If the result is `.success`, the setup succeeded.","            \/\/ This is where you can setup custom services, etc.","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Setting up KeyboardKit will unlock KeyboardKit Pro if your app defines a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/licenseKey","type":"reference","isActive":true},{"type":"text","text":", or if you have added a license file to the bundle. You can start using KeyboardKit Pro features as soon as the completion is called with a license."}]},{"type":"paragraph","inlineContent":[{"text":"Based on your ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","isActive":true,"type":"reference"},{"text":" the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/setupKeyboardKit(for:completion:)","isActive":true,"type":"reference"},{"text":" function will also set up data sync between the app and keyboard if the app defines an ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/appGroupId","isActive":true,"type":"reference"},{"text":", register ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/deepLinks-swift.property"},{"text":", set up ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article"},{"text":", etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Make sure to not customize "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services","isActive":true},{"type":"text","text":" before the completion block is called, otherwise your changes may be overwritten."}]},{"type":"heading","level":2,"anchor":"Step-4-Set-up-a-custom-keyboard-view-optional","text":"Step 4. Set up a custom keyboard view (optional)"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To replace or customize the default "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","isActive":true,"type":"reference"},{"type":"text","text":", just override "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/viewWillSetupKeyboardView()","isActive":true,"type":"reference"},{"type":"text","text":" and call "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/setupKeyboardView(_:)","isActive":true,"type":"reference"},{"type":"text","text":" with the view that you want to use:"}]},{"type":"codeListing","syntax":"swift","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewWillSetupKeyboardView() {","        setupKeyboardView { [weak self] controller in \/\/ <-- Use weak or unknowned if you must use self!","            CustomKeyboardView(","                services: controller.services","            )","        }","    }","}","","\/\/ Defining a custom view in a separate file keeps your controller clean.","struct CustomKeyboardView: View {","","    var services: Keyboard.Services","","    \/\/ All observable contexts are added to the enviroment.","    @EnvironmentObject private var keyboardContext: KeyboardContext","","    var body: some View {","        if keyboardContext ... {","            \/\/ You can customize your keyboard view for any observable state,","            \/\/ including your own custom observable state.","        } else {","            KeyboardView(","                services: services,","                buttonContent: { $0.view },        \/\/ Use $0.view to use the standard view","                buttonView: { $0.view },           \/\/ The $0 arg has additional properties             ","                collapsedView: { params in params.view },   \/\/ This is the same as $0.view","                emojiKeyboard: { $0.view },        ","                toolbar: { _ in CustomToolbar() }  \/\/ You can customize any view like this","            )","        }","    }","}"]},{"name":"Important","content":[{"inlineContent":[{"text":"Passing the controller into a keyboard view can easily result in a memory leak, if you forget to make the controller reference weak or unowned. The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/setupKeyboardView(_:)","type":"reference"},{"text":" view builder provides an unowned controller reference to avoid memory leaks. If you must refer to your specific controller type, you MUST use ","type":"text"},{"code":"[weak self]","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"[unowned self]","type":"codeVoice"},{"text":"!","type":"text"}],"type":"paragraph"}],"type":"aside","style":"important"},{"type":"heading","level":2,"anchor":"Step-5-Set-up-the-main-app-optional","text":"Step 5. Set up the main app (optional)"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The main app can be used to display the enabled and Full Access status of your keyboard, link to Settings, etc. It’s also a great place for keyboard settings, since it has more space than the keyboard extension."}]},{"type":"paragraph","inlineContent":[{"text":"The easiest way to set up an app target is to use ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAppView","isActive":true,"type":"reference"},{"text":" as the root view, with the same ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","isActive":true,"type":"reference"},{"text":" as the keyboard:","type":"text"}]},{"syntax":"swift","code":["@main","struct MyApp: App {","","    var body: some Scene {","        WindowGroup {","            KeyboardAppView(for: .myApp) {","                ContentView() \/\/ <-- Your specific app root","            }","        }","    }","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"This will set up your main app the same way as your keyboard, register your license before rendering the content view, etc. You can use any content view, and use any Pro features since the view is redrawn when a license is registered."}],"type":"paragraph"},{"inlineContent":[{"text":"See ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","isActive":true,"type":"reference"},{"text":" for more information about how to easily set up a full-blown keyboard app with KeyboardKit Pro’s various app utilities.","type":"text"}],"type":"paragraph"},{"text":"Step 6. Customize state & services (optional)","anchor":"Step-6-Customize-state--services-optional","level":2,"type":"heading"},{"inlineContent":[{"text":"The main ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","type":"reference"},{"text":" provides you with keyboard ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services","type":"reference"},{"text":", to let you build great keyboards.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can change any observable state at any time, to affect the keyboard. For instance, changing the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/keyboardType","type":"reference","isActive":true},{"type":"text","text":" will automatically redraw the keyboard. Each observable context also has its own auto-persisted "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/settings","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"KeyboardKit will inject all observable context types into the environment. This means that you can access them from anywhere, like this:"}],"type":"paragraph"},{"syntax":"swift","code":["struct CustomView: View {","","    @EnvironmentObject private var keyboardContext: KeyboardContext","    ","    var body: some View {","        ...","    }","}"],"type":"codeListing"},{"inlineContent":[{"text":"You can replace any services with custom implementations. For instance, here we replace the standard ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler","isActive":true,"type":"reference"},{"text":":","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["class KeyboardViewController: KeyboardInputViewController {","","    override func viewWillSetupKeyboardKit() {","        services.actionHandler = CustomActionHandler(controller: self)","        setupKeyboardKit(for: .myApp) { ... }","    }","}","","class CustomActionHandler: KeyboardAction.StandardActionHandler {","","    open override func handle(_ action: KeyboardAction) {","        if action == .space {","            print(\"Pressed space!\")","        }","        super.handle(action) ","    }","}"],"type":"codeListing"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Any customizations that rely on Pro features must be made within the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/setupKeyboardKit(for:completion:)"},{"type":"text","text":" completion."}]}],"style":"important","name":"Important","type":"aside"},{"type":"heading","text":"Bonus - Setting up KeyboardKit as a package dependency","level":2,"anchor":"Bonus-Setting-up-KeyboardKit-as-a-package-dependency"},{"inlineContent":[{"type":"text","text":"To set up KeyboardKit as a package dependency, just add it to your package’s dependencies list and link it to any target that needs it."}],"type":"paragraph"},{"type":"codeListing","code":["...","dependencies: [","    .package(","        url: \"https:\/\/github.com\/KeyboardKit\/KeyboardKit.git\",","        .upToNextMajor(from: \"10.0.0\")","    )","],","targets: [","    .target(","        name: \"MyPackage\",","        dependencies: [\"KeyboardKit\"]","    )","]"],"syntax":"swift"},{"name":"Important","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Since KeyboardKit is a binary package, you don’t have to link it to targets that use "},{"type":"emphasis","inlineContent":[{"type":"text","text":"your"}]},{"type":"text","text":" package, but a target "},{"type":"emphasis","inlineContent":[{"type":"text","text":"must"}]},{"type":"text","text":" update "},{"type":"strong","inlineContent":[{"text":"runpath search paths","type":"text"}]},{"type":"text","text":" under its Build Settings. Use "},{"type":"strong","inlineContent":[{"text":"@executable_path\/Frameworks","type":"text"}]},{"type":"text","text":" for apps and "},{"type":"strong","inlineContent":[{"type":"text","text":"@executable_path\/..\/..\/Frameworks"}]},{"type":"text","text":" for keyboards. Failing to set the search paths will cause a runtime crash."}],"type":"paragraph"}],"style":"important"},{"type":"heading","text":"That’s it!","level":2,"anchor":"Thats-it"},{"inlineContent":[{"text":"You should now have a fully functional keyboard extension and companion app, which you can customize even further to fit your needs. For more information, see the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","isActive":true,"type":"reference"},{"text":" article, as well as the other articles in this documentation.","type":"text"}],"type":"paragraph"},{"type":"thematicBreak"}],"kind":"content"}],"sections":[],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController":{"navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"role":"symbol","title":"KeyboardInputViewController","abstract":[{"text":"This is the main input controller type that is used in a","type":"text"},{"text":" ","type":"text"},{"text":"KeyboardKit-based keyboard extension.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/keyboardType":{"abstract":[{"text":"The keyboard type that is currently used.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/keyboardType","title":"keyboardType","url":"\/documentation\/keyboardkit\/keyboardcontext\/keyboardtype","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V"},{"text":".","kind":"text"},{"text":"KeyboardType","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V0A4TypeO"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/viewWillSetupKeyboardKit()":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/viewWillSetupKeyboardKit()","abstract":[{"type":"text","text":"This function is called when the controller is about"},{"type":"text","text":" "},{"text":"to set up KeyboardKit.","type":"text"}],"kind":"symbol","title":"viewWillSetupKeyboardKit()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillSetupKeyboardKit"},{"kind":"text","text":"()"}],"role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/viewwillsetupkeyboardkit()"},"Feature-Dictation.jpg":{"type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}],"alt":"Feature Icon","identifier":"Feature-Dictation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/state":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/state","title":"state","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/state","abstract":[{"type":"text","text":"Keyboard-specific state."}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","preciseIdentifier":"s:11KeyboardKit0A0V","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"s:11KeyboardKit0A0V5StateC","kind":"typeIdentifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","title":"KeyboardApp","navigatorTitle":[{"text":"KeyboardApp","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/keyboardapp","abstract":[{"type":"text","text":"This type can be used to define important properties for"},{"type":"text","text":" "},{"type":"text","text":"your app, and is also a namespace for app-based features."}],"role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardApp","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/setupKeyboardKit(for:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupKeyboardKit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardApp","preciseIdentifier":"s:11KeyboardKit0A3AppV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"License","preciseIdentifier":"s:11KeyboardKit7Licensea"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Set up KeyboardKit for the provided app.","type":"text"}],"type":"topic","title":"setupKeyboardKit(for:completion:)","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/setupkeyboardkit(for:completion:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/setupKeyboardKit(for:completion:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/licenseKey":{"title":"licenseKey","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/keyboardkit\/keyboardapp\/licensekey","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/licenseKey","type":"topic","role":"symbol","abstract":[{"text":"Your license key, if any.","type":"text"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Developer-Guides":{"url":"\/documentation\/keyboardkit\/developer-guides","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides","role":"collectionGroup","title":"Developer Guides","type":"topic","abstract":[{"type":"text","text":"This article links to various developer guides, include feature customiation guides."}]},"Feature-Essentials.jpg":{"identifier":"Feature-Essentials.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"Feature-App.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-App.jpg","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardActionHandler":{"navigatorTitle":[{"text":"KeyboardActionHandler","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardActionHandler","type":"topic","url":"\/documentation\/keyboardkit\/keyboardactionhandler","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardActionHandler","kind":"identifier"}],"role":"symbol","title":"KeyboardActionHandler","abstract":[{"text":"This protocol can be implemented by any classes that can","type":"text"},{"text":" ","type":"text"},{"text":"handle triggered ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","isActive":true,"type":"reference"},{"text":" events.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/services":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/services","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"services","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V"},{"text":".","kind":"text"},{"text":"Services","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V8ServicesC"}],"abstract":[{"type":"text","text":"Keyboard-specific services."}],"role":"symbol","title":"services","kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/services"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/appGroupId":{"url":"\/documentation\/keyboardkit\/keyboardapp\/appgroupid","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/appGroupId","abstract":[{"type":"text","text":"The app’s App Group identifier, if any."}],"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appGroupId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"appGroupId","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-KeyboardView":{"kind":"article","type":"topic","url":"\/documentation\/keyboardkit\/essentials-keyboardview","title":"Essentials - KeyboardView","abstract":[{"type":"text","text":"This article describes the essential "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"type":"text","text":" and how to use and configure it."}],"images":[{"type":"card","identifier":"Feature-Essentials-KeyboardView.jpg"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction":{"title":"KeyboardAction","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAction"}],"abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"type":"text","text":" "},{"type":"text","text":"a namespace for action-related types."}],"url":"\/documentation\/keyboardkit\/keyboardaction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/setupKeyboardView(_:)":{"type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/setupkeyboardview(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupKeyboardView"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Content"},{"kind":"text","text":">(("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKit@objc(cs)KeyboardInputViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Content","preciseIdentifier":"s:11KeyboardKit0A19InputViewControllerC05setupaD0yyxACc7SwiftUI0D0RzlF7ContentL_xmfp"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/setupKeyboardView(_:)","abstract":[{"text":"Set up KeyboardKit with a custom view and an unowned","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","isActive":true,"type":"reference"},{"text":" reference.","type":"text"}],"kind":"symbol","title":"setupKeyboardView(_:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/viewWillSetupKeyboardView()":{"url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/viewwillsetupkeyboardview()","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/viewWillSetupKeyboardView()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillSetupKeyboardView"},{"kind":"text","text":"()"}],"title":"viewWillSetupKeyboardView()","type":"topic","abstract":[{"type":"text","text":"This function is called when the controller is about"},{"type":"text","text":" "},{"type":"text","text":"to set up or redraw the main keyboard view."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/settings":{"url":"\/documentation\/keyboardkit\/keyboardcontext\/settings","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/settings","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settings","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A8SettingsV","text":"KeyboardSettings","kind":"typeIdentifier"}],"title":"settings","type":"topic","kind":"symbol","abstract":[{"text":"Auto-persisted keyboard settings.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"kind":"symbol","title":"KeyboardView","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/deepLinks-swift.property":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"deepLinks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A3AppV9DeepLinksV","text":"DeepLinks"},{"kind":"text","text":"?"}],"role":"symbol","title":"deepLinks","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/deepLinks-swift.property","abstract":[{"type":"text","text":"App-specific deep links, if any."}],"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardapp\/deeplinks-swift.property","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","type":"topic","url":"\/documentation\/keyboardkit\/essentials-article","kind":"article","images":[{"identifier":"Feature-Essentials.jpg","type":"card"}],"role":"article","title":"Essentials","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"url":"\/documentation\/keyboardkit\/dictation-article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","role":"article","kind":"article","title":"App Utilities","url":"\/documentation\/keyboardkit\/app-article","type":"topic","images":[{"type":"card","identifier":"Feature-App.jpg"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}]},"Feature-Essentials-KeyboardView.jpg":{"alt":"Feature Icon","type":"image","identifier":"Feature-Essentials-KeyboardView.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials-KeyboardView.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAppView":{"type":"topic","url":"\/documentation\/keyboardkit\/keyboardappview","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardAppView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardAppView"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAppView","abstract":[{"type":"text","text":"This view can be used as the root view of a keyboard app,"},{"type":"text","text":" "},{"type":"text","text":"to set up KeyboardKit for a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","type":"reference","isActive":true},{"text":".","type":"text"}],"kind":"symbol","title":"KeyboardAppView","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Developer-Guides"],"generated":true,"anchor":"Articles"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/fragments","value":[{"kind":"identifier","text":"KeyboardInputViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/navigatorTitle","value":[{"text":"KeyboardInputViewController","kind":"identifier"}]}]}]}