{"variants":[{"paths":["\/documentation\/keyboardkit\/host-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkit\/host-article"]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"metadata":{"roleHeading":"Article","modules":[{"name":"KeyboardKit"}],"title":"Host Application","images":[{"type":"card","identifier":"Feature-Host.jpg"}],"role":"article"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit lets you get the bundle ID of the host application that is using the keyboard. This may be of interest for many reasons, e.g. to vary the style or functionality of the keyboard based on the currently active app."}]},{"type":"aside","style":"important","name":"Important","content":[{"inlineContent":[{"text":"👑 KeyboardKit Pro unlocks additional ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication","isActive":true,"type":"reference"},{"text":" tools for licenses that include the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/hostApplication","type":"reference"},{"text":" feature, to integrate with certain apps. You can sign up for KeyboardKit Pro from the ","type":"text"},{"isActive":true,"identifier":"https:\/\/keyboardkit.com","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]},{"type":"heading","level":2,"text":"Host Application Bundle Identifier","anchor":"Host-Application-Bundle-Identifier"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","isActive":true,"type":"reference"},{"text":" has a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/hostApplicationBundleId","isActive":true,"type":"reference"},{"text":" property that resolves the bundle ID of the app that is currently using the keyboard.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The controller will automatically sync this property to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext"},{"type":"text","text":"’s auto-persisted "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/hostApplicationBundleId"},{"type":"text","text":" property, which can be used by your main app target to see in which app your keyboard was last used."}]},{"type":"paragraph","inlineContent":[{"text":"You can use the context’s’ ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/hostApplicationBundleIdSyncDate"},{"type":"text","text":" to check when the ID was last synced, to see if it’s still relevant. You can manually reset the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/hostApplicationBundleId"},{"type":"text","text":" value if you know that it’s not, e.g. if the app launched without a deep link."}]},{"type":"heading","level":2,"text":"👑 KeyboardKit Pro","anchor":"%F0%9F%91%91-KeyboardKit-Pro"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro unlocks ways to identify specific apps, using a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication"},{"type":"text","text":" type that defines many popular apps."}]},{"text":"Host Application","anchor":"Host-Application","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro adds a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider\/hostApplication"},{"text":" property to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext"},{"text":", which maps the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/hostApplicationBundleId"},{"text":" to any of the following known applications:","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"App Store, Apple Calendar, Apple Clock, Apple FaceTime, Apple Files, Apple Find My, Apple Health, Apple Maps, Apple Messages, Apple Music, Apple Music Classical, Apple News, Apple Notes, Apple Numbers, Apple Pages, Apple Photos, Apple Podcasts, Apple Reminders, Apple Settings, Apple Shortcuts, Apple Translate, Apple TV, Apple Weather, Amazon Prime, Bambu Handy, Bloomberg, Blue Sky, Brave, Bolt, ChatGPT, CityMapper, Discord, Disney+, Dropbox, DuckDuckGo, Duolingo, Facebook, Gmail, Goodnotes, Google Assistant, Google Calendar, Google Chat, Google Chrome, Google Docs, Google Drive, Google Home, Google Maps, Instagram, Ivory, KeyboardKit Demo, LinkedIn, Meetup, Messenger, Microsoft OneDrive, Netflix, 1Password, Signal, Slack, Snapchat, Spotify, Telegram, Trello, Twitch, X (Twitter), WhatsApp, Uber, YouTube"}]},{"inlineContent":[{"type":"text","text":"Once you have resolved a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication"},{"type":"text","text":", you can open it with "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication\/openWithAction(_:)"},{"type":"text","text":" or "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication\/openWithActionHandler(_:)","isActive":true,"type":"reference"},{"text":" and access additional information about the app from the app value.","type":"text"}],"type":"paragraph"},{"text":"How to add more host applications","anchor":"How-to-add-more-host-applications","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"You can use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider\/hostApplication(withAdditionalApps:)"},{"text":" function to inject custom applications, if the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider\/hostApplication"},{"text":" collection lacks certain apps that you want to support.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can also ","type":"text"},{"identifier":"info@keyboardkit.com","type":"reference","isActive":true},{"text":" if you want to add new a app to the list. We need the name of the app, the bundle ID (can be found with the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/hostApplicationBundleId","type":"reference","isActive":true},{"text":" in your keyboard) and a deep link that opens the app.","type":"text"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","interfaceLanguage":"swift"},"kind":"article","seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"]}],"abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro can identify and use the host application."}],"topicSections":[{"title":"Types","anchor":"Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider"]}],"references":{"Feature-Essentials.jpg":{"identifier":"Feature-Essentials.jpg","alt":"Feature Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials.jpg"}]},"Feature-AI.jpg":{"identifier":"Feature-AI.jpg","alt":"Feature Icon","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardHostApplicationProvider/hostApplication":{"type":"topic","abstract":[{"text":"Get an app within ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication\/allCases","type":"reference","isActive":true},{"text":" ","type":"text"},{"text":"that matches the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider\/hostApplicationBundleId","type":"reference","isActive":true},{"text":", if any.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostApplication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A15HostApplicationV","text":"KeyboardHostApplication"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider\/hostApplication","title":"hostApplication","role":"symbol","url":"\/documentation\/keyboardkit\/keyboardhostapplicationprovider\/hostapplication"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/hostApplicationBundleId":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/hostApplicationBundleId","url":"\/documentation\/keyboardkit\/keyboardcontext\/hostapplicationbundleid","abstract":[{"text":"The bundle ID of the keyboard host application.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostApplicationBundleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","title":"hostApplicationBundleId","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","url":"\/documentation\/keyboardkit\/app-article","images":[{"identifier":"Feature-App.jpg","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"role":"article","title":"App Utilities","kind":"article","type":"topic"},"Feature-Fonts.jpg":{"identifier":"Feature-Fonts.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg"}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardHostApplicationProvider":{"url":"\/documentation\/keyboardkit\/keyboardhostapplicationprovider","navigatorTitle":[{"text":"KeyboardHostApplicationProvider","kind":"identifier"}],"abstract":[{"text":"This protocol can be implemented by any class that has a","type":"text"},{"type":"text","text":" "},{"text":"host application ID that can be mapped to an application.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardHostApplicationProvider","kind":"identifier"}],"role":"symbol","type":"topic","title":"KeyboardHostApplicationProvider","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardHostApplicationProvider/hostApplicationBundleId":{"type":"topic","abstract":[{"text":"The host application bundle ID to resolve.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hostApplicationBundleId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider\/hostApplicationBundleId","title":"hostApplicationBundleId","role":"symbol","required":true,"url":"\/documentation\/keyboardkit\/keyboardhostapplicationprovider\/hostapplicationbundleid"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"images":[{"type":"card","identifier":"Feature-AI.jpg"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/hostApplicationBundleIdSyncDate":{"url":"\/documentation\/keyboardkit\/keyboardcontext\/hostapplicationbundleidsyncdate","abstract":[{"text":"A date when ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/hostApplicationBundleId","type":"reference","isActive":true},{"text":" was last set.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostApplicationBundleIdSyncDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","kind":"symbol","title":"hostApplicationBundleIdSyncDate","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/hostApplicationBundleIdSyncDate"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"url":"\/documentation\/keyboardkit\/fonts-article","abstract":[{"type":"text","text":"This article describes KeyboardKit’s custom font support."}],"role":"article","type":"topic","title":"Fonts","kind":"article","images":[{"identifier":"Feature-Fonts.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article"},"Feature-Callouts.jpg":{"identifier":"Feature-Callouts.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg"}],"type":"image","alt":"Feature Icon"},"Feature-Host.jpg":{"identifier":"Feature-Host.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg"}],"type":"image","alt":null},"Feature-Feedback.jpg":{"identifier":"Feature-Feedback.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg"}],"type":"image","alt":"Feature Icon"},"https://keyboardkit.com":{"url":"https:\/\/keyboardkit.com","identifier":"https:\/\/keyboardkit.com","title":"KeyboardKit website","type":"link","titleInlineContent":[{"text":"KeyboardKit website","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Gestures-Article":{"type":"topic","images":[{"identifier":"Feature-Gestures.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"role":"article","title":"Gestures","url":"\/documentation\/keyboardkit\/gestures-article"},"Feature-Dictation.jpg":{"identifier":"Feature-Dictation.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg"}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardHostApplication/allCases":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"allCases","kind":"identifier"},{"text":": [`Self`","kind":"text"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication\/allCases","title":"allCases","role":"symbol","url":"\/documentation\/keyboardkit\/keyboardhostapplication\/allcases"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"abstract":[{"type":"text","text":"This article describes KeyboardKit’s clipboard support."}],"kind":"article","title":"Clipboard","type":"topic","images":[{"identifier":"Feature-Clipboard.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","url":"\/documentation\/keyboardkit\/clipboard-article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-Article":{"url":"\/documentation\/keyboardkit\/essentials-article","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"images":[{"identifier":"Feature-Essentials.jpg","type":"card"}],"type":"topic","title":"Essentials","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"role":"article","type":"topic","kind":"article","title":"Callouts","images":[{"type":"card","identifier":"Feature-Callouts.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article"},"Feature-Input.jpg":{"identifier":"Feature-Input.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg"}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","url":"\/documentation\/keyboardkit\/feedback-article","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"role":"article","title":"Feedback","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext":{"title":"KeyboardContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"type":"text","text":"for the core keyboard functionality."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"type":"topic","url":"\/documentation\/keyboardkit\/keyboardcontext","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardHostApplicationProvider/hostApplication(withAdditionalApps:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider\/hostApplication(withAdditionalApps:)","url":"\/documentation\/keyboardkit\/keyboardhostapplicationprovider\/hostapplication(withadditionalapps:)","abstract":[{"text":"Get an app within ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication\/allCases"},{"type":"text","text":" "},{"text":"that matches the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplicationProvider\/hostApplicationBundleId","isActive":true,"type":"reference"},{"type":"text","text":", if any."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hostApplication","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAdditionalApps","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A15HostApplicationV","text":"KeyboardHostApplication","kind":"typeIdentifier"},{"text":"]) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A15HostApplicationV","text":"KeyboardHostApplication","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"hostApplication(withAdditionalApps:)","kind":"symbol","type":"topic"},"Feature-Clipboard.jpg":{"identifier":"Feature-Clipboard.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg"}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-KeyboardView":{"type":"topic","images":[{"identifier":"Feature-Essentials-KeyboardView.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","kind":"article","title":"Essentials - KeyboardView","abstract":[{"type":"text","text":"This article describes the essential "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"type":"text","text":" and how to use and configure it."}],"url":"\/documentation\/keyboardkit\/essentials-keyboardview"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardHostApplication/openWithActionHandler(_:)":{"url":"\/documentation\/keyboardkit\/keyboardhostapplication\/openwithactionhandler(_:)","kind":"symbol","abstract":[{"text":"Try to open the app with an action handler.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication\/openWithActionHandler(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openWithActionHandler"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"KeyboardActionHandler","preciseIdentifier":"s:11KeyboardKit0A13ActionHandlerP"},{"kind":"text","text":")"}],"type":"topic","title":"openWithActionHandler(_:)"},"info@keyboardkit.com":{"url":"info@keyboardkit.com","identifier":"info@keyboardkit.com","title":"reach out to us","type":"link","titleInlineContent":[{"text":"reach out to us","type":"text"}]},"Feature-External.jpg":{"identifier":"Feature-External.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg"}],"type":"image","alt":"Feature Icon"},"Feature-Gestures.jpg":{"identifier":"Feature-Gestures.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Gestures.jpg"}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardHostApplication/openWithAction(_:)":{"url":"\/documentation\/keyboardkit\/keyboardhostapplication\/openwithaction(_:)","kind":"symbol","abstract":[{"text":"Try to open the app with a URL action.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication\/openWithAction(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openWithAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI13OpenURLActionV","text":"OpenURLAction"},{"kind":"text","text":")"}],"type":"topic","title":"openWithAction(_:)"},"Feature-Essentials-KeyboardView.jpg":{"identifier":"Feature-Essentials-KeyboardView.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials-KeyboardView.jpg"}],"type":"image","alt":"Feature Icon"},"Feature-App.jpg":{"identifier":"Feature-App.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg"}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","title":"KeyboardView","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","role":"symbol","kind":"symbol","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"url":"\/documentation\/keyboardkit\/input-article","abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Input","images":[{"identifier":"Feature-Input.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"},"Feature-Autocomplete.jpg":{"identifier":"Feature-Autocomplete.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"url":"\/documentation\/keyboardkit\/external-keyboards-article","kind":"article","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","role":"article","type":"topic","images":[{"identifier":"Feature-External.jpg","type":"card"}],"title":"External Keyboards"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"url":"\/documentation\/keyboardkit\/emojis-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"role":"article","type":"topic","kind":"article","title":"Emojis","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController":{"title":"KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This is the main input controller type that is used in a","type":"text"},{"text":" ","type":"text"},{"text":"KeyboardKit-based keyboard extension.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","title":"Dictation","role":"article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"url":"\/documentation\/keyboardkit\/dictation-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/hostApplication":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"hostApplication","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/hostApplication","title":"ProFeature.hostApplication","role":"symbol","url":"\/documentation\/keyboardkit\/profeature\/hostapplication"},"Feature-Actions.jpg":{"identifier":"Feature-Actions.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}],"type":"image","alt":"Feature Icon"},"Feature-Emojis.jpg":{"identifier":"Feature-Emojis.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg"}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"url":"\/documentation\/keyboardkit\/features-articles","abstract":[{"type":"text","text":"This article links to the various KeyboardKit features."}],"role":"collectionGroup","type":"topic","title":"Features","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","url":"\/documentation\/keyboardkit\/actions-article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"role":"article","kind":"article","title":"Actions","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardHostApplication":{"url":"\/documentation\/keyboardkit\/keyboardhostapplication","navigatorTitle":[{"text":"KeyboardHostApplication","kind":"identifier"}],"abstract":[{"type":"text","text":"This enum defines a list of known host applications that"},{"text":" ","type":"text"},{"type":"text","text":"can be used to identify various application."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardHostApplication","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"KeyboardHostApplication","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/hostApplicationBundleId":{"abstract":[{"type":"text","text":"The bundle ID of the host application, if any, or if"},{"type":"text","text":" "},{"type":"text","text":"within a host app, the bundle id of the main bundle."}],"kind":"symbol","title":"hostApplicationBundleId","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/hostApplicationBundleId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostApplicationBundleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/hostapplicationbundleid","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"url":"\/documentation\/keyboardkit\/autocomplete-article","title":"Autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article"],"generated":true}]},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/title","op":"replace","value":"KeyboardInputViewController"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"KeyboardInputViewController"}]},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"KeyboardInputViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}