{"topicSections":[{"anchor":"Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInput","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTextField","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTextView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Vietnamese","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/VietnameseInputEngine"],"title":"Types"}],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkit\/input-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkit\/input-article"]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"type":"text","text":"Custom keyboard extensions use a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy","isActive":true},{"type":"text","text":" to modify text, move the text input cursor, get input-related info, etc."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This proxy points to the currently selected text field in the currently active app, and will "},{"type":"emphasis","inlineContent":[{"text":"not","type":"text"}]},{"type":"text","text":" detect if you focus on a text field inside the keyboard extension. Text that you type will still be sent to the currently active app."}],"type":"paragraph"},{"type":"aside","style":"important","name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"👑 KeyboardKit Pro unlocks "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/textInput"},{"type":"text","text":" views that let you type within the keyboard, and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Vietnamese"},{"type":"text","text":" support that let you type with TELEX, VNI and VIQR. You can sign up for KeyboardKit Pro from the "},{"isActive":true,"type":"reference","identifier":"https:\/\/keyboardkit.com"},{"type":"text","text":"."}]}]},{"level":2,"text":"Text routing","anchor":"Text-routing","type":"heading"},{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext","isActive":true,"type":"reference"},{"type":"text","text":" has a custom "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/textInputProxy","type":"reference","isActive":true},{"text":" that can be set to route text to any other text field or custom proxy. You can always access the original text document proxy with the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/originalTextDocumentProxy","isActive":true,"type":"reference"},{"text":" property.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","isActive":true,"type":"reference"},{"text":" has similar properties, but you should avoid referring to it and passing it within your code.","type":"text"}],"type":"paragraph"},{"text":"👑 KeyboardKit Pro","level":2,"type":"heading","anchor":"%F0%9F%91%91-KeyboardKit-Pro"},{"inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTextField","type":"reference","isActive":true},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTextView","type":"reference","isActive":true},{"type":"text","text":" that let you type directly within a keyboard extension, by automatically registering themselves as "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/textInputProxy","type":"reference","isActive":true},{"type":"text","text":" when they get focus"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"KeyboardKit Pro also unlocks additional "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInput"},{"type":"text","text":" support, like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Vietnamese"},{"type":"text","text":", which lets you to type in locale-specific ways."}],"type":"paragraph"},{"text":"🇻🇳 Vietnamese Input","level":3,"type":"heading","anchor":"%F0%9F%87%BB%F0%9F%87%B3-Vietnamese-Input"},{"inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Vietnamese"},{"type":"text","text":" namespace, with Vietnamese-related types, as well as a  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/VietnameseInputEngine"},{"type":"text","text":" that supports typing with TELEX, VIQR, and VNI."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"KeyboardKit Pro will automatically use the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/VietnameseInputEngine"},{"type":"text","text":" when applicable. You can also use these types as standalone features to implement Vietnamese input support elsewhere."}],"type":"paragraph"},{"text":"Input Views","level":3,"type":"heading","anchor":"Input-Views"},{"type":"tabNavigator","tabs":[{"title":"KeyboardTextField","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTextField","isActive":true},{"type":"text","text":" component wraps a native text field and can be used for single-line text input inside a keyboard extension."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTextView"},{"type":"text","text":" component wraps a native text view and can be used for multi-line text input inside a keyboard extension."}],"type":"paragraph"}],"title":"KeyboardTextView"}]},{"inlineContent":[{"text":"Both views support ","type":"text"},{"type":"codeVoice","code":"@FocusState"},{"text":", and have a custom ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/focused(_:doneButton:)","isActive":true,"type":"reference"},{"type":"text","text":" view modifier that lets you provide a custom done button that slides in when the view is focused, and can be tapped to end editing:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["struct CustomKeyboardToolbar: View {","","    unowned var controller: KeyboardInputViewController","","    @State ","    private var text = \"\"","","    @FocusState ","    private var isTextFieldFocused","","    var body: some View {","        if hasFullAccess {","            KeyboardTextField(","                \"Type here...\", ","                text: $text, ","                controller: controller,","                config: configureTextField,","                onSubmit: handleReturnKeyPressed    ","                \/\/ Use onSubmit: to detect the return key.","                \/\/ The onSubmit(...) view modifier doesn't work.","            )","            .focused($isTextFieldFocused) {","                Image(systemName: \"xmark.circle.fill\")","            }","        }","    }","    ","    func configureTextField(_ view: UITextField) {","        \/\/ Configure the underlying view in any way you want.","    }","    ","    func handleReturnKeyPressed() {","        print(\"Return key pressed!\")","    }","}"]},{"style":"important","type":"aside","name":"Important","content":[{"inlineContent":[{"type":"text","text":"These views require Full Access, due to an iOS bug that causes a crash when using them while Full Access is disabled. They will automatically disable themselves when Full Access is disabled."}],"type":"paragraph"}]}]}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit input engine."}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article"]}],"metadata":{"modules":[{"name":"KeyboardKit"}],"roleHeading":"Article","role":"article","title":"Input","images":[{"identifier":"Feature-Input.jpg","type":"card"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext":{"abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"type":"text","text":"for the core keyboard functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext","kind":"symbol","type":"topic","role":"symbol","title":"KeyboardContext","url":"\/documentation\/keyboardkit\/keyboardcontext","navigatorTitle":[{"text":"KeyboardContext","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardContext","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController":{"navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"role":"symbol","title":"KeyboardInputViewController","abstract":[{"text":"This is the main input controller type that is used in a","type":"text"},{"text":" ","type":"text"},{"text":"KeyboardKit-based keyboard extension.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/textInputProxy":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textInputProxy","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)UITextDocumentProxy","kind":"typeIdentifier","text":"UITextDocumentProxy"},{"kind":"text","text":"?"}],"role":"symbol","title":"textInputProxy","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/textInputProxy","abstract":[{"type":"text","text":"A custom text proxy to which text can be routed."}],"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardcontext\/textinputproxy","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Localization-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit localization engine."}],"url":"\/documentation\/keyboardkit\/localization-article","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","title":"Localization","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","role":"article","kind":"article","title":"App Utilities","url":"\/documentation\/keyboardkit\/app-article","type":"topic","images":[{"type":"card","identifier":"Feature-App.jpg"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Navigation-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/navigation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"images":[{"identifier":"Feature-Navigation.jpg","type":"card"}],"kind":"article","title":"Navigation","role":"article"},"Feature-Dictation.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Dictation.jpg"},"Feature-AI.jpg":{"identifier":"Feature-AI.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardTextField":{"navigatorTitle":[{"kind":"identifier","text":"KeyboardTextField"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTextField","type":"topic","url":"\/documentation\/keyboardkit\/keyboardtextfield","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardTextField"}],"role":"symbol","title":"KeyboardTextField","abstract":[{"text":"This view can be used to type within keyboard extensions.","type":"text"}]},"Feature-Localization.jpg":{"alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg"}],"type":"image","identifier":"Feature-Localization.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/textInput":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/textInput","title":"ProFeature.textInput","url":"\/documentation\/keyboardkit\/profeature\/textinput","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textInput","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","type":"topic","url":"\/documentation\/keyboardkit\/autocomplete-article","kind":"article","images":[{"type":"card","identifier":"Feature-Autocomplete.jpg"}],"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}]},"Feature-Actions.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Actions.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInput":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInput","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInput","title":"KeyboardInput","url":"\/documentation\/keyboardkit\/keyboardinput","abstract":[{"type":"text","text":"This is a namespace for input related types."}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardInput"}],"type":"topic"},"Feature-Fonts.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Fonts.jpg"},"Feature-External.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-External.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","images":[{"type":"card","identifier":"Feature-AI.jpg"}],"kind":"article","type":"topic","role":"article"},"Feature-Navigation.jpg":{"alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Navigation.jpg"}],"type":"image","identifier":"Feature-Navigation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Vietnamese":{"navigatorTitle":[{"kind":"identifier","text":"Vietnamese"}],"type":"topic","kind":"symbol","title":"Vietnamese","abstract":[{"type":"text","text":"This is a namespace for Vietnamese types."}],"url":"\/documentation\/keyboardkit\/vietnamese","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Vietnamese","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Vietnamese"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/focused(_:doneButton:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focused"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"DoneButton"},{"kind":"text","text":">("},{"preciseIdentifier":"s:7SwiftUI10FocusStateV","kind":"typeIdentifier","text":"FocusState"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":">."},{"preciseIdentifier":"s:7SwiftUI10FocusStateV7BindingV","kind":"typeIdentifier","text":"Binding"},{"kind":"text","text":", "},{"kind":"externalParam","text":"doneButton"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:7SwiftUI4ViewP11KeyboardKitE7focused_10doneButtonQrAA10FocusStateV7BindingVySb_G_qd__yctAaBRd__lFQO04DoneH0qd__mfp","kind":"typeIdentifier","text":"DoneButton"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"}],"role":"symbol","title":"focused(_:doneButton:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/focused(_:doneButton:)","abstract":[{"type":"text","text":"Apply a "},{"type":"codeVoice","code":"FocusState"},{"type":"text","text":" with a "},{"code":"doneButton","type":"codeVoice"},{"type":"text","text":" that slides"},{"type":"text","text":" "},{"type":"text","text":"in and out as the view gets and loses focus."}],"kind":"symbol","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/focused(_:donebutton:)","type":"topic"},"Feature-Emojis.jpg":{"identifier":"Feature-Emojis.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg"}],"type":"image"},"Feature-Layout.jpg":{"alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Layout.jpg"}],"type":"image","identifier":"Feature-Layout.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Layout-Article":{"title":"Layout","url":"\/documentation\/keyboardkit\/layout-article","kind":"article","images":[{"identifier":"Feature-Layout.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/emojis-article","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","title":"Emojis","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"kind":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","role":"article","images":[{"identifier":"Feature-Host.jpg","type":"card"}],"title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro lets you define and use a host application."}],"url":"\/documentation\/keyboardkit\/host-article"},"Feature-Autocomplete.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Autocomplete.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"Feature-Clipboard.jpg":{"identifier":"Feature-Clipboard.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/actions-article","role":"article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"title":"Actions"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"url":"\/documentation\/keyboardkit\/clipboard-article","abstract":[{"text":"This article describes KeyboardKit’s clipboard support.","type":"text"}],"images":[{"type":"card","identifier":"Feature-Clipboard.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","title":"Clipboard","type":"topic","kind":"article","role":"article"},"Feature-App.jpg":{"alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg"}],"type":"image","identifier":"Feature-App.jpg"},"Feature-Input.jpg":{"alt":null,"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Input.jpg"},"Feature-Feedback.jpg":{"identifier":"Feature-Feedback.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"title":"External Keyboards","url":"\/documentation\/keyboardkit\/external-keyboards-article","images":[{"type":"card","identifier":"Feature-External.jpg"}],"kind":"article","type":"topic","role":"article"},"https://keyboardkit.com":{"url":"https:\/\/keyboardkit.com","titleInlineContent":[{"text":"KeyboardKit website","type":"text"}],"title":"KeyboardKit website","type":"link","identifier":"https:\/\/keyboardkit.com"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/originalTextDocumentProxy":{"abstract":[{"type":"text","text":"The original text document proxy."}],"url":"\/documentation\/keyboardkit\/keyboardcontext\/originaltextdocumentproxy","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/originalTextDocumentProxy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalTextDocumentProxy"},{"kind":"text","text":": "},{"text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy","kind":"typeIdentifier"}],"kind":"symbol","title":"originalTextDocumentProxy","role":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"Feature-Callouts.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Callouts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/VietnameseInputEngine":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VietnameseInputEngine"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/VietnameseInputEngine","title":"VietnameseInputEngine","url":"\/documentation\/keyboardkit\/vietnameseinputengine","abstract":[{"type":"text","text":"This Vietnamese typing engine can be used to resolve any"},{"type":"text","text":" "},{"type":"text","text":"diacritic replacements when typing in Vietnamese."}],"navigatorTitle":[{"kind":"identifier","text":"VietnameseInputEngine"}],"type":"topic"},"Feature-Host.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg"}],"type":"image","alt":"Feature Icon","identifier":"Feature-Host.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardTextView":{"abstract":[{"type":"text","text":"This view can be used to type within keyboard extensions."}],"kind":"symbol","title":"KeyboardTextView","role":"symbol","navigatorTitle":[{"text":"KeyboardTextView","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/keyboardtextview","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardTextView","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTextView"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"url":"\/documentation\/keyboardkit\/dictation-article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","type":"topic","abstract":[{"text":"This article describes KeyboardKit’s custom font support.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/fonts-article","role":"article","images":[{"type":"card","identifier":"Feature-Fonts.jpg"}],"title":"Fonts"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy":{"title":"UITextDocumentProxy","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"abstract":[],"kind":"symbol","url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy","navigatorTitle":[{"kind":"identifier","text":"UITextDocumentProxy"}],"type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"url":"\/documentation\/keyboardkit\/feedback-article","type":"topic","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"title":"Feedback","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","title":"Callouts","type":"topic","images":[{"identifier":"Feature-Callouts.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"text":"This article describes the KeyboardKit callout engine.","type":"text"}],"role":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article"],"generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/fragments","value":[{"text":"KeyboardInputViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/navigatorTitle","value":[{"text":"KeyboardInputViewController","kind":"identifier"}]}]}]}