{"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardModel"},"abstract":[{"type":"text","text":"This protocol is an alias for other protocols that model"},{"type":"text","text":" "},{"type":"text","text":"types in the framework should conform to."}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkit\/keyboardmodel"]}],"metadata":{"title":"KeyboardModel","roleHeading":"Protocol","externalID":"s:11KeyboardKit0A5ModelP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardModel","kind":"identifier"}],"navigatorTitle":[{"text":"KeyboardModel","kind":"identifier"}],"role":"symbol","modules":[{"name":"KeyboardKit"}],"symbolKind":"protocol"},"seeAlsoSections":[{"title":"Essential Types","generated":true,"anchor":"Essential-Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardBehavior","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardController","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardModel","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Decodable","preciseIdentifier":"s:Se","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Encodable","preciseIdentifier":"s:SE","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Hashable","preciseIdentifier":"s:SH","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Sendable","preciseIdentifier":"s:s8SendableP","kind":"typeIdentifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/Se","doc:\/\/com.keyboardkit.KeyboardKit\/SE","doc:\/\/com.keyboardkit.KeyboardKit\/SQ","doc:\/\/com.keyboardkit.KeyboardKit\/SH","doc:\/\/com.keyboardkit.KeyboardKit\/s8SendableP","doc:\/\/com.keyboardkit.KeyboardKit\/s16SendableMetatypeP"]},{"type":"inheritedBy","kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/PickerValue"]},{"type":"conformingTypes","kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/NextWordPredictionMethod","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Suggestion","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/SuggestionType","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarItemStyle","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarSeparatorStyle","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarStyle","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/CalloutStyle","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/Clip","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/AuthorizationStatus","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationState","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/IndicatorStyle","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressViewLocalization","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressViewStyle","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressViewStyle\/ButtonVisibility","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ServiceError","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiment","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/Audio","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/AudioConfiguration","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/AudioConfiguration\/CustomFeedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/Haptic","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/HapticConfiguration","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/HapticConfiguration\/CustomFeedback","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/UnicodeFont","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/UnicodeFontOption","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/AddedLocale","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/AutocapitalizationType","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/BackspaceRange","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ButtonBorderStyle","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ButtonShadowStyle","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/DeviceType","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Diacritic","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/DockEdge","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Gesture","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/InputToolbarDisplayMode","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/InputToolbarType","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/InputType","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/InterfaceOrientation","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/KeyboardCase","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/KeyboardType","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LayoutType","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LayoutType\/NestedReference","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ReturnKeyType","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/SpacebarDragSensitivity","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/SpacebarLongPressBehavior","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/SpacebarMenuType","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ToolbarStyle","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/DeepLinks-swift.struct","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/OpenReason","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/EnabledLocalesDataSource-swift.enum","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardFont","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardFont\/FontType","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardFont\/FontWeight","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/Item","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/ItemRow","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/ItemSize","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/ItemWidth","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme\/Author-swift.struct","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme\/ButtonType"]}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/DictationState":{"title":"Dictation.DictationState","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DictationState","kind":"identifier"}],"abstract":[{"type":"text","text":"This enum defines the states that a dictation engine"},{"type":"text","text":" "},{"type":"text","text":"can be in."}],"kind":"symbol","url":"\/documentation\/keyboardkit\/dictation\/dictationstate","navigatorTitle":[{"text":"DictationState","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/InputSet/Item":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Item","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/Item","navigatorTitle":[{"text":"Item","kind":"identifier"}],"abstract":[{"text":"This struct represents an input set item, that has a","type":"text"},{"text":" ","type":"text"},{"text":"neutral, uppercased and lowercased input variant.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/keyboardlayout\/inputset\/item","title":"KeyboardLayout.InputSet.Item"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard":{"type":"topic","url":"\/documentation\/keyboardkit\/keyboard","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Keyboard"}],"navigatorTitle":[{"kind":"identifier","text":"Keyboard"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard","abstract":[{"type":"text","text":"This namespace contains essential keyboard-related types."}],"kind":"symbol","title":"Keyboard","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext":{"abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"type":"text","text":"for the core keyboard functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext","kind":"symbol","type":"topic","role":"symbol","title":"KeyboardContext","url":"\/documentation\/keyboardkit\/keyboardcontext","navigatorTitle":[{"text":"KeyboardContext","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardContext","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardBehavior":{"type":"topic","role":"symbol","abstract":[{"text":"This protocol can be implemented by any classes that can","type":"text"},{"text":" ","type":"text"},{"text":"define keyboard-specific behaviors.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardBehavior","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardBehavior"}],"title":"KeyboardBehavior","kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardbehavior","navigatorTitle":[{"kind":"identifier","text":"KeyboardBehavior"}]},"doc://com.keyboardkit.KeyboardKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/SQ","title":"Swift.Equatable"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/InputType":{"url":"\/documentation\/keyboardkit\/keyboard\/inputtype","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/InputType","abstract":[{"text":"This enum defines all supported text input types.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"InputType","kind":"identifier"}],"title":"Keyboard.InputType","kind":"symbol","navigatorTitle":[{"text":"InputType","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/ProgressViewStyle":{"abstract":[{"text":"This style can be used to modify the visual style of","type":"text"},{"text":" ","type":"text"},{"text":"the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressView","isActive":true,"type":"reference"},{"text":" component.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressViewStyle","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/keyboardkit\/dictation\/progressviewstyle","title":"Dictation.ProgressViewStyle","navigatorTitle":[{"kind":"identifier","text":"ProgressViewStyle"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressViewStyle"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/ToolbarStyle":{"title":"Keyboard.ToolbarStyle","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ToolbarStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToolbarStyle"}],"abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"type":"text","text":"the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Toolbar"},{"type":"text","text":" component."}],"url":"\/documentation\/keyboardkit\/keyboard\/toolbarstyle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ToolbarStyle"}],"type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/LayoutType/NestedReference":{"url":"\/documentation\/keyboardkit\/keyboard\/layouttype\/nestedreference","abstract":[{"text":"This enum defines references to main layout types to","type":"text"},{"text":" ","type":"text"},{"text":"allow layout types to refer other main types.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LayoutType\/NestedReference","title":"Keyboard.LayoutType.NestedReference","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NestedReference"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NestedReference"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/LayoutType":{"url":"\/documentation\/keyboardkit\/keyboard\/layouttype","type":"topic","title":"Keyboard.LayoutType","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LayoutType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayoutType"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LayoutType"}],"abstract":[{"text":"This enum defines supported keyboard layout types.","type":"text"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/InputToolbarDisplayMode":{"url":"\/documentation\/keyboardkit\/keyboard\/inputtoolbardisplaymode","kind":"symbol","navigatorTitle":[{"text":"InputToolbarDisplayMode","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/InputToolbarDisplayMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InputToolbarDisplayMode","kind":"identifier"}],"title":"Keyboard.InputToolbarDisplayMode","type":"topic","abstract":[{"text":"This enum defines various input toolbar modes, which","type":"text"},{"text":" ","type":"text"},{"text":"can be used to set what to show in the toolbar.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/ToolbarStyle":{"navigatorTitle":[{"kind":"identifier","text":"ToolbarStyle"}],"type":"topic","kind":"symbol","title":"Autocomplete.ToolbarStyle","abstract":[{"text":"This style can be used to modify the visual style of","type":"text"},{"text":" ","type":"text"},{"text":"the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Toolbar","type":"reference"},{"text":" component.","type":"text"}],"url":"\/documentation\/keyboardkit\/autocomplete\/toolbarstyle","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToolbarStyle"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts/UnicodeFont":{"kind":"symbol","navigatorTitle":[{"text":"UnicodeFont","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/UnicodeFont","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnicodeFont","kind":"identifier"}],"role":"symbol","abstract":[{"text":"This enum defines all supported Unicode fonts.","type":"text"}],"title":"Fonts.UnicodeFont","url":"\/documentation\/keyboardkit\/fonts\/unicodefont"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/InputToolbarType":{"navigatorTitle":[{"text":"InputToolbarType","kind":"identifier"}],"title":"Keyboard.InputToolbarType","abstract":[{"text":"This enum describes different kinds of input toolbar","type":"text"},{"text":" ","type":"text"},{"text":"types, to allow for settings persistency.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InputToolbarType","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/keyboard\/inputtoolbartype","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/InputToolbarType"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/SuggestionType":{"type":"topic","url":"\/documentation\/keyboardkit\/autocomplete\/suggestiontype","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/SuggestionType","title":"Autocomplete.SuggestionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SuggestionType"}],"role":"symbol","navigatorTitle":[{"text":"SuggestionType","kind":"identifier"}],"abstract":[{"text":"This enum defines every autocomplete suggestion type","type":"text"},{"text":" ","type":"text"},{"text":"that can be returned by an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService"},{"text":".","type":"text"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/Se"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/BackspaceRange":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BackspaceRange","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/BackspaceRange","url":"\/documentation\/keyboardkit\/keyboard\/backspacerange","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"This enum defines how much the backspace key deletes."}],"navigatorTitle":[{"text":"BackspaceRange","kind":"identifier"}],"title":"Keyboard.BackspaceRange"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/ButtonBorderStyle":{"navigatorTitle":[{"text":"ButtonBorderStyle","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ButtonBorderStyle","type":"topic","url":"\/documentation\/keyboardkit\/keyboard\/buttonborderstyle","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ButtonBorderStyle","kind":"identifier"}],"role":"symbol","title":"Keyboard.ButtonBorderStyle","abstract":[{"text":"This style defines the border of a keyboard button.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts/CalloutStyle":{"abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"type":"text","text":"the various callout components."}],"kind":"symbol","title":"Callouts.CalloutStyle","role":"symbol","navigatorTitle":[{"text":"CalloutStyle","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/callouts\/calloutstyle","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CalloutStyle","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/CalloutStyle"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/ItemSize":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ItemSize","kind":"identifier"}],"role":"symbol","title":"KeyboardLayout.ItemSize","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/ItemSize","abstract":[{"text":"A size with point-based height and declarative width.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ItemSize","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/keyboardlayout\/itemsize","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Experiment":{"navigatorTitle":[{"kind":"identifier","text":"Experiment"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Experiment","type":"topic","url":"\/documentation\/keyboardkit\/experiment","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Experiment"}],"role":"symbol","title":"Experiment","abstract":[{"text":"This enum defines all available experiments.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/SE":{"type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/SE","title":"Swift.Encodable"},"doc://com.keyboardkit.KeyboardKit/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/s8SendableP"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/ReturnKeyType":{"navigatorTitle":[{"kind":"identifier","text":"ReturnKeyType"}],"title":"Keyboard.ReturnKeyType","abstract":[{"text":"This enum defines various keyboard return key types.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReturnKeyType"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/keyboard\/returnkeytype","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ReturnKeyType"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/KeyboardCase":{"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboard\/keyboardcase","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardCase"}],"title":"Keyboard.KeyboardCase","navigatorTitle":[{"kind":"identifier","text":"KeyboardCase"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/KeyboardCase","abstract":[{"type":"text","text":"This enum defines various keyboard shift states."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/InterfaceOrientation":{"url":"\/documentation\/keyboardkit\/keyboard\/interfaceorientation","type":"topic","title":"Keyboard.InterfaceOrientation","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/InterfaceOrientation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterfaceOrientation","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"InterfaceOrientation","kind":"identifier"}],"abstract":[{"type":"text","text":"This enum defines supported interface orientations."}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback/Audio":{"url":"\/documentation\/keyboardkit\/feedback\/audio","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/Audio","title":"Feedback.Audio","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Audio","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Audio","kind":"identifier"}],"abstract":[{"type":"text","text":"This enum defines standard audio feedback types."}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback/AudioConfiguration":{"url":"\/documentation\/keyboardkit\/feedback\/audioconfiguration","type":"topic","title":"Feedback.AudioConfiguration","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/AudioConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AudioConfiguration","kind":"identifier"}],"abstract":[{"text":"This struct can be used to configure audio feedback.","type":"text"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/IndicatorStyle":{"kind":"symbol","navigatorTitle":[{"text":"IndicatorStyle","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/IndicatorStyle","url":"\/documentation\/keyboardkit\/dictation\/indicatorstyle","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndicatorStyle","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"type":"text","text":"the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/Indicator"},{"type":"text","text":" component."}],"type":"topic","title":"Dictation.IndicatorStyle"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController":{"navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"role":"symbol","title":"KeyboardInputViewController","abstract":[{"text":"This is the main input controller type that is used in a","type":"text"},{"text":" ","type":"text"},{"text":"KeyboardKit-based keyboard extension.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard/Clip":{"type":"topic","url":"\/documentation\/keyboardkit\/clipboard\/clip","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard\/Clip","title":"Clipboard.Clip","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Clip","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Clip","kind":"identifier"}],"abstract":[{"type":"text","text":"This struct represents a custom clipboard clip."}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/DeepLinks-swift.struct":{"url":"\/documentation\/keyboardkit\/keyboardapp\/deeplinks-swift.struct","type":"topic","title":"KeyboardApp.DeepLinks","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/DeepLinks-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeepLinks","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DeepLinks","kind":"identifier"}],"abstract":[{"type":"text","text":"This type can define app-specific deep links."}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback/HapticConfiguration/CustomFeedback":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"This struct is used for custom haptic feedback."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/HapticConfiguration\/CustomFeedback","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomFeedback"}],"url":"\/documentation\/keyboardkit\/feedback\/hapticconfiguration\/customfeedback","kind":"symbol","title":"Feedback.HapticConfiguration.CustomFeedback","navigatorTitle":[{"kind":"identifier","text":"CustomFeedback"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback/Haptic":{"navigatorTitle":[{"text":"Haptic","kind":"identifier"}],"title":"Feedback.Haptic","abstract":[{"text":"This enum defines standard haptic feedback types.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Haptic","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/feedback\/haptic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/Haptic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/ProgressViewStyle/ButtonVisibility":{"abstract":[],"url":"\/documentation\/keyboardkit\/dictation\/progressviewstyle\/buttonvisibility","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressViewStyle\/ButtonVisibility","title":"Dictation.ProgressViewStyle.ButtonVisibility","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ButtonVisibility"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ButtonVisibility"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts/ActionCallout":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/ActionCallout","title":"Callouts.ActionCallout","navigatorTitle":[{"text":"ActionCallout","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/callouts\/actioncallout","abstract":[{"text":"This callout can show secondary callout actions when","type":"text"},{"text":" ","type":"text"},{"text":"long pressing input keys with secondary actions.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionCallout","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardTheme/ButtonType":{"title":"KeyboardTheme.ButtonType","abstract":[{"type":"text","text":"This enum defines various button types."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme\/ButtonType","url":"\/documentation\/keyboardkit\/keyboardtheme\/buttontype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ButtonType","kind":"identifier"}],"navigatorTitle":[{"text":"ButtonType","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardSettings/PickerValue":{"type":"topic","url":"\/documentation\/keyboardkit\/keyboardsettings\/pickervalue","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/PickerValue","title":"KeyboardSettings.PickerValue","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PickerValue","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PickerValue","kind":"identifier"}],"abstract":[{"type":"text","text":"This value protocol can be implemented by all models"},{"type":"text","text":" "},{"type":"text","text":"that can be used with a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/Picker"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts/UnicodeFontOption":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"UnicodeFontOption","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts\/UnicodeFontOption","url":"\/documentation\/keyboardkit\/fonts\/unicodefontoption","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnicodeFontOption","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"This struct defines Unicode font options."}],"title":"Fonts.UnicodeFontOption"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/ToolbarSeparatorStyle":{"navigatorTitle":[{"kind":"identifier","text":"ToolbarSeparatorStyle"}],"type":"topic","kind":"symbol","title":"Autocomplete.ToolbarSeparatorStyle","abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarSeparator"},{"type":"text","text":" component."}],"url":"\/documentation\/keyboardkit\/autocomplete\/toolbarseparatorstyle","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarSeparatorStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToolbarSeparatorStyle"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/SpacebarLongPressBehavior":{"navigatorTitle":[{"text":"SpacebarLongPressBehavior","kind":"identifier"}],"type":"topic","kind":"symbol","title":"Keyboard.SpacebarLongPressBehavior","abstract":[{"type":"text","text":"This enum defines spacebar long press behaviors."}],"url":"\/documentation\/keyboardkit\/keyboard\/spacebarlongpressbehavior","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/SpacebarLongPressBehavior","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SpacebarLongPressBehavior","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/OpenReason":{"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardapp\/openreason","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenReason","kind":"identifier"}],"title":"KeyboardApp.OpenReason","navigatorTitle":[{"text":"OpenReason","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/OpenReason","abstract":[{"type":"text","text":"This enum defines common reasons to why the main app"},{"type":"text","text":" "},{"text":"was opened by the keyboard.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/AutocapitalizationType":{"abstract":[{"type":"text","text":"This enum defines keyboard auto-capitalization types."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/AutocapitalizationType","url":"\/documentation\/keyboardkit\/keyboard\/autocapitalizationtype","title":"Keyboard.AutocapitalizationType","kind":"symbol","navigatorTitle":[{"text":"AutocapitalizationType","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutocapitalizationType","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/s16SendableMetatypeP":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/DeviceType":{"type":"topic","url":"\/documentation\/keyboardkit\/keyboard\/devicetype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceType","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceType","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/DeviceType","abstract":[{"text":"This enum defines supported keyboard device types.","type":"text"}],"kind":"symbol","title":"Keyboard.DeviceType","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardSettings/Picker":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Picker","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/Picker","type":"topic","navigatorTitle":[{"text":"Picker","kind":"identifier"}],"abstract":[{"text":"This standard picker can be used to pick a type that","type":"text"},{"text":" ","type":"text"},{"text":"implements ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardSettings\/PickerValue"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardsettings\/picker","role":"symbol","title":"KeyboardSettings.Picker"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/Toolbar":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"Toolbar","kind":"identifier"}],"role":"symbol","abstract":[{"text":"This view can be used to render a toolbar with a min","type":"text"},{"type":"text","text":" "},{"type":"text","text":"height, to ensure that callouts are not cut off."}],"url":"\/documentation\/keyboardkit\/keyboard\/toolbar","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Toolbar"}],"title":"Keyboard.Toolbar","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Toolbar"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardHostApplication":{"url":"\/documentation\/keyboardkit\/keyboardhostapplication","abstract":[{"text":"This enum defines a list of known host applications that","type":"text"},{"text":" ","type":"text"},{"text":"can be used to identify various application.","type":"text"}],"title":"KeyboardHostApplication","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardHostApplication","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardHostApplication"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardHostApplication"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/InputSet/ItemRow":{"title":"KeyboardLayout.InputSet.ItemRow","type":"topic","navigatorTitle":[{"text":"ItemRow","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"This type represents an input set item row."}],"url":"\/documentation\/keyboardkit\/keyboardlayout\/inputset\/itemrow","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ItemRow","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/ItemRow","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/KeyboardType":{"abstract":[{"type":"text","text":"This enum defines various keyboard types for various"},{"text":" ","type":"text"},{"text":"kinds of inputs.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/KeyboardType","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/keyboard\/keyboardtype","title":"Keyboard.KeyboardType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"KeyboardType","kind":"identifier"}],"navigatorTitle":[{"text":"KeyboardType","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/ToolbarSeparator":{"type":"topic","url":"\/documentation\/keyboardkit\/autocomplete\/toolbarseparator","title":"Autocomplete.ToolbarSeparator","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarSeparator","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ToolbarSeparator","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ToolbarSeparator","kind":"identifier"}],"abstract":[{"type":"text","text":"This view mimics a native autocomplete separator."}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/ToolbarItemStyle":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ToolbarItemStyle","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarItemStyle","type":"topic","navigatorTitle":[{"text":"ToolbarItemStyle","kind":"identifier"}],"abstract":[{"text":"This style can be used to modify the visual style of","type":"text"},{"text":" ","type":"text"},{"text":"the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarItem"},{"text":" component.","type":"text"}],"kind":"symbol","url":"\/documentation\/keyboardkit\/autocomplete\/toolbaritemstyle","role":"symbol","title":"Autocomplete.ToolbarItemStyle"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/SpacebarMenuType":{"navigatorTitle":[{"kind":"identifier","text":"SpacebarMenuType"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/SpacebarMenuType","type":"topic","url":"\/documentation\/keyboardkit\/keyboard\/spacebarmenutype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpacebarMenuType"}],"role":"symbol","title":"Keyboard.SpacebarMenuType","abstract":[{"text":"This enum defines spacebar context menus that can be","type":"text"},{"type":"text","text":" "},{"type":"text","text":"added as leading and trailing items to the spacebar."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/InputSet":{"url":"\/documentation\/keyboardkit\/keyboardlayout\/inputset","kind":"symbol","title":"KeyboardLayout.InputSet","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputSet"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputSet"}],"abstract":[{"type":"text","text":"A keyboard layout input set defines which input keys"},{"type":"text","text":" "},{"type":"text","text":"to add to a keyboard layout."}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/DictationMethod":{"abstract":[{"type":"text","text":"This enum defines the supported dictation methods."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/DictationMethod","title":"Dictation.DictationMethod","url":"\/documentation\/keyboardkit\/dictation\/dictationmethod","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DictationMethod"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DictationMethod"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/Indicator":{"type":"topic","url":"\/documentation\/keyboardkit\/dictation\/indicator","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/Indicator","title":"Dictation.Indicator","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Indicator"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Indicator"}],"abstract":[{"text":"This view can be presented when dictation is active.","type":"text"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/Toolbar":{"url":"\/documentation\/keyboardkit\/autocomplete\/toolbar","abstract":[{"text":"This toolbar can be added above the keyboard to show","type":"text"},{"text":" ","type":"text"},{"text":"autocomplete suggestions as the user types.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Toolbar","title":"Autocomplete.Toolbar","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Toolbar","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Toolbar","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardFont":{"abstract":[{"type":"text","text":"This type represents a keyboard-specific font, which can"},{"type":"text","text":" "},{"type":"text","text":"be used by "},{"type":"codeVoice","code":"Codable"},{"type":"text","text":" types."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardFont","kind":"symbol","type":"topic","role":"symbol","title":"KeyboardFont","url":"\/documentation\/keyboardkit\/keyboardfont","navigatorTitle":[{"text":"KeyboardFont","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardFont","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/AddedLocale":{"navigatorTitle":[{"text":"AddedLocale","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/AddedLocale","type":"topic","url":"\/documentation\/keyboardkit\/keyboard\/addedlocale","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AddedLocale","kind":"identifier"}],"role":"symbol","title":"Keyboard.AddedLocale","abstract":[{"type":"text","text":"This type can be used to define metadata for locales"},{"type":"text","text":" "},{"type":"text","text":"that have been added to a keyboard."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardModel":{"url":"\/documentation\/keyboardkit\/keyboardmodel","type":"topic","title":"KeyboardModel","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardModel","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardModel","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"KeyboardModel","kind":"identifier"}],"abstract":[{"text":"This protocol is an alias for other protocols that model","type":"text"},{"text":" ","type":"text"},{"text":"types in the framework should conform to.","type":"text"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/DockEdge":{"type":"topic","url":"\/documentation\/keyboardkit\/keyboard\/dockedge","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/DockEdge","title":"Keyboard.DockEdge","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DockEdge"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DockEdge"}],"abstract":[{"text":"This enum defines supported keyboard dock edges.","type":"text"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/Gesture":{"url":"\/documentation\/keyboardkit\/keyboard\/gesture","kind":"symbol","navigatorTitle":[{"text":"Gesture","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Gesture","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Gesture"}],"title":"Keyboard.Gesture","type":"topic","abstract":[{"type":"text","text":"This enum defines various keyboard gestures that can"},{"type":"text","text":" "},{"text":"be used to interact with a keyboard.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardController":{"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardcontroller","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardController"}],"title":"KeyboardController","navigatorTitle":[{"kind":"identifier","text":"KeyboardController"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardController","abstract":[{"type":"text","text":"This protocol can be implemented by any classes that can"},{"type":"text","text":" "},{"type":"text","text":"be used to control a keyboard extension."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/AuthorizationStatus":{"navigatorTitle":[{"text":"AuthorizationStatus","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/AuthorizationStatus","type":"topic","url":"\/documentation\/keyboardkit\/dictation\/authorizationstatus","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthorizationStatus","kind":"identifier"}],"role":"symbol","title":"Dictation.AuthorizationStatus","abstract":[{"type":"text","text":"This enum defines various dictation statuses."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback/HapticConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"This struct can be used to configure haptic feedback."}],"title":"Feedback.HapticConfiguration","role":"symbol","navigatorTitle":[{"text":"HapticConfiguration","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/feedback\/hapticconfiguration","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HapticConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/HapticConfiguration"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/ItemWidth":{"url":"\/documentation\/keyboardkit\/keyboardlayout\/itemwidth","kind":"symbol","navigatorTitle":[{"text":"ItemWidth","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/ItemWidth","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ItemWidth","kind":"identifier"}],"title":"KeyboardLayout.ItemWidth","type":"topic","abstract":[{"type":"text","text":"This enum specifies various layout item width types."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/SpacebarDragSensitivity":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/SpacebarDragSensitivity","navigatorTitle":[{"text":"SpacebarDragSensitivity","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"This enum defines spacebar drag sensitivities.","type":"text"}],"url":"\/documentation\/keyboardkit\/keyboard\/spacebardragsensitivity","title":"Keyboard.SpacebarDragSensitivity","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SpacebarDragSensitivity","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/Suggestion":{"url":"\/documentation\/keyboardkit\/autocomplete\/suggestion","abstract":[{"type":"text","text":"This type represents an autocomplete suggestion that"},{"type":"text","text":" "},{"type":"text","text":"is returned by an "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/Suggestion","title":"Autocomplete.Suggestion","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Suggestion","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Suggestion","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/ToolbarItem":{"abstract":[{"text":"This view mimics a native autocomplete toolbar item.","type":"text"}],"kind":"symbol","title":"Autocomplete.ToolbarItem","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ToolbarItem"}],"url":"\/documentation\/keyboardkit\/autocomplete\/toolbaritem","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ToolbarItem"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/ToolbarItem"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardFont/FontWeight":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FontWeight","kind":"identifier"}],"abstract":[{"type":"text","text":"This enum defines various keyboard font weights."}],"title":"KeyboardFont.FontWeight","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardFont\/FontWeight","kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardfont\/fontweight","navigatorTitle":[{"text":"FontWeight","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardFont/FontType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FontType","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardFont\/FontType","navigatorTitle":[{"text":"FontType","kind":"identifier"}],"abstract":[{"text":"This enum defines various keyboard font types.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/keyboardfont\/fonttype","title":"KeyboardFont.FontType"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/Diacritic":{"navigatorTitle":[{"kind":"identifier","text":"Diacritic"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Diacritic","type":"topic","url":"\/documentation\/keyboardkit\/keyboard\/diacritic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Diacritic"}],"role":"symbol","title":"Keyboard.Diacritic","abstract":[{"type":"text","text":"This type can be used to replace character(s) with a"},{"type":"text","text":" "},{"type":"text","text":"diacritic variant."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/EnabledLocalesDataSource-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnabledLocalesDataSource"}],"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardcontext\/enabledlocalesdatasource-swift.enum","role":"symbol","abstract":[{"text":"This enum defines various enabled locale datasources.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/EnabledLocalesDataSource-swift.enum","title":"KeyboardContext.EnabledLocalesDataSource","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EnabledLocalesDataSource"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete/NextWordPredictionMethod":{"url":"\/documentation\/keyboardkit\/autocomplete\/nextwordpredictionmethod","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NextWordPredictionMethod"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete\/NextWordPredictionMethod","title":"Autocomplete.NextWordPredictionMethod","abstract":[{"text":"This enum defines next word prediction request types","type":"text"},{"text":" ","type":"text"},{"text":"that are provided by KeyboardKit Pro.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NextWordPredictionMethod"}]},"doc://com.keyboardkit.KeyboardKit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/SH","title":"Swift.Hashable"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AutocompleteService":{"abstract":[{"type":"text","text":"This protocol can be implemented by any type that can be"},{"type":"text","text":" "},{"type":"text","text":"used perform autocomplete as the user types."}],"kind":"symbol","title":"AutocompleteService","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutocompleteService"}],"url":"\/documentation\/keyboardkit\/autocompleteservice","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutocompleteService"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AutocompleteService"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts/Actions":{"navigatorTitle":[{"text":"Actions","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/Actions","type":"topic","url":"\/documentation\/keyboardkit\/callouts\/actions","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Actions","kind":"identifier"}],"role":"symbol","title":"Callouts.Actions","abstract":[{"text":"This type can be used to define callout actions that","type":"text"},{"text":" ","type":"text"},{"text":"can be shown in an ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts\/ActionCallout","isActive":true,"type":"reference"},{"text":".","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/ButtonShadowStyle":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ButtonShadowStyle","navigatorTitle":[{"text":"ButtonShadowStyle","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"This style defines the shadow of a keyboard button."}],"url":"\/documentation\/keyboardkit\/keyboard\/buttonshadowstyle","title":"Keyboard.ButtonShadowStyle","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ButtonShadowStyle","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback/AudioConfiguration/CustomFeedback":{"abstract":[{"type":"text","text":"This struct is used for custom audio feedback."}],"url":"\/documentation\/keyboardkit\/feedback\/audioconfiguration\/customfeedback","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback\/AudioConfiguration\/CustomFeedback","title":"Feedback.AudioConfiguration.CustomFeedback","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomFeedback"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomFeedback"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/ServiceError":{"title":"Dictation.ServiceError","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ServiceError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ServiceError","kind":"identifier"}],"abstract":[{"type":"text","text":"This enum defines dictation service errors."}],"kind":"symbol","url":"\/documentation\/keyboardkit\/dictation\/serviceerror","navigatorTitle":[{"text":"ServiceError","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/ProgressView":{"kind":"symbol","url":"\/documentation\/keyboardkit\/dictation\/progressview","title":"Dictation.ProgressView","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProgressView"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProgressView"}],"abstract":[{"type":"text","text":"This view can be used to visualize ongoing dictation"},{"type":"text","text":" "},{"type":"text","text":"progress and let users cancel or apply."}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressView"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardTheme/Author-swift.struct":{"url":"\/documentation\/keyboardkit\/keyboardtheme\/author-swift.struct","kind":"symbol","navigatorTitle":[{"text":"Author","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme\/Author-swift.struct","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Author","kind":"identifier"}],"title":"KeyboardTheme.Author","abstract":[{"text":"This struct defines a theme author.","type":"text"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation/ProgressViewLocalization":{"abstract":[{"type":"text","text":"This type can be used to configure the localizations"},{"type":"text","text":" "},{"type":"text","text":"of a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressView","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/keyboardkit\/dictation\/progressviewlocalization","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation\/ProgressViewLocalization","title":"Dictation.ProgressViewLocalization","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProgressViewLocalization","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ProgressViewLocalization","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction":{"title":"KeyboardAction","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAction"}],"abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"type":"text","text":" "},{"type":"text","text":"a namespace for action-related types."}],"url":"\/documentation\/keyboardkit\/keyboardaction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/fragments","value":[{"text":"KeyboardInputViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/navigatorTitle","value":[{"text":"KeyboardInputViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}