{"metadata":{"role":"article","title":"Layout","modules":[{"name":"KeyboardKit"}],"images":[{"identifier":"Feature-Layout.jpg","type":"card"}],"roleHeading":"Article"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"sections":[],"topicSections":[{"anchor":"Types","title":"Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout"]}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article"],"generated":true}],"primaryContentSections":[{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"text":"The keyboard layout of a software keyboard can vary between locales and devices, which means that a layout engine must be flexible.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In KeyboardKit, a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout","type":"reference","isActive":true},{"type":"text","text":" is used to define the full set of keys of a keyboard. A layout can be created from an "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet","type":"reference","isActive":true},{"type":"text","text":", which defines only the input keys. This allows us to reuse identical layouts for many compatible input sets."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit defines some input sets like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/qwerty"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/numeric"},{"type":"text","text":", and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/symbolic"},{"type":"text","text":", as well as a standard keyboard layout that is compatible with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/qwerty"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/qwertz"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/azerty"},{"type":"text","text":" and similar input sets."}]},{"type":"aside","style":"important","content":[{"inlineContent":[{"type":"text","text":"👑 KeyboardKit Pro unlocks more input sets, like "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/qwertz","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/azerty","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/dvorak","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/colemak","isActive":true},{"type":"text","text":", and localized multi-device layouts for all supported locales. You can sign up for KeyboardKit Pro from the "},{"type":"reference","identifier":"https:\/\/keyboardkit.com","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"name":"Important"},{"type":"heading","text":"Namespace","level":2,"anchor":"Namespace"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout","type":"reference"},{"text":" type that defines a full keyboard layout. It’s also a namespace for other layout-related types, like ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/DeviceConfiguration-swift.struct","type":"reference"},{"text":", which has a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/DeviceConfiguration-swift.struct\/standard(for:)","type":"reference"},{"text":" function that returns a standard configuration for a certain context.","type":"text"}]},{"level":2,"type":"heading","anchor":"Input-Set","text":"Input Set"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In KeyboardKit an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet"},{"type":"text","text":" specifies the input keys of a keyboard. KeyboardKit comes with a few input sets, like "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/qwerty"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/numeric"},{"text":", and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/symbolic"},{"text":", while KeyboardKit Pro unlocks many more, like  ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/qwertz"},{"text":",  ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/azerty"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/dvorak"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/colemak"},{"text":", etc.","type":"text"}]},{"level":2,"type":"heading","anchor":"Keyboard-Layout","text":"Keyboard Layout"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout"},{"type":"text","text":" can be generated from an alphabetic, numeric, and symbolic input set. Certain locales support multiple "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LayoutType"},{"type":"text","text":"s and can be added multiple times with different layouts, like "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LayoutType\/qwerty","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LayoutType\/colemak","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LayoutType\/dvorak","isActive":true,"type":"reference"},{"text":", etc.","type":"text"}]},{"type":"heading","level":2,"anchor":"Keyboard-Layout-Customization","text":"Keyboard Layout Customization"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","isActive":true,"type":"reference"},{"text":" will automatically apply the default layout for the current ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/locale","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/deviceType","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/keyboardInputType","isActive":true,"type":"reference"},{"text":", and many other parameters. You can inject a custom ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout","isActive":true,"type":"reference"},{"text":" if you for instance want to adjust certain keys.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit can generate a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/standard(for:)","isActive":true},{"type":"text","text":" layout for the current "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext","isActive":true},{"type":"text","text":". This makes it easy to adjust the standard layout, using layout extensions like "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/insert(_:before:)","type":"reference","isActive":true},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/remove(_:)","isActive":true},{"text":", etc.","type":"text"}]},{"type":"thematicBreak"},{"type":"heading","text":"👑 KeyboardKit Pro","level":2,"anchor":"%F0%9F%91%91-KeyboardKit-Pro"},{"inlineContent":[{"text":"KeyboardKit Pro unlocks more input sets, like ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/qwertz","type":"reference","isActive":true},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/azerty"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/colemak","type":"reference","isActive":true},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/dvorak","isActive":true,"type":"reference"},{"text":", as well as localized input sets and layouts for all ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/keyboardKitSupported","isActive":true,"type":"reference"},{"text":" locales that are included in your license.","type":"text"}],"type":"paragraph"},{"columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"keyboardview-dvorak"}],"type":"paragraph"}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"identifier":"keyboardview-greek","type":"image"}]}]}],"type":"row","numberOfColumns":2},{"inlineContent":[{"text":"You can access localized layouts with the throwing builders. like ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/swedish(for:)","type":"reference","isActive":true},{"text":". These builders will throw a license error if you try to access them without a valid license. If you are on the Basic or Silver plan, you must specify which locales to use in your ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"},{"text":"Keyboard Layout Extensions","type":"heading","anchor":"Keyboard-Layout-Extensions","level":3},{"inlineContent":[{"type":"text","text":"KeyboardKit Pro extends "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout","isActive":true,"type":"reference"},{"text":" with even more functionality, to make it easier to add, remove, and replace items. See the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout","isActive":true,"type":"reference"},{"text":" documentation and its nested ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/Item","isActive":true,"type":"reference"},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/ItemRow","isActive":true,"type":"reference"},{"text":" types for a full list of additional capabilities.","type":"text"}],"type":"paragraph"},{"type":"heading","text":"Locales With Multiple Layouts","level":3,"anchor":"Locales-With-Multiple-Layouts"},{"inlineContent":[{"text":"KeyboardKit Pro extends ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale"},{"text":" with a list of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/supportedLayoutTypes"},{"text":" and makes the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LocaleSettingsScreen"},{"text":" add a layout picker to all locales that support multiple layouts.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"This means languages like ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/english","isActive":true,"type":"reference"},{"text":" can be added many times, with different layouts. The following locales support multiple layouts:","type":"text"}],"type":"paragraph"},{"inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/catalan","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/croatian","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/dutch","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/dutch_belgium","isActive":true,"type":"reference"},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/english","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/english_australia","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/english_canada","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/english_gb","isActive":true},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/english_us"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/estonian"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/hungarian"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/indonesian"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/irish"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/italian"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/latvian"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/malay"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/polish"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/portuguese"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/portuguese_brazil"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/romanian"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/serbian_latin"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/slovenian"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/swahili"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/uzbek"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/vietnamese"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/welsh"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"All localized layout implementations use the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/keyboardLayoutType","isActive":true,"type":"reference"},{"text":" to adjust their alphabetic input set for the current layout type.","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"variants":[{"paths":["\/documentation\/keyboardkit\/layout-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/layout-article"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/supportedLayoutTypes":{"abstract":[{"text":"A list of layout types that the locale supports.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/supportedLayoutTypes","kind":"symbol","type":"topic","role":"symbol","title":"supportedLayoutTypes","url":"\/documentation\/keyboardkit\/foundation\/locale\/supportedlayouttypes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedLayoutTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V"},{"text":".","kind":"text"},{"text":"LayoutType","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V10LayoutTypeO"},{"text":"]","kind":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/keyboardKitSupported":{"url":"\/documentation\/keyboardkit\/foundation\/locale\/keyboardkitsupported","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/keyboardKitSupported","abstract":[{"text":"A list of KeyboardKit supported locales.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardKitSupported","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"},{"text":"]","kind":"text"}],"kind":"symbol","title":"keyboardKitSupported"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/InputSet/qwerty":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qwerty","kind":"identifier"},{"text":": `Self`","kind":"text"}],"role":"symbol","title":"qwerty","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/qwerty","abstract":[{"text":"A standard QWERTY input set.","type":"text"}],"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardlayout\/inputset\/qwerty","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/InputSet/qwertz":{"url":"\/documentation\/keyboardkit\/keyboardlayout\/inputset\/qwertz","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/qwertz","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"qwertz"},{"kind":"text","text":": `Self`"}],"title":"qwertz","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This is a QWERTZ alphabetic input set."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/portuguese":{"kind":"symbol","title":"portuguese","abstract":[],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/portuguese","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portuguese","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"}],"type":"topic","url":"\/documentation\/keyboardkit\/foundation\/locale\/portuguese"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/Item":{"abstract":[{"text":"A keyboard layout items defines an action, size, and","type":"text"},{"text":" ","type":"text"},{"text":"optional insets for a key on a layout-based keyboard.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/Item","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/keyboardkit\/keyboardlayout\/item","title":"KeyboardLayout.Item","navigatorTitle":[{"kind":"identifier","text":"Item"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Item"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/DeviceConfiguration-swift.struct":{"navigatorTitle":[{"text":"DeviceConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/DeviceConfiguration-swift.struct","type":"topic","url":"\/documentation\/keyboardkit\/keyboardlayout\/deviceconfiguration-swift.struct","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceConfiguration","kind":"identifier"}],"role":"symbol","title":"KeyboardLayout.DeviceConfiguration","abstract":[{"type":"text","text":"This type defines layout configs for various devices."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/english":{"url":"\/documentation\/keyboardkit\/foundation\/locale\/english","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/english","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"english"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale"}],"type":"topic","title":"english"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"title":"External Keyboards","url":"\/documentation\/keyboardkit\/external-keyboards-article","images":[{"type":"card","identifier":"Feature-External.jpg"}],"kind":"article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/swahili":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/swahili","abstract":[],"url":"\/documentation\/keyboardkit\/foundation\/locale\/swahili","role":"symbol","title":"swahili","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swahili","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"}],"type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"url":"\/documentation\/keyboardkit\/feedback-article","type":"topic","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"title":"Feedback","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/DeviceConfiguration-swift.struct/standard(for:)":{"url":"\/documentation\/keyboardkit\/keyboardlayout\/deviceconfiguration-swift.struct\/standard(for:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/DeviceConfiguration-swift.struct\/standard(for:)","abstract":[{"text":"The standard config for the provided ","type":"text"},{"code":"context","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"standard","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A7ContextC","text":"KeyboardContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A6LayoutV","text":"KeyboardLayout","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A6LayoutV19DeviceConfigurationV","text":"DeviceConfiguration","kind":"typeIdentifier"}],"kind":"symbol","title":"standard(for:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/locale":{"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardcontext\/locale","title":"locale","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locale"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation6LocaleV","kind":"typeIdentifier","text":"Locale"}],"type":"topic","abstract":[{"text":"The current locale, by default ","type":"text"},{"code":".current","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/locale"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","title":"Callouts","type":"topic","images":[{"identifier":"Feature-Callouts.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"text":"This article describes the KeyboardKit callout engine.","type":"text"}],"role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/LayoutType":{"url":"\/documentation\/keyboardkit\/keyboard\/layouttype","type":"topic","title":"Keyboard.LayoutType","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LayoutType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayoutType"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LayoutType"}],"abstract":[{"text":"This enum defines supported keyboard layout types.","type":"text"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/InputSet/numeric":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"numeric"},{"kind":"text","text":": `Self`"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/numeric","title":"numeric","abstract":[{"text":"A standard numeric input set.","type":"text"}],"url":"\/documentation\/keyboardkit\/keyboardlayout\/inputset\/numeric","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Navigation-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/navigation-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"images":[{"identifier":"Feature-Navigation.jpg","type":"card"}],"kind":"article","title":"Navigation","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/english_australia":{"url":"\/documentation\/keyboardkit\/foundation\/locale\/english_australia","abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/english_australia","role":"symbol","title":"english_australia","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"english_australia","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation6LocaleV","kind":"typeIdentifier","text":"Locale"}],"type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/standard(for:)":{"url":"\/documentation\/keyboardkit\/keyboardlayout\/standard(for:)","kind":"symbol","title":"standard(for:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"standard"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A7ContextC","text":"KeyboardContext"},{"kind":"text","text":") -> "},{"text":"KeyboardLayout","preciseIdentifier":"s:11KeyboardKit0A6LayoutV","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"The standard keyboard layout to use for the provided"},{"type":"text","text":" "},{"type":"text","text":"keyboard context and input set."}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/standard(for:)"},"Feature-Localization.jpg":{"type":"image","identifier":"Feature-Localization.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg","traits":["1x","light"]}],"alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/dutch_belgium":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/dutch_belgium","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dutch_belgium","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","title":"dutch_belgium","url":"\/documentation\/keyboardkit\/foundation\/locale\/dutch_belgium","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/croatian":{"type":"topic","url":"\/documentation\/keyboardkit\/foundation\/locale\/croatian","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"croatian","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/croatian","abstract":[],"kind":"symbol","title":"croatian","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"url":"\/documentation\/keyboardkit\/dictation-article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/welsh":{"kind":"symbol","title":"welsh","abstract":[],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/welsh","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"welsh","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/keyboardkit\/foundation\/locale\/welsh"},"Feature-Autocomplete.jpg":{"type":"image","alt":"Feature Icon","identifier":"Feature-Autocomplete.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}]},"Feature-Host.jpg":{"type":"image","identifier":"Feature-Host.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg"}]},"Feature-Fonts.jpg":{"type":"image","identifier":"Feature-Fonts.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg","traits":["1x","light"]}],"alt":"Feature Icon"},"Feature-Dictation.jpg":{"type":"image","alt":"Feature Icon","identifier":"Feature-Dictation.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg"}]},"Feature-AI.jpg":{"type":"image","identifier":"Feature-AI.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg"}],"alt":"Feature Icon"},"https://keyboardkit.com":{"title":"KeyboardKit website","titleInlineContent":[{"text":"KeyboardKit website","type":"text"}],"type":"link","identifier":"https:\/\/keyboardkit.com","url":"https:\/\/keyboardkit.com"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/InputSet/symbolic":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"symbolic","kind":"identifier"},{"text":": `Self`","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/symbolic","type":"topic","abstract":[{"type":"text","text":"A standard symbolic input set."}],"title":"symbolic","url":"\/documentation\/keyboardkit\/keyboardlayout\/inputset\/symbolic","kind":"symbol","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/dutch":{"kind":"symbol","title":"dutch","abstract":[],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/dutch","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dutch","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"}],"type":"topic","url":"\/documentation\/keyboardkit\/foundation\/locale\/dutch"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","type":"topic","url":"\/documentation\/keyboardkit\/autocomplete-article","kind":"article","images":[{"type":"card","identifier":"Feature-Autocomplete.jpg"}],"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"kind":"symbol","title":"KeyboardView","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/serbian_latin":{"url":"\/documentation\/keyboardkit\/foundation\/locale\/serbian_latin","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/serbian_latin","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serbian_latin","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"}],"title":"serbian_latin","type":"topic","abstract":[]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/indonesian":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/indonesian","title":"indonesian","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indonesian","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkit\/foundation\/locale\/indonesian","type":"topic","abstract":[],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/latvian":{"abstract":[],"kind":"symbol","url":"\/documentation\/keyboardkit\/foundation\/locale\/latvian","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"latvian","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/latvian","type":"topic","title":"latvian"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/catalan":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/catalan","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"catalan","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"}],"abstract":[],"role":"symbol","title":"catalan","url":"\/documentation\/keyboardkit\/foundation\/locale\/catalan","kind":"symbol","type":"topic"},"keyboardview-dvorak":{"type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/keyboardview-dvorak.jpg","traits":["1x","light"]}],"alt":"A Dvorak keyboard","identifier":"keyboardview-dvorak"},"Feature-Feedback.jpg":{"type":"image","identifier":"Feature-Feedback.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/InputSet/colemak":{"abstract":[{"type":"text","text":"This is a Colemak alphabetic input set."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/colemak","url":"\/documentation\/keyboardkit\/keyboardlayout\/inputset\/colemak","title":"colemak","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"colemak","kind":"identifier"},{"kind":"text","text":": `Self`"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/InputSet/dvorak":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dvorak","kind":"identifier"},{"text":": `Self`","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/dvorak","type":"topic","abstract":[{"type":"text","text":"This is an Dvorak alphabetic input set."}],"kind":"symbol","title":"dvorak","url":"\/documentation\/keyboardkit\/keyboardlayout\/inputset\/dvorak","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/LayoutType/qwerty":{"abstract":[{"text":"A QWERTY keyboard layout type.","type":"text"}],"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboard\/layouttype\/qwerty","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"qwerty"}],"type":"topic","role":"symbol","title":"Keyboard.LayoutType.qwerty","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LayoutType\/qwerty"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Localization-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit localization engine."}],"url":"\/documentation\/keyboardkit\/localization-article","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","title":"Localization","type":"topic","kind":"article","role":"article"},"Feature-External.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg"}],"identifier":"Feature-External.jpg","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale":{"navigatorTitle":[{"text":"Locale","kind":"identifier"}],"title":"Locale","abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/foundation\/locale","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp","title":"KeyboardApp","navigatorTitle":[{"text":"KeyboardApp","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/keyboardapp","abstract":[{"type":"text","text":"This type can be used to define important properties for"},{"type":"text","text":" "},{"type":"text","text":"your app, and is also a namespace for app-based features."}],"role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardApp","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/insert(_:before:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"insert"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A6LayoutV4ItemV","text":"Item","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"before","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A6ActionO","text":"KeyboardAction","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"insert(_:before:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/insert(_:before:)","abstract":[{"text":"Insert an item before an action in all rows.","type":"text"}],"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardlayout\/insert(_:before:)","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/deviceType":{"type":"topic","url":"\/documentation\/keyboardkit\/keyboardcontext\/devicetype","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Keyboard","preciseIdentifier":"s:11KeyboardKit0A0V","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"DeviceType","preciseIdentifier":"s:11KeyboardKit0A0V10DeviceTypeO","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/deviceType","abstract":[{"text":"The device type that is currently being used.","type":"text"}],"kind":"symbol","title":"deviceType","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/remove(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"KeyboardAction","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A6ActionO"},{"text":")","kind":"text"}],"role":"symbol","title":"remove(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/remove(_:)","abstract":[{"type":"text","text":"Remove a certain action from all rows."}],"kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardlayout\/remove(_:)","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","images":[{"type":"card","identifier":"Feature-AI.jpg"}],"kind":"article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/swedish(for:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/swedish(for:)","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swedish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"KeyboardContext","preciseIdentifier":"s:11KeyboardKit0A7ContextC","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"KeyboardLayout","preciseIdentifier":"s:11KeyboardKit0A6LayoutV","kind":"typeIdentifier"}],"title":"swedish(for:)","url":"\/documentation\/keyboardkit\/keyboardlayout\/swedish(for:)","type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","title":"Input","url":"\/documentation\/keyboardkit\/input-article","images":[{"type":"card","identifier":"Feature-Input.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/emojis-article","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","title":"Emojis","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"kind":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","role":"article","images":[{"identifier":"Feature-Host.jpg","type":"card"}],"title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro lets you define and use a host application."}],"url":"\/documentation\/keyboardkit\/host-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/malay":{"kind":"symbol","role":"symbol","title":"malay","url":"\/documentation\/keyboardkit\/foundation\/locale\/malay","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"malay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/malay"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"url":"\/documentation\/keyboardkit\/clipboard-article","abstract":[{"text":"This article describes KeyboardKit’s clipboard support.","type":"text"}],"images":[{"type":"card","identifier":"Feature-Clipboard.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","title":"Clipboard","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/italian":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/italian","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"italian","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","title":"italian","url":"\/documentation\/keyboardkit\/foundation\/locale\/italian","kind":"symbol","type":"topic"},"Feature-Clipboard.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg","traits":["1x","light"]}],"alt":"Feature Icon","type":"image","identifier":"Feature-Clipboard.jpg"},"Feature-App.jpg":{"identifier":"Feature-App.jpg","type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/portuguese_brazil":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portuguese_brazil","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"}],"role":"symbol","url":"\/documentation\/keyboardkit\/foundation\/locale\/portuguese_brazil","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/portuguese_brazil","title":"portuguese_brazil"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/estonian":{"url":"\/documentation\/keyboardkit\/foundation\/locale\/estonian","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/estonian","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"estonian"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale"}],"type":"topic","title":"estonian"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/irish":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"irish","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale"}],"url":"\/documentation\/keyboardkit\/foundation\/locale\/irish","title":"irish","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/irish","role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","type":"topic","abstract":[{"text":"This article describes KeyboardKit’s custom font support.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/fonts-article","role":"article","images":[{"type":"card","identifier":"Feature-Fonts.jpg"}],"title":"Fonts"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout":{"kind":"symbol","abstract":[{"type":"text","text":"This type defines the full set of keys on a keyboard and"},{"type":"text","text":" "},{"type":"text","text":"is also a namespace for layout-related types."}],"title":"KeyboardLayout","role":"symbol","navigatorTitle":[{"text":"KeyboardLayout","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/keyboardlayout","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardLayout","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","role":"article","kind":"article","title":"App Utilities","url":"\/documentation\/keyboardkit\/app-article","type":"topic","images":[{"type":"card","identifier":"Feature-App.jpg"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/actions-article","role":"article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"title":"Actions"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/LocaleSettingsScreen":{"url":"\/documentation\/keyboardkit\/keyboard\/localesettingsscreen","kind":"symbol","title":"Keyboard.LocaleSettingsScreen","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocaleSettingsScreen"}],"type":"topic","navigatorTitle":[{"text":"LocaleSettingsScreen","kind":"identifier"}],"abstract":[{"type":"text","text":"This screen can be used as the main keyboard locales"},{"type":"text","text":" "},{"text":"screen in your app or keyboard extension.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LocaleSettingsScreen"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/english_gb":{"kind":"symbol","title":"english_gb","abstract":[],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/english_gb","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"english_gb","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"}],"type":"topic","url":"\/documentation\/keyboardkit\/foundation\/locale\/english_gb"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/InputSet":{"url":"\/documentation\/keyboardkit\/keyboardlayout\/inputset","kind":"symbol","title":"KeyboardLayout.InputSet","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputSet"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputSet"}],"abstract":[{"type":"text","text":"A keyboard layout input set defines which input keys"},{"type":"text","text":" "},{"type":"text","text":"to add to a keyboard layout."}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/english_canada":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"english_canada","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"}],"type":"topic","title":"english_canada","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/english_canada","url":"\/documentation\/keyboardkit\/foundation\/locale\/english_canada","role":"symbol"},"Feature-Navigation.jpg":{"alt":"Feature Icon","type":"image","identifier":"Feature-Navigation.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Navigation.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/LayoutType/dvorak":{"url":"\/documentation\/keyboardkit\/keyboard\/layouttype\/dvorak","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LayoutType\/dvorak","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dvorak","kind":"identifier"}],"title":"Keyboard.LayoutType.dvorak","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A Dvorak keyboard layout type."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/vietnamese":{"url":"\/documentation\/keyboardkit\/foundation\/locale\/vietnamese","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/vietnamese","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vietnamese","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"}],"title":"vietnamese","type":"topic","abstract":[]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/uzbek":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/uzbek","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uzbek","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","title":"uzbek","url":"\/documentation\/keyboardkit\/foundation\/locale\/uzbek","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/romanian":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/romanian","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"romanian","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","title":"romanian","url":"\/documentation\/keyboardkit\/foundation\/locale\/romanian","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/hungarian":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hungarian"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/hungarian","title":"hungarian","role":"symbol","url":"\/documentation\/keyboardkit\/foundation\/locale\/hungarian","type":"topic"},"Feature-Layout.jpg":{"alt":null,"identifier":"Feature-Layout.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Layout.jpg"}],"type":"image"},"Feature-Callouts.jpg":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg"}],"alt":"Feature Icon","identifier":"Feature-Callouts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/InputSet/azerty":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/InputSet\/azerty","kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardlayout\/inputset\/azerty","title":"azerty","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"azerty"},{"kind":"text","text":": `Self`"}],"abstract":[{"type":"text","text":"This is an AZERTY alphabetic input set."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/keyboardInputType":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/keyboardInputType","abstract":[{"text":"The keyboard input type that is currently used.","type":"text"}],"title":"keyboardInputType","url":"\/documentation\/keyboardkit\/keyboardcontext\/keyboardinputtype","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardInputType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A0V","text":"Keyboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"InputType","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A0V9InputTypeO"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/english_us":{"url":"\/documentation\/keyboardkit\/foundation\/locale\/english_us","abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/english_us","role":"symbol","title":"english_us","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"english_us"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV"}],"type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/slovenian":{"url":"\/documentation\/keyboardkit\/foundation\/locale\/slovenian","role":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"slovenian"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV"}],"type":"topic","kind":"symbol","title":"slovenian","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/slovenian"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext/keyboardLayoutType":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardLayoutType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11KeyboardKit0A0V","kind":"typeIdentifier","text":"Keyboard"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11KeyboardKit0A0V10LayoutTypeO","kind":"typeIdentifier","text":"LayoutType"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext\/keyboardLayoutType","abstract":[{"type":"text","text":"The current keyboard layout type, if any."}],"title":"keyboardLayoutType","type":"topic","url":"\/documentation\/keyboardkit\/keyboardcontext\/keyboardlayouttype","kind":"symbol"},"Feature-Input.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg","traits":["1x","light"]}],"alt":"Feature Icon","identifier":"Feature-Input.jpg","type":"image"},"Feature-Emojis.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-Emojis.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Foundation/Locale/polish":{"abstract":[],"title":"polish","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV"}],"type":"topic","url":"\/documentation\/keyboardkit\/foundation\/locale\/polish","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Foundation\/Locale\/polish"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/LayoutType/colemak":{"title":"Keyboard.LayoutType.colemak","abstract":[{"text":"A Colemak keyboard layout type.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/LayoutType\/colemak","url":"\/documentation\/keyboardkit\/keyboard\/layouttype\/colemak","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"colemak"}]},"Feature-Actions.jpg":{"identifier":"Feature-Actions.jpg","type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext":{"abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"type":"text","text":"for the core keyboard functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext","kind":"symbol","type":"topic","role":"symbol","title":"KeyboardContext","url":"\/documentation\/keyboardkit\/keyboardcontext","navigatorTitle":[{"text":"KeyboardContext","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardContext","kind":"identifier"}]},"keyboardview-greek":{"type":"image","alt":"A Greek keyboard","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/keyboardview-greek.jpg","traits":["1x","light"]}],"identifier":"keyboardview-greek"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardLayout/ItemRow":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardLayout\/ItemRow","abstract":[{"text":"This typealias represents a list of layout items.","type":"text"}],"title":"KeyboardLayout.ItemRow","url":"\/documentation\/keyboardkit\/keyboardlayout\/itemrow","kind":"symbol","navigatorTitle":[{"text":"ItemRow","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ItemRow","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Navigation-Article"]}]}],"traits":[{"interfaceLanguage":"occ"}]}]}