{"variants":[{"paths":["\/documentation\/keyboardkit\/proxy-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/proxy-article"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"article","images":[{"identifier":"Feature-Proxy.jpg","type":"card"}],"modules":[{"name":"KeyboardKit"}],"roleHeading":"Article","title":"Proxy Utilities"},"primaryContentSections":[{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"iOS keyboards use a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy","type":"reference","isActive":true},{"text":" to integrate with the currently selected text field. The proxy lets you insert and delete text, get the currently selected text, move the input cursor, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The native APIs are however very limited, which makes it hard to get detailed text information and to perform many standard operations. For instance, the native proxy can’t get all the text from the document, and lacks many important capabilities.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit therefore extends the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy","type":"reference","isActive":true},{"text":" with additional capabilities. ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","type":"reference","isActive":true},{"text":" also has a custom ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/textDocumentProxy","type":"reference","isActive":true},{"text":" that lets you hijack the original proxy with a custom one.","type":"text"}]},{"name":"Important","type":"aside","content":[{"inlineContent":[{"text":"👑 KeyboardKit Pro unlocks ways for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy","type":"reference"},{"text":" to read the full document content to all licenses that includes the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/fullDocumentContext","type":"reference"},{"text":" feature. You can sign up for KeyboardKit Pro from the ","type":"text"},{"isActive":true,"identifier":"https:\/\/keyboardkit.com","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"style":"important"},{"anchor":"Namespace","type":"heading","text":"Namespace","level":2},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy","type":"reference","isActive":true},{"text":" namespace with proxy-related types, like ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy\/FullDocumentReaderConfiguration","type":"reference","isActive":true},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy\/FullDocumentReaderResult","type":"reference","isActive":true},{"text":".","type":"text"}]},{"anchor":"Extensions","type":"heading","text":"Extensions","level":2},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit extends the native ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy","type":"reference","isActive":true},{"text":" with additional capabilities, such as the ability to get more content from the document, analyze words, sentences & quotations, end the current sentence, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Here are some examples of extensions that are added to the proxy by KeyboardKit, to make it much more capable than it is by default:","type":"text"}]},{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/currentWord","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/deleteBackward(range:)","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/deleteBackward(times:)","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/documentContext","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/endSentence(withText:)","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/fullDocumentContext(config:)","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/hasUnclosedQuotationBeforeInput(for:)","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/isCursorAtNewSentence","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/isCursorAtNewWord","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/isCursorAtTheEndOfTheCurrentWord","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/isReadingFullDocumentContext","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/moveTextInputCursor(steps:)","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/moveTextInputCursorToBeginning()","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/moveTextInputCursorToEnd()","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/replaceCurrentWord(with:)","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/sentenceBeforeInput","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/sentenceDelimiters","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/wordBeforeInput","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/wordDelimiters","type":"reference","isActive":true}]},{"type":"paragraph","inlineContent":[{"text":"See the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy","type":"reference","isActive":true},{"text":" documentation for more information and a full list of extension that are applied by KeyboardKit.","type":"text"}]},{"type":"thematicBreak"},{"anchor":"%F0%9F%91%91-KeyboardKit-Pro","type":"heading","text":"👑 KeyboardKit Pro","level":2},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro unlocks additional proxy capabilities, like the ability to read the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/fullDocumentContext(config:)","type":"reference","isActive":true},{"text":" instead of just the content closest to the input cursor.","type":"text"}]},{"anchor":"Full-Document-Context","type":"heading","text":"Full Document Context","level":3},{"type":"paragraph","inlineContent":[{"text":"Apple’s native text document proxy doesn’t return all the text within the document. It instead cuts off the available text at any time, e.g. at the previous or next paragraph. This makes it hard to provide AI-based features that require more context.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro therefore unlocks ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/fullDocumentContext(config:)","type":"reference","isActive":true},{"text":" proxy extensions that let you read ","type":"text"},{"inlineContent":[{"text":"all","type":"text"}],"type":"strong"},{"text":" text from the proxy. This will provide you with all the text before and after the input cursor, as well as an aggregate of all the available text in the document.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The proxy also has ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/fullDocumentContextBeforeInput(config:)","type":"reference","isActive":true},{"text":" & ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/fullDocumentContextAfterInput(config:)","type":"reference","isActive":true},{"text":" functions if you’re only interested in the text before or after the input cursor.","type":"text"}]},{"name":"Important","type":"aside","content":[{"inlineContent":[{"text":"The full document read operation is a best effort operation, that makes the most of the very limited capabilities that are provided by the operating system. It’s not guaranteed to return a valid result. You can configure the operation to yield better results, for instance by waiting longer when moving the input cursor, try to move more times around the edges, etc.","type":"text"}],"type":"paragraph"}],"style":"important"}],"kind":"content"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy-Article"},"kind":"article","seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article"],"generated":true}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}],"topicSections":[{"title":"Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy"],"anchor":"Types"}],"references":{"Feature-Essentials.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials.jpg"}],"identifier":"Feature-Essentials.jpg"},"Feature-AI.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg"}],"identifier":"Feature-AI.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/currentWord":{"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/currentword","kind":"symbol","abstract":[{"type":"text","text":"The word at the cursor location, if any."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/currentWord","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentWord"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","title":"currentWord"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","url":"\/documentation\/keyboardkit\/app-article","images":[{"identifier":"Feature-App.jpg","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}],"role":"article","title":"App Utilities","kind":"article","type":"topic"},"Feature-Fonts.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg"}],"identifier":"Feature-Fonts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/sentenceBeforeInput":{"type":"topic","abstract":[{"text":"The sentence just before the input cursor.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sentenceBeforeInput","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/sentenceBeforeInput","title":"sentenceBeforeInput","role":"symbol","url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/sentencebeforeinput"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"images":[{"type":"card","identifier":"Feature-AI.jpg"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Proxy/FullDocumentReaderConfiguration":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy\/FullDocumentReaderConfiguration","url":"\/documentation\/keyboardkit\/proxy\/fulldocumentreaderconfiguration","abstract":[{"text":"This configuration can be used to set up how to read","type":"text"},{"text":" ","type":"text"},{"text":"the full document context of a ","type":"text"},{"code":"UITextDocumentProxy","type":"codeVoice"},{"text":" .","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullDocumentReaderConfiguration"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullDocumentReaderConfiguration"}],"title":"Proxy.FullDocumentReaderConfiguration","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/endSentence(withText:)":{"abstract":[{"text":"End the current sentence by removing trailing spaces,","type":"text"},{"text":" ","type":"text"},{"text":"then injecting a dot and a space.","type":"text"}],"kind":"symbol","title":"endSentence(withText:)","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/endSentence(withText:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endSentence"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/endsentence(withtext:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"url":"\/documentation\/keyboardkit\/fonts-article","abstract":[{"type":"text","text":"This article describes KeyboardKit’s custom font support."}],"role":"article","type":"topic","title":"Fonts","kind":"article","images":[{"identifier":"Feature-Fonts.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article"},"Feature-Callouts.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg"}],"identifier":"Feature-Callouts.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"url":"\/documentation\/keyboardkit\/host-article","abstract":[{"text":"This article describes how KeyboardKit Pro can identify and use the host application.","type":"text"}],"role":"article","type":"topic","kind":"article","title":"Host Application","images":[{"type":"card","identifier":"Feature-Host.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/hasUnclosedQuotationBeforeInput(for:)":{"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/hasunclosedquotationbeforeinput(for:)","kind":"symbol","abstract":[{"type":"text","text":"Whether the last trailing quotation before the input"},{"type":"text","text":" "},{"type":"text","text":"cursor is a quotation begin delimiter."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/hasUnclosedQuotationBeforeInput(for:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hasUnclosedQuotationBeforeInput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"hasUnclosedQuotationBeforeInput(for:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/sentenceDelimiters":{"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/sentencedelimiters","kind":"symbol","abstract":[{"text":"A list of western sentence delimiters.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/sentenceDelimiters","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sentenceDelimiters"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}],"type":"topic","title":"sentenceDelimiters"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/deleteBackward(range:)":{"type":"topic","abstract":[{"text":"Delete backwards a certain range.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteBackward","kind":"identifier"},{"text":"(","kind":"text"},{"text":"range","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A0V","text":"Keyboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A0V14BackspaceRangeO","text":"BackspaceRange","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/deleteBackward(range:)","title":"deleteBackward(range:)","role":"symbol","url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/deletebackward(range:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/moveTextInputCursor(steps:)":{"abstract":[{"type":"text","text":"Move the text input cursor a certain number of steps."}],"kind":"symbol","title":"moveTextInputCursor(steps:)","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/moveTextInputCursor(steps:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveTextInputCursor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"steps","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/movetextinputcursor(steps:)","role":"symbol"},"Feature-Feedback.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg"}],"identifier":"Feature-Feedback.jpg"},"Feature-Host.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg"}],"identifier":"Feature-Host.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/replaceCurrentWord(with:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceCurrentWord"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/replaceCurrentWord(with:)","kind":"symbol","title":"replaceCurrentWord(with:)","abstract":[{"type":"text","text":"Replace the current word with a text."}],"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/replacecurrentword(with:)"},"https://keyboardkit.com":{"type":"link","title":"KeyboardKit website","identifier":"https:\/\/keyboardkit.com","titleInlineContent":[{"type":"text","text":"KeyboardKit website"}],"url":"https:\/\/keyboardkit.com"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Gestures-Article":{"type":"topic","images":[{"identifier":"Feature-Gestures.jpg","type":"card"}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","abstract":[{"text":"This article describes the KeyboardKit gesture engine.","type":"text"}],"role":"article","title":"Gestures","url":"\/documentation\/keyboardkit\/gestures-article"},"Feature-Dictation.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg"}],"identifier":"Feature-Dictation.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/deleteBackward(times:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/deleteBackward(times:)","url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/deletebackward(times:)","abstract":[{"type":"text","text":"Delete backwards a certain number of times."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteBackward","kind":"identifier"},{"text":"(","kind":"text"},{"text":"times","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","title":"deleteBackward(times:)","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"abstract":[{"type":"text","text":"This article describes KeyboardKit’s clipboard support."}],"kind":"article","title":"Clipboard","type":"topic","images":[{"identifier":"Feature-Clipboard.jpg","type":"card"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","url":"\/documentation\/keyboardkit\/clipboard-article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-Article":{"url":"\/documentation\/keyboardkit\/essentials-article","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"images":[{"identifier":"Feature-Essentials.jpg","type":"card"}],"type":"topic","title":"Essentials","role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/wordBeforeInput":{"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/wordbeforeinput","kind":"symbol","abstract":[{"text":"The last ended word right before the cursor, if any.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/wordBeforeInput","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"wordBeforeInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","title":"wordBeforeInput"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"role":"article","type":"topic","kind":"article","title":"Callouts","images":[{"type":"card","identifier":"Feature-Callouts.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/moveTextInputCursorToEnd()":{"type":"topic","abstract":[{"text":"Move the text input cursor to the end.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveTextInputCursorToEnd"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/moveTextInputCursorToEnd()","title":"moveTextInputCursorToEnd()","role":"symbol","url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/movetextinputcursortoend()"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/fullDocumentContext(config:)":{"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/fulldocumentcontext(config:)","title":"fullDocumentContext(config:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/fullDocumentContext(config:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Get the full document context from the proxy."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullDocumentContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Proxy","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit5ProxyV"},{"text":".","kind":"text"},{"text":"FullDocumentReaderConfiguration","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit5ProxyV31FullDocumentReaderConfigurationV"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Proxy","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit5ProxyV"},{"text":".","kind":"text"},{"text":"FullDocumentReaderResult","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit5ProxyV24FullDocumentReaderResultV"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","url":"\/documentation\/keyboardkit\/feedback-article","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"role":"article","title":"Feedback","kind":"article","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Proxy/FullDocumentReaderResult":{"url":"\/documentation\/keyboardkit\/proxy\/fulldocumentreaderresult","kind":"symbol","abstract":[{"type":"text","text":"This type is returned by "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy","isActive":true},{"type":"text","text":" "},{"type":"text","text":"after reading the full document context."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy\/FullDocumentReaderResult","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullDocumentReaderResult"}],"navigatorTitle":[{"kind":"identifier","text":"FullDocumentReaderResult"}],"type":"topic","title":"Proxy.FullDocumentReaderResult"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/moveTextInputCursorToBeginning()":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveTextInputCursorToBeginning"},{"kind":"text","text":"()"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/moveTextInputCursorToBeginning()","kind":"symbol","title":"moveTextInputCursorToBeginning()","abstract":[{"type":"text","text":"Move the text input cursor to the beginning."}],"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/movetextinputcursortobeginning()"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/isCursorAtNewSentence":{"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/iscursoratnewsentence","title":"isCursorAtNewSentence","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/isCursorAtNewSentence","role":"symbol","kind":"symbol","abstract":[{"text":"Whether the proxy’s input cursor is at the beginning","type":"text"},{"text":" ","type":"text"},{"text":"of a sentence, with or without trailing whitespaces.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isCursorAtNewSentence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Essentials-KeyboardView":{"type":"topic","images":[{"identifier":"Feature-Essentials-KeyboardView.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","kind":"article","title":"Essentials - KeyboardView","abstract":[{"type":"text","text":"This article describes the essential "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","type":"reference","isActive":true},{"type":"text","text":" and how to use and configure it."}],"url":"\/documentation\/keyboardkit\/essentials-keyboardview"},"Feature-Clipboard.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg"}],"identifier":"Feature-Clipboard.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/fullDocumentContextBeforeInput(config:)":{"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/fulldocumentcontextbeforeinput(config:)","title":"fullDocumentContextBeforeInput(config:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/fullDocumentContextBeforeInput(config:)","role":"symbol","kind":"symbol","abstract":[{"text":"Get the full document context before the text cursor.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullDocumentContextBeforeInput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Proxy","preciseIdentifier":"s:11KeyboardKit5ProxyV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"FullDocumentReaderConfiguration","preciseIdentifier":"s:11KeyboardKit5ProxyV31FullDocumentReaderConfigurationV","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic"},"Feature-External.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg"}],"identifier":"Feature-External.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/fullDocumentContextAfterInput(config:)":{"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/fulldocumentcontextafterinput(config:)","title":"fullDocumentContextAfterInput(config:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/fullDocumentContextAfterInput(config:)","role":"symbol","kind":"symbol","abstract":[{"text":"Get the full document context after the text cursor.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullDocumentContextAfterInput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit5ProxyV","text":"Proxy","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit5ProxyV31FullDocumentReaderConfigurationV","text":"FullDocumentReaderConfiguration","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic"},"Feature-Gestures.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Gestures.jpg"}],"identifier":"Feature-Gestures.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy","url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDocumentProxy"}],"fragments":[{"kind":"keyword","text":"extension"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UITextDocumentProxy","kind":"identifier","text":"UITextDocumentProxy"}],"title":"UITextDocumentProxy","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/isCursorAtNewWord":{"type":"topic","abstract":[{"text":"Whether the cursor is at the beginning of a word.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCursorAtNewWord"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/isCursorAtNewWord","title":"isCursorAtNewWord","role":"symbol","url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/iscursoratnewword"},"Feature-Essentials-KeyboardView.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Essentials-KeyboardView.jpg"}],"identifier":"Feature-Essentials-KeyboardView.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","title":"KeyboardView","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","role":"symbol","kind":"symbol","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"Feature-App.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg"}],"identifier":"Feature-App.jpg"},"Feature-Autocomplete.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"identifier":"Feature-Autocomplete.jpg"},"Feature-Proxy.jpg":{"type":"image","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Proxy.jpg"}],"identifier":"Feature-Proxy.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"url":"\/documentation\/keyboardkit\/external-keyboards-article","kind":"article","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","role":"article","type":"topic","images":[{"identifier":"Feature-External.jpg","type":"card"}],"title":"External Keyboards"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"url":"\/documentation\/keyboardkit\/emojis-article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"role":"article","type":"topic","kind":"article","title":"Emojis","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/isCursorAtTheEndOfTheCurrentWord":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/isCursorAtTheEndOfTheCurrentWord","url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/iscursorattheendofthecurrentword","abstract":[{"type":"text","text":"Whether the cursor is at the end of the current word."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isCursorAtTheEndOfTheCurrentWord"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isCursorAtTheEndOfTheCurrentWord","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController":{"title":"KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This is the main input controller type that is used in a","type":"text"},{"text":" ","type":"text"},{"text":"KeyboardKit-based keyboard extension.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/documentContext":{"abstract":[{"type":"text","text":"Get the document context (the text) before and after"},{"type":"text","text":" "},{"type":"text","text":"the input cursor."}],"kind":"symbol","title":"documentContext","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/documentContext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/documentcontext","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/textDocumentProxy":{"url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/textdocumentproxy","kind":"symbol","abstract":[{"text":"The text document proxy that is currently active.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/textDocumentProxy","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDocumentProxy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"navigatorTitle":[{"kind":"identifier","text":"textDocumentProxy"}],"type":"topic","title":"textDocumentProxy"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","title":"Dictation","role":"article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"url":"\/documentation\/keyboardkit\/dictation-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/wordDelimiters":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wordDelimiters","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/wordDelimiters","title":"wordDelimiters","role":"symbol","url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/worddelimiters"},"Feature-Emojis.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg"}],"identifier":"Feature-Emojis.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","url":"\/documentation\/keyboardkit\/actions-article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"role":"article","kind":"article","title":"Actions","type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"url":"\/documentation\/keyboardkit\/features-articles","abstract":[{"type":"text","text":"This article links to the various KeyboardKit features."}],"role":"collectionGroup","type":"topic","title":"Features","kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UIKit/UITextDocumentProxy/isReadingFullDocumentContext":{"url":"\/documentation\/keyboardkit\/uikit\/uitextdocumentproxy\/isreadingfulldocumentcontext","title":"isReadingFullDocumentContext","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UIKit\/UITextDocumentProxy\/isReadingFullDocumentContext","role":"symbol","kind":"symbol","abstract":[{"text":"Whether the proxy is currently reading the full text","type":"text"},{"type":"text","text":" "},{"text":"from the current document.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isReadingFullDocumentContext","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Proxy":{"url":"\/documentation\/keyboardkit\/proxy","navigatorTitle":[{"text":"Proxy","kind":"identifier"}],"abstract":[{"type":"text","text":"This namespace contains proxy-related types."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Proxy","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"Proxy","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy"},"Feature-Actions.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}],"identifier":"Feature-Actions.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"url":"\/documentation\/keyboardkit\/autocomplete-article","title":"Autocomplete","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","role":"article","kind":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}],"images":[{"identifier":"Feature-Autocomplete.jpg","type":"card"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/fullDocumentContext":{"url":"\/documentation\/keyboardkit\/profeature\/fulldocumentcontext","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullDocumentContext","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"ProFeature.fullDocumentContext","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/fullDocumentContext"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Essentials-KeyboardView","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article"],"generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","value":"KeyboardInputViewController","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/title"},{"op":"replace","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/fragments"},{"op":"replace","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/navigatorTitle"},{"op":"replace","value":"textDocumentProxy","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController~1textDocumentProxy\/title"},{"op":"replace","value":[{"text":"textDocumentProxy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController~1textDocumentProxy\/fragments"}]}]}