{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Status-Article"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Types","anchor":"Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext"]}],"metadata":{"modules":[{"name":"KeyboardKit"}],"roleHeading":"Article","images":[{"identifier":"Feature-Status.jpg","type":"card"}],"title":"Status","role":"article"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"abstract":[{"type":"text","text":"This article describes the KeyboardKit status engine."}],"kind":"article","variants":[{"paths":["\/documentation\/keyboardkit\/status-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkit\/status-article"]}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"text":"KeyboardKit has ways to check various keyboard statuses, e.g. if a keyboard is enabled in System Settings, if Full Access is enabled, if a keyboard is actively being used, etc.","type":"text"}],"type":"paragraph"},{"anchor":"Namespace","text":"Namespace","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus","isActive":true},{"type":"text","text":" namespace that contains status-related types and views, like the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus\/Label"},{"type":"text","text":" that can be used to visualize a certain status value, as well as the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus\/Section"},{"type":"text","text":" which is unlocked by KeyboardKit Pro."}],"type":"paragraph"},{"level":2,"anchor":"Context","type":"heading","text":"Context"},{"inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext"},{"type":"text","text":" class with observable state, which can be used to observe the state of your keyboard."}],"type":"paragraph"},{"type":"codeListing","code":["struct MyView: View {","","    @StateObject private var status = KeyboardStatusContext(bundleId: \"com.myapp.*\")","","    var body: some View {","        VStack {","            Text(\"Enabled: \\(status.isKeyboardEnabled.description)\")","            Text(\"Active: \\(status.isKeyboardActive.description)\")","            Text(\"Full Access: \\(status.isFullAccessEnabled.description)\")","        }","    }","} "],"syntax":"swift"},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext","isActive":true},{"type":"text","text":" has properties like "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext\/bundleId","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext\/isFullAccessEnabled","isActive":true},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext\/isKeyboardActive"},{"type":"text","text":", and "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext\/isKeyboardEnabled","type":"reference","isActive":true},{"type":"text","text":", and functions like "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext\/refresh()","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"text":"Unlike most other context classes, the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext","isActive":true,"type":"reference"},{"type":"text","text":" is not injected into the view environment. You must therefore set up an instance like above when you want to use one. It supports wildcards, to let you inspect multiple keyboards with a single instance."}],"type":"paragraph"},{"text":"Views","type":"heading","level":2,"anchor":"Views"},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus","isActive":true},{"type":"text","text":" namespace has status-specific views, that can be used to display various keyboard status-related values:"}],"type":"paragraph"},{"tabs":[{"content":[{"type":"row","columns":[{"content":[{"inlineContent":[{"type":"image","identifier":"keyboardstatus-label"}],"type":"paragraph"}],"size":1},{"content":[{"type":"paragraph","inlineContent":[{"text":"A keyboard status ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus\/Label","isActive":true,"type":"reference"},{"text":" can display various keyboard statuses, e.g. if a keyboard is enabled, if Full Access is enabled, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The view supports a custom text and icon, and can be styled with the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardStatusLabelStyle(_:)","isActive":true,"type":"reference"},{"text":" view modifier.","type":"text"}]}],"size":1}],"numberOfColumns":2}],"title":"Label"},{"content":[{"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"keyboardstatus-section"}]}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"text":"A keyboard status ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus\/Section","isActive":true,"type":"reference"},{"type":"text","text":" can display all relevant status labels for a keyboard extension, with a link to System Settings if needed."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This view is used by the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen","type":"reference","isActive":true},{"type":"text","text":", and also can be added as a standalone component."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The view can be styled with the following view modifiers:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardStatusSectionStyle(_:)","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardStatusLabelStyle(_:)","isActive":true,"type":"reference"}]}]}]}]}],"type":"row","numberOfColumns":2}],"title":"Section"}],"type":"tabNavigator"}]}],"references":{"Feature-Localization.jpg":{"identifier":"Feature-Localization.jpg","alt":"Feature Icon","type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"url":"\/documentation\/keyboardkit\/feedback-article","type":"topic","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"title":"Feedback","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"title":"External Keyboards","url":"\/documentation\/keyboardkit\/external-keyboards-article","images":[{"type":"card","identifier":"Feature-External.jpg"}],"kind":"article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","title":"Callouts","type":"topic","images":[{"identifier":"Feature-Callouts.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"text":"This article describes the KeyboardKit callout engine.","type":"text"}],"role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardStatus":{"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardStatus","kind":"identifier"}],"title":"KeyboardStatus","navigatorTitle":[{"text":"KeyboardStatus","kind":"identifier"}],"abstract":[{"text":"This namespace contains keyboard status-related types.","type":"text"}],"url":"\/documentation\/keyboardkit\/keyboardstatus","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"url":"\/documentation\/keyboardkit\/dictation-article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardStatus/LabelStyle":{"navigatorTitle":[{"text":"LabelStyle","kind":"identifier"}],"type":"topic","kind":"symbol","title":"KeyboardStatus.LabelStyle","abstract":[{"type":"text","text":"This style can be used to modify the visual style of"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus\/Label","isActive":true},{"type":"text","text":" component."}],"url":"\/documentation\/keyboardkit\/keyboardstatus\/labelstyle","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus\/LabelStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LabelStyle"}],"role":"symbol"},"Feature-Autocomplete.jpg":{"type":"image","identifier":"Feature-Autocomplete.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}]},"Feature-Fonts.jpg":{"alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg"}],"type":"image","identifier":"Feature-Fonts.jpg"},"Feature-Host.jpg":{"alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg"}],"type":"image","identifier":"Feature-Host.jpg"},"Feature-Dictation.jpg":{"type":"image","identifier":"Feature-Dictation.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg"}]},"Feature-AI.jpg":{"alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg"}],"type":"image","identifier":"Feature-AI.jpg"},"keyboardstatus-label":{"alt":"KeyboardStatus.Label","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/keyboardstatus-label.jpg"}],"type":"image","identifier":"keyboardstatus-label"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","type":"topic","url":"\/documentation\/keyboardkit\/autocomplete-article","kind":"article","images":[{"type":"card","identifier":"Feature-Autocomplete.jpg"}],"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardStatusLabelStyle(_:)":{"title":"keyboardStatusLabelStyle(_:)","abstract":[{"type":"text","text":"Apply a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus\/LabelStyle"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardStatusLabelStyle(_:)","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardstatuslabelstyle(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardStatusLabelStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"KeyboardStatus","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A6StatusV"},{"text":".","kind":"text"},{"text":"LabelStyle","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A6StatusV10LabelStyleV"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"kind":"symbol","type":"topic","role":"symbol"},"Feature-Feedback.jpg":{"alt":"Feature Icon","type":"image","identifier":"Feature-Feedback.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg","traits":["1x","light"]}]},"keyboardstatus-section":{"identifier":"keyboardstatus-section","alt":"KeyboardStatus.Label","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/keyboardstatus-section.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Localization-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit localization engine."}],"url":"\/documentation\/keyboardkit\/localization-article","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","title":"Localization","type":"topic","kind":"article","role":"article"},"Feature-External.jpg":{"alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg","traits":["1x","light"]}],"type":"image","identifier":"Feature-External.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardStatusContext/isKeyboardEnabled":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext\/isKeyboardEnabled","title":"isKeyboardEnabled","kind":"symbol","abstract":[{"text":"Whether the keyboard extension has been enabled.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isKeyboardEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/keyboardkit\/keyboardstatuscontext\/iskeyboardenabled","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardStatusContext/isKeyboardActive":{"title":"isKeyboardActive","abstract":[{"type":"text","text":"Whether the keyboard extension is actively used."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext\/isKeyboardActive","url":"\/documentation\/keyboardkit\/keyboardstatuscontext\/iskeyboardactive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isKeyboardActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardStatus/Section":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Section","kind":"identifier"}],"abstract":[{"text":"This section can be used to show keyboard status for","type":"text"},{"text":" ","type":"text"},{"text":"a certain keyboard bundle ID.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus\/Section","title":"KeyboardStatus.Section","kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardstatus\/section","navigatorTitle":[{"text":"Section","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","images":[{"type":"card","identifier":"Feature-AI.jpg"}],"kind":"article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardStatus/Label":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"This label can be used to show the currently enabled"},{"type":"text","text":" "},{"type":"text","text":"state for a keyboard."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus\/Label","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Label"}],"title":"KeyboardStatus.Label","url":"\/documentation\/keyboardkit\/keyboardstatus\/label","kind":"symbol","navigatorTitle":[{"text":"Label","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","title":"Input","url":"\/documentation\/keyboardkit\/input-article","images":[{"type":"card","identifier":"Feature-Input.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/emojis-article","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","title":"Emojis","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"kind":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","role":"article","images":[{"identifier":"Feature-Host.jpg","type":"card"}],"title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro lets you define and use a host application."}],"url":"\/documentation\/keyboardkit\/host-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardStatusContext":{"abstract":[{"type":"text","text":"This class has observable, keyboard status-related state."}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext","kind":"symbol","type":"topic","url":"\/documentation\/keyboardkit\/keyboardstatuscontext","title":"KeyboardStatusContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardStatusContext"}],"navigatorTitle":[{"text":"KeyboardStatusContext","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"url":"\/documentation\/keyboardkit\/clipboard-article","abstract":[{"text":"This article describes KeyboardKit’s clipboard support.","type":"text"}],"images":[{"type":"card","identifier":"Feature-Clipboard.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","title":"Clipboard","type":"topic","kind":"article","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardStatusSectionStyle(_:)":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardStatusSectionStyle(_:)","title":"keyboardStatusSectionStyle(_:)","kind":"symbol","abstract":[{"type":"text","text":"Apply a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus\/SectionStyle"},{"type":"text","text":"."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyboardStatusSectionStyle"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A6StatusV","text":"KeyboardStatus"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A6StatusV12SectionStyleV","text":"SectionStyle"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardstatussectionstyle(_:)","role":"symbol"},"Feature-Clipboard.jpg":{"type":"image","identifier":"Feature-Clipboard.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg","traits":["1x","light"]}]},"Feature-App.jpg":{"identifier":"Feature-App.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg"}],"alt":"Feature Icon","type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","type":"topic","abstract":[{"text":"This article describes KeyboardKit’s custom font support.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/fonts-article","role":"article","images":[{"type":"card","identifier":"Feature-Fonts.jpg"}],"title":"Fonts"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","role":"article","kind":"article","title":"App Utilities","url":"\/documentation\/keyboardkit\/app-article","type":"topic","images":[{"type":"card","identifier":"Feature-App.jpg"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/actions-article","role":"article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"title":"Actions"},"Feature-Callouts.jpg":{"type":"image","identifier":"Feature-Callouts.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg","traits":["1x","light"]}]},"Feature-Layout.jpg":{"alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Layout.jpg"}],"type":"image","identifier":"Feature-Layout.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Layout-Article":{"title":"Layout","url":"\/documentation\/keyboardkit\/layout-article","kind":"article","images":[{"identifier":"Feature-Layout.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}]},"Feature-Status.jpg":{"alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Status.jpg"}],"type":"image","identifier":"Feature-Status.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardStatusContext/bundleId":{"url":"\/documentation\/keyboardkit\/keyboardstatuscontext\/bundleid","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext\/bundleId","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","title":"bundleId"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardStatusContext/isFullAccessEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFullAccessEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext\/isFullAccessEnabled","title":"isFullAccessEnabled","abstract":[{"type":"text","text":"Whether Full Access is enabled in System Settings."}],"url":"\/documentation\/keyboardkit\/keyboardstatuscontext\/isfullaccessenabled","type":"topic"},"Feature-Input.jpg":{"alt":"Feature Icon","type":"image","identifier":"Feature-Input.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg","traits":["1x","light"]}]},"Feature-Emojis.jpg":{"identifier":"Feature-Emojis.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg"}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardApp/HomeScreen":{"navigatorTitle":[{"text":"HomeScreen","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardApp\/HomeScreen","type":"topic","url":"\/documentation\/keyboardkit\/keyboardapp\/homescreen","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HomeScreen","kind":"identifier"}],"role":"symbol","title":"KeyboardApp.HomeScreen","abstract":[{"type":"text","text":"This screen can be used as the main home screen of a"},{"type":"text","text":" "},{"type":"text","text":"keyboard app that should look like iOS Settings."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardStatusContext/refresh()":{"url":"\/documentation\/keyboardkit\/keyboardstatuscontext\/refresh()","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatusContext\/refresh()","abstract":[{"type":"text","text":"Refresh the observable state."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"()"}],"type":"topic","title":"refresh()"},"Feature-Actions.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon","identifier":"Feature-Actions.jpg"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardStatus/SectionStyle":{"abstract":[{"text":"This type can style a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus\/Section","isActive":true},{"text":".","type":"text"}],"kind":"symbol","title":"KeyboardStatus.SectionStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SectionStyle"}],"url":"\/documentation\/keyboardkit\/keyboardstatus\/sectionstyle","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SectionStyle","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStatus\/SectionStyle"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}