{"metadata":{"title":"Styling","roleHeading":"Article","modules":[{"name":"KeyboardKit"}],"role":"article","images":[{"identifier":"Feature-Styling.jpg","type":"card"}]},"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"KeyboardKit’s various views can be customized to great extent. Most views have a corresponding view modifier to let you apply custom styles or style builders.","type":"text"}],"type":"paragraph"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"text":"👑 KeyboardKit Pro unlocks a theme engine for licenses that include the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/themes","isActive":true,"type":"reference"},{"text":" feature. This is discussed in the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Themes-Article","isActive":true,"type":"reference"},{"text":" article. You can sign up for KeyboardKit Pro from the ","type":"text"},{"identifier":"https:\/\/keyboardkit.com","isActive":true,"type":"reference"},{"text":".","type":"text"}]}],"name":"Important","type":"aside"},{"level":2,"text":"Namespace","anchor":"Namespace","type":"heading"},{"inlineContent":[{"type":"text","text":"KeyboardKit has a "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStyle","isActive":true},{"type":"text","text":" namespace that contains style-related types. However, most styles are defined next to their type, like the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","isActive":true},{"type":"text","text":"‘s "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardViewStyle","isActive":true},{"type":"text","text":" and the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard","isActive":true},{"type":"text","text":" namespace’s "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Button","isActive":true},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ButtonStyle","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"},{"text":"Color & Image Extensions","level":2,"anchor":"Color--Image-Extensions","type":"heading"},{"inlineContent":[{"text":"KeyboardKit defines additional, keyboard-specific ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Color","isActive":true},{"type":"text","text":" and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Image"},{"text":" extensions, like ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Color\/keyboardBackground"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Image\/keyboard"},{"text":", etc. to make it easy to create keyboards that look like a native iOS keyboard.","type":"text"}],"type":"paragraph"},{"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"identifier":"styling-images","type":"image"}]}]},{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"styling-colors"}],"type":"paragraph"}]}],"type":"row","numberOfColumns":2},{"inlineContent":[{"text":"KeyboardKit defines contextual colors that take a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext","isActive":true,"type":"reference"},{"text":", like ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Color\/keyboardBackground(for:)","isActive":true,"type":"reference"},{"text":". These colors vary the color result based on the context. Prefer these context-based colors whenever possible.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"KeyboardKit defines variable-based icons like "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Image\/keyboardNewline"},{"text":", which make it easy to use them as toggles and indicators.","type":"text"}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Some keyboard colors are semi-transparent to work around a system bug in iOS, where iOS defines an invalid color scheme when a keyboard is used with a dark appearance text field in light mode. iOS will say that the color scheme is ","type":"text"},{"code":".dark","type":"codeVoice"},{"text":", even if the system color scheme is light. Since dark appearance keyboards in light mode look quite different from keyboards in dark mode, this makes it impossible to apply the correct style. This has been ","type":"text"},{"isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit\/issues\/305","type":"reference"},{"text":", but until it’s fixes, thse colors will stay semi-transparent.","type":"text"}]}],"style":"important","name":"Important","type":"aside"},{"text":"Type Extensions","anchor":"Type-Extensions","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Many types in the library define standard images, texts & colors. You can for instance get the standard image and text for a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","type":"reference","isActive":true},{"text":" with the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/standardButtonImage(for:)","type":"reference","isActive":true},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/standardButtonText(for:)","type":"reference","isActive":true},{"text":":","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["let context = KeyboardContext()","let image = KeyboardAction.command.standardButtonImage(for: context) \/\/ Command icon","let text = KeyboardAction.space.standardButtonText(for: context)     \/\/ KKL10n.space"]},{"type":"paragraph","inlineContent":[{"text":"These values will be used by the standard button style, to generate a proper style for each keyboard action. They can be overridden by applying a custom ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardButtonStyle(_:)","type":"reference"},{"text":" view modifier to the keyboard view.","type":"text"}]},{"level":2,"type":"heading","text":"View Styles","anchor":"View-Styles"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit defines styles for its various view, which can be applied with style view modifiers. For instance, the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","isActive":true},{"text":" has a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardViewStyle","isActive":true},{"text":" that can be applied with the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardViewStyle(_:)","isActive":true},{"text":" modifier.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Most views have static, standard styles that can be replaced by custom styles to change the global default style for that particular view. Some views have dynamic view modifiers, that provide you with a parameter object for contextual values."}]},{"level":2,"type":"heading","text":"👑 KeyboardKit Pro","anchor":"%F0%9F%91%91-KeyboardKit-Pro"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks additional image assets, and a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme","type":"reference","isActive":true},{"type":"text","text":" engine that makes easier to style keyboards with themes."}]},{"text":"Emoji Icons","type":"heading","level":3,"anchor":"Emoji-Icons"},{"columns":[{"content":[{"inlineContent":[{"type":"image","identifier":"styling-images-emojis"}],"type":"paragraph"}],"size":1},{"size":1,"content":[{"inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks vectorized emoji assets for all "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/EmojiCategory","isActive":true},{"type":"text","text":"s, e.g. "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Image\/keyboardEmoji","isActive":true},{"type":"text","text":" & "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Image\/emojiCategory(_:)","type":"reference"},{"text":":","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"These images are vectorized and scale well when they’re resized, but they don’t support different font weights."}],"type":"paragraph"}]}],"type":"row","numberOfColumns":2},{"text":"Themes","type":"heading","level":3,"anchor":"Themes"},{"inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme","type":"reference","isActive":true},{"type":"text","text":" engine that makes easier to style keyboards with themes, as well as a bunch of themes:"}],"type":"paragraph"},{"type":"row","numberOfColumns":3,"columns":[{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"theme-standard-green"}],"type":"paragraph"}]},{"size":1,"content":[{"inlineContent":[{"identifier":"theme-blueprint","type":"image"}],"type":"paragraph"}]},{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"theme-candyshop"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"text":"You can apply standard & custom themes with the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardTheme(_:)"},{"text":" view modifier. See the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Themes-Article"},{"text":" article for more information.","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles"]]},"topicSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardFont","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStyle"],"anchor":"Types","title":"Types"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article"],"generated":true}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit styling engine."}],"variants":[{"paths":["\/documentation\/keyboardkit\/styling-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/styling-article"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Styling-Article","interfaceLanguage":"swift"},"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardStyle":{"navigatorTitle":[{"kind":"identifier","text":"KeyboardStyle"}],"url":"\/documentation\/keyboardkit\/keyboardstyle","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardStyle","abstract":[{"type":"text","text":"This namespace contains style-related types."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardStyle"}],"type":"topic","title":"KeyboardStyle"},"https://github.com/KeyboardKit/KeyboardKit/issues/305":{"title":"reported to Apple","type":"link","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit\/issues\/305","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKit\/issues\/305","titleInlineContent":[{"text":"reported to Apple","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/EmojiCategory":{"navigatorTitle":[{"text":"EmojiCategory","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/EmojiCategory","type":"topic","url":"\/documentation\/keyboardkit\/emojicategory","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmojiCategory","kind":"identifier"}],"role":"symbol","title":"EmojiCategory","abstract":[{"type":"text","text":"This enum defines the standard emoji categories, as well"},{"type":"text","text":" "},{"type":"text","text":"as their emojis."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Feedback-Article":{"url":"\/documentation\/keyboardkit\/feedback-article","type":"topic","images":[{"type":"card","identifier":"Feature-Feedback.jpg"}],"title":"Feedback","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","role":"article","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/Image/emojiCategory(_:)":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Image\/emojiCategory(_:)","kind":"symbol","url":"\/documentation\/keyboardkit\/swiftuicore\/image\/emojicategory(_:)","title":"emojiCategory(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emojiCategory","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit13EmojiCategoryO","kind":"typeIdentifier","text":"EmojiCategory"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:7SwiftUI5ImageV","kind":"typeIdentifier","text":"Image"}],"abstract":[{"text":"An emoji category icon for the provided category.","type":"text"}]},"Feature-Localization.jpg":{"identifier":"Feature-Localization.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Localization.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/External-Keyboards-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit external keyboard engine."}],"title":"External Keyboards","url":"\/documentation\/keyboardkit\/external-keyboards-article","images":[{"type":"card","identifier":"Feature-External.jpg"}],"kind":"article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/Color":{"abstract":[{"type":"text","text":"This extension extends "},{"type":"codeVoice","code":"Color"},{"type":"text","text":" with codable capabilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Color","title":"Color","url":"\/documentation\/keyboardkit\/swiftuicore\/color","kind":"symbol","navigatorTitle":[{"text":"Color","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Color","kind":"identifier","preciseIdentifier":"s:7SwiftUI5ColorV"}]},"https://keyboardkit.com":{"url":"https:\/\/keyboardkit.com","type":"link","title":"KeyboardKit website","titleInlineContent":[{"type":"text","text":"KeyboardKit website"}],"identifier":"https:\/\/keyboardkit.com"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Callouts-Article":{"kind":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","title":"Callouts","type":"topic","images":[{"identifier":"Feature-Callouts.jpg","type":"card"}],"url":"\/documentation\/keyboardkit\/callouts-article","abstract":[{"text":"This article describes the KeyboardKit callout engine.","type":"text"}],"role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/Image/keyboardEmoji":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Image\/keyboardEmoji","kind":"symbol","url":"\/documentation\/keyboardkit\/swiftuicore\/image\/keyboardemoji","title":"keyboardEmoji","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardEmoji","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI5ImageV","text":"Image","kind":"typeIdentifier"}],"abstract":[]},"Feature-Themes.jpg":{"type":"image","identifier":"Feature-Themes.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Themes.jpg","traits":["1x","light"]}]},"styling-colors":{"identifier":"styling-colors","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/styling-colors.jpg","traits":["1x","light"]}],"type":"image","alt":"Color Extensions"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardTheme":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardTheme","kind":"identifier"}],"abstract":[{"text":"This struct defines a keyboard-specific theme, which can","type":"text"},{"text":" ","type":"text"},{"text":"be used to define a bunch of styles at once.","type":"text"}],"type":"topic","title":"KeyboardTheme","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardTheme","kind":"symbol","url":"\/documentation\/keyboardkit\/keyboardtheme","navigatorTitle":[{"text":"KeyboardTheme","kind":"identifier"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Dictation-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"url":"\/documentation\/keyboardkit\/dictation-article","images":[{"type":"card","identifier":"Feature-Dictation.jpg"}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","type":"topic","kind":"article","role":"article"},"Feature-Autocomplete.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Autocomplete.jpg"}],"type":"image","identifier":"Feature-Autocomplete.jpg","alt":"Feature Icon"},"Feature-Fonts.jpg":{"type":"image","identifier":"Feature-Fonts.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Fonts.jpg","traits":["1x","light"]}]},"Feature-Host.jpg":{"identifier":"Feature-Host.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Host.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon"},"Feature-Dictation.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Dictation.jpg"}],"type":"image","identifier":"Feature-Dictation.jpg","alt":"Feature Icon"},"Feature-AI.jpg":{"type":"image","identifier":"Feature-AI.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-AI.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Autocomplete-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","type":"topic","url":"\/documentation\/keyboardkit\/autocomplete-article","kind":"article","images":[{"type":"card","identifier":"Feature-Autocomplete.jpg"}],"role":"article","title":"Autocomplete","abstract":[{"type":"text","text":"This article describes the KeyboardKit autocomplete engine."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Themes-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/themes-article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Themes-Article","abstract":[{"type":"text","text":"This article describes the KeyboardKit Pro theme engine."}],"images":[{"type":"card","identifier":"Feature-Themes.jpg"}],"kind":"article","title":"Themes","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardView":{"url":"\/documentation\/keyboardkit\/keyboardview","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView","abstract":[{"text":"This view renders a view that mimics the native keyboard.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardView","kind":"identifier"}],"kind":"symbol","title":"KeyboardView","navigatorTitle":[{"text":"KeyboardView","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/Image/keyboardNewline":{"role":"symbol","title":"keyboardNewline","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Image\/keyboardNewline","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardNewline","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"s:7SwiftUI5ImageV","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkit\/swiftuicore\/image\/keyboardnewline","abstract":[]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardViewStyle":{"url":"\/documentation\/keyboardkit\/keyboardviewstyle","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardViewStyle","title":"KeyboardViewStyle","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardViewStyle","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"KeyboardViewStyle","kind":"identifier"}],"abstract":[{"text":"This style can be used to style a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardView"},{"text":".","type":"text"}],"kind":"symbol"},"Feature-Feedback.jpg":{"identifier":"Feature-Feedback.jpg","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Feedback.jpg","traits":["1x","light"]}],"type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/Color/keyboardBackground":{"type":"topic","url":"\/documentation\/keyboardkit\/swiftuicore\/color\/keyboardbackground","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardBackground","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI5ColorV","text":"Color","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Color\/keyboardBackground","abstract":[{"type":"text","text":"The standard keyboard background color."}],"kind":"symbol","title":"keyboardBackground","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/Image/keyboard":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Image\/keyboard","kind":"symbol","url":"\/documentation\/keyboardkit\/swiftuicore\/image\/keyboard","title":"keyboard","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboard","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI5ImageV","text":"Image","kind":"typeIdentifier"}],"abstract":[]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardViewStyle(_:)":{"url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardviewstyle(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardViewStyle(_:)","abstract":[{"type":"text","text":"Apply a custom "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardViewStyle","isActive":true},{"type":"text","text":"."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardViewStyle"},{"kind":"text","text":"("},{"preciseIdentifier":"s:11KeyboardKit0A9ViewStyleV","kind":"typeIdentifier","text":"KeyboardViewStyle"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"kind":"symbol","title":"keyboardViewStyle(_:)"},"theme-blueprint":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/theme-blueprint.jpg"}],"type":"image","identifier":"theme-blueprint","alt":"Blueprint"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Localization-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit localization engine."}],"url":"\/documentation\/keyboardkit\/localization-article","images":[{"type":"card","identifier":"Feature-Localization.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article","title":"Localization","type":"topic","kind":"article","role":"article"},"Feature-External.jpg":{"type":"image","identifier":"Feature-External.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-External.jpg","traits":["1x","light"]}]},"theme-standard-green":{"identifier":"theme-standard-green","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/theme-standard-green.jpg","traits":["1x","light"]}],"type":"image","alt":"Standard Green Theme"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/AI-Article":{"abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","url":"\/documentation\/keyboardkit\/ai-article","title":"AI Support","images":[{"type":"card","identifier":"Feature-AI.jpg"}],"kind":"article","type":"topic","role":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardButtonStyle(_:)":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Apply a fixed, custom "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ButtonStyle","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardButtonStyle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Keyboard","preciseIdentifier":"s:11KeyboardKit0A0V"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ButtonStyle","preciseIdentifier":"s:11KeyboardKit0A0V11ButtonStyleV"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"role":"symbol","url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardbuttonstyle(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardButtonStyle(_:)","title":"keyboardButtonStyle(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/ProFeature/themes":{"type":"topic","title":"ProFeature.themes","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/ProFeature\/themes","url":"\/documentation\/keyboardkit\/profeature\/themes","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"themes","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Input-Article":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","title":"Input","url":"\/documentation\/keyboardkit\/input-article","images":[{"type":"card","identifier":"Feature-Input.jpg"}],"abstract":[{"text":"This article describes the KeyboardKit input engine.","type":"text"}],"role":"article","kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Emojis-Article":{"type":"topic","url":"\/documentation\/keyboardkit\/emojis-article","images":[{"type":"card","identifier":"Feature-Emojis.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","title":"Emojis","role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"kind":"article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Host-Article":{"kind":"article","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","role":"article","images":[{"identifier":"Feature-Host.jpg","type":"card"}],"title":"Host Application","abstract":[{"type":"text","text":"This article describes how KeyboardKit Pro lets you define and use a host application."}],"url":"\/documentation\/keyboardkit\/host-article"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Clipboard-Article":{"url":"\/documentation\/keyboardkit\/clipboard-article","abstract":[{"text":"This article describes KeyboardKit’s clipboard support.","type":"text"}],"images":[{"type":"card","identifier":"Feature-Clipboard.jpg"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","title":"Clipboard","type":"topic","kind":"article","role":"article"},"styling-images":{"identifier":"styling-images","alt":"Image Extensions","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/styling-images.jpg","traits":["1x","light"]}],"type":"image"},"theme-candyshop":{"identifier":"theme-candyshop","type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/theme-candyshop.jpg","traits":["1x","light"]}],"alt":"Cotton Candy Theme"},"Feature-Clipboard.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Clipboard.jpg"}],"type":"image","identifier":"Feature-Clipboard.jpg","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/ButtonStyle":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ButtonStyle","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/ButtonStyle","type":"topic","navigatorTitle":[{"text":"ButtonStyle","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"This style can be used to style a "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Button","type":"reference","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/keyboardkit\/keyboard\/buttonstyle","role":"symbol","title":"Keyboard.ButtonStyle"},"Feature-App.jpg":{"identifier":"Feature-App.jpg","alt":"Feature Icon","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-App.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Fonts-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","type":"topic","abstract":[{"text":"This article describes KeyboardKit’s custom font support.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/fonts-article","role":"article","images":[{"type":"card","identifier":"Feature-Fonts.jpg"}],"title":"Fonts"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/App-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","role":"article","kind":"article","title":"App Utilities","url":"\/documentation\/keyboardkit\/app-article","type":"topic","images":[{"type":"card","identifier":"Feature-App.jpg"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit app-specific utilities."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/Image":{"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Image","kind":"symbol","type":"topic","role":"symbol","title":"Image","url":"\/documentation\/keyboardkit\/swiftuicore\/image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image","preciseIdentifier":"s:7SwiftUI5ImageV"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Features-Articles":{"title":"Features","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Features-Articles","abstract":[{"text":"This article links to the various KeyboardKit features.","type":"text"}],"url":"\/documentation\/keyboardkit\/features-articles","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Actions-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"kind":"article","url":"\/documentation\/keyboardkit\/actions-article","role":"article","images":[{"identifier":"Feature-Actions.jpg","type":"card"}],"title":"Actions"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/Color/keyboardBackground(for:)":{"type":"topic","url":"\/documentation\/keyboardkit\/swiftuicore\/color\/keyboardbackground(for:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardBackground","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI11ColorSchemeO","text":"ColorScheme","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI5ColorV","text":"Color","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/Color\/keyboardBackground(for:)","abstract":[{"type":"text","text":"The standard keyboard button background color."}],"kind":"symbol","title":"keyboardBackground(for:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardFont":{"abstract":[{"type":"text","text":"This type represents a keyboard-specific font, which can"},{"type":"text","text":" "},{"type":"text","text":"be used by "},{"type":"codeVoice","code":"Codable"},{"type":"text","text":" types."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardFont","kind":"symbol","type":"topic","role":"symbol","title":"KeyboardFont","url":"\/documentation\/keyboardkit\/keyboardfont","navigatorTitle":[{"text":"KeyboardFont","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardFont","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/standardButtonImage(for:)":{"url":"\/documentation\/keyboardkit\/keyboardaction\/standardbuttonimage(for:)","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/standardButtonImage(for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standardButtonImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"KeyboardContext","kind":"typeIdentifier","preciseIdentifier":"s:11KeyboardKit0A7ContextC"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI5ImageV"},{"text":"?","kind":"text"}],"title":"standardButtonImage(for:)","abstract":[{"type":"text","text":"The standard button image."}],"type":"topic"},"Feature-Callouts.jpg":{"identifier":"Feature-Callouts.jpg","type":"image","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Callouts.jpg","traits":["1x","light"]}],"alt":"Feature Icon"},"Feature-Layout.jpg":{"variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Layout.jpg"}],"type":"image","identifier":"Feature-Layout.jpg","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Layout-Article":{"title":"Layout","url":"\/documentation\/keyboardkit\/layout-article","kind":"article","images":[{"identifier":"Feature-Layout.jpg","type":"card"}],"role":"article","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","type":"topic","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard/Button":{"abstract":[{"type":"text","text":"This view can be used to create keyboard buttons for"},{"type":"text","text":" "},{"type":"text","text":"various keyboard actions."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard\/Button","kind":"symbol","type":"topic","role":"symbol","title":"Keyboard.Button","url":"\/documentation\/keyboardkit\/keyboard\/button","navigatorTitle":[{"text":"Button","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Button","kind":"identifier"}]},"Feature-Styling.jpg":{"identifier":"Feature-Styling.jpg","alt":null,"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Styling.jpg","traits":["1x","light"]}],"type":"image"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/SwiftUICore/View/keyboardTheme(_:)":{"kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/SwiftUICore\/View\/keyboardTheme(_:)","title":"keyboardTheme(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardTheme","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A5ThemeV","text":"KeyboardTheme","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkit\/swiftuicore\/view\/keyboardtheme(_:)","abstract":[{"type":"text","text":"Apply a keyboard theme to the provided view."}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction/standardButtonText(for:)":{"role":"symbol","type":"topic","title":"standardButtonText(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standardButtonText","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11KeyboardKit0A7ContextC","text":"KeyboardContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction\/standardButtonText(for:)","abstract":[{"type":"text","text":"The standard button text."}],"url":"\/documentation\/keyboardkit\/keyboardaction\/standardbuttontext(for:)","kind":"symbol"},"Feature-Input.jpg":{"identifier":"Feature-Input.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Input.jpg"}],"type":"image"},"Feature-Emojis.jpg":{"type":"image","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Emojis.jpg"}],"identifier":"Feature-Emojis.jpg"},"Feature-Actions.jpg":{"type":"image","identifier":"Feature-Actions.jpg","alt":"Feature Icon","variants":[{"traits":["1x","light"],"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Actions.jpg"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardContext":{"abstract":[{"type":"text","text":"This class has observable states and persistent settings"},{"type":"text","text":" "},{"type":"text","text":"for the core keyboard functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardContext","kind":"symbol","type":"topic","role":"symbol","title":"KeyboardContext","url":"\/documentation\/keyboardkit\/keyboardcontext","navigatorTitle":[{"text":"KeyboardContext","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardContext","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Keyboard":{"type":"topic","url":"\/documentation\/keyboardkit\/keyboard","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Keyboard"}],"navigatorTitle":[{"kind":"identifier","text":"Keyboard"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Keyboard","abstract":[{"type":"text","text":"This namespace contains essential keyboard-related types."}],"kind":"symbol","title":"Keyboard","role":"symbol"},"styling-images-emojis":{"type":"image","identifier":"styling-images-emojis","alt":"Asset-based Images","variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/styling-images-emojis.jpg","traits":["1x","light"]}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardAction":{"title":"KeyboardAction","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAction"}],"abstract":[{"type":"text","text":"This enum defines keyboard-specific actions, and is also"},{"type":"text","text":" "},{"type":"text","text":"a namespace for action-related types."}],"url":"\/documentation\/keyboardkit\/keyboardaction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/App-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Clipboard-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Fonts-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Host-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Input-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Localization-Article"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}