{"abstract":[{"type":"text","text":"This protocol can be implemented by any type that can be"},{"text":" ","type":"text"},{"text":"used to open URLs from anywhere.","type":"text"}],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UrlOpener\/openUrl(_:)","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UrlOpener\/openUrlDefault(_:)"],"generated":true}],"metadata":{"externalID":"s:11KeyboardKit9UrlOpenerP","modules":[{"name":"KeyboardKit"}],"symbolKind":"protocol","role":"symbol","title":"UrlOpener","navigatorTitle":[{"text":"UrlOpener","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UrlOpener"}],"roleHeading":"Protocol"},"relationshipsSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/objc(cs)UIResponder"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforming Types","identifiers":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardPreviews\/InputViewController"],"type":"conformingTypes","kind":"relationships"}],"variants":[{"paths":["\/documentation\/keyboardkit\/urlopener"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UrlOpener"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UrlOpener"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIResponder","text":"UIResponder"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"While you must implement "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UrlOpener\/openUrl(_:)","isActive":true,"type":"reference"},{"type":"text","text":" it can call the"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UrlOpener\/openUrlDefault(_:)","isActive":true,"type":"reference"},{"text":" function internally.","type":"text"}]}],"kind":"content"}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardPreviews/InputViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"InputViewController","kind":"identifier"}],"role":"symbol","title":"KeyboardPreviews.InputViewController","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardPreviews\/InputViewController","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"InputViewController","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/keyboardpreviews\/inputviewcontroller","type":"topic"},"doc://com.keyboardkit.KeyboardKit/objc(cs)UIResponder":{"type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/objc(cs)UIResponder","title":"UIKit.UIResponder"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController":{"navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"role":"symbol","title":"KeyboardInputViewController","abstract":[{"text":"This is the main input controller type that is used in a","type":"text"},{"text":" ","type":"text"},{"text":"KeyboardKit-based keyboard extension.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UrlOpener/openUrl(_:)":{"kind":"symbol","required":true,"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Try to open a URL."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UrlOpener\/openUrl(_:)","url":"\/documentation\/keyboardkit\/urlopener\/openurl(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openUrl"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?)","kind":"text"}],"title":"openUrl(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UrlOpener/openUrlDefault(_:)":{"type":"topic","title":"openUrlDefault(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openUrlDefault","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UrlOpener\/openUrlDefault(_:)","url":"\/documentation\/keyboardkit\/urlopener\/openurldefault(_:)","abstract":[{"type":"text","text":"Try to open a URL with the default logic."}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/UrlOpener":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UrlOpener","kind":"identifier"}],"role":"symbol","title":"UrlOpener","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/UrlOpener","abstract":[{"text":"This protocol can be implemented by any type that can be","type":"text"},{"text":" ","type":"text"},{"text":"used to open URLs from anywhere.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"UrlOpener","kind":"identifier"}],"url":"\/documentation\/keyboardkit\/urlopener","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"KeyboardInputViewController","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/title"},{"op":"replace","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/navigatorTitle","value":[{"kind":"identifier","text":"KeyboardInputViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}