{"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/preview","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyboardInputViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@KeyboardKit@objc(cs)KeyboardInputViewController","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"sections":[],"metadata":{"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@KeyboardKit@objc(cs)KeyboardInputViewController","kind":"typeIdentifier","text":"KeyboardInputViewController"}],"title":"preview","symbolKind":"property","externalID":"s:11KeyboardKit0A19InputViewControllerC7previewACvpZ","modules":[{"name":"KeyboardKit"}],"role":"symbol","extendedModule":"KeyboardKit"},"variants":[{"paths":["\/documentation\/keyboardkit\/keyboardinputviewcontroller\/preview"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/preview":{"url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/preview","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/preview","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKit@objc(cs)KeyboardInputViewController"}],"type":"topic","title":"preview"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController":{"navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"role":"symbol","title":"KeyboardInputViewController","abstract":[{"text":"This is the main input controller type that is used in a","type":"text"},{"text":" ","type":"text"},{"text":"KeyboardKit-based keyboard extension.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/fragments","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/navigatorTitle","value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}