{"variants":[{"paths":["\/documentation\/keyboardkit\/keyboardinputviewcontroller\/textwillchange(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/keyboardinputviewcontroller\/textwillchange(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController"]]},"metadata":{"modules":[{"name":"KeyboardKit"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textWillChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITextInput","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextInput"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@KeyboardKit@objc(cs)KeyboardInputViewController(im)textWillChange:","navigatorTitle":[{"text":"textWillChange:","kind":"identifier"}],"title":"textWillChange(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textWillChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"textInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextInput","preciseIdentifier":"c:objc(pl)UITextInput"},{"kind":"text","text":"?)"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/textWillChange(_:)"},"kind":"symbol","references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/textWillChange(_:)":{"url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/textwillchange(_:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/textWillChange(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textWillChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITextInput","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextInput"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"textWillChange:","kind":"identifier"}],"type":"topic","title":"textWillChange(_:)"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController":{"title":"KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This is the main input controller type that is used in a","type":"text"},{"text":" ","type":"text"},{"text":"KeyboardKit-based keyboard extension.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"textWillChange:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textWillChange:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"textWillChange:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<UITextInput>","preciseIdentifier":"c:Qoobjc(pl)UITextInput","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"textInput","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController~1textWillChange(_:)\/title","value":"textWillChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController~1textWillChange(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textWillChange:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/fragments","value":[{"text":"KeyboardInputViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/navigatorTitle","value":[{"text":"KeyboardInputViewController","kind":"identifier"}]}]}]}