{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"The text document proxy that is currently active."}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/textDocumentProxy","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textDocumentProxy","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]},{"mentions":["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy-Article"],"kind":"mentions"}],"metadata":{"symbolKind":"property","externalID":"c:@M@KeyboardKit@objc(cs)KeyboardInputViewController(py)textDocumentProxy","role":"symbol","navigatorTitle":[{"text":"textDocumentProxy","kind":"identifier"}],"modules":[{"name":"KeyboardKit"}],"title":"textDocumentProxy","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textDocumentProxy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITextDocumentProxy","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/keyboardkit\/keyboardinputviewcontroller\/textdocumentproxy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/keyboardinputviewcontroller\/textdocumentproxy"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/textDocumentProxy":{"url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/textdocumentproxy","kind":"symbol","abstract":[{"text":"The text document proxy that is currently active.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/textDocumentProxy","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDocumentProxy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextDocumentProxy","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"navigatorTitle":[{"kind":"identifier","text":"textDocumentProxy"}],"type":"topic","title":"textDocumentProxy"},"Feature-Proxy.jpg":{"variants":[{"url":"\/images\/com.keyboardkit.KeyboardKit\/Feature-Proxy.jpg","traits":["1x","light"]}],"identifier":"Feature-Proxy.jpg","type":"image","alt":"Feature Icon"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController":{"title":"KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This is the main input controller type that is used in a","type":"text"},{"text":" ","type":"text"},{"text":"KeyboardKit-based keyboard extension.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"url":"\/documentation\/keyboardkit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"type":"topic","title":"KeyboardKit","role":"collection","identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","kind":"symbol"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/Proxy-Article":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/Proxy-Article","url":"\/documentation\/keyboardkit\/proxy-article","images":[{"identifier":"Feature-Proxy.jpg","type":"card"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}],"role":"article","title":"Proxy Utilities","kind":"article","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"textDocumentProxy","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"textDocumentProxy"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)UITextDocumentProxy","text":"id<UITextDocumentProxy>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"textDocumentProxy","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"textDocumentProxy","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController~1textDocumentProxy\/title"},{"op":"replace","value":[{"kind":"identifier","text":"textDocumentProxy"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController~1textDocumentProxy\/fragments"},{"op":"replace","value":"KeyboardInputViewController","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/navigatorTitle"}]}]}