{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/keyboardkit\/keyboardinputviewcontroller\/viewdidlayoutsubviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkit\/keyboardinputviewcontroller\/viewdidlayoutsubviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"modules":[{"name":"KeyboardKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@KeyboardKit@objc(cs)KeyboardInputViewController(im)viewDidLayoutSubviews","title":"viewDidLayoutSubviews()"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController"]]},"sections":[],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/viewDidLayoutSubviews()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"references":{"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController":{"navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController","type":"topic","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"role":"symbol","title":"KeyboardInputViewController","abstract":[{"text":"This is the main input controller type that is used in a","type":"text"},{"text":" ","type":"text"},{"text":"KeyboardKit-based keyboard extension.","type":"text"}]},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit","abstract":[{"type":"text","text":"KeyboardKit helps you create fully customizable keyboard extensions, using Swift and SwiftUI."}],"url":"\/documentation\/keyboardkit","title":"KeyboardKit","kind":"symbol","type":"topic","role":"collection"},"doc://com.keyboardkit.KeyboardKit/documentation/KeyboardKit/KeyboardInputViewController/viewDidLayoutSubviews()":{"title":"viewDidLayoutSubviews()","abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKit\/documentation\/KeyboardKit\/KeyboardInputViewController\/viewDidLayoutSubviews()","url":"\/documentation\/keyboardkit\/keyboardinputviewcontroller\/viewdidlayoutsubviews()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"viewDidLayoutSubviews","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"KeyboardInputViewController","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/title"},{"value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/fragments"},{"value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController\/navigatorTitle"},{"value":"viewDidLayoutSubviews","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController~1viewDidLayoutSubviews()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKit~1documentation~1KeyboardKit~1KeyboardInputViewController~1viewDidLayoutSubviews()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}